### ISSUE TITLE
Implement the undo manager

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#100]
To be implemented in ckeditor5-undo.

**Comment by scofalik** [comment]
Undo manager should be introduced as a Feature for CKE5. Quick overview:

* it should listen to change event and register it's own operations/deltas/batches history,
* it should be able to revert and apply the Batch from which most recently got updated,
* it should keep a separate stack for undo and redo, so deltas applied by undo'ing won't be then undone, but could be redone,
* it should be ready for "selective undo" feature,
* it should introduce two commands: "undo" and "redo".


I guess that's all?

**Comment by Reinmar** [comment]
We should also have buttons.

**Comment by scofalik** [comment]
Thank you cptn' Obvious :P

**Comment by Reinmar** [comment]
It's not that obvious, but you're welcome :P.

**Comment by pjasiun** [comment]
`Ctrl+z` shortcut?

**Comment by pjasiun** [comment]
Also `Batch`es should be kept in the order of creation.

**Comment by Reinmar** [comment]
As for the keystroke it will be good to open an issue on https://github.com/ckeditor/editor-recommendations/, because the redo keystroke is not that obvious. There are two options: <kbd>Ctrl+y</kbd> or <kbd>Ctrl+Shift+z</kbd>. IMO, both should work.

**Comment by pjasiun** [comment]
And `F4` for Microsoft applications.

**Comment by luzfcb** [comment]
since ckeditor 5 is something completely new and different from ckeditor4, I do not know if that makes any sense, but if ckeditor5 has something like SharedSpaces plugin, It would be good to include an optional feature to global undo and redo ( global undo and redo in relation to the context of editor instances connected by a sharedspaces ).

I am currently trying to implement, using ckeditor4, a simple editor similar to google docs writer. this is a feature that still can not build with ckeditor4. (perhaps because my knowledge with javascript is not extensive)

**Comment by Reinmar** [comment]
@luzfcb 

CKEditor 5 will support an editor with multiple roots. So you can have multiple editable root elements sharing one undo manager. That's like shared spaces on steroids. Lots of steroids :D.

**Comment by fredck** [comment]
> it should be ready for "selective undo" feature,

This is a secondary feature. If you feel that it would be any complication or drawback (like amount of code) to handle because of this, please be sure to postpone it.

**Comment by pjasiun** [comment]
Undo should also handle selection. Undoing changes, the selection should be restored too.

**Comment by Reinmar** [comment]
This has been fixed in ckeditor/ckeditor5-undo#3.
