### ISSUE TITLE
The code block does not remember the language

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#10005]
## 📝 Provide detailed reproduction steps (if any)

1.  Insert C++ code block
2.  Insert another code block via the Autorformatting feature shortcode.
3.  A new code block is created

### ✔️ Expected result

_The new code block should_ be a C++ block.

### ❌ Actual result

It is a plain text code bock instead as pictured:

![](https://user-images.githubusercontent.com/68123541/123960243-5d22d480-d9af-11eb-92f5-41404530f4f6.gif)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: Safari 14
*   OS: MacOS Catalina
*   First affected CKEditor version: pre v29.x release
*   Installed CKEditor plugins: default for the Code blocks feature demo.  

    also on:

*   Browser: Chrome 91.0.4472.114  
*   OS: MacOS Catalina  
*   First affected CKEditor version: pre v29.x release  
*   Installed CKEditor plugins: default in the image feature guide (namely image styles guide)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by godai78** [comment]
@ckeditor/ckeditor-5-triage

**Comment by mlewand** [comment]
The unfortunate side effect is that making inserting code block with autoformat **will break your remembered code language** for future button uses.

That being said I don't see it as a release blocker but something we should do as a follow-up in next iteration.

Things could be simpler if we had support for picking the snippet language by typing "\`\`\`cpp".

**Comment by pomek** [comment]
I changed labels. This issue should be fixed on the autoformat side. 

Going to details, we need to execute the `codeBlock` command with specified arguments to use the previously used language:

https://github.com/ckeditor/ckeditor5/blob/84207596a1979384e230c2ee2536527885a36f96/packages/ckeditor5-code-block/src/codeblockui.js#L58-L60

Currently, we just execute the command without any additional modifiers.

https://github.com/ckeditor/ckeditor5/blob/84207596a1979384e230c2ee2536527885a36f96/packages/ckeditor5-autoformat/src/autoformat.js#L181

The last argument can be a function (instead of a string) and it should fix the problem.
