### ISSUE TITLE
Paste from Word support

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1003]
Since we're soon starting to work on support for paste from Word, we need a ticket :) 

The current state of things is that since content pastes from Word is html-ish-like-something some content will appear in the editor. However, since it's not really an HTML the structure of the content (its semantics) is lost. 

What's the plan to improve this situation? We'll follow the architecture implemented in CKEditor 4:

1. Normalize the crazy input to something which is a valid and correctly structured HTML.
2. Filter out unnecessary (disallowed) stuff.

The latter is already done by how the conversion mechanism works in CKEditor 5. Basically, things that aren't handled by the loaded feature are automatically dropped (since they have no representation in the model). We may need to work, though, on stabilising this mechanism in edge cases.

Most of the job needs to be done in the first step. I'll just quote myself here:

> HTML exposed by Microsoft Word does not comply to any imaginable rules. It is a poetry of what can be done wrong.

We need to design a system for processing this input. I'm not sure about this yet but perhaps it will extend the view layer as the processing can be done based on this structure (or on the DOM). This may benefit some other use cases in which you may want to pre-process view structure before converting it to the model.

**Comment by pcrozer** [comment]
Hi there - any news/timescale on paste from word? (tables in particular!)  Would be a brilliant feature to have.

**Comment by Reinmar** [comment]
No, not yet. I wouldn't risk guessing now. But we'll be certainly trying to bring this iteratively, to have some MVP ASAP and then improving it over time. Just like we did with tables recently.

**Comment by f1ames** [comment]
I went through most common MS Word formatting options which relates to the content and could be potentially used in the editor, we have:

## Text formatting

- bold
- italics
- underline
- strikethrough
- font size
- font family
- headings
- quotes
---
- font color
- highlight color (background color)
- sub/super script
- text shading (works like highlight but uses predefined color)
- other text effects (shadows, reflection, etc)
- character border (wraps selected text into a rectangular box - different than adding regular border via `Borders` button)

## Alignments

- text alignment (left, right, justify, center)
- text indentation
- test distribution (adds equal spaces between each character in the line)

## Lists

- flat lists (one level)
- nested lists
- lists with non-standard bulleting
- lists with non-standard indentation

## Tables

- tables
- nested tables
- tables with non-default borders, styling, colors, etc

## Other objects

- links
- images
- math formulas
- horizontal line
- other media (charts, cliparts, shapes, etc)

## Others

- borders (adding borders to different elements via `Borders` button)
- styles (there are predefined/custom styles in Word which are applied in a different manner than a regular formatting)
- spacing (letters, lines, paragraphs, etc)
- LTR/RTL support

Of course all this formatting options may occur at once (e.g. nested list with some colored text inside a table).

---

One thing to notice is that some of the above are not supported at all in the editor at the moment. Since we would like to work on PFW iteratively to bring MVP ASAP as mentioned by @Reinmar:

> But we'll be certainly trying to bring this iteratively, to have some MVP ASAP and then improving it over time. Just like we did with tables recently.

We will focus on supporting basic formatting first and then proceed with more complex input. To prioritise thing a little I suggest a following order for a start:

1. bold, italics, underline, strikethrough
1. headings
1. links
1. lists
1. images

**Comment by Reinmar** [comment]
OK, all that we wanted to do in the current iteration is done. We track issues and feature requests in ckeditor/ckeditor5-paste-from-office.
