### ISSUE TITLE
Undeprecate the element to marker upcast converter and add proper docs

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#10128]
in HTML Comments we plan to use the `elementToMarker` upcast as it fits well our needs. I'm not sure why it is deprecated as the `dataToMarker` can't easily replace this one.

We plan to use `UIElement`s in the view layer and markers in the model.

https://github.com/ckeditor/ckeditor5/blob/e90f18b4bd5a9fb427367dd9022db13978b0d13f/packages/ckeditor5-engine/src/conversion/upcasthelpers.js#L333-L353

cc @scofalik, maybe you remember this case? (fe3785e)

**Comment by scofalik** [comment]
This was because markers, in general, can be placed anywhere, also in spots like between `<td>`s. If we add HTML elements there, even custom, that produces an incorrect HTML code. To prevent that, we changed how markers are converted and now we prefer to add an attribute if it is possible (elements are used only if there is no element next to marker boundary).

One of other solutions would have been to use comments tags instead of HTML elements to mark markers boundaries. These are allowed everywhere and we would keep the old solution. I am not sure why we eventually dropped this idea. Maybe because some HTML validators/processors are dropping comments too or maybe we thought that attributes are the safest bet.

In this case, we know that we will be converting to something that is allowed everywhere. So I think you could use that conversion, just don't use the main method so there's no warning logged.

**Comment by ma2ciek** [comment]
> In this case, we know that we will be converting to something that is allowed everywhere. So I think you could use that conversion, just don't use the main method so there's no warning logged.

Do you think we can undeprecate this method instead of using internals? With @psmyrek and @Reinmar we discussed this problem, and perhaps we could undeprecate it and improve this method's docs to clarify that the data achieved using this converter may lead to incorrect HTML markup if used the wrong way.  

> One of other solutions would have been to use comments tags instead of HTML elements to mark markers boundaries. These are allowed everywhere and we would keep the old solution. I am not sure why we eventually dropped this idea. Maybe because some HTML validators/processors are dropping comments too or maybe we thought that attributes are the safest bet.

Markers saved in HTML comment tags could conflict with the support for normal HTML comments that we want to introduce :sweat\_smile:

**Comment by scofalik** [comment]
> Markers saved in HTML comment tags could conflict with the support for normal HTML comments that we want to introduce 😅

Wellll, yeah :) I guess we would have some very distinct format and it would be quite a coincidence if somebody would use something like below out of the blue :D

```
<!-- CKE-MARKER-START comment:foo:bar !-->
```

**Comment by scofalik** [comment]
> Do you think we can undeprecate this method instead of using internals? With [**@psmyrek**](https://github.com/psmyrek) and [**@Reinmar**](https://github.com/Reinmar) we discussed this problem, and perhaps we could undeprecate it and improve this method's docs to clarify that the data achieved using this converter may lead to incorrect HTML markup if used the wrong way.  

Okay.

**Comment by ma2ciek** [comment]
Closed by #10227.
