### ISSUE TITLE
Whitespace gets removed when adjacent to inline image

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#10147]
## 📝 Provide detailed reproduction steps (if any)

1. Open a demo, e.g. https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html .
2. Execute in the console:
```js
editor.setData(
    '<p>foo <img src="../../assets/img/volcano.jpg"></p>'
)
```
or
```js
editor.setData(
    '<p><img src="../../assets/img/volcano.jpg"> bar</p>'
)
```

### ✔️ Expected result

Spaces after `foo` and before `bar` are preserved.

### ❌ Actual result

Spaces are removed.

### ❓ Further details

In the `DomConverter#_processDataFromDomText()` method there are calls for picking adjacent inline elements.

https://github.com/ckeditor/ckeditor5/blob/a39c5ed569c1f73436661ff494e4548ee54a8866/packages/ckeditor5-engine/src/view/domconverter.js#L1112-L1113

The problem is that method `DomConverter#_getTouchingInlineDomNode()` accepts only text and `<br>` as an inline element:

https://github.com/ckeditor/ckeditor5/blob/a39c5ed569c1f73436661ff494e4548ee54a8866/packages/ckeditor5-engine/src/view/domconverter.js#L1265-L1277

Next call in `_processDataFromDomText()` is `_checkShouldLeftTrimDomText()`. Which is only checking if a node is an element without checking if the element is an inline kind. This returns `true` for `imageInline` and allows the parent method to remove the space

https://github.com/ckeditor/ckeditor5/blob/a39c5ed569c1f73436661ff494e4548ee54a8866/packages/ckeditor5-engine/src/view/domconverter.js#L1168-L1175

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Some explanations to #10197:

*   It turned out it's not only about inline images but also about other "inline objects".
    *   As of today, they are not supported by the editor yet, though (mostly form elements).
*   `DomConverter#inlineObjectElements` was created to distinguish this category of DOM elements.
    *   This way, the solution is future-proof.
*   To address the issue, lots of changes in `DomConverter` were necessary. Mainly in the `_getTouchingInlineDomNode()` helper method that now correctly recognizes that `<img /> foo` and `<b>...</b> foo` (and similar) are two different cases in terms of trimming white spaces.
*   Because the white spaces around inline objects are not trimmed now, we had to override the GFM checkbox rendering function as it always returns a checkbox followed by white space to avoid duplicated white spaces (`<input type=checkbox />\s\stext`).
*   We had to change paste from office tests because despite the images being obviously inline in Word documents (fixtures), these tests had only block images enabled. And since handling of whitespaces around `<img>` has changed in the input (`domToView()`), some of those tests failed because `DomConverter` treated them as inline elements, and they were upcasted to block images in the model.

**Comment by niegowski** [comment]
There also was a case of `<span class="mso-spacerun: true"> </span>` in PFO that is replaced to NBSP during content normalization (to keep sequences of spaces) and those NBSPs are replaced to plain spaces if they are next to an inline object (not to glue an object to a text). This is behaving as before but the logic had to be split (previously inline object was treated the same as the block element boundary).
