### ISSUE TITLE
HtmlEmbed UI doesn't reflect isEnabled/isReadOnly state

### ISSUE THREAD

**Issue by PhiR42** [ckeditor/ckeditor5#10182]
## 📝 Provide detailed reproduction steps (if any)

1. insert a HtmlEmbed block in the editor, type something and save
2. switch the editor to isReadOnly mode
3. It is now impossible to add new HtmlEmbed blocks to the content via the toolbar
4. BUT the "pencil" button to edit existing blocks in the content still works and allows you to modify the html code inside the block.
5. This is a UI bug rather that a functionnality bug since the "save" button on the htmlembed block is disabled, so it is indeed impossible to actually modify the content of the editor. 

### ✔️ Expected result

The "pencil" button of the existing htmlembed blocks in the content should be in disabled state. 

### ❌ Actual result

The "pencil" button of the existing htmlembed blocks is enabled and allows one to change the html code in the block (but not to save it)

**Comment by Reinmar** [comment]
We discussed this issue internally. Some (random) notes:

*   I want to prioritize it because command state is important for some features (comments only mode, e.g).
*   Assumption: It goes through commands. Is that correct?
*   It may not be a bug... people should perhaps have access to the source of the embed.
*   In this case, we should replace the icon, label and... well, review the UI. Big changes needed.
*   The source editing is disabled in read-only, though. In CKEditor 4 it is enabled but the source is read-only.
*   Plot twist: Link's data is not accessible. Hence, HTML embed's data may not be accessible too. Let's just disable the "Edit button" button (there's no command for that).
*   Same line as [https://github.com/ckeditor/ckeditor5/blob/1fc2435/packages/ckeditor5-html-embed/src/htmlembedediting.js#L388-L389](https://github.com/ckeditor/ckeditor5/blob/1fc2435/packages/ckeditor5-html-embed/src/htmlembedediting.js#L388-L389)?

**Comment by dawidurbanski** [comment]
Fixed in #10570
