### ISSUE TITLE
Angular 6 Installing plugins fail 

### ISSUE THREAD

**Issue by keatkeat87** [ckeditor/ckeditor5#1021]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

CKEditor5 v10.0.0

## 📋 Steps to reproduce

1.git clone https://github.com/keatkeat87/angular-ckeditor5-install-plugin.git
2.npm install
3.npm start
4. browser chrome visit http://localhost:4200/
5. open dev tool F12
6.press button editorClassic, you view see the error message. 
note press button buildClassic will work fine.

## ✅ Expected result
it will work like button buildClassic.

## ❎ Actual result
error come out

## 📃 Other details that might be useful
Angular v6
Angular CLI v6 
I no direct setting webpack config. 
the project is build by Angular CLI. "ng new Project";

**Comment by Reinmar** [comment]
cc @oleq

**Comment by oleq** [comment]
> error come out

Which error?

**Comment by keatkeat87** [comment]
![image](https://user-images.githubusercontent.com/8691013/40302352-6c9f700c-5d21-11e8-9541-dd9f33a33688.png)
![image](https://user-images.githubusercontent.com/8691013/40302405-93214692-5d21-11e8-99e2-a8ab7fce8af3.png)
svg is undefined

**Comment by keatkeat87** [comment]
no, i create my app by Angular CLI.
due to some [reason](https://github.com/angular/angular-cli/issues/10618), CLI 6.0 currently not support to edit the webpack.config.
any idea ?

**Comment by Reinmar** [comment]
That's a question to Angular CLI's community. I know this topic was discussed there. 

As for solutions on our side – you can always create a [custom CKEditor 5 build](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html) in some other place (not in your Angular project) and include that. Including a build does not require any additional steps (if you [built CKEditor 5 to ES5](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target) because Angular CLI had problems with ES6 recently).

**Comment by keatkeat87** [comment]
all right, I'll take your advice.
thank you so much @Reinmar.
