### ISSUE TITLE
Empty `<figcaption>` model element produces `&nbsp;` in content view

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5#10240]
## 📝 Provide detailed reproduction steps (if any)

1. Go to [table caption demo](https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-caption).
2. Clear the content and create a new table with an empty caption.
3. Get editor content by `getData()` method.

### ✔️ Expected result

`<figcaption>` element should be empty.

### ❌ Actual result

`<figcaption>` element contains a `&nbsp;`.

## 📃 Other details

* Browser: any
* OS: any
* First affected CKEditor version: 28.0.0
* Installed CKEditor plugins: `TableCaption`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Same thing is happening for easy image captions. Previously when the caption was empty it was simply not added in the output markup.

**Comment by Reinmar** [comment]
Since the release of inline images, the caption is shown once you click the button in the toolbar, not on a widget focus. So, this is an intentional action of the user to show the caption, hence empty caption is represented in the data.

Previously, empty captions disappeared once you blurred a widget, hence, they weren't also output in the data.
