### ISSUE TITLE
Feature Request: Cycle Through List Styles on Click

### ISSUE THREAD

**Issue by duracell80** [ckeditor/ckeditor5#1028]
Rather than supporting "ordered list" and "ordered list" alone, the styles of those elements should be supported. Particularity for ordered lists the browser default might be numbers but the user may want roman numerals or an alphabetical order. This isn't something a designer should impose on the user (aka all OL's will be Roman).

To facilitate this without a drop down and because there are a small number of options the user could cycle through these styles on click of the icon with "none" either being the last or first on the cycle, currently the only option is "do you want an un/ordered list or not?".

https://www.w3schools.com/cssref/pr_list-style-type.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

User expectation on ordered lists is different from ours as developers, sometimes a user may expect that if a list is not ordered that when they click the ordered list icon it will auto-magically reorder. There is also in HTML the missing semantic of order direction (asc/desc) this can be inferred with a class or data attribute.

**Start Attribute**
There is the "start" attribute to consider ... as a user I may not want my list to start at "1" there's a bias in code for all lists to start at 1 but what if I want to split my list and have a paragraph of text between step 6 and 7? I can't my second list would start at 1. This isn't good.

**Reverse the Order**
https://www.w3schools.com/tags/att_ol_reversed.asp

**Comment by Reinmar** [comment]
> This isn't something a designer should impose on the user (aka all OL's will be Roman).

I disagree. When it's the content what matters, the styling plays a secondary role. And list style is about content styles. It may be imposed by the designer and it may differ e.g. depending on a target medium (print, website, newsletter, etc.).

Of course, there are also valid scenarios (e.g. a "document editor") where such feature is required in the editor. Therefore, while not obligatory,  we know that this feature would be welcomed by many developers.

Thanks for the ideas how it could be implemented. Perhaps not all ideas make sense for a rich-text editor like CKEditor 5 because we're not building next MS Word, but we'll see.

---

> There is the "start" attribute to consider ... as a user I may not want my list to start at "1"

Yup, +1. Would be good to handle this one day.

> Reverse the Order

And this too.

---

You reported a single ticket with 3 different features mentioned in it. I'll close this one and report these things separately.
