### ISSUE TITLE
Redesign and introduce new reconversion system

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10294]
### What do we have now

There is a downcast helper for `elementToElement` with a `triggerBy` option that triggers reconversion of a specific model element by removing its view representation (but keeping mappings), triggering the new view structure conversion callbacks (for that model element only), and reusing the child elements' old view representations. 

### What’s wrong with what we have now

To downcast a single model element to a slightly more complex structure we need to use the low-level API (so we need to take care of consuming what we converted and to bind model elements with view elements). That's because we are converting a subtree of a model structure. The reusing of view elements works sort of in a "magical" way. 

There is also an issue about the current implementation conflicting different `triggerBy` converters: #9641.

### What could we improve in the current solution

It could be more understandable if a single `elementToElement` converter would handle a single model element and do not touch its children elements. The conversion callback could provide a view structure with the special placeholders (slots) that model child elements should be downcasted into.

### Why do we think it can be done better?

The current `triggerBy` usage is very confusing. It requires to convert (in a single converter) not only an element itself but also its model child elements (and only their content is reused). This would be more declarative if we could provide conversion for a single model element to a bigger view structure with placeholders/slots for model child elements so that it could take care of inserting view elements in the correct positions in the view structure (not only as a direct child of the main element).

That slots could also have conditions for example to handle specific table rows (`thead` vs `tbody` that depends on `headingRows` attribute value).

### What do we have prototyped so far? Where’s that code?

The early PoC is in the [list reconversion branch](https://github.com/ckeditor/ckeditor5/compare/i/9407-list-reconversion) (that includes a lot of other experiments for `rangeToStructure` conversion). That branch is currently broken (because of changes in progress). The most interesting function is [`insertSlotted`](https://github.com/ckeditor/ckeditor5/blob/4a001997e3f522994efc0ef584cd53902d69c312/packages/ckeditor5-engine/src/conversion/downcasthelpers.js#L1084) that is supposed to get triggered after the old view was removed (but the view mapping was temporarily kept until the end of the conversion process to be reused while converting slots' content).

### A high-level overview of a new mechanism

The solution could be split into layers:

*   `DowncastDispatcher` could fire a new `reduceChanges` event before the conversion process starts to allow features (or conversion helpers) to alter the list of changes provided by the `Differ` so it could detect cases where the reconversion should be used. The re-conversion would be split into 2 events - one to remove the old view representation of a model element and one to insert a new representation. The old view elements would get removed from the view and unbound in the `Mapper` but it could keep temporal mapping to allow reusing view elements that got removed in the same conversion process. Those would get flushed at the end of the whole conversion.
*   `DowncastHelpers` `elementToElement` and `elementToStructure` would listen for the `reduceChanges` event to register callbacks for `triggerBy` changes to trigger re-conversion is a specified situation.
*   `elementToStructure` downcast helper could provide a factory for placeholders/slots so the simple view generator could put those into the structure and the helper itself would take care of converting those slot's content or reusing the view that was previously there.

### Example API proposal

The high-level API:

```javascript
editor.conversion.for( 'downcast' ).elementToStructure( {
	model: 'table', 
	view: ( modelElement, conversionApi ) => {
		const viewElement = conversionApi.writer.createContainerElement( 'div' );
		
		// ...
		
		writer.insert( writer.createPositionAt( viewElement, 0 ), conversionApi.slotFor( modelElement, 'children' ) );
		
		// ...
		
		return viewElement;
	}, 
	triggerBy: { 
		attributes: [ 'headingRows' ]
	}
} );
```

### Success criteria

*   Simple conversion for a single model element to a bigger view structure without taking care of mapping or consumables.
*   Can be used in tables to simplify the current downcast of the whole table and enable its reconversion with the preservation of table rows and cells.
*   Should be adjustable to use with a `rangeToStructure` future helper that will be used for the document list conversion.

### Risks, other things to change.

*   Temporal mappings kept for the conversion process are not yet in PoC (it was a simple one converter solution).
*   It seems that markers downcasted to view should properly reconvert themself (as it works for the current reconversion).

### Why now

The PoC was prepared while working on #9784 and #9783. This could be extracted from that PoC as it's a separate feature that would be later used by `rangeToStructure` downcast helper.

### What’s next

The next step would be to implement `rangeToStructure` downcast helper and use it for document list conversion.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
The `elementToStructure` PoC is now extracted to a new branch: [https://github.com/ckeditor/ckeditor5/compare/ck/10294-elementToStructure](https://github.com/ckeditor/ckeditor5/compare/ck/10294-elementToStructure)

It also implements the logic of `remove` + `reconvert` diff items.

**Comment by Reinmar** [comment]
> There is also an issue about the current implementation conflicting different `triggerBy` converters: #9641.

Another issue: #10306 (not sure if related).

**Comment by niegowski** [comment]
I just noticed another bug in the current reconversion implementation: #10314

**Comment by dawidurbanski** [comment]
I have couple thoughts after working on adding support for reconversion in `elementToElement` downcast helper.

Let me put them all together in this ticket so they are at least noted somewhere.

### Children prop `Boolean|Function`

The new API for describing `model` in `elementToElement` config object looks like this:

```js
model: {
	name: 'items',
	attributes: [ 'mode' ],
	children: true
},
```

I found some obscure use cases where it could be useful if `children` prop accepted not only `boolean` but also a function returning `boolean` (ideally with `modelElement` passed). This way we could set `children` dynamically based on model element attribute / element type / it's children type etc.

```js
model: {
	name: 'items',
	attributes: [ 'mode' ],
	children: ( modelElement ) => modelElement.getAttribute( 'mode' ) !== 'no-reconvert'
},
```

I don't have any specific use cases for this at the moment, so it's just for the records. Probably not very important nor needed.

### Docs / comments

https://github.com/ckeditor/ckeditor5/blob/e10b4ea05cce5b75ec06a7ade85b70b3de1a6c44/packages/ckeditor5-engine/src/conversion/downcasthelpers.js#L229-L230

Do we have to mention consumables here? Isn't enough to say the second part **View will be reconverted if any of the listed attributes will change.**

Also, to keep it consistent with other parts of this API, shouldn't we accept both array of strings and string for single attribute?

```js
@param {String|Array.<String>} [config.model.attributes]
```
________________________

https://github.com/ckeditor/ckeditor5/blob/e10b4ea05cce5b75ec06a7ade85b70b3de1a6c44/packages/ckeditor5-engine/src/conversion/downcasthelpers.js#L219-L220

I know it has been added as part of "improving docs" commit, but this note is still a bit unclear to me. Yeah it describes the constraint but does not say why nor what happens if you don't follow it. Will it raise an error? Will it crash?

I guess this probably might be a part of improving conversion docs and be just a matter of putting a link to it near this note.


@Reinmar @niegowski FYI

**Comment by niegowski** [comment]
> Also, to keep it consistent with other parts of this API, shouldn't we accept both array of strings and string for single attribute?
> 
> ```js
> @param {String|Array.<String>} [config.model.attributes]
> ```

The normalization accepts it, maybe it's just missing JSDoc?

**Comment by dawidurbanski** [comment]
Crosslinking the summary of changes for this huge feature: https://github.com/ckeditor/ckeditor5/issues/11268#issuecomment-1061655977
