### ISSUE TITLE
Checkboxes and list bullets are too close to left-aligned images

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#10309]
## 📝 Provide detailed reproduction steps (if any)

Create a left-aligned word-wrapped image and add a list or todo-list to the right (you can use of the demos [here](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-styles.html) or a custom build):

![image](https://user-images.githubusercontent.com/1523306/128235302-2b64dcaf-f304-4967-92ca-797b5b679b12.png)

![image](https://user-images.githubusercontent.com/1523306/128235515-83c4ebbc-190f-4c22-85ac-d8a0da0a92b8.png)

## 📃 Other details

* Browser: Chrome
* OS: macOS

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Thank CSS for that :( 

There's overflow:hidden that could change this behavior if set for `<ul>`, but we cannot use it for obvious reasons.

There's also some other CSS property (that has the same behavior but doesn't trim the content) AFAIR that we cannot use as well because then the list that starts next to an image will not flow to the left when the image ends.

So... the only thing I can think of is changing a margin of an image but it's not a good choice as well.

@oleq Did I miss something?

**Comment by oleq** [comment]
Probably a DUP of #8412.
