### ISSUE TITLE
Highlight Marker Needs Option For Text Color

### ISSUE THREAD

**Issue by duracell80** [ckeditor/ckeditor5#1030]
There seems to be a missing variable for the text color of the highlighter. Only the background color seems to be configurable, from looking at the documentation and examples all of the text is black. When the background is dark the text can't be black for accessibility reasons ( contrast ).

Suggest as an example:
--ck-highlight-marker-green-text: white

https://github.com/ckeditor/ckeditor5-highlight/blob/master/theme/highlight.css

**Comment by Reinmar** [comment]
cc @dkonopka @oleq

Ideally, we should avoid having too many variables due to the code size and just because there's never enough of them. Here, we'd need to add 6 more variables. Therefore, I'd rather like to avoid that. We can mention in the documentation that if you want to override more than the bg color you should do that by overriding these entire selectors. WDYT?

**Comment by oleq** [comment]
I'd rather keep things simple if that's possible. 

I'm pretty sure no integration will use more than 10 of markers/pens so it's not a huge chore to maintain them. What we have in https://github.com/ckeditor/ckeditor5-highlight/blob/master/theme/highlight.css is just a default set of markers/pens and many integrations will develop their own sets anyway.

**Comment by Reinmar** [comment]
Let's merge this into https://github.com/ckeditor/ckeditor5/issues/5677

**Comment by oleq** [comment]
I'm still against creating variables for such purposes and given that there was no more feedback since the last year, I decided to mark it as invalid.
