### ISSUE TITLE
Implement ordered lists start index and reverse order options

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1032]
Beside [list styles](https://github.com/ckeditor/ckeditor5/issues/1031) the other two important list settings are:

*   the start index (controlled in HTML by the `start` attribute),
*   the order (controlled by the `reversed` attribute.

Setting them may be required in some specific cases, especially when creating "documents".

Note to self: Don't forget about a follow-up with support for MSWord.

**Comment by alx1004** [comment]
Our current customer CityInnovate indicate the need for numbering lists changing, which I trust falls under this issue. There is nothing concrete just yet, but we'll need to get back to the topic with them. Once I get more information, I'll share and potentially offer the sponsoring of this feature.

**Comment by raoshahid799** [comment]
Microsoft word has this feature user can change index number numberedList , the Writer who has ms word skilsl will miss this feature, in some scenario writer has to change index number

**Comment by MPIIIMan** [comment]
I was looking for a way to implement a method to set the start number for lists and came across this.
I see this issue has been open for almost 3 years and is categorized as a nice-to-have.
For my application it's critical to adjust the numbers since there are html elements between lists.
Will the option to adjust the start number ever be implemented?

**Comment by Reinmar** [comment]
This feature has been released in CKE5 v32.0.0: https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html#list-properties
