### ISSUE TITLE
Enable support for reconversion in `elementToElement()`

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10359]
## Provide a description of the task

**Scope**

*   Introduce: Support for an object format of the model property to handle attributes + name + children
*   Conversion helpers: `insertElement()`
*   `downcastElementToElement()`

**Comment by Reinmar** [comment]
Note from the refinement:

*   **Sub-task**: Introduce: Support for an object format of the `model` property to handle `attributes` + `name` + `children`
    *   Triggers reconversion of that element
    *   Use cases: none currently, but it's clear that it's needed and the API will be consistent
    *   TODO: find a better name `children` - it's unclear what it triggers
        *   `children` makes the parent element be reconverted when the list of its children changes (children are converted separately).
*   **Sub-task:** Changes necessary for `insertElement()`
    *   We don't need support for slots here. We can be inspired by `insertStructure` which is already implemented.
    *   Changes needed because of reconvert option of `elementToElement()`
    *   TODO:
        *   `reinsertNodes()` - it will be reused from `elementToStructure` support.
        *   check for the element to have no children (for that we should use `elementToStructure()`)
    *   DO NOT:
        *   Try to reuse the view element that was mapped to the element being reconverted. It's fine to re-create it – reasonably cheap and easier to implement.
*   ~**Sub-task**: Update HTML Embed feature to use `elementToElement` instead of `triggerBy`.~
    *   Done in e2S
*   **Sub-task: `downcastElementToElement()`**
    *   Plug a listener to reduceChanges
*   **Tests**: If there's a lack of tests for `insertElement` (it may happen that we only tested `elementToElement` so far), it's not a part of this task to introduce them. However, if there are tests, we should introduce new ones to cover new changes.
