### ISSUE TITLE
Spike for imperative reconversion method

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#10381]
## Provide a description of the task

This spike is necessary because we have to find a proper way to handle #10360.

**Scope**:

*   Try to create an imperative method that will trigger reconversion.
*   It should allow reacting to `Document#change()` event.

**Comment by niegowski** [comment]
The PoC is available here: [https://github.com/ckeditor/ckeditor5/compare/ck/10294/reconversion...ck/10381-imperative-reconversion](https://github.com/ckeditor/ckeditor5/compare/ck/10294/reconversion...ck/10381-imperative-reconversion) It contains the PoC for element-to-element reconversion and changes needed in the table feature to verify the approach. The table downcast converters simplified there to the great extent and made the code much more readable and clear.

The overview:

*   A feature requests some model elements to get reconverted by calling `differ.reconvertItem()` for all elements that need reconversion.
*   The `Differ` is storing those requests in parallel to other buffered changes (but it should filter out reconversion requests that are inside inserted/removed subtrees, same as it does with other changes.
*   The `DowncastDispatcher` collects reconversion requests from the `Differ` and appends them to the list of all changes. Those are different from the reconversions triggered by the buffered changes because those are not replacing the original changes. 

Additional notes:

*   The re-conversion as handled currently re-attaches view elements based on their previous mapping. This works ok for elements that have mapping on the outer-most view elements but fails for those that are mapped to inner nodes (for example list items, code block). For element-to-element conversion, this can be handled by re-attaching the previous content of the re-converted element (instead of finding inner nodes from mapping) but for slots, this might be tricky.
*   Element-to-element conversion helper should not allow providing any sub-nodes from element creator to make it possible to find which nodes should get re-attached and where exactly.
*   Reducing changes for element-to-element should not remove the insert/remove changes, those should trigger reconversion but should not be removed so the content of the element can get converted.

Remaining questions:

*   In the proposed solution there are 2 separate sets of elements that need reconversion, one in the `Differ` and another one in the `reduceChanges` event. Those are used to not reconvert the same element multiple times but are separate for those two kinds of reconversion. Maybe it should be unified in some way?
*   Re-conversion diff items are generated separately in two places: in the downcast helpers while reducing the changes list, and in the differ to generate imperative reconversion triggers. Should it be unified? How?

**Comment by Reinmar** [comment]
Notes from a recent f2f meeting:

*   [#10381](https://github.com/ckeditor/ckeditor5/issues/10381): Spike for imperative reconversion method
    *   Use case: \<table headerRows>
        *   headerRows changes
        *   it needs to affect td → th in the view
        *   so, it's not a converter for tableCell's events, but the surrounding
    *   So far:
        *   we had post-fixers
        *   they detected headerRows or similar changes
        *   and were triggering Differ.refreshItem(table)
        *   What did refreshItem() do?
            *   removed entire table
            *   converted the table (as `insert:table`)
        *   This method was introduced a year ago and probably isn't used anywhere else
    *   What's wrong with the current refreshItem()?
        *   That it removes the entire old tree and re-creates it from scratch
        *   We suspect performance issues
        *   But we didn't research this
    *   #10381 proved that we can greatly simplify converters in the table feature
        *   We do not need to touch refreshItem() for that
        *   It's a reconversion but without re-use
    *   The new solution prototyped in #10381 would introduce new problems related to mapping.
        *   E.g. \<ul> is not mapped to anything in the model
        *   \<pre> is not mapped as well
        *   What should we re-use?
    *   Second aspect: post-fixers should not be used together with refreshItem()
        *   Post-fixers are not very performant due to their re-run-post-fixers if any post-fixer changed something
        *   Here, we're not changing anything in the model. We're not post-fixing anything
        *   Can we use Document#change?
        *   According to PoC, yes, we can
        *   It sounds well
    *   Followup: API to act on a specific change.
        *   Today: We listen to a generic event and then we check what changed
            *   Checking what changed today is hard
        *   Option: Declarative API to react on specific changes
            *   Declarative APIs are usually more limited but easier to start with
        *   Alternative option: Generic event + better API for checking changes
        *   Sidequest: post-fixer could be an event
            *   Priotization would be possible
            *   Preventing executing an already existing post-fixers
            *   It'd be consistent with Document#change
