### ISSUE TITLE
Collaborative comments error `Cannot read property '_source' of null` from rect.js:62

### ISSUE THREAD

**Issue by archonic** [ckeditor/ckeditor5#1042]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Decoupled editor 10.0.1 with collaborative editing, presence list and collaborative comments.

## 📋 Steps to reproduce
1. Repo/branch here: https://github.com/archonic/ckeditor5-build-decoupled-document/tree/collaborative-comments-error
2. Open index.html

## ✅ Expected result
Collaborative comments should behave like the demo here: https://docs.ckeditor.com/ckeditor5/latest/features/collaboration/overview.html

## ❎ Actual result
Console error `Cannot read property '_source' of null` from rect.js:62.

<img width="684" alt="developer_tools_-_http___localhost_8080_" src="https://user-images.githubusercontent.com/588846/40579627-c76201e0-60e0-11e8-8ef1-127292caca09.png">

## 📃 Other details that might be useful
Just collaborative editing and the presence list were working well. The error came up after adding collaborative comments following the instructions in the overview linked above.

**Comment by oskarwrobel** [comment]
Hello @archonic!

Thanks for trying CollaborativeComments feature.

This error occurs because column with editable element and column with sidebar element are not positioned elements. According to [documentation](https://docs.ckeditor.com/ckeditor5/latest/features/collaboration/collaborative-comments.html#html-structure) both columns should be relative for its children:
> What is important is that the editor and sidebar elements should be positioned elements (relative for its children) and should have the same top offset for their positioned children.

Setting `position: relative` to `div.document-editor__editable-container` should solve the problem. BTW I'll change this `Cannot read property '_source' of null` to something that better explains what is wrong in this case.

Second thing is that the sidebar column should have some minimal width because elements in the sidebar are absolutely positioned and won't expand it (I reccomend to use flexbox insetad of floats).

This two fixes make comments working for your example:
```diff
diff --git a/index.html b/index.html
index 82fc767..eaf6b38 100644
--- a/index.html
+++ b/index.html
@@ -14,7 +14,7 @@
        <div class="document-editor">
                <div class="document-editor__presence-list-container"></div>
     <div class="document-editor__toolbar"></div>
-           <div class="document-editor__editable-container">
+           <div class="document-editor__editable-container" style="position: relative;">
                                <div style="max-width: 800px;float: left;">
                                        <div class="document-editor__editable">
                        <h2>Heading 2 to start things off</h2>
@@ -31,8 +31,7 @@
                        <p>Lo-fi typewriter air plant intelligentsia PBR&amp;B. Bicycle rights aesthetic gentrify kickstarter migas synth actually seitan tattooed neutra raw denim celiac slow-carb. Normcore migas glossier neutra hell of, mumblecore cray food truck gastropub heirloom selvage meditation pug biodiesel pok pok. Synth raw denim hashtag pabst poutine, +1 kale chips. Synth semiotics pabst, wayfarers vexillologist taxidermy live-edge wolf iPhone next level blue bottle flexitarian. Everyday carry hot chicken vegan sartorial hashtag vape.</p>
                      </div>
                    </div>
-                               <div style="max-width: 400px;float: left;">
-                                       <h6>Sidebar needs some content to make comments visible. That's silly. Here's more width.</h6>
+                               <div style="min-width: 400px;float: left;">
                                        <div class="document-editor__sidebar"></div>
                                </div>
                        </div>
```

![image](https://user-images.githubusercontent.com/1057056/40580681-b5d57084-6143-11e8-87db-cfece81182dd.png)

I hope it helps.

**Comment by archonic** [comment]
Thanks! I was so close.

If it's possible to improve the error messaging, that would help. The collaborative comments package could add the relative position styling itself if it's not detected, but maybe that's beyond its responsibility.
