### ISSUE TITLE
Source editing view loses borders on scroll

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#10422]
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/features/source-editing.html
2.  Open source editing mode
3.  Scroll content (both horizontally and vertically)

### ✔️ Expected result

The border is still visible.

### ❌ Actual result

Borders scroll out of the visible area.

![](https://user-images.githubusercontent.com/1232187/130806677-620008a1-dc50-47fe-9469-25ab4256330e.gif)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
The textarea is too wide:

![](https://user-images.githubusercontent.com/156149/131642037-2322bc4f-ce1b-4866-af6a-591a24baf133.png)

We need to force it to have 100% of its parent width. Not more.

But, why do we use `display: inline-grid` there?

A thing to consider (that we should not break): the auto-resize of textarea's height.

This needs to be tested in all browsers.

**Comment by Reinmar** [comment]
The horizontal scroll solution: `word-break: break-all` + `white-spaces: pre-wrap`.

The vertical scroll has to be checked, because we must make the container of the textarea not scrollable. The tricky part is why is there `max-width: 700px` for the container. If it's a workaround for the toolbar not being sticky in source editing, we should not break it here. So, if in a reasonable 2h check this cannot be fixed, let's not change it.

Also: test this in a manual test (without documentation page style)!

**Comment by dawidurbanski** [comment]
Instead of adding `word-break: break-all` + `white-space: pre-wrap` to fix it, I went for removing the source of the problem, the grid thing.

I replaced it with some good old `position` stuff.

After making it work in manual test (in general case) I slightly modified source editing snippet css to work with the new update (so it works in conjunction with `max-width: 700px` on the container).

Fixed in #10566

**Comment by dawidurbanski** [comment]
@ckeditor/qa-team could you check this cross-browser? Steps are described in PR additional information section: https://github.com/ckeditor/ckeditor5/pull/10566#issue-1002130995

**Comment by Mgsy** [comment]
> [**@ckeditor/qa-team**](https://github.com/orgs/ckeditor/teams/qa-team) could you check this cross-browser? Steps are described in the PR additional information section: [#10566 (comment)](https://github.com/ckeditor/ckeditor5/pull/10566#issue-1002130995)

Looks good in all browsers :+1:

**Comment by shahzebgit** [comment]
@dawidurbanski @Mgsy Can we use the new update of source editing? or should i wait?
since i was also using my custom CSS for text area in source editing this might help the issue i was having in my project.

**Comment by shahzebgit** [comment]
@dawidurbanski I have integrated the CKE5(decoupled-editor), but here i'm not getting the scroll for some reason, could you look at this?


![image](https://user-images.githubusercontent.com/51449693/134470148-8e030bd0-cad3-4bd7-bc83-b1a009c538be.png)

**Comment by dawidurbanski** [comment]
@shahzebgit by default Source Editing feature textarea has `overflow: hidden` applied. If for any reason you restrict editor (and therefore source textarea) height, you need to make sure this field gets correct overflow:

```css
.your-container-class .ck-source-editing-area textarea {
    overflow: auto;
}
```
