### ISSUE TITLE
Support autoParagraph=false like in CKEditor4

### ISSUE THREAD

**Issue by aimeos** [ckeditor/ckeditor5#10448]
## Support autoParagraph=false like in CKEditor4

Up to now a `<p></p>` tag is always added around string content. If the string `Test header` is added in an HTML template `<h1>{{ string }}</h1>`, this produces invalid results:

```
<h1><p>Test header</p></h1>
```

## Other details

* CKEditor version: latest
* Installed CKEditor plugins: none

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! CKEditor 5 has stricter rules for content quality than CKEditor 4. The autoParagraph feature was a nightmare to maintain in CKEditor 4 times and we're not going to work on it for CKEditor 5.

CKEditor 5 offers other ways to deal with such aspects, though. E.g. you can customize how the model's paragraph element is being output by overriding its downcast converte. Also, it seems that your use case doesn't actually rely on autoParagraph but on a more conscious way of integrating editor's output with a template that you have. 

Also, it kinda sounds like you might be interested in #762.

In any case, I'm closing this issue because we'll not work on autoP anyway.
