### ISSUE TITLE
There's a black rectangle rendered under inline editor's toolbar

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#10529]
## 📝 Provide detailed reproduction steps (if any)

![](https://user-images.githubusercontent.com/1099479/133282454-663c30d5-e703-49c9-aad5-18bb03f0607b.png)

Looks like the aftermath of recent `viewportTopOffset` changes. The panel gets obsolete `.ck-balloon-panel_with-arrow` without any specific arrow class.

### ❓ Possible solution

[This line used to do the trick](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js#L74) but now it's probably obsolete and things are handled on the fly as new positions are chosen for the panel. This worked for me

```diff
diff --git a/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js b/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js
index c97ed66273..4b98ea591c 100644
--- a/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js
+++ b/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js
@@ -71,8 +71,6 @@ export default class InlineEditorUIView extends EditorUIView {
                    */
                   this.panel = new BalloonPanelView( locale );
 
-                  this.panel.withArrow = false;
-
                   /**
                    * A set of positioning functions used by the {@link #panel} to float around
                    * {@link #element editableElement}.
@@ -217,14 +215,20 @@ export default class InlineEditorUIView extends EditorUIView {
                                     return {
                                              top: this._getPanelPositionTop( editableRect, panelRect ),
                                              left: editableRect.left,
-                                             name: 'toolbar_west'
+                                             name: 'toolbar_west',
+                                             config: {
+                                                      withArrow: false
+                                             }
                                     };
                            },
                            ( editableRect, panelRect ) => {
                                     return {
                                              top: this._getPanelPositionTop( editableRect, panelRect ),
                                              left: editableRect.left + editableRect.width - panelRect.width,
-                                             name: 'toolbar_east'
+                                             name: 'toolbar_east',
+                                             config: {
+                                                      withArrow: false
+                                             }
                                     };
                            }
                   ];
```

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dawidurbanski** [comment]
Just for sake of completeness I'll post here **why** it does not work anymore like before.

Currently the `withArrow` value is being set in `BalloonPanelView#attachTo` method. It's the same place where we set default value for it. Because of this if we do (pseudocode):

```js
const panel = new BalloonPanelView();

panel.withArrow = false;
panel.attachTo( { target } );
```

now `panel.withArrow` will be set to true if the positioning function does not specify `config: { withArrow: false }` because we set this in `BalloonPanelView`

https://github.com/ckeditor/ckeditor5/blob/a5e0392d24d98091b05d419515071622f51b093c/packages/ckeditor5-ui/src/panel/balloon/balloonpanelview.js#L249-L250

Since it's the `attachTo` responsibility now, I removed one test from `InlineEditorUIView#constructor`:

https://github.com/ckeditor/ckeditor5/blob/a5e0392d24d98091b05d419515071622f51b093c/packages/ckeditor5-editor-inline/tests/inlineeditoruiview.js#L92-L94

And added more robust test in `BalloonPanelView`:

https://github.com/ckeditor/ckeditor5/pull/10532/files#diff-aa83b945ff49c55a0f93974d49f5654bf5dcbbf48561c7b64f54309462d2abbfR214-R245

It's all in [this PR](#10532).
