### ISSUE TITLE
Multi page in "Document Editor"?

### ISSUE THREAD

**Issue by hnviradiya** [ckeditor/ckeditor5#1054]
🆕 Feature request

ckeditor5

Do we have multi page feature in "Document editor"? as I could not find any such configuration. and if not, do we have plan to add?

**Comment by Reinmar** [comment]
What do you mean by multi page? Rendering content split to multiple pages like in Google Docs?

**Comment by hnviradiya** [comment]
yes. also same as docx file.

**Comment by Reinmar** [comment]
OK, then, unfortunately, this is not supported and most likely won't be (at least for the next couple of years). The reason is that we cannot simulate page splitting in the DOM. CSS doesn't allow that yet. There were works on CSS properties which would make that possible (and even first implementations), but this was never standardized.

However, enabling us to enforce page splitting is one thing. The other is why do you need page splitting? This, most often, is required because people want to work on documents that will be printed. And here we have a problem. Every browser and every OS render the content a bit differently and every browser will split it differently too. This means that you can't have a reliable print preview in the editor like CKEditor 5 even if CSS will enable page splitting because the content will look differently when edited in different browsers.

So, the only reasonable solution for me is to have a separate "print preview" option where the content is sent from the editor to e.g. an HTML->PDF converter and presented to the user for verification. This way, you will ensure that what's printed on paper looks exactly like what the user saw on the screen. 

PS. Why can Google Docs have page splitting? It's because they use a completely custom rendering. The completely dropped ability to style the content via CSS and use the DOM as a "canvas" on which they paint the text. I guess that they also had to create a compatible HTML -> PDF converter for the print option. This solution is more DTP-oriented but loses many of the web's powerful features (e.g. styling via CSS stylesheets, support for native components, etc.).

**Comment by Reinmar** [comment]
More details: https://github.com/ckeditor/ckeditor5-design/issues/147.

**Comment by celsowm** [comment]
I was looking for something similar, I found the one used by this company, I hope one day ckeditor has something like or better: https://ej2.syncfusion.com/demos/#/material/document-editor/headers-and-footers.html
