### ISSUE TITLE
If it is an iOS browser, the first character of each line will be fixed without permission.

### ISSUE THREAD

**Issue by yuya-tani** [ckeditor/ckeditor5#10625]
I am using CKEditor5.

The following phenomenon occurs in safari on iOS (14.7.1) and macOS (10.15.7).
In the case of iOS, the same phenomenon occurs with chrome,
In case of macOS, it does not occur in chrome.

Only the first character of each line in the editor in a language such as Japanese that has a character conversion process
It will be confirmed during input.

For example, if you type "![image](https://user-images.githubusercontent.com/22019718/135555810-b5bf6bda-2774-4803-b939-93cfda7d6ba7.png)" (typing key is "nihon"), you will get "n ![image](https://user-images.githubusercontent.com/22019718/135555810-b5bf6bda-2774-4803-b939-93cfda7d6ba7.png)".
It is a phenomenon that the first character "n" is fixed.

It didn't happen in a normal text area that wasn't an editor.

Best regard.

**Comment by FilipTokarski** [comment]
Hi, thank you for the report. This is a known issue. We are aware of the problems with IME, but unfortunately solving those issues is not trivial and requires a lot of effort. We will try to address as many of such cases as possible with [migration to `beforeInput`](https://github.com/ckeditor/ckeditor5/issues/7462), but due to our current amount of work and other obligations, we cannot guarantee any ETA for this.
  
I'll close this issue as a duplicate.

**Comment by yuya-tani** [comment]
Hi, thank you for your reply.

Was it a problem you already had? I'm sorry.
After all it is a problem of IME.

I am looking forward to a future that will be fixed someday.
Best regard.
