### ISSUE TITLE
I can't insert new line after image widget.

### ISSUE THREAD

**Issue by dvlpr91** [ckeditor/ckeditor5#1062]
When I upload image, I can not insert new line after selected image widget. of course, just press enter key then do work... but I wanna do work as like 'quill editor'.

I am not good at English and can not write in detail. I'm sorry.

**Comment by Reinmar** [comment]
It's a DUP of #407. And make sure to check https://github.com/ckeditor/ckeditor5/issues/407#issuecomment-397304141.

**Comment by dvlpr91** [comment]
I don't quite understand, but you seem to be trying to correct it. I hope this problem is resolved.

**Comment by Reinmar** [comment]
BTW, I checked Quill out of curiosity and it seems like they do nothing:

![jun-18-2018 10-27-37](https://user-images.githubusercontent.com/156149/41525745-4e86b64e-72e2-11e8-9733-30e8c60ae0d0.gif)

You can click but you won't see the caret. Typing works (most likely) due to the browser virtually placing the selection at those positions. It all kinda works only because this is a normal inline content:

![image](https://user-images.githubusercontent.com/156149/41525851-a8c58914-72e2-11e8-885b-42f8c2a81d83.png)

If someone would try anything like captioned images or block images, things would look worse.

**Comment by dvlpr91** [comment]
I agree with you. To be honest, if there was no scrolling bug in 'quill' I might have been using it.

If I look at scalability, I think 'ckeditor' is the best editor. Thank you for your hard work.

**Comment by mjadobson** [comment]
> You can click but you won't see the caret. Typing works (most likely) due to the browser virtually placing the selection at those positions.

There is a caret visible, it's just difficult to see as the browser makes it the height of the image, and places it immediately to the image's left/right.

As you say, it only works because the image is an inline element.

**Comment by dvlpr91** [comment]
@mjadobson When you saw it, did it seem to work normally? I can't.

**Comment by projct1** [comment]
I wasted about two hours and still did not understand how to insert a new line after the uploaded image until I went here. How can you guess that it turns out you need to select the image and press enter or shift + enter? This is terribly uncomfortable.

**Comment by Reinmar** [comment]
I completely agree with you. This was a quick workaround that we were able to implement. A real solution is much more complex and will take us still some time to develop.

**Comment by projct1** [comment]
Thanks :)
