### ISSUE TITLE
Nested Block Element causes to break backspace behaviour

### ISSUE THREAD

**Issue by shahzebgit** [ckeditor/ckeditor5#10669]
## Provide a description of the task

1. I have a custom block element
2. Add `p` inside an div (i.e `<div><p></p></div>`)
3. Use Enter key and create new `p` and use Backspace it wont remove newly created paragraphs

How to deal with such issues,since they both behave like block-elements and editor thinks that its single block-elements so it doesn't remove those newly created `p` tag

## 📃 Other details

  ```
  schema.register('OzDiv', {
      allowWhere: '$block',
      allowContentOf: '$root',
      isBlock: true,
    });

 conversion.elementToElement({
      model: 'OzDiv',
      view: 'div'
    });
```
![nested-block](https://user-images.githubusercontent.com/51449693/136751951-75a52540-fda3-4477-8859-8550101539e7.gif)

* Browser:Chrome
* OS: Ubuntu 20.4 LTS
* CKEditor version: 24.0.0
* Installed CKEditor plugins: …

**Comment by Reinmar** [comment]
A `<div>` in this case is not a block. It's a container. Just like a blockquote, which is defined this way: [https://github.com/ckeditor/ckeditor5/blob/dc1117b22d76530aed93a7d46b20ba17296003e9/packages/ckeditor5-block-quote/src/blockquoteediting.js#L47-L50](https://github.com/ckeditor/ckeditor5/blob/dc1117b22d76530aed93a7d46b20ba17296003e9/packages/ckeditor5-block-quote/src/blockquoteediting.js#L47-L50)

Could you recheck whether removing `isBlock` fixes the problem?

**Comment by shahzebgit** [comment]
@Reinmar 
  >  Could you recheck whether removing isBlock fixes the problem?
	
No, the behaviour is still the same, the paragraph's aren't deleted/cleared.
	
paragraph schema, just for reference
```
model.schema.register( 'paragraph', {
 inheritAllFrom: '$block' 
 } );
editor.conversion.elementToElement( { 
model: 'paragraph', view: 'p' 
} );
```

**Comment by shahzebgit** [comment]
@Reinmar @niegowski  can you provide any solution for the situation i have?_(sorry for the ping)_ but i'm not able to find any solution for this yet.

**Comment by FilipTokarski** [comment]
@shahzebgit I see you're using very old editor version (`24.0.0`). A lot has changes in the editor internals since that version and we recommend to use the latest one (which is `31.0.0`, and also a new release coming soon). 

Could you try checking your code with the latest version or latest `master` and confirm that this behaviour is gone (of course assuming that you don't have some other custom code that might interfere)?

**Comment by shahzebgit** [comment]
@FilipTokarski when i reported this issue i was on v(`24.0.0`) but now i'm on v(`31.0.0`) and i still have this issue,
the issue here is as per @Reinmar  pointed out that the `div` isn't a block but a container.

i'm using some custom code here but its just that here i'm changing the model name for `div` to `OzDiv` in model, I have also allowed `div`(OzDiv) to have `p` tag in it., even the paragraph plugin is untouched.

**Comment by FilipTokarski** [comment]
Unfortunately, we cannot provide any sensible advice as we're still not able to reproduce this and the bug doesn't seem to be in the editor itself:

https://user-images.githubusercontent.com/34380544/144442658-de337092-b684-412d-b499-321dc7390908.mp4

If you believe that there's something wrong inside the editor, we'll need precise steps to reproduce the issue. Otherwise, considering that you're using some custom solutions, I'm afraid you'll need to debug this on your side.

As it comes to GHS, you might be interested in _[enabling custom elements](https://ckeditor.com/docs/ckeditor5/31.0.0/features/general-html-support.html#enabling-custom-elements)_ section in the docs.

**Comment by shahzebgit** [comment]
@FilipTokarski Can you please provide the code, if i can i get an idea of how did you get the desired behaviour? because this seems to be the solution,with the code you provide i can try to reproduce it in my editor and report you back.

**Comment by shahzebgit** [comment]
@FilipTokarski Okay found what is the issue in my custom Code, thank you for providing me some insight.
