### ISSUE TITLE
How to use Base64UploadAdapter with Vue and classic build

### ISSUE THREAD

**Issue by zwik** [ckeditor/ckeditor5#10773]
## I can't use the the Base64UploadAdapter with the classic build and Vue 2

I'm a new ckeditor user and I'm confused with how to configure a basic build. I created a default Vue 2 and installed CKEditor5 and the Vue2 bindings as described here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v2.html

Next I wanted to use the base64 encoding for image upload. So I followed the instructions here: https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/base64-upload-adapter.html

When browsing the node-modules I noticed that the `ckeditor5-upload` package was already there so I didn't bother to install that.

The next line to add is the import. As soon as I do that I can see in the console that there's a duplicate. So how do I then configure the upload adapter?

**Comment by zwik** [comment]
That's what I understood as well. The question is, how should I then use it if it's already there? The documentation doesn't seem to mention any of that. I don't want a at a custom editor. I just want to use what's already there. The `node_modules` seem to suggest that everything I need is already there but I don't know how to use it.

**Comment by FilipTokarski** [comment]
Did you see [guide on installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)? Basically anytime you want to change plugins configuration in your editor, you need to rebuild it. So if you installed the package, you may have it in your `node_modules`, but you need to change the source code of the editor anyway.  

On a side note - duplicated modules error might also be caused by importing CKEditor plugins which have different version. For example, if all your editor packages have version `29.0.0` and you install and import some freshly released package with version `31.0.0`, there will be an error. It's also mentioned in the red info-box [in the docs I linked](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#requirements).

**Comment by zwik** [comment]
Thank you for your answer @FilipTokarski . I did read that guide, though it was not clear to me that it was this guide that would be applicable to my situation. I think that part of the documentation can be worked on a bit more.

Why is it like this? It seems like a hassle to rebuild an entire editor for something "tiny".
