### ISSUE TITLE
Image caption stretches down in Decoupled Document build sample

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#10940]
## 📝 Provide detailed reproduction steps (if any)

1. Go to http://127.0.0.1:8081/ckeditor5-build-decoupled-document/sample/
2. Click on the image and toggle the caption on.

### ✔️ Expected result

Image caption shows below the image.

### ❌ Actual result

Image caption shows below the image but stretches down (twice the height of the image by the looks of it).

![image](https://user-images.githubusercontent.com/1112966/144434507-6e939e7b-5fd1-459f-a9ab-71ff8ea70fdc.png)

## 📃 Other details

* Browser: Firefox, Chrome
* OS: MacOS

**Comment by oleq** [comment]
The issue is [here](https://github.com/ckeditor/ckeditor5/blob/16847d53da4848af44d415b0ebe0410c820ea93f/packages/ckeditor5-build-decoupled-document/sample/index.html#L41-L42). Introduced a few months ago. `.ck-content` should be used instead because `.ck-editor__editable` are not only roots but also nested editables.
