### ISSUE TITLE
Pasting a table into an existing nested table causes unexpected behaviour

### ISSUE THREAD

**Issue by letdowncrush** [ckeditor/ckeditor5#10966]
I can reproduce this at: https://ckeditor.com/docs/ckeditor5/latest/features/images/images-overview.html#base-image-support

1. Create a one cell table
2. Create another once cell table inside the one from (1)
3. Create a separate table, highlight it, copy to clipboard and then try pasting into the nested table we created in (2).

### ✔️ Expected result

Would expect to end up with a table within a table within a table.

### ❌ Actual result

The nested table from (2) gets replaced with the table we are pasting into it.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I'm not sure I fully understood the steps you provided but I think the behaviour you described is actually not a bug. Could you add some screenshots or screencast to visualise the expected and actual results?

**Comment by letdowncrush** [comment]
Hi,

Please see the gif below. I create a table and then another one inside. Then when I try and paste another table into the inner table... it replaces it entirely rather than pasting into it.

![gh-issue-10966](https://user-images.githubusercontent.com/15230196/145975706-58bd1975-d1af-4520-9262-d5bfa21af313.gif)

**Comment by FilipTokarski** [comment]
Thanks for clarifying. Basically that's how the current implementation of table feature works. When pasting a table into another, it overwrites the cells and the content. In this case it looks like it's getting replaced because you're pasting a bigger table into smaller one. In a reversed scenario, you can see only the content of the cells gets replaced:

https://user-images.githubusercontent.com/34380544/145989367-3506da3f-5f50-4e3c-9cf9-ef967113e6e2.mp4

**Comment by letdowncrush** [comment]
@FilipTokarski thanks for the clarification.
