### ISSUE TITLE
Manual tests validation fails on CI

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#10982]
## Provide a description of the task

After migration to webpack 5, the manual test server ends with the `137` error, which means the machine is out of memory.

It does not seem easy to fix, so I disabled the verification process (770daa6).

https://github.com/ckeditor/ckeditor5/blob/acf49d3f6d35fa8e8dbdce735e101a9ef01d200c/scripts/ci/travis-check.js#L42

Once we figure out what's going on, let's enable the validation again.

**Comment by pomek** [comment]
Scope:

- Does webpack 5 change anything regarding memory?
- Run the server multiple times.
- Each run should process around 100 manual tests.

**Comment by psmyrek** [comment]
I took some time to find out more about what has changed between webpack v4 and v5, because I was very curious why our CI suddenly stopped working.

It turns out that webpack v5 by default uses RAM as its cache, but not the filesystem as it was in v4 - see https://github.com/webpack/webpack/issues/12102#issuecomment-855237846. My first thought was to configure the cache back to the filesystem to free up some RAM then. Unfortunately, this did not give the expected results because, as it turned out, even when the cache is set to filesystem, [writing to cache will write to both caches: memory and filesystem](https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md#watching), so the memory consumption did not decrease.

This, in turn, gave me another idea: the manual test verification on CI should have its own webpack config, in which two unnecessary options would be disabled: `devtool` and `watch`. And in fact it is very promising, because on my local environment, after turning off these two unnecessary for CI options, RAM consumption has dropped from ~7 GB to < 1 GB and manual tests are built faster.

@pomek: what do you think about this approach?

**Comment by pomek** [comment]
Thanks, @psmyrek, for digging into details. We could add an option for disabling watchers. As you pointer out, it makes sense when developing the editor locally, but it's useless when validating these tests as we need to process these files without listening for changes.

As it changes the scope, I'll remove the estimation.

**Comment by pomek** [comment]
Disabling watchers and generating source maps resolve the problem. Webpack compiles all tests, and the crawler starts verifying manual tests.

However, all of them end with the following error:

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://cksource.com".
```

So far, replacing the `mode` from `'development'` to `'none'` helps. Let's see what CI says.

**Comment by pomek** [comment]
It takes almost 10 mins, but it works.

![image](https://user-images.githubusercontent.com/2270764/145479399-a39042f2-f78d-4df5-8f5d-f9da14e104b7.png)

I wonder about enabling printing the progress.

![image](https://user-images.githubusercontent.com/2270764/145479529-bfff8b53-6f34-43b6-a665-159ced593501.png)

**Comment by pomek** [comment]
We went with the solution posted in https://github.com/ckeditor/ckeditor5/issues/10982#issuecomment-989642362.
