### ISSUE TITLE
ms word to html to ms word

### ISSUE THREAD

**Issue by richard49bc** [ckeditor/ckeditor5#1103]
## Is this a bug report or feature request? (choose one)

I would like to know if it is possible to take ms word document , display it in your editor, edit it, save it , then convert it back to a word doc. If you don't provide these facilities do you recommend  third party s/w to work with your editor?

**Comment by wwalc** [comment]
As you already mentioned, ideally you should do something like:

```
MS Word document ---->
 ---> (conversion) ----> HTML (dirty) 
 ---> (cleaning up) ---> HTML (clean)
 ---> CKEditor --------> HTML (clean)
 ---> (conversion) ----> MS Word document` 
```

We do not have anything to recommend for the conversion process though. There are tools like [Pandoc](http://pandoc.org/demos.html), for example, but we did not use it.

The cleaning up process is optional, dpeends on your expectations/project requirements. For example it may turn out that in order to preserve text color/highlight you will need to make some extra steps.
