### ISSUE TITLE
Setting up Revision History

### ISSUE THREAD

**Issue by shaklin-essenvia** [ckeditor/ckeditor5#11078]
## 📝 Provide detailed reproduction steps (if any)

1. Follow the [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/revision-history/revision-history-integration.html#prepare-a-custom-build) 
2. Clone CKEditor5
3. Install Revision History
4. Copy the stub code from documentation
5. Build 

### ✔️ Expected result

Revision History Working

### ❌ Actual result

_What is the actual result of the above steps?_

<img width="1129" alt="Screenshot 2022-01-06 at 7 09 18 PM" src="https://user-images.githubusercontent.com/93765906/148391534-d936cf15-70d5-41ed-a401-277077de142f.png">

Error:

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Mac Os Monterey
* OS: Chrome 94
* First affected CKEditor version: …
* Installed CKEditor plugins: RevisionHistory

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply, this ticket somehow slipped our attention. It's hard to tell based only on the error message, without seeing the actual code, but I'd guess that revisions are not loaded properly because of some mismatch in `id` property of revisions or users.

Apart from that, revision history is a premium plugin and this repository is mainly for the open source part of the project. If you are using trial or are already a licensed user, we'd highly recommend to contact us via the [dedicated support channel](https://ckeditor.com/contact/). When reporting a bug, please remember to describe precise steps to reproduce the issue and provide as much information as possible about your environment, editor configuration, custom code you use, etc.
