### ISSUE TITLE
[GHS] Handle <style>

### ISSUE THREAD

**Issue by wimleers** [ckeditor/ckeditor5#11104]
**Sibling issue of #10891.**

`<style>` is now ignored by GHS and cannot be enabled with it in any way.

Discovered downstream, by Drupal: https://www.drupal.org/project/drupal/issues/3256566

## 📝 Provide detailed reproduction steps (if any)

1. Load the `htmlSupport.GeneralHtmlSupport` and `sourceEditing.SourceEditing` CKE5 plugins, with the following `htmlSupport` config:
```
{"allow":[{"name":{"regexp":{"pattern":"/.*/"}},"attributes":true,"classes":true,"styles":true},{"name":"style"}]}
```
2. Access a CKEditor 5 instance, use the `Source` button to paste this:
```
<style>p { color: red}</style>
<p>
    Hi
</p>
```
3. Click the `Source` button again to access the rendered HTML representation
4. Click the `Source` button again to access the raw HTML representation

### ✔️ Expected result
Exactly what we pasted:
```
<style>p { color: red}</style>
<p>
    Hi
</p>

```

### ❌ Actual result
```
<p>
    Hi
</p>
```

## 📃 Other details

* Browser: N/A — reproduced in Chrome and Firefox.
* OS: N/A — reproduced in macOS Big Sur
* First affected CKEditor version: `v31.0.0`
* Installed CKEditor plugins: see above.

**Comment by Reinmar** [comment]
*   `<style>` in CKEditor 4 does affect the editor content (applies to it). In CKEditor 5 we cannot go this way because we don't use an iframed editable element anymore and such a style element would affect the entire page. Hence, let's go the same way as we chose for `<script>`s – render a dummy `<span>` in the editing view.
*   Note: We must make sure that pasted content that contains `<style>`s.
    *   CKEditor 4 allows copy (from the editor) pasting `<style>` elements.
        *   Use case: copy&paste of the entire content does not change it.
    *   To be checked: 
        *   The `<style>` element that's in a content coming from Word does not leak to the content of the editor
        *   Same for paste from Google Docs
        *   Same for paste from an external website (on all browsers)

When discussing the above we realised that this is getting more and more complex and depends on the resolution of #11110. So, let's wait for #11110.
