### ISSUE TITLE
[iOS] Broken auto-capitalization for the first letter in each new line (iPhone)

### ISSUE THREAD

**Issue by zhaoyouliang** [ckeditor/ckeditor5#1111]
## Is this a bug report or feature request? (choose one)
🐞 Bug report 
Iphone 7plus : version :11.2.2

## 💻 Version of CKEditor
ckeditor5-build-inline 3

## 📋 Steps to reproduce

When composing notes on his iPhone, Damien is used to the auto-capitalization feature his phone normally provides in other text areas.  He'd like the first letter in each line to automatically become capitalized.

## ✅ Expected result
auto-capitalize
## ❎ Actual result
not

**Comment by zhaoyouliang** [comment]
Do you have a good way to do it ?@Reinmar
thanks

**Comment by Reinmar** [comment]
It's a bug so it requires a fix on our side. It's a tricky topic because we don't control this native behaviour (switching the onscreen keyboard to uppercase after a period+space and after a new line).

What we need to do, therefore, is to not get in a browser's way. This is tricky, because we want to handle input by ourselves. But, unless things will start to jump on the screen, we may try to allow the browser to perform its default action. There's a chance that removing this line: https://github.com/ckeditor/ckeditor5-enter/blob/a5ae66e3c590bab3d982bd29f2c869ea84761981/src/enter.js#L45 will help. With the new renderer, there's a chance that we'll even avoid re-inserting the new paragraph.

cc @f1ames could you check it, out of curiosity?

**Comment by zhaoyouliang** [comment]
@Reinmar I use this for testing：
```
      .editor p:first-letter {
         text-transform: capitalize;
  }
```
I found it works on the web, but in the mobile browser. I open the switch of Auto - Capitalization, then found that can't be done in safari Implement capital . It does work on Android machines. That's what I found。thank you very much

**Comment by Reinmar** [comment]
This would be a workaround. Interesting, but not something that we can ship with. Not every new paragraph must start with an uppercase letter. And this workaround doesn't fix the output data, which would still be lowercased.

**Comment by f1ames** [comment]
> What we need to do, therefore, is to not get in a browser's way. This is tricky, because we want to handle input by ourselves. But, unless things will start to jump on the screen, we may try to allow the browser to perform its default action. There's a chance that removing this line: https://github.com/ckeditor/ckeditor5-enter/blob/a5ae66e3c590bab3d982bd29f2c869ea84761981/src/enter.js#L45 will help. With the new renderer, there's a chance that we'll even avoid re-inserting the new paragraph.

Checked and removing mentioned line helps 👍 Haven't dive deeper what may get broken by this change though.

**Comment by derekm228** [comment]
After implementing this fix, a new issue arises:

1. Create first-level bulleting, enter a few lines of content.
2. Hit tab to create second-level bulleting, enter content and press enter

The cursor loses focus within the bulleting and immediately jumps to the top. Video attached:

[Bulleting_Bug.zip](https://github.com/ckeditor/ckeditor5/files/2383813/Bulleting_Bug.zip)

**Comment by josephdpurcell** [comment]
Note: I see a similar issue for ckeditor4 here https://github.com/ckeditor/ckeditor4/issues/4180 and one from an old site here https://dev.ckeditor.com/ticket/12142. I identified a similar issue with CodeMirror5 https://github.com/codemirror/codemirror5/issues/7009, though CodeMirror6 seems to not have the issue.
