### ISSUE TITLE
Secure slotFor() use for cases where only elements are used

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11163]
Extracted from #11149.

For now, we need to go for:

> *   D: Make slots handle only elements, not text nodes.
>     *   Reasonable for now.
>     *   Throw when a text node was encountered by `slotFor()`.

Source: [https://github.com/ckeditor/ckeditor5/issues/11149#issuecomment-1021291990](https://github.com/ckeditor/ckeditor5/issues/11149#issuecomment-1021291990)

Scope: The slot mechanism should throw an error when encountering a text node.

**Comment by Reinmar** [comment]
> ```js
>         model: 'myElement',
> ```

IF POSSIBLE in 10 minutes (if we have access to the schema): We may check whether the schema allows `$text` in `myElement`. If so, throw immediately.

If not possible, check&throw when the slot is being filled with nodes.

**Comment by niegowski** [comment]
Closed in #11229.

**Comment by oleq** [comment]
The #11229 has been merged and then reverted due to failing tests of the `Widget` plugin. Turns out, there were some tests that assumed that text can be allowed in an element that gets converted via `elementToStructure()`. Let's figure out whether the use case was valid and how many integrations would be affected if we went with an error in this case

https://github.com/ckeditor/ckeditor5/blob/92595b24cf455abfad8f97fbe39162b7f1fb4d42/packages/ckeditor5-widget/tests/widget.js#L232-L239
