### ISSUE TITLE
ckedior5 abort highlight

### ISSUE THREAD

**Issue by ToggDream** [ckeditor/ckeditor5#1119]
hello
   My project does not use NPM , used HTML +jquery. How can I introduce highlight in ckeditor?

**Comment by Reinmar** [comment]
Hi!

You need to use npm to [install this plugin](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/installing-plugins.html) because by default it's only available in the [document editor build](https://docs.ckeditor.com/ckeditor5/latest/examples/builds/document-editor.html). There's no other way to install a new plugin.

**Comment by ToggDream** [comment]
Therefore, I can't use the highlight plug-in, but I want to make the font color change, without NPM, how to implement it?

**Comment by Reinmar** [comment]
The most straightforward way is to customise an existing build which is described in https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html. That will require you to use npm (cause customising a build requires that) but your project wont' have to use npm.
