### ISSUE TITLE
[Styles dropdown] Research feasibility of adding editing downcast converters for `htmlAttributes` attribute changes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11260]
### Why

Research for https://github.com/ckeditor/ckeditor5/issues/5700.

We need to figure out whether we can use GHS's `htmlAttributes` for SD.

### What

GHS uses `htmlAttributes` to store all attributes allowed by GHS on certain elements.

Currently, downcast converters for GHS do not support changes of `htmlAttributes` value.

The idea is that this should update the editing view:

```javascript
editor.model.change( writer => {
	writer.setAttribute( 'htmlAttributes', newValue, pElement );
} );
```

Currently, it will have no effect on the editing view.

**Comment by maxbarnas** [comment]
I can confirm that it's quite simple to add converter for editing pipeline in GHS. Actually, I reused the converter for data pipeline with no changes. What is missing is the case where the attributes are removed. This is missing because data downcast converter was created as a one-way transformation.
