### ISSUE TITLE
Spike for creating a custom rule for "stylelint"

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#11270]
## Provide a description of the task

In https://github.com/ckeditor/ckeditor5/issues/6082, we'll introduce a custom rule for the "eslint" tool.

However, in the project, we also use "stylelint" for verifying CSS files. The main goal of the issue is to check whether we can write our own rule for checking license headers in `*.css`.

**Comment by przemyslaw-zan** [comment]
[Spike](https://github.com/ckeditor/ckeditor5/compare/ck/11270)

As it turns out, it is fairly easy to write custom rule to check license headers. My example is quite barebones, but more rigorous checks are possible to implement thanks to extensive [PostCSS API](https://postcss.org/api/#comment-raws). Automatic fixing is possible as well.

**Comment by pomek** [comment]
Awesome. So, we can prepare a new repository for custom stylelint plugins and port this code here.

I close the spike as it proves the goal is doable.
