### ISSUE TITLE
table - insert table stop/reset number list

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor5#11281]
## 📝 Provide detailed reproduction steps (if any)

1. create number list
2. insert table

3. cant keep the number list/ if insert it in the middle reset the number

### ✔️ Expected result

keep the number/order list

### ❌ Actual result

reset/stop the number list

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---
first:
![media1](https://user-images.githubusercontent.com/59637560/154027510-cf7dd08f-f2f0-42b4-b00f-ade486c524e8.gif)
second:
![media2](https://user-images.githubusercontent.com/59637560/154027626-88521efb-331f-4b84-8ce7-dbff1507710c.gif)

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
Hello @kuku711 👋 

Tables in CKEditor 5 are block elements and in the current implementation, it is not supported to put them into a list. Therefore, it is expected behaviour at the moment.

However, we are currently working on the feature that will support this. To track the progress of that effort you might take a look here: #2973 

Closing.
