### ISSUE TITLE
[Document list] Cannot remove a widget which is a list item

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11346]
## 📝 Provide detailed reproduction steps (if any)

1. Switch to `ck/10812-document-list-editing` 
2. Create a list with a few list items and a table as one of the list items
3. Select the table
4. Press `backspace`

### ✔️ Expected result

Table is deleted, there is an empty list item.

### ❌ Actual result

Table is not deleted. The list item after the one with the table gets deleted.

### Screencast

https://user-images.githubusercontent.com/34380544/155955622-9c540e1d-8a31-48ec-b029-8e87b6a7d07a.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
The editor does not differentiate these two situations:

![](https://user-images.githubusercontent.com/156149/156341197-3a8b6096-dac1-43ca-9101-27816078dc2b.png)

And this one:

![](https://user-images.githubusercontent.com/156149/156341261-5c3c2b5d-efc9-4806-8de8-9056b58ce9ed.png)

**Comment by Reinmar** [comment]
Expected behavior: When the table is selected, the table should be removed.

Possible future improvements:

*   If we have a fake caret before a widget, then on backspace, the current item (the one with the table inside) should be merged to the preceding item (2). This deserves a followup but definitely should not be part of this ticket.

**Comment by oleq** [comment]
Closed in #11527.
