### ISSUE TITLE
[Plain table output]: The PlainTableOutput overrides downcast converters of other features

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#11394]
### Why

This ticket is a follow-up to [#11240](https://github.com/ckeditor/ckeditor5/pull/11240).

There's a bug in the converter that it affects conversion of `<caption>` elements in other widgets than table.

Use this below code (excerpt from [`ImageCaptionEditing`](https://github.com/ckeditor/ckeditor5/blob/1824dce6d132c3118d70ddf02a80ed5d1e118371/packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js#L106-L115)):

```javascript

// Model -> view converter for the data pipeline.
editor.conversion.for( 'dataDowncast' ).elementToElement( {
    model: 'caption',
    view: ( modelElement, { writer } ) => {
        const imageUtils = editor.plugins.get( 'ImageUtils' );
        if ( !imageUtils.isBlockImage( modelElement.parent ) ) {
            return null;
        }

        return writer.createContainerElement( 'foobar' );
    },
    converterPriority: 'high'
} );
```

It should override ImageCaptionEditing's converter to produce the `<foobar>` element instead.

It works without the `PlainTableOutput` plugin but fails with it (if the order in which plugins are loaded is `PlainTableOutput, ImageFooBar`).

**Comment by Reinmar** [comment]
Let's merge this to the `release` branch because it seems to be a blocker.

**Comment by dawidurbanski** [comment]
@Reinmar Pull request is ready to review: https://github.com/ckeditor/ckeditor5/pull/11407

**Comment by dawidurbanski** [comment]
This was happening due to the fact that the `PlainTableOutput` downcast converter was unnecessary creating `<figcaption>` element for all model elements other than table.

Since this converter is registered with the `high` priority, only higher priority converters would actually be able to override this behaviour. In case of other `high` priority converters it was a plugin loading order issue.

The solution was to just simply do nothing inside the converter callback if we detect we are within other element than table.
