### ISSUE TITLE
Not escaping the list item when at the start of code block

### ISSUE THREAD

**Issue by CatStrategist** [ckeditor/ckeditor5#11538]
### Steps:
1. Create a list item
2. In this list item add codeblock
3. Type `foo`
4. Put the cursor at the beginning of the text - `[]foo`
5. Press `backspace`

### Expected:
List item is removed.

### Actual:
Nothing happens, `backspace` for removing list item works only if you first remove the whole text.

### Screencast:

https://user-images.githubusercontent.com/34380544/161070329-1dd450e1-1fe1-4c64-8d33-4a8df7999196.mp4

_Originally posted by @FilipTokarski in https://github.com/ckeditor/ckeditor5/issues/11377#issuecomment-1084601510_

**Comment by FilipTokarski** [comment]
This behaviour is cased by the `Text part language` plugin. If you remove it from the build, everything works fine.

**Comment by arkflpc** [comment]
Root cause: `CodeBlockEditing` added `codeBlock` element to model with `language` attribute. `TextPartLanguageEditing` was triggered by this attribute and added `span` around `codeBlock` which wasn't expected by `DocumentListEditing`'s downcast. So the list was outdented correctly in the model, but view retained `<ul><li>...</li></ul>`.

Possible solution: Downcast in `TextPartLanguageEditing` should ignore `language` attributes when the item is neither `$textProxy` nor `documentSelectin`
