### ISSUE TITLE
Table / SwitchButton - Incorrect initial value

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1156]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest masters

## 📋 Steps to reproduce

1. Build docs and go to **Features / Table** page
2. Click _Milk_, then click switch button (Header row) inside _Row_ dropdown.

## ✅ Expected result

First row shouldn't be the header row.

## ❎ Actual result

SwitchButton does not change anything. After second clicking, everything works fine.

## 📃 Other details that might be useful

![lip-16-2018 10-46-59](https://user-images.githubusercontent.com/2270764/42750234-cbd819a2-88e6-11e8-8adf-ff028d725b16.gif)

**Comment by jodator** [comment]
DUP of: https://github.com/ckeditor/ckeditor5-table/issues/34.

**Comment by pomek** [comment]
I'm not sure how this ticket is a dup of https://github.com/ckeditor/ckeditor5-table/issues/34. 

I'm describing an issue related to SwitchButton. From my point of view, SwitchButton has initial value equals to `false` but it should be `true` because the switch is active and the entire row is marked as a header. After the first click, the value is switching to `true`, some commands are executing but… we switched from active to active.

**Comment by jodator** [comment]
On the GIF:
1. you click in header
2. the switch button is ON (initial value is `true`)
3. you click it
4. the headings get shrunk from `headingRows=2` to `headingRows=1` (a bug)
5. the switch button is ON
6. you click it
7. the heading get shrunk from `headingRows=1` to `headingRows=0` (OK)
8. the switch button is OFF (as currently selected row isn't a heading)

The steps 4,5,6 are redundant. After step. 4 you should have `headingRows=0` and that ticket is abut that.

The thing that button is ON (initial value is `true`) is by design as this indicates that currently selected row is a heading. So moving from that clicking it should remove a header - so it's value will `false` then.

**Comment by pomek** [comment]
👍
