### ISSUE TITLE
[Style dropdown] Missing integration with block widgets

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11577]
Pretty self-explanatory, it should be possible to apply and remove styles on block widgets.

Support for inline widgets is tracked in a separate issue #11584.

**Comment by wimleers** [comment]
Being reported by the Drupal community over at https://www.drupal.org/forum/support/post-installation/2022-11-30/how-do-i-configure-the-styles-dropdown-in-ckeditor-5#comment-14808215

**Comment by graber-1** [comment]
Here's an issue with some additional info I discovered when trying to add / remove classes to a <table> tag that may be of some help: https://github.com/ckeditor/ckeditor5/issues/13208.

**Comment by Reinmar** [comment]
DUP in #12441. You can find some valuable context in it.

**Comment by Witoso** [comment]
[In May](https://github.com/ckeditor/ckeditor5/issues/11574), we closed a significant iteration on Styles (integrating with tables, lists, etc.) As this issue is pretty generic, and we need more specific needs, I will close it.

We have an umbrella issue for further refinements: #14274. Open new issues (and link to them in the epic), and we’ll look into them. Thanks!
