### ISSUE TITLE
Django ck-editor can't add extra plugin

### ISSUE THREAD

**Issue by MDFARHYN** [ckeditor/ckeditor5#11592]
I am trying to add an extra plugin but I can't. When I am inspecting my console it's saying can't load the javascript file. Here is my code:

error which I am getting in my console but I have youtube plugin in my plugins folder:

`Loading failed for the <script> with source “http://127.0.0.1:8000/static/ckeditor/ckeditor/plugins/youtube/plugin.js?t=LAHF”.`
settings.py

```
STATIC_ROOT = 'var/static'

CKEDITOR_UPLOAD_PATH = "uploads/"

 CKEDITOR_CONFIGS = {
        'default': {
            'toolbar': 'full',
            'extraPlugins': ','.join([
                'youtube',
            ]),
    
        },
    }
urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
models.py

class Blog(models.Model):
    blog_title = models.CharField(max_length=255)
    blog_body = RichTextUploadingField(blank=True, null=True,)


#I also tried this but didn't work:
blog_body = RichTextUploadingField(
        config_name='default',

        # CKEDITOR.config.extraPlugins:
        extra_plugins=['youtube'],

        # CKEDITOR.plugins.addExternal(...)
        external_plugin_resources=[(
            'youtube',
            'var/static/ckeditor/ckeditor/plugins/youtube/',
            'plugin.js',
        )],
    )
```

**Comment by FilipTokarski** [comment]
Hi, I'm not sure if the problem here is with the editor or your Django app. Does your CKEditor work correctly when using it outside Django and adding the extra plugin? If yes, then please make sure that in your Django app you have properly collected and loaded the static files. 
But if the standalone editor does not work, then to add a plugin to CKEditor you would need to basically create a new build (install plugin, add to source file, bundle the editor again). Please see the [docs on installing plugins](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/installing-plugins.html). If you don't want to do everything manually, you can always use [online builder](https://ckeditor.com/ckeditor-5/online-builder/), to download a custom editor build.

**Comment by MDFARHYN** [comment]
Thanks for your comment. After lot of research I found that my static files was not loading properly. Then I put **ck-editor** all files in my static directory and now it's working. I want to share my code. It will help others people if they want to add extra plugin and don't know how to do it.

For adding extra plugin you have to download the plugin then put it in your ck-editor plugin folder which look like this `static/ckeditor/ckeditor/plugins` then add the name of your extra plugin 

**settings.py**  
```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'extraPlugins': ','.join([
            'youtube', #add your extra plugin name
            'codesnippet',
          
        ]),
        "removePlugins": "exportpdf",

    },
}
```
