### ISSUE TITLE
[beforeinput] Handle changes triggered by direct modification of DOM

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#11636]
Part of #11438.

## Provide a description of the task

Although `beforeinput` makes mutation-based typing obsolete, some external applications (spell checkers, etc.) may still want to modify the editing root via native DOM API. We may need a basic mutation observer logic to be able to respond to these changes.

However, any other changes applied directly to the DOM, without being applied to the editing view first must be reverted (that's the current behavior on `master`). In other words, this mechanism must ensure that any changes applied to the DOM, that were not also applied to the editing view, must be reverted.

A separate question is whether we should keep the current `mutations` event.

Relevant pieces of code that ensures that changes applied to DOM are then checked by the rendered and reverted if needed:

*   https://github.com/ckeditor/ckeditor5/blob/f1ab675836473ca1e29cc3e3409fb433808e0d13/packages/ckeditor5-engine/src/view/observer/mutationobserver.js#L201-L224
*   https://github.com/ckeditor/ckeditor5/blob/f1ab675836473ca1e29cc3e3409fb433808e0d13/packages/ckeditor5-engine/src/view/observer/mutationobserver.js#L253-L254

**Comment by Reinmar** [comment]
How do Grammarly and WSC apply their suggestions to the content?

* WSC uses our API so that's safe.
* Grammarly uses clipboard API so that's safe too.

Hence, none of them relied on the mutation observer + typing support. There's a chance that there are some external applications that did rely on this,  but:

* We don't know of any.
* They relied on a completely accidental behavior.
* Even if we tried to keep the current typing observer as a fallback, there's a high chance that due to the migration to beforeInput something would change in this mechanism that would break these accidental integrations.

**Comment by Reinmar** [comment]
> A separate question is whether we should keep the current `mutations` event.

It's very unlikely that anyone beside us uses this event. We don't have any way to learn that except removing it and waiting for feedback.

Hence, let's remove it (it's actually already removed on the PoC branch) and wait for the feedback.

**Comment by Reinmar** [comment]
Closed by #12024.

**Comment by urbanspr1nter** [comment]
This I think actually broke our spell checker integration. Our spellchecker (MS Editor) actually does a directly mutation on the DOM. I think after 35.3.0 released which has the beforeinput migration, everything is now broken. :( 

Any plans to bring this back?
