### ISSUE TITLE
CKEditor versions

### ISSUE THREAD

**Issue by Trysor** [ckeditor/ckeditor5#1164]
## Is this a bug report or feature request? (choose one)

Other (brainstorm / suggestion)

## 💻 Version of CKEditor

This here is the topic of this issue:

alignment, basic-styles, block-quote, heading, paragraph: 10.0.2,
editor-classic, theme-lark: 11.0.0
essentials: 10.1.1
link, dev-utils: 10.0.3
list:11.0.1
image: 10.2.0
webpack-plugin: 6.0.3

And those are (I think...?) supposedly compatible with CKEditor version 11.

## 📋 Steps to reproduce

Attempt to install versions that work together, post webpack 4.0 and that are compatible with CKEditor 11.

## ✅ Expected result

**Easily** recognize and install correct versions compatible with webpack 4.0 and CKEditor 11

## ❎ Actual result

I have no clue which versions (of both plugins and dev tools) are and are not compatible with CKEditor 11 by just looking at the version numbers. I have no clue which versions exist either; have to look them up one by one.

## 📃 Other details that might be useful

Looking at for instance [Angular](https://github.com/angular/angular), they release a new version across all their sub-packages whenever one (or more) has changes, so that all their package-versions are in sync. This may be easier to follow for custom-build developers.

**Comment by Reinmar** [comment]
This wasn't an easy choice for us how to version all these things. We knew that this is confusing – it's in fact, a bit problematic for us too. However, there are advantages of such a scheme as well.

All source packages follow [semver](https://semver.org/). This means that we can treat them separately, which already happened as you can see by the numbers. E.g., one package can have a breaking change without affecting the whole project. If you're a consumer of this package you will easily learn whether you can upgrade it easily or not.

While a single-version strategy may work for Angular, it'd be a lot more problematic for us. AFAICS, Angular [has about 20 pkgs](https://github.com/angular/angular/tree/master/packages) (so far less than we have) and they seem to have different nature than our packages. Most of our packages are plugins, which are highly independent so we even went a step further and keep them in separate repositories. Angular packages seem far more connected. I may be mistaken regarding Angular, because I don't know it well, but nevertheless, our cases are certainly quite different.

Besides, we actually do what Angular does in the most "public" API which are CKEditor 5 builds. They always follow the version of the whole project.

If you'd like to read more about it we discussed it in https://github.com/ckeditor/ckeditor5/issues/426#issuecomment-300280971.

---

So how to leave with that? You can always find the latest versions in https://github.com/ckeditor/ckeditor5/blob/stable/package.json. That's a good reference point.

The other options include tools like [Greenkeeper](https://greenkeeper.io/), [npm-check](https://www.npmjs.com/package/npm-check) or always doing `npm i --save-dev <all-cke5-deps>`. We use `npm-check` quite often to handle dependencies of our tools (because this problem is not specific to CKEditor 5 :)).

**Comment by Reinmar** [comment]
I'm close this ticket as a DUP of #426.

**Comment by Reinmar** [comment]
PS. If you have some ideas how we could improve the visibility of what are the latest versions of our source packages or what other changes we might do, we'd love to hear that. But I think that, based on our observations how the current versioning model works, changing it is not an option (yet). Let's see if we'll have more feedback on this.

**Comment by Trysor** [comment]
Thank you for the reply. It is indeed an issue that require thought. One major part of this is, as you mention, whether developers can verify upgrade strategy or not. Granted a perfect world where every code repository is flawless -- source and target -- semver works. However, bugs happen. Unforeseen breaking changes, weird configurations (as you've already seen and done work to mend), unnoticed bugs and incompatible versions (which does not show all to well between say versions a.b.c1 and a.b.c2 of package so-and-so and x.y.z of package this-and-that) all muddles the waters somewhat.

Good error messages also connect with this; updating a package (major as well as minor versions) and then getting an error which is explicit and well formed gives much better insight whether said error is something you ought to handle / solve there and then or whether to roll back and delay upgrading, compared to errors that are not. The sources of errors -- connecting them to a given plugin or package and their respective versions -- is a sore point of CKEditor as things currently stand.

I mention errors here because the "this is supposed to work" part of synced versions is a lot clearer. If all packages are version 11.0.3 then the fault is (a lot more likely to be) with your code and you need to find it. If the packages you have installed are of versions x.y.z, a.b.c, 1.2.3 it could still be an issue with your code but the scope widens to also include package compatibility mismatch, and you will have to look up each package separately to figure out what versions of CKEditor "core" they belong to.

I do not have answers here. Both aforementioned approaches have their strengths and drawbacks.

**Comment by Reinmar** [comment]
> I mention errors here because the "this is supposed to work" part of synced versions is a lot clearer. If all packages are version 11.0.3 then the fault is (a lot more likely to be) with your code and you need to find it. If the packages you have installed are of versions x.y.z, a.b.c, 1.2.3 it could still be an issue with your code but the scope widens to also include package compatibility mismatch, and you will have to look up each package separately to figure out what versions of CKEditor "core" they belong to.

This is an interesting point. But I don't think that having one-version model would completely solve it. Let's say you use `ckeditor5-editor-classic@11.0.0` and there are two plugins `ckeditor5-paragraph@11.0.0` and `ckeditor5-basic-styles@11.0.0` (so, all versioned the same way). Now, all these packages depend on `ckeditor5-engine@^11.0.0`, but one day we release `ckeditor5-engine@11.0.1` cause there was some bug. This means we also release `11.0.1` versions of all the other packages.

If we made a mistake, and the change in the engine is breaking (but that change worked with `11.01` version of all the other packages), it may happen (depending on how your `package.json` looks) that you'll have `11.0.0` of all the packages except `ckeditor5-engine` which will be in `11.0.1` cause it's not listed in `package.json`. So, you have this in your `package.json`:

```js
"ckeditor5-editor-classic": "11.0.0",
"ckeditor5-paragraph": "11.0.0",
"ckeditor5-basic-styles": "11.0.0",
```

And yet it doesn't work. Using `package-lock.json` would help with this situation not happening completely automatically, but it can still happen.

So, for us, it's a kind of a bigger problem. Due to transitive dependencies, things may blow up unless you have the latest versions of everything. We were thinking how to improve this and you can see my long comment in https://github.com/ckeditor/ckeditor5/issues/1061 with some findings. At the end of that long comment there's a list of improvemnts that we planned or did already. E.g. we've already added a runtime check which links to this error: https://docs.ckeditor.com/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-version-collision. We also plan to add a check in our `CKEditorWepbackPlugin`  which will detect situation where you have some packages duplicated (due to version mismatch). This should help further. But I know that it's still not everything. What else could we do?
