### ISSUE TITLE
content-styles.css can not be applied to the browser directly?

### ISSUE THREAD

**Issue by yoyo837** [ckeditor/ckeditor5#11646]
## Provide a description of the task

Browsers do not support css nesting. Do I need to compile it with tools such as postcss before using it?

<img width="480" alt="image" src="https://user-images.githubusercontent.com/6134547/163797162-5f674441-111c-4b1c-a225-88b03c8b6c27.png">

I copied it from https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html

## 📃 Other details

* Browser: Chrome latest.
* OS: macOS 12.3.1
* CKEditor version: 34.0.0
* Installed CKEditor plugins: …

**Comment by yoyo837** [comment]
Please forgive my wrong choice of label.

**Comment by yoyo837** [comment]
33.0.0 does not have this problem

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/163798297-14a8c15b-8d69-43bd-ba25-18dd045a32e3.png)

In two days it changed

**Comment by pomek** [comment]
The [`Once`](https://postcss.org/api/#plugin-once) hook used by the extractor (a custom PostCSS plugin) is called _before_ processing a file. We need to use [`OnceExit`](https://postcss.org/api/#plugin-onceexit) instead.

https://github.com/ckeditor/ckeditor5/blob/0f6c74b82278a6b8ccb8cfebc05d9eb29af19238/scripts/docs/list-content-styles-plugin.js#L28

I am sure this change is somehow connected with https://github.com/ckeditor/ckeditor5-dev/releases/tag/v30.1.3. Unfortunately, when checking whether the upgrade was safe, I focused on building processes instead of verifying their content.

I apologize.

**Comment by pomek** [comment]
Fixed on https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html.
