### ISSUE TITLE
[TS MVP] Research how to build API Docs from *.ts files

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#11721]
Running `yarn run docs:api` should produce exactly the same documentation for `.ts` files that it would if they were `.js` files.

Probably the easiest way it could be done, by first converting them to `.js` retaining JsDoc comments. I wouldn't bother with TypeScript type annotations in MVP, just JsDoc comments.

**Comment by arkflpc** [comment]
Let's see if https://www.npmjs.com/package/better-docs would be ok for us.

**Comment by Reinmar** [comment]
Story:

*   We'll be migrating gradually. Hence, we need a solution that handles JS + TS
*   We use JSDoc + many custom plugins. JSDoc's JSON output is fed to Umberto.
*   TSDoc is not compatible with JSDoc.
*   **Idea 1**: Transpile TS files to JS and feed that to JSDoc
    *   Similar to what the above-mentioned better-docs does
    *   Unfortunately, TS strips some comments (especially ones not adjacent to any TS code) during transpilation and there's no sane/safe way around this. 
    *   Hence: 🛑
*   **Idea 2**: Rewrite entire API docs to TSDoc
    *   We'd need to have all doclets rewritten at once. TSDoc does not understand JSDoc's doclets.
    *   TSDoc's output differs from JSDoc's one.
    *   We'd also have to port our custom JSDoc pugins (~10).
    *   In the future, it'll make sense to migrate to TSDoc.
*   **Idea 3**: Rewrite JSDoc so it handles JS and TS, but for our needs only
    *   We considered this anyway due to JSDoc's issues and many custom plugins that we had to maintain due to missing JSDoc's features.
    *   This is a complex task anyway. Two different parses (JS and TS) and two mechanisms extracting them from these different ASTs
    *   A lot of work would need to be put now into handling JS that we'll get rid of soon anyway.
*   **Idea 4**: Extract all doclets from TS files and feed that to JSDoc
*   **Idea 5**: Use existing API docs for the time being (and pretend we froze the API)
    *   This will motivate us to port code of remaininig packages faster
    *   But we need to have integration with TSDoc ready
    *   We could use this occasion to fix some odd decisions (e.g. protected vs package)

**Comment by Reinmar** [comment]
Questions to be answered:

*   What TSDoc can? What features would we miss in it? What we'd have to customize? This is a universal question that we need to answer regardless of the migration option, if we ever want to use TSDoc.
*   Figure out how Umberto works – what's the input format of its API builder? How doable it is to convert TSDoc's format to make it Umberto-compatible. This is again a universal question if we ever want to use TSDoc.

**Comment by Reinmar** [comment]
We continued researching TS-related docs builders and found also TypeDoc. However, after giving it more thought, building from JS and TS files at the same time and merging those two JSON outputs into one and feeding that to Umberto is crazy. A lot of work, if feasible at all. What's worse – this would be needed only temporarily. 

Therefore, we decided to go with option 4. For the time being, we'll also keep the JS files, next to the new TS files.

**Comment by oleq** [comment]
# Full API docs migration to TS

## TSDoc vs TypeDoc

There are two serious projects on the market that allow building API docs out of TS files with the support for JSON output.

### Arguments for TSDoc

*   TSDoc is maintained by Microsoft, it should get updated quicker when a new TS version is out.
    *   OTOH TypeDoc is in the [TypeStrong org on GH](https://github.com/TypeStrong). They provide the official TS loader for Webpack so they’re not anonymous either.

### Arguments for TypeDoc

*   TypeDoc produces JSON that is easier to read and parse.
*   TypeDoc parses `*.ts` files directly. (TSDoc requires generating `.d.ts` declaration files first)
*   TypeDoc understands more of the JSDoc syntax (e.g. `@module`) out-of-the-box.
*   TypeDoc is slightly more popular than TSDoc + api extractor.

**Decision for the PoC: TypeDoc.** For the record: I’m using this assumption in the rest of the document. But if we go with TSDoc for whatever the reason, IMO this will not change much in what follows.

## Some notes about building the API docs

*   Currently, the building chain works as follows:
    1.  When you call something like `yarn docs --skip-validation --skip-snippets --skip-guides`...
    2.  In `ckeditor5` the `build-docs.js` gets executed…
    3.  And it runs `lib/docs/index.js` in `ckeditor5-dev-docs`...
    4.  Which loads the JSDoc plugins and runs JSDoc…
    5.  Which then outputs the JSON file to `ckeditor5/docs/api/output.json`...
    6.  Which is then used by Umberto in `build-api-docs.js` task…
    7.  That utilities `ApiBuilder`...
    8.  That uses the `data-converter` stack with `jsdoc2umberto.js` and `jsduck2umberto.js` to process `output.json` and feed it to Umberto so HTML pages are built out of templates.
*   Umberto has been developed with CKE5 in mind. Since CKE5 API docs are built with JSDoc, its input format is like ~98% JSDoc.
    *   There are two dedicated converters in Umberto: `jsdoc2umberto.js` and `jsduck2umberto.js`. The latter is used for CKE4.
    *   `jsdoc2umberto.js` is very small. Like I said, Umberto understands JSDoc.
    *   In the PoC, another `typedoc2umberto.js` converter was developed.

## About the PoC

*   To run the PoC, you need to check out `ck/11721-build-API-from-typedoc` branches in 3 repositories: `ckeditor5`, `ckeditor5-dev`, and `umberto`.
    *   In `ckeditor5/node_modules` create symlinks to `ckeditor5-dev-docs` and `umberto`.
    *   **Note**: The branch in `ckeditor5` is based on the TS migration epic branch `ck/epic/11708-migrate-typescript-mvp`. Merge the epic for the latest collection of TS files.
    *   **Tip**: Before you check out the branches, narrow down the scope of the API built by JSDoc in `ckeditor5/scripts/docs/buildapi.js` (to a couple of files, just a single package, etc.) and run the default docs builder. Copy the `ckeditor5/docs/api/output.json` file somewhere else, it will work as a reference for you when writing a converter from TypeDocs JSON format to Umberto JSON format.
*   API docs should build after `yarn docs --skip-validation --skip-snippets --skip-guides`.
    *   **Note**: Only `ckeditor5-utils` was written in TS when the PoC was created.
    *   **Note**: The current `typedoc2umberto.js` is very rough. I suppose it converts ~10% of the doclet data it should. Don’t expect much in the generated API docs, it’s a PoC.
*   **Tip**: In `ckeditor5/scripts/docs/buildapi.js` you can narrow down the scope of TS files. The `ckeditor5/docs/api/output.json` generated by TypeDoc (previously by JSDoc) is massive (megabytes for the entire project). You probably want to narrow it down to a single or just a couple of files to understand what is going on.
*   **Tip**: In `ckeditor5-dev-docs/lib/docs/index.js` uncomment `typeDoc.generateDocs()` that will make TypeDoc generate the standard docs (out of default HTML templates) next to the `output.json` file (used for screenshots below). This will give you a chance to see what the “official” documentation looks like and what is missing while extending Umberto and/or writing typedoc→umberto converter.

## TODOs and tasks breakdown

Here are the tasks that need to be done on top of the PoC to get everything done:

### In Umberto

*   `typedoc2umberto.js` converter
    *   If you compare the JSON output from JSDoc and TypeDoc you’ll find out they’re dramatically different (it’s even worse for TSDoc). Conversion from one structure to another is not easy and the [lack of official reference for the JSON file](https://typedoc.org/guides/development/#json-output) does not help.
        *   Writing this converter is a reverse engineering task followed by a trail and error implementation.
    *   There’s a lot of new syntax in TS that does not exist in JS. Types can be expressed in many different ways.
        *   We support simple types (`Boolean`, `String`), unions `Foo | Bar`, and more complex ones like `Map<String,Object>`. These convert to Umberto quite easily.
        *   But in TS world, types can be `string | { [ name: string ]: unknown }` or `set<K extends keyof this & string>( name: K, value: this[ K ] ): void;` or `bind<K1 extends keyof this & string, K2 extends keyof this & string>(bindProperty1: K1,bindProperty2: K2): DualBindChain<this[ K1 ], this[ K2 ]>;` which is quite complex by itself and even more in JSON.
            *   You need to find a way to convey this to Umberto and present to the reader.
            *   Umberto understands the JSDoc JSON syntax. There’s no spec for these complex types in the JSDoc syntax, so writing a converter is not only 1:1 mapping between formats but coming up with the new JSON syntax for new TS stuff.
    *   **Decision to be made**: When CKE5 goes pure TS, there will be no JSDoc-based project to document using Umberto (to be confirmed). Maybe instead of writing a converter from TypeDoc to JSDoc, we’d be better off if Umberto understood the output of TypeDoc? This way we’re future-proofing Umberto (I guess other projects will also go TS) and only `jsduck2umberto` needs to be updated (JSDuck → JSDoc becomes JSDuck→TypeDoc).
*   Umberto API template renderer to consume all the new stuff from JSON and present it to the readers.
    *   This includes complex types for parameters and return values:

![](https://user-images.githubusercontent.com/1099479/174604208-b1b765d9-4559-4861-b643-d15fdd8982f1.png) ![](https://user-images.githubusercontent.com/1099479/174604230-9eb893cd-6d4a-4fdf-8a78-debcbd10f06b.png)

*   This includes support for function overrides. Each override can (should…) have its own doclet. See what it looks like when TypeDoc generates HTML (see the tip about `typeDoc.generateDocs()`).

![](https://user-images.githubusercontent.com/1099479/174604169-7851452b-8192-49a1-88ac-e52657963ec8.png)

![](https://user-images.githubusercontent.com/1099479/174604181-53a7597d-fe46-4d97-aaa8-026092bb8a9a.png)

### In ckeditor5-dev

*   In `lib/docs/index.js`: Support for `JSDOC_VALIDATE_ONLY` and `JSDOC_STRICT_CHECK`. Honestly I was lost when I tried to understand which is used when but I assume we need them for the CI (together with the JSDoc plugin below 👇).
*   In `lib/docs/index.js`: Support for `extraPlugins`. Not sure which project injects anything extra but we need to check this out before we get into the task.
*   Porting existing JSDoc plugins to Typedoc if they are still necessary. Before we dig into that, it’s worth checking for off-the-shelf solutions among the plugins provided by TypeDoc [https://typedoc.org/guides/plugins/](https://typedoc.org/guides/plugins/).
    *   `jsdoc/plugins/markdown` ("Translate doclet descriptions from Markdown into HTML.")
        *   I assume Umberto expects the doclet comments to be HTML, not MD. So we’d need to do that too if we went with `typedoc2umberto`.
    *   `@ckeditor/jsdoc-plugins/lib/purge-private-api-docs`
        *   Integration with the @PublicAPI tag. Mandatory.
    *   `@ckeditor/jsdoc-plugins/lib/export-fixer/export-fixer`
        *   [Pre-processing](https://github.com/ckeditor/ckeditor5-design/blob/jsdoc-module-test/jsdoc/plugins/export-fix.js) for `export` statement. Could be handy. For instance, TypeDoc generates “default” as a name of the function if this is the `export default function someName()` and, even though, it does not matter for the import statement (you can name it whatever you want), this looks pretty weird in the docs (lots of functions named “default”).
    *   `@ckeditor/jsdoc-plugins/lib/custom-tags/error`
        *   `@error` tag support. Mandatory (didn’t see anything like this in TypeDoc).
    *   `@ckeditor/jsdoc-plugins/lib/custom-tags/observable`
        *   `@observable` tag support. Mandatory.
    *   `@ckeditor/jsdoc-plugins/lib/observable-event-provider` Mandatory. "Creates event doclets for observable properties if they're missing."
        *   `@ckeditor/jsdoc-plugins/lib/longname-fixer/longname-fixer`
            *   I don’t know what it’s for. More research is needed.
    *   `@ckeditor/jsdoc-plugins/lib/fix-code-snippets`
        *   Code snippet pre-processor for JSDoc. I’d assume it’s obsolete.
    *   `@ckeditor/jsdoc-plugins/lib/relation-fixer`
        *   Something about ignored doclets. Could also be JSDoc specific and, hopefully, become obsolete.
    *   `@ckeditor/jsdoc-plugins/lib/event-extender/event-extender`
        *   Injects `module:utils/eventinfo~EventInfo` probably also mandatory.
    *   `@ckeditor/jsdoc-plugins/lib/cleanup`
        *   Some clean-ups, looks like this will also be mandatory.
    *   `@ckeditor/jsdoc-plugins/lib/validator/validator`
        *   Mandatory. I guess CI relies on this one.
    *   `@ckeditor/jsdoc-plugins/lib/utils/doclet-logger`
        *   A helper. IMO optional.
*   Tests.

### In ckeditor5

*   Re-configure `build-content-styles.js` so the content styles are built from TS files.
*   Change `.js` to `.ts` in `scripts/docs/buildapi.js`.
*   Make sure the CI works find (see `JSDOC_VALIDATE_ONLY` and `JSDOC_STRICT_CHECK` in ckeditor5-dev 👆)
*   Update some public (and internal?) guides about building the API docs of the editor.
