### ISSUE TITLE
Online builder for CKEditor 5?

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1174]
For CKEditor 4 we offer the [online builder](https://ckeditor.com/cke4/builder). It allows users to build a custom CKEditor 4 package online with selected additional plugins.
The last time I checked over 30% of CKEditor 4 downloads came from there.

For CKEditor 5 we could offer a similar service.

Few doubts:

 * Shall it offer just the official plugins made by CKSource so that e.g. one could build a version with markdown, font style or collaboration support easily?
 * Shall it offer all npm packages with [`ckeditor5-feature`](https://www.npmjs.com/search?q=keywords:ckeditor5-feature) keyword (including 3rd party)? (Cons: sometimes the created build could not work because e.g. of an incompatible plugin)

Anyone interested: add thumbs up if you **really** are interested in such a service and it would make your life much easier. Also add a comment if you have any particular requirements.

**Comment by Reinmar** [comment]
The simplest option would be an app which:

1. Finds features on npm (via its search API)
2. Extracts from those features informations about plugins which they expose. We'd need to describe these plugins in `package.json` or another file of each package.
3. Displays that list to the user, lets him/her choose plugins and the editor creator.
4. After you're done you press download and:
  * You get a zipped `ckeditor5-build-custom` directory with `package.json` and `webpack.config.js` and `src/ckeditor.js` preconfigured for you. The only thing you need to do is to type `npm run install && npm run build` in it. That's simple to do.
  * Our service would do the above for you (`npm run install && npn run build`) and let you download  either the same set of files which we expose now in zips, or `ckeditor5-build-custom` directory with the all the source files + a ready to use `build/` directory. The latter may be better because it will let you further play with that configuration. The problem with this solution is security and performance (a significant cost for us).

**Comment by wwalc** [comment]
In order to protect against security issues (e.g. packages intentionally published with a [malicious postinstall script](https://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability)), we were considering running every single build in an isolated container. Otherwise, if the same environment was reused for building packages, an attacker could write an own package, run the online builder with his package (that would poison other cached packages), causing the builder to serve packages with security issues.

That could be pretty inefficient. Using `npm install --ignore-scripts` could help us in protecting against this security issue and speeding up the builder, by allowing us to take benefit from the npm cache. Not sure though how many packages would be broken because of not running postinstall scripts. The good thing is that in theory we could simply filter out such packages and not list them in the online builder.

Regarding cache, to check if https://docs.npmjs.com/misc/config#prefer-offline would be fine in our case. https://docs.npmjs.com/misc/config#cache-min is deprecated.

**Comment by wwalc** [comment]
Once ready, please make sure to place an information about it in the documentation in all the places where it make sense / where it may be helpful for the reader. (Or at least make a follow up issue for this docs task)

**Comment by ma2ciek** [comment]
The CKEditor 5 Online Builder is live 🔥💥

Check it now: [https://ckeditor.com/ckeditor-5/online-builder/](https://ckeditor.com/ckeditor-5/online-builder/)

If you find anything not working as expected, report it here ([https://github.com/ckeditor/ckeditor5/issues](https://github.com/ckeditor/ckeditor5/issues))
