### ISSUE TITLE
paste table from word 

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor5#11746]
## 📝 Provide detailed reproduction steps (if any)

1. create table in word
2. add text before and after the table
3. paste to the editor

### ✔️ Expected result

editor will have the same display as the word

### ❌ Actual result

table is inserted as align left inline and not as block so all the text not display as in the word

### ❓ Possible solution

add to table align left/right as block (like images)

## 📃 Other details
WORD:
![image](https://user-images.githubusercontent.com/59637560/168014423-708aa0ce-3b9e-4507-b079-65bebcba70e2.png)
editor:
![image](https://user-images.githubusercontent.com/59637560/168014547-f9cd0db6-e347-4887-b333-b8aa419b9cae.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, are you sure you didn't have any additional formatting in your word file? I tried to reproduce it, but was unable to:

https://user-images.githubusercontent.com/34380544/168085309-7eab21e9-ba5c-4c77-8511-c039896e62a1.mov

In order to look into this issue, we'll need more information (word version, os, etc.) and precise steps on how to reproduce it.

**Comment by kuku711** [comment]
maybe because the table in the word is expanded, try to resize it to smaller one and than paste it

**Comment by FilipTokarski** [comment]
Still the same. After resizing, the table stays in the center as well.

**Comment by kuku711** [comment]
there is no any additional formatting.. clean version of office is 2019 and is RTL
