### ISSUE TITLE
Styles inside text editor

### ISSUE THREAD

**Issue by edirectorios** [ckeditor/ckeditor5#1178]
Hello, i'm using ckeditor5 for first tiem and i wanted to kow if there a way to add own styles to the text inside the InlineEditor.
Having  a basic structure like :
             

>     <div class="editor" >
>                      <span id="cover">I Cover Page</span>
>                         <p id="document">Document full title:...</p>
>                         <p id="scheme">Type Scheme:</p>
>                         <p id="participants">List of items:</p>
>                     </div>

I want that the editor keeps the style that are being applied to them.

Is that possible?
Thanks.

**Comment by wwalc** [comment]
@edirectorios did you mean that you want to keep CSS styles associated with "id" elements?

**Comment by edirectorios** [comment]
Right! Because ckeditor5 reset all styles

**Comment by wwalc** [comment]
CKEditor 5 is not dropping styles, the elements/attributes which are unsupported are removed, see https://docs.ckeditor.com/ckeditor5/latest/builds/guides/faq.html#why-does-the-editor-filter-out-my-content-styles-classes-elements-where-is-configallowedcontent-true

The text content is left unchanged, that's why most likely you understood it as having the styles removed.

Related (long) discussion: https://github.com/ckeditor/ckeditor5/issues/592
