### ISSUE TITLE
how to allow insert custom block element to document list?

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor5#11927]
## Provide a description of the task
I want to create custom element of block type and be able to insert the element inside a document list, 
there is a way to do it? i dont see there is schema of document list that let me do allow children

**Comment by dufipl** [comment]
Hello @kuku711,

For the starters, please be aware that the document list is currently on the "experimental" level (https://github.com/ckeditor/ckeditor5/issues/2973#issuecomment-1089355036) and we don't recommend using it in production without assessing the risk.

However, if you decide to give it a try, I can provide some tips for you.

If you would like to create your own custom widget and use it with the document lists, you need to register it inside of the schema as `$blockObject`:
```
schema.register( 'customWidget', {
	inheritAllFrom: '$blockObject',
	isBlock: true
} );
```

It is one of our generic items: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html#generic-items

Also, to insert that element you should use `model.insertObject()` instead of `model.insertContent()`. Example of that you can find here: https://github.com/ckeditor/ckeditor5/blob/ebc3465df4738054005c8c5f3c682b9e40a89970/packages/ckeditor5-html-embed/src/htmlembedcommand.js#L68

I hope that will help you, but please let me know if something remains unclear. :)

**Comment by kuku711** [comment]
thanks, its work !
i know its experimental i'm just checking my custom widgets because we will move to use it when it will be ready and will support checklist.

**Comment by dufipl** [comment]
I'm very glad to hear that! :) 

I will close the issue now but feel free to post new comments in case of any additional questions.
