### ISSUE TITLE
Allow to compile a single manual test

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#12251]
### Story

* **Given**: I am a developer who writes a plugin for CKEditor 5.
* **And**: I would like to compile a single manual test to preview my changes.
* **When**: I run the `yarn run manual -f ckeditor5/article` command.
* **Or**: I run the `yarn run manual -f alignment/alignment` command.
* **Then**: The testing environment compiles a single manual test.

### Scope

* Implement the story.
* Document the `--files` option for both (automated and manual) testing environments.
	* A guide to update: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/contributing/testing-environment.html
	* https://www.npmjs.com/package/@ckeditor/ckeditor5-dev-tests contains a description for supported rules. We can drop the table in favor of a redirect to the CKEditor 5 docs. 

### Hints

Debug notes from a refinement meeting:

```
yarn run manual -f ckeditor5/all-features.js # Does not work.

# ---

yarn run manual -f ckeditor5/manual/all-features.js # Does not work.
yarn run v1.22.18
$ node --max_old_space_size=8192 node_modules/@ckeditor/ckeditor5-dev-tests/bin/test-manual.js -f ckeditor5/manual/all-features.js
Removed directory '/Users/pomek/Projects/ckeditor/ckeditor5/build/.manual-tests'
[Webpack] Starting scripts compilation...
[Webpack] Finished the compilation.
[Server] Server running at http://localhost:8125/

# ---

yarn run manual -f alignment/alignment.js # Does not work now.

# ---

yarn run manual -f alignment/manual/alignment.js # We should skip the `manual/` directory.
```

**Comment by przemyslaw-zan** [comment]
[In current implementation of this feature](https://github.com/ckeditor/ckeditor5-dev/blob/4b66ccf50809a6fe7559b029de78dc67663756a2/packages/ckeditor5-dev-tests/lib/utils/transformfileoptiontotestglob.js#L12-L17), the `foo/bar` syntax is already taken. Our current ideas to work around the issue are:
- Instead, introduce the feature using `foo/bar.html` syntax
- Introduce a breaking change, where `foo/bar` is used for the new feature, and the old feature will instead use `foo/bar/` syntax, to signify that it is a directory

**Comment by Reinmar** [comment]
We can certainly consider breaking changes here as this is a development tool and does not affect a broader audience. So, that would not be a blocker.

I think the best way to probe which option is better will be proposing two or more alternative syntaxes covering all use cases and making a poll among CKE5 devs to see which works better for them. I wouldn't be surprise if there's a clear winner even before you ask other devs :D It's often that writing such things down with pros and cons allow making your own mind,

**Comment by Reinmar** [comment]
PS. Just focus on the experience for the users (the other devs). The implementation is something that should not matter here (assuming all options are actually doable).

**Comment by przemyslaw-zan** [comment]
[The branch.](https://github.com/ckeditor/ckeditor5-dev/compare/ck/12251) Current list of changes is:
- Single manual / automated test can now be compiled using syntax: `ckeditor5/article`, `alignment/alignment`
- Previously available option to compile tests from a directory now requires a slash at the end: `engine/view/`
- [Previously, compiling manual tests from a single directory required inclusion of `/manual` in the path.](https://github.com/ckeditor/ckeditor5-dev/compare/ck/12251#diff-fc4a108dbcd46ff18046814b62ea6da8f434b8fa7c48349391919843e0dbb384L109) This is no longer the case, and now it relies solely on the `isManualTest` flag.
- Path produced by the aforementioned option will now include `**` between the picked directory and the `manual` directory. The fact that it was not the case previously seems to be the quirk of the implementation, and not a conscious decision. New version makes it more consistent across the function.
- Simplified glob option was removed - we need to know whether this was used by anyone. It would seem more intuitive to allow the developer to provide normal glob instead of shortened one, but we'd need to decide what we consider a glob, and not any of the other options.

**Comment by przemyslaw-zan** [comment]
We've added wildcard support to the filename test syntax. For example calling the `yarn run test -f basic-styles/bold*` command would compile tests from `bold.js`, `boldediting.js` and `boldui.js`. Together with the directory syntax, this should cover all use cases previously covered by the "simplified glob" syntax.

**Comment by pomek** [comment]
The proposed changes LGTM. It would be good to describe the supported patterns and expected results in the documentation.

More or less, we cover this point in the README on npm - https://www.npmjs.com/package/@ckeditor/ckeditor5-dev-tests. Unfortunately, it isn't obvious. Could you update the [Testing environment](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/contributing/testing-environment.html) guide to include rules for converting the `--files` option to glob pattern? Once done, you can paste a screenshot here so everybody can share feedback regarding new options.

**Comment by przemyslaw-zan** [comment]
# Preview of the updated guide for the `--files` option.

![image](https://user-images.githubusercontent.com/69513154/188633981-a0cf0db6-91a0-46ea-87a3-0e7e1ac499fd.png)

**Comment by pomek** [comment]
Could we present these examples in a table?

**Comment by przemyslaw-zan** [comment]
![image](https://user-images.githubusercontent.com/69513154/188681595-b2dc9671-fa72-433d-938d-e1e6f9b752a8.png)
