### ISSUE TITLE
CKEditor5 can support Chinese Font family?

### ISSUE THREAD

**Issue by sunfeng90** [ckeditor/ckeditor5#1230]
Hello, I want to config the fontFamily in the CkEditor5. It can support the chinese font? Such as '黑体' and '仿宋'？

**Comment by sunfeng90** [comment]
Following are all fonts? 
Such as:
   **'default',
    'Arial, Helvetica, sans-serif',
    'Courier New, Courier, monospace',
    'Georgia, serif',
    'Lucida Sans Unicode, Lucida Grande, sans-serif',
    'Tahoma, Geneva, sans-serif',
    'Times New Roman, Times, serif',
    'Trebuchet MS, Helvetica, sans-serif',
    'Ubuntu, Arial, sans-serif',
     'Ubuntu Mono, Courier New, Courier, monospace'
    'Verdana, Geneva, sans-serif'** I have try the chinese font,but it doesn't work for me.

**Comment by Reinmar** [comment]
These are the fonts which are available to the user by default. You can change that list. But the user must have those fonts installed in his/her OS. Otherwise, they won't work. So if something may be limiting you is what fonts are available on your users computers. You may need to load missing fonts via CSS.

**Comment by sunfeng90** [comment]
OK,thanks!
