### ISSUE TITLE
Clicking on the table column edge changes the width of all columns

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#12335]
## 📝 Provide detailed reproduction steps (if any)

1. Open the demo for table column resize: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/table.html#table-column-resize
2. Start clicking on the column edge. No need to drag anything, just click on it.

### ✔️ Expected result

All columns should have the same width as previously.

### ❌ Actual result

After each click, all columns become narrower.

https://user-images.githubusercontent.com/56868128/186580516-bfc3c3f8-4e67-4a59-aaef-6864d01186bd.mp4

This error occurs only in the docs. I am not able to reproduce it in manual tests.
It works fine in the latest official release: https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-column-resize

## 📃 Other details

* Browser: Firefox, Chrome
* OS: Win 11

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Does it have something to do with the fact that this particular table is centered? Maybe that's why it's reproducible in the docs.

**Comment by psmyrek** [comment]
It looks like the table alignment is not the cause:
- The error still occurs in the docs after changing the table alignment.
- The error still does not occur in manual tests after changing the table alignment.

**Comment by Dumluregn** [comment]
I'll take a look at it today.

**Comment by Dumluregn** [comment]
The issue is caused by the [`box-sizing` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

By default, it is set to `content-box`. That means that when the element's width is calculated (e.g. by `getElementWidthInPixels()` helper), the padding and border are not included in the outcome. However, in our documentation, all the elements have the `border-box` value set for this property. That results in the opposite approach, so including the padding and border - so the actual values are higher than expected.

For this very case, if you had a table with the maximum size (100%), after recalculations it always turned out it is actually not 100% because the padding was included in the table's (actually - figure's) parent width, making it impossible to reach the _computed_ 100%.

Changing the styles in docs seems to be too risky, so instead we're adjusting the helpers calculating the width to take into account the `box-sizing` property value and either include or deduct padding and border (depending on the case).

**Comment by Dumluregn** [comment]
Done in ckeditor/ckeditor5#12359.
