### ISSUE TITLE
Focus moves diagonally in list style demo

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/ckeditor5#12340]
## 📝 Provide detailed reproduction steps (if any)

1. Open http://127.0.0.1:8080/ckeditor5/latest/features/lists/lists.html#list-styles 
2. Click on the numbered list splitButton arrow
3. Press arrowDown or arrowUp key

### ✔️ Expected result

Focus moves down.

### ❌ Actual result

Focus moves diagonally

https://user-images.githubusercontent.com/11699569/186644486-2bfd1931-e939-417f-ba7f-d22b88bbbd70.mov

## 📃 Other details

* Browser: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
List properties have hardcoded 4-items grid row: [https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js#L195-L200](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js#L195-L200), and in this demo there are only 3 elements in the row.

I think it happens if there is no `List properties` component, which makes the dropdown wider.

**Comment by mateuszzagorski** [comment]
I've tried it and enabling `list properties` does seem to resolve the issue ( by widening the dropdown ).  
  
I think it's worth noting that we do have multiple tests that do not use `list properties`.

**Comment by mlewand** [comment]
Is a fix as simple as setting repeat to `4` in:

[https://github.com/ckeditor/ckeditor5/blob/7dfb504a3339fe287627bf422cae8c2a295303bf/packages/ckeditor5-theme-lark/theme/ckeditor5-list/liststyles.css#L11](https://github.com/ckeditor/ckeditor5/blob/7dfb504a3339fe287627bf422cae8c2a295303bf/packages/ckeditor5-theme-lark/theme/ckeditor5-list/liststyles.css#L11)

And removing:

[https://github.com/ckeditor/ckeditor5/blob/7dfb504a3339fe287627bf422cae8c2a295303bf/packages/ckeditor5-theme-lark/theme/ckeditor5-list/listproperties.css#L25-L27](https://github.com/ckeditor/ckeditor5/blob/7dfb504a3339fe287627bf422cae8c2a295303bf/packages/ckeditor5-theme-lark/theme/ckeditor5-list/listproperties.css#L25-L27)

?

**Comment by mmotyczynska** [comment]
That would be the easiest option I guess. There are two more options we can discuss:

1.  Allowing to configure a number of columns as in font feature with a default value e.g. 4.  
    https://github.com/ckeditor/ckeditor5/blob/7dfb504a3339fe287627bf422cae8c2a295303bf/packages/ckeditor5-font/src/ui/colorui.js#L66-L71
2.  Add a logic similar to special characters where because of the responsive layout we are checking number of columns dynamically by reading it from the css value.  
    https://github.com/ckeditor/ckeditor5/blob/7dfb504a3339fe287627bf422cae8c2a295303bf/packages/ckeditor5-special-characters/src/ui/charactergridview.js#L81-L85

**Comment by mlewand** [comment]
I have built the docs and it looks correctly in both cases

![](https://user-images.githubusercontent.com/5353898/186849951-8c3061fd-3166-4029-aa5e-06c9393ca7c9.png)

full featured example:

![](https://user-images.githubusercontent.com/5353898/186850128-1608e5f5-e8bf-411f-a284-1cb9f60362cf.png)

**Comment by oleq** [comment]
> Add a logic similar to special characters where because of the responsive layout we are checking number of columns dynamically by reading it from the css value.

I'm totally for this solution. This is gonna be a copy-paste thing.

**Comment by oleq** [comment]
Closed in ckeditor/ckeditor5#12354.
