### ISSUE TITLE
[Android/IME] Can't exit a list with the Enter key

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#12368]
## 📝 Provide detailed reproduction steps (if any)

1.  Create a numbered list.
2.  Type "Test".
3.  Press Space.
4.  Press Enter twice.

### ✔️ Expected result

The second list item disappears and you exit the list.

### ❌ Actual result

New list items appear after pressing Enter.

## 📃 Other details

Branch: `ck/11438-beforeinput-ime-research-vol1.1-android`  
Language: English  
Keyboards: GBoard  
Device: Nexus 10 emulator@Android v12

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I tested this on Chrome 104.0.5112.97 and it works for me.

https://user-images.githubusercontent.com/156149/187635323-b2db885b-e7b3-45c1-854a-6ecadc0dc898.mp4

Could you run it in the manual test `yarn manual --files typing -d typing`, plug Chrome inspector, enable the "log native events" option (at the top of the manual test) and post here:

* a screencast
* the console logs

**Comment by Reinmar** [comment]
Ok, I managed to reproduce this.

The thing is that pressing the space (I need to do that twice in my case to see anything) inserts one space before the caret and one after the caret.

Since there's one space after the caret pressing Enter in what seems to be an empty line doesn't work because it's not an empty line. Its:

```
<li>[] </li>
```

**Comment by Reinmar** [comment]
An alternative scenario here is to:

1.  Create a list item
2.  Type "Test"
3.  Press Enter. Assuming that we're still in the composition mode (the "Test" is underlined) Chrome tends to send a `beforeInput:insertText` with `\n` string instead of `beforeInput:insertParagraph`. We add this `\n` to the model but it gets added after the selection. 
4.  Press Space. It does nothing visible. The space gets inserted into the model but again - after the selection.
5.  Press Space again. Now it works. Composition ends.
6.  Press Enter. Now it works (because we're not in composition and apparently normal beforeInput:insertParagraph is fired)
7.  Press Enter. It does not escape the list because there's content after the selection – `' \n'`.

**Comment by Reinmar** [comment]
Comment from the main Android thread: https://github.com/ckeditor/ckeditor5/issues/12058#issuecomment-1232681093

> *   Let's try to fix [**\[beforeInput\] Bring back basic typing support in Android #12058 (comment)**](https://github.com/ckeditor/ckeditor5/issues/12058#issuecomment-1221984375) + [**\[IME\] Can't exit a list with the Enter key #12368**](https://github.com/ckeditor/ckeditor5/issues/12368) assuming they are the same problem. Let's simply add support for `beforeInput:insertText` with `'\n'` and see if they go away. It should certainly resolve [**\[IME@Android\] Enter doesn't work at the end of the line while using GBoard #11906**](https://github.com/ckeditor/ckeditor5/issues/11906). It may resolve [**\[iOS\] Dictation is not working ("new line" breaks the editor) #2045**](https://github.com/ckeditor/ckeditor5/issues/2045) too.

**Comment by Reinmar** [comment]
Implementation idea: let's forward the `beforeInput:insertCompositionText` with `'Word\n'` to an `enter` event and stop the original flow (so the default handler for insert text is not executed).

The idea is to do this only on Android and as early as possible, so still in the `InputObserver`'s code. This heuristic will look for any `insertCompositionText` event which `data` ends with `\n`.

Theoretically, this specific event may be fired on Android in different scenarios than Enter key, so we might lose some text that the user wanted to insert. However, we don't know about any such scenarios right now, plus, it wouldn't work anyway.

Resolving this issue may also resolve:

*   ckeditor/ckeditor5#12391
*   ckeditor/ckeditor5#11906
*   ckeditor/ckeditor5#2045

**Comment by Mgsy** [comment]
Fixed on `ck/11438-beforeinput-ime-research-vol1.1-android`.
