### ISSUE TITLE
Adding plugins forces to type all used plugins?

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5#1237]
I've installed `@ckeditor/ckeditor5-build-classic` with `@ckeditor/ckeditor5-angular`.
Now I want to add font plugin so I install it with `@ckeditor/ckeditor5-font`.
I have to configure ckeditor so I put something like this:

```
{
          plugins: [Font],
          fontSize: {
            options: [
              'sm',
              '',
              'lg'
            ]
          },
          toolbar: [
            'heading', '|',
            'bold', 'italic', 'link', '|',
            'blockquote',
            'fontSize',
            'bulletedList', 'numberedList', '|',
            'undo', 'redo'
          ],
}
```
But now all build-in plugins are not working. I suppose I have to define `plugins` array but I don't know where are plugins (I'm using ready `@ckeditor/ckeditor5-build-classic`). I can't see no usefull information in docs.

**Comment by Reinmar** [comment]
It is impossible to add plugins to an existing build. Please see https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html

**Comment by piernik** [comment]
Maybe a good idea is to export `const` with config or plugins or toolbars.
Then I could use something like this:

```
import {Plugins, Toolbar} from '@ckeditor/ckeditor5-build-classic';
import {Font} from '@ckeditor/ckeditor5-font';

{
          plugins: [...Plugins, Font],
          fontSize: {
            options: [
              'sm',
              '',
              'lg'
            ]
          },
          toolbar: [
            ...Toolbar, 'fontSize',
          ],
}
```

**Comment by Reinmar** [comment]
Hm... I initially thought that this is a brilliant idea, but unfortunately it still won't work. The problem is with the dependencies of the `Font` plugin and plugins in the `Plugins` array. They can both rely on `ckeditor5-engine`, `ckeditor5-ui`, `ckeditor5-widget`, `ckeditor5-theme-lark`, etc. If a bult-in plugin and the one you want to add depends on the same code, but that code was in case of the build already compiled, it will get duplicated on the next compilation. In other words, some modules from `ckeditor5-engine` and other packages will end up twice in your final bundle.

**Comment by piernik** [comment]
I'm using typescript so I think webpack would handle this. But I see Your point.

**Comment by Reinmar** [comment]
Webpack won't be able to handle this. At least, not by default. When optimising bundles webpack strips information about source modules. This is especially strong since webpack does tree shaking and module concatenation. 

One idea that we had for that was to use Webpack DLLs, but we haven't worked on it yet.

**Comment by piernik** [comment]
How about publish Your library like angular does. Splited into packages (not only as boundled `js` files). 
Then when installing ex `npm i @ckeditor/all` You can provide all plugins in single file when will have only pointers to source files (correct packages)

```
import {Font, Alignment, Toolbar} from '@ckeditor/all/plugins';

{
	plugins: [Toolbar, Alignment, Font],
	toolbar: [
	'alignmnet', 'fontSize',
	],
}
```
Webpack should tree-shake unnecessary source files.

**Comment by ma2ciek** [comment]
Hi, @piernik.

If you're using angular@6, I'd recommend you to create the editor bundle outside of the project, as it's described [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) or try to build editor from the source according to docs available here: https://github.com/ckeditor/ckeditor5-angular/issues/26. Otherwise, you'll hit the problem with webpack configured for angular@6.

**Comment by piernik** [comment]
@ma2ciek I did it in new project and imported it using `tsconfig`'s `paths`. It's working.

**Comment by ma2ciek** [comment]
We use different SVG loaders and use PostCSS with custom plugins, I'm sure it will break for many ckeditor5 packages. TS and its `tsconfig` has nothing to do with it actually as the code is transpiled through the webpack.

**Comment by piernik** [comment]
I imported built `ckeditor.js` file only.

**Comment by ma2ciek** [comment]
Ok. That's a different story :) I meant that importing CKE5 source files causes breaking the angular build and https://github.com/ckeditor/ckeditor5/issues/1237#issue-358051451 won't work because of it too.

**Comment by Reinmar** [comment]
BTW, we introduced [`config.extraPlugins`](https://github.com/ckeditor/ckeditor5-core/issues/146) for adding standalone plugins to builds or other preconfigured editors.

I think this solves this issue. If not, we can reopen it.
