### ISSUE TITLE
Cannot set block style on table

### ISSUE THREAD

**Issue by DawidKossowski** [ckeditor/ckeditor5#12441]
## 📝 Provide detailed reproduction steps (if any)

1.  Open an editor with tables and styles dropdown (e.g. from styles manual tests).
2.  Create a table.
3.  Select the whole table.
4.  Open "Styles" from the toolbar.

### ✔️ Expected result

It should be possible to select block styles for tables.

### ❌ Actual result

All block styles are disabled.

![](https://user-images.githubusercontent.com/20561161/189117621-62cabb01-0d7e-443e-b386-fe18837e1d7f.png)

**Comment by mmichaelis** [comment]
I totally agree to that issue. But there is possibly more to consider:

Regarding table styling, we already have [Table Properties](https://ckeditor.com/docs/ckeditor5/35.2.0/api/module_table_tableproperties-TableProperties.html) feature:

![Screenshot of Table Properties Dialog](https://user-images.githubusercontent.com/71911/201280477-1a708043-dd4f-44e3-9a74-4ae2a98136bb.png)

Unfortunately, this feature is based on `style` attribute and there is no option mapping this to classes instead, like it is for similar features like [Text Alignment](https://ckeditor.com/docs/ckeditor5/latest/features/text-alignment.html#using-classes-instead-of-inline-style) and to some extent for font related features such as [Font Family](https://ckeditor.com/docs/ckeditor5/35.2.0/api/module_font_fontfamily-FontFamilyOption.html#member-view) via `view` `ElementDefinition` (not documented well, though).

So, trying to leverage this to a desired behavior:

> As an editor
> In order to apply styling to inserted tables
> I want to be able to select from a set of predefined styles, represented as `class` attribute in view.

The [Styles](https://ckeditor.com/docs/ckeditor5/35.2.0/features/style.html) feature may be one way to cope with that, another one would be providing an alternative table properties dialog (same would apply to table cell properties then, even a new feature table row properties).

In the end, we should have a good decision matrix when to use which feature... or perhaps even better: There is some way so that all of them "come together". Example:

* I can define style classes for `<table>`.

* I can select corresponding style classes in _Table properties_ dialog (thus, a restricted view for applicable styles).

* To align with the existing `style` based table properties:

  * The class based styling is considered the desired way to style tables: Thus, by default, editors can only choose different styles (not that up to now styles are additive, thus, don't toggle).

  * Given defined style-classes exist for `<table>`, explicit style properties are hidden in a collapsed region labelled, for example, as "Override". Possibly, the collapsed region is shown as soon as an `Override` checkbox is clicked.

  * All styles in "Override" section are unset by default (this is different to now and possibly challenging to design a good user interaction here).

**Comment by Reinmar** [comment]
Let's merge this into a more general #11577.
