### ISSUE TITLE
Add media embed and tables to all builds

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1247]
* [x] Add them to the builds themselves.
    * [x] Find the space for them in the toolbars.
    * [x] Change builds configuration.
* [x] Update examples (and demos) of these builds to showcase the new features. (Consult @m-kr and @gok9ok about the content.)
* [x] Check out the "Installation" sections of these features docs. There were notes like "This feature is not available in the builds..." which needs to be changed (take inspiration from guides of the features that are included).
* [x] Update screenshots in https://ckeditor.com/docs/ckeditor5/latest/builds/guides/overview.html.

Did I forget about something?

**Comment by oleq** [comment]
Just for the record, I increased the priority of [this issue](https://github.com/ckeditor/ckeditor5-ui/issues/123) 
![image](https://user-images.githubusercontent.com/1099479/45810643-5f6a8700-bccb-11e8-9121-3fe9dca447ad.png)
because as the toolbars grow up (e.g. addition the media-embed dropdown), this issue becomes visible even more.

**Comment by oleq** [comment]
We also need to start looking for solutions for https://github.com/ckeditor/ckeditor5/issues/894

![image](https://user-images.githubusercontent.com/1099479/45814849-3e0f9800-bcd7-11e8-833c-6c17e60f784f.png)

because if overcrowded toolbars in the classic/inline/document do wrap to the next line, there's no such thing in the balloon editor. And this becomes a problem because no matter what, there's no way to position the balloon to fit the toolbar in the viewport in some situations because it's just too wide.

**Comment by gok9ok** [comment]
>Update examples (and demos) of these builds to showcase the new features. 

I can provide the content by midweek next week at best since I'm pretty overloaded right now. 😅 hope that's okay

**Comment by oleq** [comment]
@gok9ok Sounds good to me. @Reinmar, does it make sense for the roadmap?

---

I'll be able to update the build screenshots when

>  Find the space for them in the toolbars.

is approved by the reviewer. 

The constellation is here https://github.com/ckeditor/ckeditor5/pull/1254.

**Comment by Reinmar** [comment]
Let's keep this open to not forget about updating the content of editor demos.

**Comment by oleq** [comment]
Just FYI  https://github.com/ckeditor/ckeditor5/issues/1247#issuecomment-423119193 has been addressed in  https://github.com/ckeditor/ckeditor5-ui/issues/123

**Comment by oleq** [comment]
Updated the content of the build examples in b18b18c24ccf0138a2ee8e64487008f65e4341cd.
