### ISSUE TITLE
MS Word's heading and title styles support in Paste from Office plugin

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#12548]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html
2. Try pasting content formatted with Word's default headings or title styles.

### ✔️ Expected result

I'd expect the content gets pasted as headings.

### ❌ Actual result

Title is turned into paragraph. 
For headings it depends on Word version:
- For Office 365 heading 1 is turned into list. Levels 2, 3, and so on are pasted properly as headings.
- For Word 2016 all headings are turned into lists.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
It depends on the headings configuration. With headings level 1 to 6 in the editor, pasted content is preserved properly, however the title is still not recognized.

**Comment by Reinmar** [comment]
Those are my results:

![](https://user-images.githubusercontent.com/156149/196635888-a5088bcb-26fe-41dd-9c3a-5c58bd4d97b1.png)

Taken how this specific sample is configured (no \<h1> support) the results are pretty good in terms of preserving the semantics. Headings became headings, although, I wonder if we shouldn't differentiate Heading1 and Heading2 (by shifting levels down when `<h1>` is not available). The title was converted to a paragraph because there's no semantical representation for it in CKEditor 5. Perhaps it could become Heading 1 as well, but it's not perfect.

Anyway, assuming the integrator enabled all heading levels (h1+) this is the result:

![](https://user-images.githubusercontent.com/156149/196637610-d4cd6721-4ad6-4220-95c4-896c4eeb709d.png)

H1 and H2 are correctly detected.

---

As for colors and font family, etc, – they were dropped because we don't do style inlining yet. But this is a separate feature request: #10577.

For comparison, CKE4 with style inlining mechanism generated this:

```html
<p class="MsoTitle"><span style="font-size:28pt"><span style="font-family:&quot;Calibri Light&quot;,sans-serif"><span style="letter-spacing:-0.5pt">Title</span></span></span></p>

<h1 style="margin-top:16px"><span style="font-size:16pt"><span style="font-family:&quot;Calibri Light&quot;,sans-serif"><span style="color:#2f5496"><span style="font-weight:normal">Heading1</span></span></span></span></h1>

<h2 style="margin-top:3px"><span style="font-size:13pt"><span style="font-family:&quot;Calibri Light&quot;,sans-serif"><span style="color:#2f5496"><span style="font-weight:normal">Heading2</span></span></span></span></h2>

<h3 style="margin-top:3px"><span style="font-size:12pt"><span style="font-family:&quot;Calibri Light&quot;,sans-serif"><span style="color:#1f3763"><span style="font-weight:normal">Heading3</span></span></span></span></h3>
```

We need #10577 to take CKE5 to that level of style retention.

---

Taken all this... I wonder if this ticket still makes sense? There are some minor tweaks we could do with detecting content semantics, but I suppose the person reporting it had the style inlining in mind.

**Comment by FilipTokarski** [comment]
Closing as invalid. The problem was with the file, not the feature itself.
