### ISSUE TITLE
Lerna version supported should be mentioned in the docs

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor5#1268]
We don't support Lerna 3 (see https://github.com/ckeditor/ckeditor5/issues/1214). This should be mentioned in the [development docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/development-environment.html).

**Comment by Reinmar** [comment]
It'll be enough to make people run this:

```
npm install -g lerna@2 mgit2
```

And perhaps adding a note that Lerna@3 is not supported yet with a link to https://github.com/ckeditor/ckeditor5/issues/1214.

It may happen that this is completely temporary because we're considering leaving Lerna as version 3 is starting to drop support for treating the root package as one of the packages to install. We need that now and there are other solutions that we're discussing in #1214 that may handle this for us (e.g. yarn workspaces).
