### ISSUE TITLE
Table size selector just says "0x0"

### ISSUE THREAD

**Issue by archonic** [ckeditor/ckeditor5#1269]
## Is this a bug report or feature request? (choose one)
🐞 Bug report

## 💻 Version of CKEditor

Decoupled editor, v10.1.0

I've recompiled my editor without changing versions and found that the table button is broken. There are no console errors. Instead of the table size selector, I just see this:
![collaborase](https://user-images.githubusercontent.com/588846/46249147-5f5c3c80-c3d9-11e8-8261-9ebf8f533a1f.png)

**Comment by Reinmar** [comment]
Hi! Sorry to hear that. It's hard to tell, though, what happened. It looks like some styles are not loaded (dunno why). It may be a browser cache too. We need to be able to reproduce this issue to tell more because it works for us fine. Could you provide a repository or steps that'd allow us to reproduce this issue?

**Comment by archonic** [comment]
I found out just yesterday that this was the result of loading 2 separate
builds. Not sure yet if it's the result of loading 2 builds or more
specifically a global version mismatch. I have a different issue for that
but thought I'd leave a note here in case it helps others.

**Comment by Reinmar** [comment]
Cool. Thanks for letting us know. 

Since October an error is logged on the console when two builds are used together, so that should help finding this issue.

Also, we created a guide on how to use two different editor types on one page: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-3-using-two-different-editors

**Comment by archonic** [comment]
I could use more insight into how the table 0x0 bug appears. I've now got a Decoupled + Classic super build working and the table works in the sample, but not in my own app.

https://github.com/archonic/c3-ckeditor5-super-build

The only difference is that the sample doesn't actually connect the collaborative editing, and there's some slight difference in initialization. Does anyone know how I could get insight into what error is causing the 0x0 issue?

**Comment by archonic** [comment]
This was indeed a styling issue. The CKEditor styles are inserted after the script tag, so if others have this issue, just move the CKEditor script to after your apps stylesheet.
