### ISSUE TITLE
Markdown plugin generates html tables instead of md

### ISSUE THREAD

**Issue by mariusrak** [ckeditor/ckeditor5#12793]
## 📝 Provide detailed reproduction steps (if any)

- Use markdown plugin
- Add table
- Inspect output
- See table is in html not in md while rest of content is in md as it should

### ✔️ Expected result

To see table constructed by md syntax

### ❌ Actual result

The table is constructed by html

## 📃 Other details

* Browser: Firefox
* OS: Windows 10
* Installed CKEditor plugins:
```
    "@ckeditor/ckeditor5-basic-styles": "^35.2.0",
    "@ckeditor/ckeditor5-dev-utils": "^30.5.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^30.5.0",
    "@ckeditor/ckeditor5-editor-classic": "^35.2.0",
    "@ckeditor/ckeditor5-essentials": "^35.2.0",
    "@ckeditor/ckeditor5-heading": "^35.2.0",
    "@ckeditor/ckeditor5-html-support": "^35.2.0",
    "@ckeditor/ckeditor5-image": "^35.2.0",
    "@ckeditor/ckeditor5-indent": "^35.2.0",
    "@ckeditor/ckeditor5-link": "^35.2.0",
    "@ckeditor/ckeditor5-list": "^35.2.0",
    "@ckeditor/ckeditor5-markdown-gfm": "^35.2.0",
    "@ckeditor/ckeditor5-paragraph": "^35.2.0",
    "@ckeditor/ckeditor5-table": "^35.2.0",
    "@ckeditor/ckeditor5-theme-lark": "^35.2.0",
    "@ckeditor/ckeditor5-upload": "^35.2.0",
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This is interesting because this:

![](https://user-images.githubusercontent.com/156149/210320554-916d55a8-f492-4bb6-ad6c-862638267e7b.png)

produces an HTML table.

But this:

![](https://user-images.githubusercontent.com/156149/210320581-3073de4d-afb6-4815-b869-50e47b304a00.png)

Produces:

```markdown
| a |   |   |
| --- | --- | --- |
|   | b |   |
|   |   | c |
```

So, the output generator expects there to be a heading row (or some other detail).

**Comment by arkflpc** [comment]
We support GFM dialect of Markdown. According to their [spec](https://github.github.com/gfm/#tables-extension-), tables consist of exactly one header row, one delimiter and zero or more data rows. It means that a table without header row is not considered as table. This is true (and non-configurable) for [`marked`](https://marked.js.org) and [`turndown`](https://github.com/mixmark-io/turndown) packages we use for `getData()/setData` and for comments in GitHub as well.

Even if we developed a custom rule for [turndown](https://github.com/mixmark-io/turndown), the data wouldn't produce a table when set back to the editor.

Moreover, [the purpose of GFM spec](https://github.github.com/gfm/#why-is-a-spec-needed-) is to remove any ambiguity in its syntax, so that every parsing library has the same behavior. Changing it wouldn't mean it's no longer GFM, but another dialect.

**Comment by mariusrak** [comment]
So can we change the table plugin to check whether the output is md and if yes, it would always generate header row? Otherwise it is unusable for normal non tech savvy user. We cannot expect a user to guess to add header row and a purpose for md is to avoid html. Thanks.

**Comment by arkflpc** [comment]
@mariusrak, that would change the semantics of the given table. If the requirement that user adds heading manually is an issue, it can be enabled by default:

```typescript
ClassicEditor.create( {
  plugins: [ TableEditing ],
  table: { defaultHeadings: { rows: 1 } }
}
```

See https://ckeditor.com/docs/ckeditor5/latest/api/module_table_table-TableConfig.html#member-defaultHeadings.

**Comment by arkflpc** [comment]
cc: @Reinmar
