### ISSUE TITLE
Docs issue report from "installation/getting-started/frameworks/vuejs-v3.html"

### ISSUE THREAD

**Issue by apollyV** [ckeditor/ckeditor5#12794]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/vuejs-v3.html

### Project version

35.2.1

### Is there anything else you would like to add?

I am not able to use ckeditor with "Using CKEditor from source" I get an error `Cannot read properties of null (reading 'getAttribute')` in my browser's console. I followed all of the tutorial and and it doesn't works. 
<img width="783" alt="image" src="https://user-images.githubusercontent.com/80909725/199929092-a42b5a48-1098-4ec7-b8f3-78a5082b7580.png">

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

**Comment by mabryl** [comment]
Hi apollyV,

Thanks for reaching out and bringing this issue to our attention. Unfortunately, I wasn't able to reproduce this case, so I'm asking you to provide us with more details regarding it.

In my debugging I followed [this section](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/vuejs-v3.html#using-ckeditor-from-source) of our Vue integration tutorial and I was able to create an App containing our editor built from source. The contents of my `main.js` file look as follows:

```
import { createApp } from 'vue'
import App from './App.vue'
import CKEditor from '@ckeditor/ckeditor5-vue';

createApp( App ).use( CKEditor ).mount( '#app' )
```

And in the `App.vue` file I pasted the contents of this code snippet from our docs:

```
<template>
    <div id="app">
        <ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>
    </div>
</template>

<script>
    // ⚠️ NOTE: We don't use @ckeditor/ckeditor5-build-classic any more!
    // Since we're building CKEditor from source, we use the source version of ClassicEditor.
    import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

    import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials';
    import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
    import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic';
    import LinkPlugin from '@ckeditor/ckeditor5-link/src/link';
    import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph';

    export default {
        name: 'app',
        data() {
            return {
                editor: ClassicEditor,
                editorData: '<p>Content of the editor.</p>',
                editorConfig: {
                    plugins: [
                        EssentialsPlugin,
                        BoldPlugin,
                        ItalicPlugin,
                        LinkPlugin,
                        ParagraphPlugin
                    ],

                    toolbar: {
                        items: [
                            'bold',
                            'italic',
                            'link',
                            'undo',
                            'redo'
                        ]
                    }
                }
            };
        }
    };
</script>
```

By doing that I was able to successfully create a Vue app that includes our editor. Could you make sure that you followed our tutorial closely?

Please let us know whether you found this response helpful and, if not, provide more detailed steps on how to recreate your issue so that we can help you in debugging it.
