### ISSUE TITLE
ckeditor5 tab character doesn't work

### ISSUE THREAD

**Issue by nian-x** [ckeditor/ckeditor5#12826]
## 📝 Provide a description of the new feature
when I set the value like this: `<p>\txsadasda</p>`
finally, it will be: `<p>xsadasda</p>`

`\t` It's gone

## _What is the expected behavior of the proposed feature?_
tab character work normally

**Comment by mabryl** [comment]
Hello @nian-x,

Thank you for your message. The behavior that you described stems from the fact that, as of now, CKE5 doesn't support inserting tab characters.

This has been brought to our attention in the past, and you can join [this discussion](https://github.com/ckeditor/ckeditor5/issues/1197) if you wish to learn more. If we decide to implement this feature, the linked thread will get updated.

I'll close your issue now since it's directly related to the thread linked above.
