### ISSUE TITLE
Typedoc - validate the output

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#12965]
## Provide a description of the task

Points to cover:

* Validating links between API members.
* Verify whether overloads are described (`@label`).
* Check if `@see` annotations point to valid signatures.
* Check if an event described in the `@fires` annotation exists.
* …?

Any error should break the process when running in strict or validate modes. Otherwise, let's report warnings.

**Comment by psmyrek** [comment]
I found some problem. Now, we use `project.getChildByName()` to find the target reflection, but this method returns only the first matching reflection. It may happen that e.g. a class has two reflections with the same name:
- `Collection#add` - method,
- `Collection#add` - event.

I see two solutions for now:
1. Instead of targeting the final reflection in `project.getChildByName()`, find its parent and the manually iterate over its children to find matching child.
2. Add a `event:` prefix for events.

**Comment by pomek** [comment]
Done in https://github.com/ckeditor/ckeditor5-dev/pull/831.
