### ISSUE TITLE
Define JSHint globals

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#13]
Based on https://github.com/ckeditor/ckeditor5/pull/11/files#r23282090.

I wasn't sure if I shouldn't report this ticket in ckeditor/ckeditor5-design repository, but we'll need this one anyway, so let's start here :).

**Comment by fredck** [comment]
I've been using the `/* global */` comment on tests with some good success. Usually we start a test from a copy-paste from an existing one (for header, etc..), so that comment comes together.

The nice thing is that JSHint points out unused entries in this comment so we always have it clean.

Therefore, when it comes to tests, I'm ok to keep using the comments... but I'm also ok to have them in the grunt config file... I mean, I'm ok with what the team will find is better. Just wanted to report my recent experience with it here.

**Comment by Reinmar** [comment]
I'm ok with both solutions - defining all globals in every file or defining wide set of globals in the global config (https://github.com/ckeditor/ckeditor5/pull/11/files#r23292195). Since you started the first way, we can continue it.

**Comment by fredck** [comment]
Agreed.
