### ISSUE TITLE
iPhone -> IOS 12.5.4 -> Safari - Editor not showing up

### ISSUE THREAD

**Issue by Joaquim3** [ckeditor/ckeditor5#13049]
## 📝 Provide detailed reproduction steps (if any)

1. Page I'm loading : https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

### ✔️ Expected result

_CkEditor should be displayed _

### ❌ Actual result

_Text and images are displayed but the Editor is not showing up. I can't edit_

### ❓ Possible solution

_?_

## 📃 Other details

* Browser: Safari…
* OS: iphone 12.5.4…
* ![iPhone-12_5_4_safari](https://user-images.githubusercontent.com/48619284/206857605-5fd53cc7-b73f-4b24-bd1d-9e124daefd2d.png)
![Desktop](https://user-images.githubusercontent.com/48619284/206857606-533f4c09-e7ff-4d4c-8367-5386d40b0796.png)
* First affected CKEditor version: 5…
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mabryl** [comment]
Hi @Joaquim3,

Thanks for reaching out.

iOS 12.5.4 is now quite a bit behind the newest versions of the operating system and, since we're always focusing on ensuring proper functionality on the latest OSes and browsers, we can't guarantee that everything will work seamlessly on older versions of software.

The linked page works correctly on the newest versions of iOS and mobile Safari as well as on version 13.7 of iOS, which is the oldest version that I could check via Xcode without having an actual old iPhone for testing.

In relation to that, we recommend that you try updating your OS and browser to the latest versions and test whether our page works correctly there.

I'll be closing your issue now but feel free to reopen it if you have more questions.
