### ISSUE TITLE
Travis & Node@19 & npm@9.2 stopped working

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#13076]
## Provide a description of the task

https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/591276388

```
$ nvm install node
npm ERR! `spin` is not a valid npm option
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2022-12-15T10_48_14_808Z-debug-0.log
The command "npm config set spin false" failed and exited with 1 during .
```

I propose to use the latest `LTS` instead of any latest Node version.

https://github.com/ckeditor/ckeditor5/blob/23635bc471993e93e745855781f851fd529a5657/.travis.yml#L15-L16

**Comment by psmyrek** [comment]
I noticed that CI ([example run](https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/596102219)) started reporting the same error again:
```
npm ERR! `spin` is not a valid npm option
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2023-02-16T05_57_10_836Z-debug-0.log

$ node --version
v18.14.0

$ npm --version
9.3.1

$ nvm --version
0.39.3
```

It turns out that the **minor bump** of Node from v18.13.0 to v18.14.0 made a **major bump** of npm from 8.19.3 to 9.3.1.

![Zrzut ekranu 2023-02-16 093801](https://user-images.githubusercontent.com/56868128/219312266-8396de92-32ee-48aa-8755-cd80998c6433.png)

Previously, npm was throwing an error that ended the CI run. Now, in version 9.3.1, npm probably doesn't throw an error anymore, so CI is not stopped.
