### ISSUE TITLE
Hello, how is it like this?

### ISSUE THREAD

**Issue by gongzhiq** [ckeditor/ckeditor5#1308]
![small2](https://user-images.githubusercontent.com/5800062/47016203-907e9000-d181-11e8-9b1b-0ded83eca22d.gif)

```
<image1></image1>
<p><br/></p>
<image2></image2>
<p><br/></p>
<image3></image3>
<p><br/></p>
```

**Comment by gongzhiq** [comment]
This problem does not solve my problem
https://github.com/ckeditor/ckeditor5/issues/1255

**Comment by pomek** [comment]
Again, DUP of https://github.com/ckeditor/ckeditor5/issues/1255.

As you pointed out, #1255 is about the same issue that you're reporting. Would be good to keep a discussion about it in one place.

**Comment by gongzhiq** [comment]
> Again, DUP of #1255.
> 
> As you pointed out, #1255 is about the same issue that you're reporting. Would be good to keep a discussion about it in one place.

Will this question be invisible below, and no one will answer?

**Comment by gongzhiq** [comment]
Can you put this problem on the top?

**Comment by gongzhiq** [comment]
> Again, DUP of #1255.
> 
> As you pointed out, #1255 is about the same issue that you're reporting. Would be good to keep a discussion about it in one place.

Can you put this problem on the top?

**Comment by Reinmar** [comment]
Hi! @pomek closed this ticket by mistake. It's not a dup of #1255. However, it's also not written in a way that'd make it possible to reply with all certainty. You didn't post any code and a TC what confused us what your ticket is about. Please use the template that we created for tickets when reporting new tickets *and reply all questions in it*.

Anyway, the answer to your question will be – you're encoding HTML entities in the data produced by the editor too many times before printing them on your website. A `<p><br /></p>` becomes something like `&lt;p&gt;&ltbr /&gt;&lt;/p&gt;` so you can see the source instead of paragraphs in the editor. However, how many times the source needs to be encoded before being printed depends on whether you initialize the editor on a `<div>` or a `<textarea>`. Since you haven't showed any code I can't tell you precisely what you should do.
