### ISSUE TITLE
Can't set the style on <div> using Styles dropdown

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#13341]
## 📝 Provide detailed reproduction steps (if any)

*   Add GHS configuration:

```javascript
htmlSupport: {
                allow: [
                    {
                        name: /.*/,
                        attributes: true,
                        classes: true,
                        styles: true
                    }
                ] 
 }
```

*   Add Styles configuration:

```javascript
style: {
   definitions: [
      { name: 'Message: Success', element: 'div', classes: ['alert', 'alert-success'] },
      { name: 'Message: Info', element: 'div', classes: ['info-boxalert', 'alert-info'] }
   ]
}
```

*   Call `editor.setData( '<div>Test</div>' )` and put the selection inside of it.
*   Try to apply defined styles.

### ✔️ Expected result

_It's possible to apply styles to the element._

### ❌ Actual result

_It's impossible to apply styles to the element._

## 📃 Other details

Might be related - #12625.

The same scenario works fine for the example `<section>` element.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by JTubex** [comment]
Possibly related to https://github.com/ckeditor/ckeditor5/issues/11577

**Comment by Witoso** [comment]
Confirming as per #13763.
On `div`'s it works partially.
Works:
```html
<div>
    <p>
        Hello, world!
    </p>
</div>
```

Doens't work:
```html
<div>
        Hello, world!
</div>
```

**Comment by jameswilson** [comment]
This is a fairly significant regression for several folks trying to upgrade CKEditor 4 to CKEditor 5 on Drupal 9 and losing what were previously working block styles. 

https://www.drupal.org/project/drupal/issues/3326261#comment-15031422 (33 followers on the issue)

**Comment by Witoso** [comment]
Thanks for raising this @jameswilson, we are going to ship a few updates and fixes of the Style dropdown in the next release. This is not part of it unfortunately but we will discuss it internally.

**Comment by jameswilson** [comment]
@wimleer requested I upload some screenshots from Drupal 9 + CKEditor 4 config vs. same config in CKE5 to demonstrate the basics of the issue. (We have plugins to make adding style dropdowns easier than writing the JS demonstrated in previous comments of this issue).

I should note that the issue here isn't limited to div, but pretty much any block-level element appearing in the styles dropdown, like DL, IMG, TABLE, H1, H2, etc.  I havent done extensive testing on which block level items are affected.

<img width="922" alt="Screen Shot 2023-05-01 at 1 41 04 PM" src="https://user-images.githubusercontent.com/243532/236233165-557697b6-2981-40e5-a669-8f0a1011b53f.png">

<img width="883" alt="Screen Shot 2023-05-01 at 1 40 43 PM" src="https://user-images.githubusercontent.com/243532/236233206-52c569

CKE4: 
<img width="234" alt="Screen Shot 2023-05-01 at 1 39 21 PM" src="https://user-images.githubusercontent.com/243532/236233820-686a8316-c9aa-44d5-9682-2724a424c9af.png">
3f-6066-44c1-9dcc-0f32b1904d98.png">


CKE5:
<img width="462" alt="Screen Shot 2023-05-01 at 1 39 02 PM" src="https://user-images.githubusercontent.com/243532/236233937-e7367f00-2d50-4d8f-b71a-de83a334938e.png">

I should note that one can still manually switch to Source mode, and enter the HTML code manually and it works.  Eg `<div class="alert success"> </div>`

CKE5, with manual edits via src mode:
<img width="1312" alt="Screen Shot 2023-05-01 at 2 21 13 PM" src="https://user-images.githubusercontent.com/243532/236234221-074d974f-1fb3-4e4a-a641-09755429b93a.png">

**Comment by Witoso** [comment]
There's one important difference between CKE4 and CKEdi5 that needs mentioning, that relates to your case @jameswilson as well.

Style dropdown in CKE5 will not add the div when you select the style. I noticed it [was possible in CKE4](https://ckeditor.com/docs/ckeditor4/latest/examples/styles.html). The style in CKE5 is only applicable to the element that is already in the editor and matches the element criteria. The addition of a new div element would need to be done with the Source editing which is not the best content creation experience. I'm afraid we also need to consider how the divs should be added (or an element that resembles their purpose) or we should allow the style dropdown to create such elements. WDYT @Reinmar?

@wimleers FYI we need to think a bit on this, so it may take time.

**Comment by Witoso** [comment]
1. First action on our side could be enabling the styling on "paragraph like" `<div>`s (model's `htmlDivParagraph`). To unblock this on Drupal's side and the current CKEditor 4 content.
2. Second step is to refine and figure out from the UX side how to add the divs (containers vs blocks).

Thoughts:
* container divs are similar in behavior to the blockquote feature.
* blocks divs are similar in behavior to the paragraph/headings features.

**Comment by Witoso** [comment]
Inserting elements by Style dropdown will be tracked in the https://github.com/ckeditor/ckeditor5/issues/14372

In this ticket we will enable possibility of styling already present `div`'s.

**Comment by wimleers** [comment]
👍 Captured and shared with the Drupal community at https://www.drupal.org/project/drupal/issues/3326261#comment-15107914 😊

**Comment by wimleers** [comment]
🥳
