### ISSUE TITLE
Editor initialization is very slow

### ISSUE THREAD

**Issue by huzedong2015** [ckeditor/ckeditor5#13351]
## 📝 Provide detailed reproduction steps (if any)

1. download [example](https://github.com/huzedong2015/pictures/blob/main/ckeditor5-36.0.0.zip)
2. unzip file
3. open `./sample/index.html`

### ✔️ Expected result

Quick initialization completed

### ❌ Actual result

Initialization takes 3 seconds

### ❓ Possible solution

null

## 📃 Other details

* Browser:  Chrome 108
* OS: windows 11
* First affected CKEditor version: 36.0
* Installed CKEditor plugins:  view package.json

---
**May be related to a large number of tables**

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mabryl** [comment]
Hi @huzedong2015,

Thank you for reaching out and for sending your build for testing.

On my machine (2020 MacBook Air running macOS Ventura and Chrome v109) your sample opens in about 1.5 seconds as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/72079603/216327490-898a3a21-275a-4dc7-9369-f0c07eccc7bf.png)

Since CKEditor 5 is a web application, it has to operate within certain constraints (the browser that you're using, your hardware etc.) and these constraints will always influence the performance of the editor.

Additionally, your content (a large table containing many rows) can be considered quite heavy and, in our experience, other WYSISYG editors can also struggle with processing such content.

Please, let us know whether you found this information useful and if you think that the performance of the editor is not acceptable for your use case.

**Comment by huzedong2015** [comment]
I have deleted some of these data, but actually more. It takes 6,7 seconds to initialize an editor and getData

There are many editors on our page

**Comment by mabryl** [comment]
Hi @huzedong2015,

Thank you for your response and for elaborating on your case.

Your issue is probably related to the high number of editors running at the same time on a single page. Basically, CKEditor 5 is a complex web application that can consume significant browser resources, so initializing multiple editors can cause a significant performance drop, as browsers have limits.

In cases such as yours, where there is a need to have multiple editors open on one page at the same time, our advice is to keep only one active editor instance to avoid the drop in performance. You can achieve it by adding listeners to your source elements (the HTML elements on your page used for creating the editor) and the logic might look something like this:

1. There are multiple editors on a page.
2. A user wants to edit the content in Editor 2.
3. The user clicks on the content in Editor 2.
4. Editor 2 initializes.
5. The user edits some content in Editor 2.
6. Then, the user wants to edit the content from Editor 3.
7. The users clicks on the content in Editor 3.
8. The Editor 2 destroys.
9. The Editor 3 initializes.

For destroying the editor, you can use the [Editor#destroy()](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#function-destroy) method. Remember to save your data in your database before destroying the editor instance.

If you want to display the content created in the destroyed editor in the source element, you can configure the editor to update the source element on destroy by setting the [updateSourceElementOnDestroy](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-updateSourceElementOnDestroy) property to true in the editor’s configuration.

Hope you find this useful.
