### ISSUE TITLE
Development environment documentation advising to run npm install as root

### ISSUE THREAD

**Issue by elliarbtan** [ckeditor/ckeditor5#1337]
Running` npm install `as root for global installation of package (`npm -g`) is considered bad practice. Please don't advise doing so !  Alternative : https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by Reinmar** [comment]
Hi! Thanks for reporting this. We're aware of that, but it's at the same time the simplest way to install packages globally and we don't want to be making this too complex in the documentation. We could add a note, but frankly speaking, we can't try to educate developers about everything because the core message (so explaining CKEditor 5) will get lost in between all that.

**Comment by Reinmar** [comment]
How would you write the documentation to be both – easy to understand and not advising to use `-g`?

**Comment by elliarbtan** [comment]
I totally agree that you "can't try to educate developers about everything". So I would suggest to just remove the note about macos and linux. 
If you want to provide insight, write something like "remember to add a `prefix` line your ` ~/.npmrc`" which would be enough keywords to get to further explanations if needed.

**Comment by Reinmar** [comment]
As per your request :) https://github.com/ckeditor/ckeditor5/commit/60efd45b22e2878de22831f43ba2a3b3b107a0bb#diff-48d17b21eed469a88a8741da6cab042fR38

Thank you!
