### ISSUE TITLE
Content styles documentation has generated an incomplete content-styles.css file

### ISSUE THREAD

**Issue by Ansis100** [ckeditor/ckeditor5#13451]
The full list of content styles used by CKEditor are contained [here](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html#the-full-list-of-content-styles), however the page contains an incomplete stylesheet (for example, block quote styles are missing). 

I used the [Wayback Machine](https://web.archive.org/web/20220929031814/https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html) to compare how the stylesheet _should_ look vs how it looks now. The old stylesheet has almost 2x more lines of code than the new one.

**Comment by pomek** [comment]
Internal notes:

* https://github.com/ckeditor/ckeditor5/blob/c8a89f383efcd7d6369012039b2db6409d419467/scripts/docs/utils.js#L49
* Target a PR to `#stable`.

**Comment by pomek** [comment]
I'm reopening it as it works locally, but the changes broke the nightly docs builder (which uses JavaScript output in `node_modules`).

**Comment by pomek** [comment]
The content styles builder script works in three different environments:

1. Local: `node_modules/` contains symlinks to the `packages/` directory.
2. Nightly: `node_modules/` contains compiled/minified/obfuscated JavaScript, resulting in a compilation of sources TypeScript.
3. Production: `node_modules/` contains packages installed from npm.

All of these have a common point - the `node_modules/` directory. Instead of looking for packages in the `packages/` directory, we should search in the shared directory.

However, we should consider only packages specified in the `packages/` directory. So, the updated flow should present as follows:

* Find CKEditor 5 package names.
* Find CKEditor 5 plugins for found packages.
* Prepare an entry point for webpack. All imports should come from the `node_modules/` directory instead of `packages/`.
* Bonus point: Create a TypeScript entry point. It may work by default. Otherwise, let's resolve issues. We will prepare a path to migrate CKEditor 5 builds to TS.
