### ISSUE TITLE
Server side conversion with/without asynchronous data processor

### ISSUE THREAD

**Issue by topekTopperson** [ckeditor/ckeditor5#1347]
## Is this a bug report or feature request? (choose one)
Other
## 💻 Version of CKEditor
CKEditor5
Markdown Output
## 📋 Steps to reproduce
Hi,
I have external service for converting markdown to html written in PHP. It is widely used in our company because we have our custom markdown specification, hence it is impossible to rewrite it to javascript library.
I assume that if I want to use it with CKEditor5 then I need to make some async request to it from my data processor's toView method.

I came across this issue about asynchronous data processor which you were discussing durning phase of designing ckeditor5: https://github.com/ckeditor/ckeditor5-design/issues/102 . 

I know the result of this discussion but maybe it is still possible to use server side conversion? If yes could give me some tips how to achieve it? I will be very grateful.

## ✅ Expected result
Async request to API for server side markdown -> html conversion.

**Comment by Reinmar** [comment]
Hi! I'm really sorry for replying after such a long time.

I've read through the old discussion and checked the code that we have. It seems that we abandoned this idea that a DP can be asynchronous. I can't clearly recall it right now, but I think that our decision was to simplify the API because in great majority (really, 99.9% cases) a DP will be synchronous.

However, from API design perspective, you can create an editor which setting/getting data logic is asynchronous. The base `Editor` class does not specify `setData()/getData()` methods (they come from `DataApi` interface), so you can implement them on your own. Also, if you do that, you will need to implement your own `DataController` because that's the consumer of the data processor. With those things implemented differently, you should be able to make DP asynchronous.

**Comment by Reinmar** [comment]
PS. However, I'd recommend to keep the asynchronousity outside the editor :)
