### ISSUE TITLE
[TS] PoC of using types in Angular integration

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#13544]
Part of #13471.

**Comment by Witoso** [comment]
The result of PoC: 
* Angular project using angular integration (updated in #13541) and `alpha.1` release. On ckeditor5 repo in the dedicated branch. 
* Write down how the integration went. What steps happened, etc. what was not obvious, did it help, in what, we could later reuse it in guides for this dedicated technology and in TS blog post.

**Comment by mremiszewski** [comment]
As there is already a demo in the `ckeditor5-angular` repository I'll write what's different from an integration perspective.

The most significant changes need to be done in creating a custom build due to the #13707 issue. Currently `Context`, `EditorWatchdog`, and `ContextWatchdog` are exposed as static fields in the editor class, so there is no more need to do custom builds in a different way than the ones in the `ckeditor5` repository. So in cases when `Watchdog` or `Context` needs to be used would be much simpler - as in the demo.

With the changed build, the imports are changing as well. `Context` and `*Watchdog` are no longer included in the build, so instead of importing them from the build, they are already included in the editor class. In most scenarios, only their types need to be imported as shown in the demo.

**Comment by mremiszewski** [comment]
As there is already a demo in the `ckeditor5-angular` repository I'll write what's different from an integration perspective.

The most significant changes need to be done in creating a custom build due to the #13707 issue. Currently `Context`, `EditorWatchdog`, and `ContextWatchdog` are exposed as static fields in the editor class, so there is no more need to do custom builds in a different way than the ones in the `ckeditor5` repository. So in cases when `Watchdog` or `Context` needs to be used would be much simpler - as in [the demo](https://github.com/ckeditor/ckeditor5-angular/tree/master/src/app).

With the changed build, the imports are changing as well. `Context` and `*Watchdog` are no longer included in the build, so instead of importing them from the build, they are already included in the editor class. In most scenarios, only their types need to be imported as shown in [the demo](https://github.com/ckeditor/ckeditor5-angular/tree/master/src/app).
