### ISSUE TITLE
ckeditor5 Read-only support hide

### ISSUE THREAD

**Issue by woisk** [ckeditor/ckeditor5#1357]
ckeditor5 Read-only support How to hide the Toolbar[toolbar and border on the front page?

You can't always read the style of the page that you write, and show it to the front page equally.

1. Appearance in editing
![image](https://user-images.githubusercontent.com/18644664/48468347-87d3b500-e826-11e8-9b4c-4e646c5f30c0.png)

2.When the editor completes the release, it shows to the visitor how to hide the editor bar.
![image](https://user-images.githubusercontent.com/18644664/48468469-ea2cb580-e826-11e8-932a-404fb7561a44.png)

**Comment by Reinmar** [comment]
cc @dkonopka @Mgsy I think we had a ticket for widget's outline in read-only mode?

**Comment by woisk** [comment]
Thank you! I have carefully searched and tried to solve this problem. The source code I use is the latest version pulled out by Github. Do I need to change my point of view?

The concept of read-only mode is to show consumers the appearance, rather than let consumers see the editor's interface;

**Comment by oleq** [comment]
> The concept of read-only mode is to show consumers the appearance, rather than let consumers see the editor's interface;

To be honest, this is the first time I see someone trying to use the read-only mode like that in a WYSIWYG editor. Or at least I don't recall anyone making similar assumptions in CKEditor 4 and we had years of feedback from developers so if this was an issue, we would have encountered it in the past.

OTOH I know nothing about your integration. But what I know is that, read-only or not, there is no easy way to hide the UI of the Classic editor ATM. 

I see 3 altertives for you:
   
* You might consider [Inline](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/inline-editor.html) or [Balloon](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/balloon-editor.html) editors instead. They have dynamic UI which stays hidden when in the RO mode.
* Or you can simply destroy the Classic editor instead of entering the read–only mode. 
* You can write some listener and modify the UI according to your needs
   ```js
   const toolbarContainer = editor.ui.view.stickyPanel;

   editor.on( 'change:isReadOnly', ( evt, propertyName, isReadOnly ) => {    
       if( isReadOnly ) {
            editor.ui.view.top.remove( toolbarContainer );
       } else {
            editor.ui.view.top.add( toolbarContainer );
       }
   } );
   ```
