### ISSUE TITLE
[Styles dropdown] Refine missing integrations between Styles dropdown and block widgets and document lists

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#13585]
In order to unblock #11577 and #11590 we need to remind what kind of issues we stumbled upon when working on these integrations for the fist time.

**Comment by niegowski** [comment]
### Widgets

The only written reason behind not handling them in MVC1 that I could find was this:

> There’s a too deep clash with e.g. image styles and predefined sizes.

_**My idea for this:**_ We could extend the styles dropdown API so that other features (like image style and image resize) could register their styles together with their custom implementation. This way it could use the dedicated commands and model attributes instead of using GHS for those features. This would essentially make the styles dropdown a central point of different styles repository with a single UI and it would be an integrator decision whether some styles should be applied with GHS underneath or it should use some feature's commands. Even the headings dropdown could register into the styles dropdown to make it a single dropdown for both (styles and headings). Of course as an option for an integrator.

### Document Lists

I'm not sure but it feels like it was a timing issue and both features were released and developed at the same time.
