### ISSUE TITLE
Speed up the CKEditor 5 development environment

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#13643]
### Why

* It's PITA that a quite simple change requires almost one hour to verify.
	* https://app.travis-ci.com/github/ckeditor/ckeditor5/builds/261295530
	* https://github.com/ckeditor/ckeditor5/commit/5a9e7cb15e62e73f8b739951a3c96b37705ee967

### What / ideas

* A new third thread could help. It could handle testing CKEditor 5 features.
* Try to execute CKEditor 5 features in parallel. Still determining how many threads are at the same time, but for sure, we can handle two processes simultaneously. 
	* AFAIR Travis gives a single thread, so we must make some magic with promises and the JavaScript loop.
* Perhaps it's time to configure CircleCI to compare times.
* (?)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
> *   AFAIR Travis gives a single thread, so we must make some magic with promises and the JavaScript loop.

That won't speed up anything (at least not significantly) if it's still a single thread. Running two Chrome instances may also be prone to these focus issues unless the headless Chrome can take care of detaching focus/selection from the OS in which it operates.

**Comment by filipsobol** [comment]
I agree that using promises will not help us much, but will probably increase the complexity of our tools. In the current state of the JavaScript ecosystem, we have to run TypeScript (`tsc`, `ts-loader`, etc.) to check types or generate `d.ts` files. However, for code transpilation and bundling we should aim to update our tools to something that can handle TypeScript files, but ignores typing, such as `esbuild` (I used it in the past and liked it a lot), `vite` (same), or `swc`.

I did some quick tests with promising results, but it (obviously) requires much more research.

I ran the `yarn test -f XXX --reporter=dots --production --coverage` command with the current Karma + webpack configuration for 3 packages and these are the results:

<table><tbody><tr><td>Package name</td><td>Total time</td><td>webpack time</td><td>webpack time as %</td></tr><tr><td>clipboard</td><td>36s</td><td>29s</td><td>81%</td></tr><tr><td>engine</td><td>71s</td><td>37s</td><td>52%</td></tr><tr><td>ui</td><td>44s</td><td>32s</td><td>73%</td></tr></tbody></table>

Then I replaced the `ts-loader` with `esbuild-loader` and ran the same commands:

<table><tbody><tr><td>Package name</td><td>Total time</td><td>webpack time</td><td>webpack time as %</td><td>Improvement over <code>ts-loader</code></td></tr><tr><td>clipboard</td><td>10s</td><td>4s</td><td>40%</td><td>-72%</td></tr><tr><td>engine</td><td>42s</td><td>10s</td><td>19%</td><td>-41%</td></tr><tr><td>ui</td><td>17s</td><td>5s</td><td>29%</td><td>-61%</td></tr></tbody></table>

In my experience, if we went even further and replaced `karma-webpack` with `karma-esbuild`, then the build time would be negligible (200-1000ms). Unfortunately, to my knowledge switching to \`esbuild\` isn't something we can do quickly, because we have a lot of tools written specifically for webpack.

What we can probably do in a reasonable amount of time is to prebuild all the TypeScript code before running the tests, so that Webpack doesn't have to handle it. There are some improvements we can make in this area as well.

I ran `build` commands for all packages between `adapter-ckfinder` and `table` with the current setup, then updated tsconfigs to use [TypeScript's project references](https://www.typescriptlang.org/docs/handbook/project-references.html) (see [changes on my test branch](https://github.com/ckeditor/ckeditor5/commit/1bd2c4b94c6c29a0a3246236070c602319c40cf3)), then changed the same configuration to only emit declarations (no JS output).

<table><tbody><tr><td>Current setup</td><td>7m 33s</td></tr><tr><td>Project references</td><td>2m 25s</td></tr><tr><td>Project references + <code>emitDeclarationOnly: true</code></td><td>2m 18s</td></tr></tbody></table>

Another small win might be the caching of yarn dependencies.

**Comment by pomek** [comment]
Thanks @filipsobol for the detailed research.

I am fine with replacing `ts-loader` with `esbuild-loader`. Then, we can talk about the next steps.

**Comment by martnpaneq** [comment]
Some progress was achieved with esbuild-loader and CI is green now. 

1. Most of the issues were caused by esbuild removing `/* istanbul ignore */` comments when transpiling code from typescript to javascript. In order to keep them, `-- @preserve` option needs to be added to all of them.

2. In the `engine` package, there were some new errors, but their origin is not fully known.
Looks like some paths, like missing `else` statements, that were previously just an info icon, are turning into errors - only on CI.

Prev:
![image](https://user-images.githubusercontent.com/114912428/229838945-c279da84-07fe-4126-99a0-d0e7883f4d6d.png)
Now:
![image](https://user-images.githubusercontent.com/114912428/229839212-8cfb74c9-419d-4906-981a-7152358ab183.png)

To fix those errors I used 4 new `/* istanbul ignore */` comments.

3. One `/* istanbul ignore */` comment that was meant for a single `case` clause is not being preserved even with `-- @preserve` option ([in this file](https://github.com/ckeditor/ckeditor5/pull/13809/files#diff-9fc89ca35370937e15cbdbdd3872b551e84389cd290bd0003bbd11362afbdba0)). 
I tried writing a proper test for it, but it took too long time with no progress. I had to ignore the whole `switch` statement.

4. The last thing to fix are `CK_DEBUG` comments. If we want them preserved, we also need to add `-- @preserve` flag to them. I added some code to the loader that handles them in `ckeditor5-dev`, but I need some help with testing it.

There are 2 PRs to merge:
https://github.com/ckeditor/ckeditor5-dev/pull/862 - needs testing for `CK_DEBUIG` loader with `-- @preserve` option
https://github.com/ckeditor/ckeditor5/pull/13809 - needs to wait for the PR above and need to add`-- @preserve` option to `CK_DEBUG` comments
