### ISSUE TITLE
Plug-in technology, please advise!!! wait anxiously

### ISSUE THREAD

**Issue by woisk** [ckeditor/ckeditor5#1367]
https://github.com/Suraj151/ckeditor5-code-block
I install this plug-in has been reporting errors, I seriously look for the reasons, did not find, has been reporting errors! 
![image](https://user-images.githubusercontent.com/18644664/48907909-d0811300-eea3-11e8-8bbc-0233c7378d7e.png)

**Comment by woisk** [comment]
For this plug-in, or to solve the pre-code code highlighting problem! I hope someone can guide me!!!! thank you very much indeed

**Comment by Reinmar** [comment]
I'm sorry, but we can't help you in debugging a  3rd party plugin. It may be incompatible with the current version of CKEditor 5 (it actually seems so, because it's based on `ckeditor5-engine@10.2.0`). I recommend either asking that package's author to update it or to fork it and do it yourself. I hope that'll help.

**Comment by woisk** [comment]
Plug-in idea: click on the label icon to appear a pre-code block container element, drop-down list to select the code language. According to the idea, the above plug-in seems to be a semi-finished product. Perhaps the API documents I understand are not thorough or biased, please guide me.

**Comment by woisk** [comment]
I'm sorry to disturb you again. But I really need a simple pre-code block container element. I tried to implement this function, but it took me a week to integrate it into ckeditor 5. Unfortunately,
