### ISSUE TITLE
TypeError: Class constructor ClassicEditor cannot be invoked without 'new'

### ISSUE THREAD

**Issue by maikkel** [ckeditor/ckeditor5#1369]
## Is this a bug report or feature request? (choose one)

🐞 Bug report (i guess)

## 💻 Version of CKEditor

^11.0.1

## 📋 Steps to reproduce

1. Recreate Code from Tutorial to add Plugin:
`// The editor creator to use.
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';

export default class ClassicEditor extends ClassicEditorBase {}

// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
    Essentials,
    UploadAdapter,
    Autoformat,
    Bold,
    Italic,
    BlockQuote,
    EasyImage,
    Heading,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Link,
    List,
    Paragraph
];

// Editor configuration.
ClassicEditor.defaultConfig = {
    toolbar: {
        items: [
            'heading',
            '|',
            'bold',
            'italic',
            'link',
            'bulletedList',
            'numberedList',
            'imageUpload',
            'blockQuote',
            'undo',
            'redo'
        ]
    },
    image: {
        toolbar: [
            'imageStyle:full',
            'imageStyle:side',
            '|',
            'imageTextAlternative'
        ]
    },
    // This value must be kept in sync with the language defined in webpack.config.js.
    language: 'en'
};

`
2.

## ✅ Expected result

Build ClassicEditor with Plugins included

## ❎ Actual result

No Build error, everything runs fine (webpack 4 / Babel),
But when i want to start the editor with ClassicEditor.create(...), I get the js error "Class constructor ClassicEditor cannot be invoked without 'new'"

## 📃 Other details that might be useful
I just need to add an icon with custom functionality and I must say i'm getting frustrated. In other editors i could do that by just adding something to the config. Here I have to use a Plugin and the whole editor must be rebuilt. I'm not a fan. I'm a fan of simplicity, this is not that. (and then it of course doesn't work... Sorry, but I lost hours to this and am contemplating abandoning ckEditor 5 for v. 4 or even TinyMCE or something else)

**Comment by Reinmar** [comment]
Hi! I'm sorry to hear that. Extending CKEditor 5 could indeed be easier, but we had to choose quite early between modularity (while avoiding magic) and apparent simplicity. We chose the former because it gives much better results in most scenarios. We sacrificed the latter ([for now](https://github.com/ckeditor/ckeditor5/issues/667)). We have experience how costly it is and how much magic is required to ensure cheap extensibility. Many developers are thankful that we dropped all that magic and went with popular build tools. They can integrate CKEditor 5 into their setups without fighting some custom build tools and automatic asset loading (present in CKEditor 4) which is incompatible with all modern build tools.

Anyway, I think that in your case the issue is that you used Babel but only for your own code and not for the libs. If you want to transpile your app to ES5, then you need to transpile CKEditor 5 as well. However, I don't know why are you transpiling your app to ES5 because CKEditor 5 works only in browsers which support ES6.

**Comment by oleq** [comment]
> you used Babel but only for your own code and not for the libs

Just FYI I had exactly the same issue (and error) when working on the Vue.js integration and using Vue CLI. The reason was, just like @Reinmar mentioned, that the dependency (CKEditor) was not processed by Babel.

**Comment by GoltsovS** [comment]
@maikkel i think [this](https://github.com/babel/babel/issues/4269) babel developers response help you :)

**Comment by shruthi-Salian** [comment]
Hello ,
I am getting below issue 
![image](https://user-images.githubusercontent.com/128622521/227233863-6b02ee9b-d938-4e92-8491-b8eb4ab90ec9.png)
