### ISSUE TITLE
Can't override css variables in ckeditor with vite builder

### ISSUE THREAD

**Issue by galtsevt** [ckeditor/ckeditor5#13709]
## 📝 Provide detailed reproduction steps (if any)

Using this [article](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html)  I found problems. After the build, ckeditor always inserts its css last in the head, which makes it impossible to override it with custom css.

![image](https://user-images.githubusercontent.com/104002161/226102184-7ca6ede4-e71d-47e2-9b09-965cb39b3dc3.png)

In vite dev development mode everything works fine, but after vite build ckeditor styles are always latest in head tag

### ✔️ Expected result

Override css variables in ckeditor

### ❌ Actual result

ckeditor's standard css variables always override custom ones

## 📃 Other details

* Browser: all
* OS: windows
* First affected CKEditor version: 36.0.1
* Installed CKEditor plugins: none

**Comment by Reinmar** [comment]
@LukaszGudel any ideas?

**Comment by LukaszGudel** [comment]
In my opinion, the issue is not related to using Vite. Looking at the style tag with `data-cke` attribute, it seems like an editor that was built with Webpack, as in our Vite integration we do not append editor styles as `<style>` tags. Instead, we only apply necessary modifications and leave modified CSS files to Vite for further processing/bundling.

The same issue can be seen here: https://codesandbox.io/s/misty-leaf-4qojw0?file=/index.html. In this example, the background color of the editor is customized in an additional `<style>` element, but it does not apply. The reason is that editor styles are appended to head as the last element, and as both style definitions have the same specificity, the styles from the editor "wins".  

@galtsevt Could you describe how are you applying your custom styles on the editor? Could you check if increasing the specificity in your custom CSS is fixing your issue? (e.g using `body` instead of setting the styles on `:root`)

**Comment by galtsevt** [comment]
> На мой взгляд, проблема не встречается с использованием Vite. Глядя на стиль тега с `data-cke`атрибутом, редактор был создан с помощью Webpack, так как в нашей работе с Vite мы не нашли стиль редактора в качестве `<style>`тегов. Вместо этого мы вносим только необходимые изменения и оставляем измененные файлы CSS в Vite для дальнейшей обработки/объединения.
> 
> Ту же проблему можно увидеть здесь: https://codesandbox.io/s/misty-leaf-4qojw0?file=/index.html . В этом цветном редакторе фонарей настраивается дополнительный `<style>`элемент, но он не присоединен. Причина в том, что стили редактора добавляются к заголовку в качестве последнего элемента, и поскольку оба определения имеют одинаковую спецификацию стиля, стили из редактора «выигрывают».
> 
> @galtsevtНе могли бы вы описать, как вы привлекли свои регионы стиле в редакторе? Не могли бы вы проверить, решает ли ваша проблема повышение специфики вашего пользовательского CSS? (например, использование `body`вместо установки стиля `:root`)

My code:
`import ClassicEditor from '@ckeditor/ckeditor5-build-classic'
import '../sass/themes/ckeditor/_dark_theme.scss'

    let editor = document.getElementById('editor');
    if (editor) {
        ClassicEditor.create(editor, {
            toolbar: {
                shouldNotGroupWhenFull: true
            }
        })
            .catch(error => {
                console.error(error);
            });
    }`
In vite dev development mode, the styles are merged and nothing is added at the end of the head tag. But after npm run build ckeditor adds its css styles in a separate tag to the end of head. I am using vite 4.0 and laravel 10. I am not using webpack

**Comment by Witoso** [comment]
I think the problem relates to the build process. As you're not using webpack to build the editor some unexpected things may happen, depending on your Vite config.

Try to use our experimental Vite plugin: https://github.com/ckeditor/vite-plugin-ckeditor5
Here's the guide: https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/integrating-from-source-vite.html

With it, I managed to import custom styles, and it worked both for dev and prod modes.
