### ISSUE TITLE
Convert back DLL packages to JavaScript

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#13794]
### Why

* We must prepare DLL builds from JavaScript files to save backward compatibility between them.
	* Example: As a maintainer of a package written for v33.0.0, I would like to have it compatible with the latest version - v37.0.0.
	* If there were no breaking changes in the editor API, my dll feature should work fine with the latest DLL build.
* JS, TS, and typing contain the same value. TS needs to bring something here, and unfortunately, it doesn't.
* Whenever somebody tries to prepare DLL builds, we must prepare JS files first. We tried to solve it using npm scripts (pre hooks), but there is at least one script that does not trigger them ([`scripts/dll/build-dlls.js`](https://github.com/ckeditor/ckeditor5/blob/02fcc03a27e96337b7bcc18980da9140768317b9/scripts/dll/build-dlls.js)).

### Decisions

* Let's convert `ckeditor5` and `ckeditor5-collaboration` packages to JavaScript.
* Make sure to generate typings for them.

**Comment by Reinmar** [comment]
> *   We must prepare DLL builds from JavaScript files to save backward compatibility between them.

We should, but doing such changes as completing the huge migration to TS we can break this compatibility. We never claimed it actually existed anyway.

> *   JS, TS, and typing contain the same value. TS needs to bring something here, and unfortunately, it doesn't.

The value is that the entire `src/*` in all related packages on GH is in TS. This is consistency.

Having them in JS might be a bit odd. I suppose we can run into weird issues due to that inconsistency. Like for instance, we may forget we have such files and mistakenly disable linting for them at some point. Or something more serious.

> *   Whenever somebody tries to prepare DLL builds, we must prepare JS files first. We tried to solve it using npm scripts (pre hooks), but there is at least one script that does not trigger them ([`scripts/dll/build-dlls.js`](https://github.com/ckeditor/ckeditor5/blob/02fcc03a27e96337b7bcc18980da9140768317b9/scripts/dll/build-dlls.js)).

Do I understand correctly that this was the actual trigger for opening this issue?

If not – I want to understand what was that.

Because, by converting them back to JS we do an unintuitive step back and that made me worried.

**Comment by pomek** [comment]
> We should, but doing such changes as completing the huge migration to TS we can break this compatibility. We never claimed it actually existed anyway.

The manifest file contains paths to the JavaScript file. If we decide to build it from TypeScript, the paths will point to TS that are not published anywhere. So, the entire idea of the DLL concept will fail and each feature will include the entire CKEditor 5 framework inside its distribution.

**Comment by pomek** [comment]
We decided to keep these packages as TypeScript and fix issues in the builder.
