### ISSUE TITLE
Question: CKE5 and React

### ISSUE THREAD

**Issue by iPaoo** [ckeditor/ckeditor5#138]
Will the CKE5 release good to work with ReactJS ?

**Comment by fredck** [comment]
That's an interesting question, @ZeGregg. Let's try to work further to understand this together... how do you see the participation of CKEditor 5, or any text editor, into a isomorphic app realm?

**Comment by ZeGregg** [comment]
Hmm, sorry I edited my post because the question was not relevant. Not sure it is better now :)

**Comment by ZeGregg** [comment]
Currently we need to manage all DOM mutations ourself in the contenteditable area and can't take advantage of React.

**Comment by fredck** [comment]
If you're talking about CKEditor internals, we'll have a dedicated "model <--> view" implementation that handles this. When it comes to changes on external data, CKEditor participates as a component merely, which gets connected to the data through any web technology, including React.

But the fact is that I may not get your expectations on your questions, so maybe you could expose what you would like to happen and how you would see this and then we can comment on how CKEditor 5 fit on that. Thanks!

**Comment by Reinmar** [comment]
I'm not sure I understand the question so I'll answer two that come to my mind.

1. Will you be able to use CKEditor with React?

  I guess you will. It's just like any other library. Perhaps some integration will need to be done, but not more than ensuring that React won't destroy the editor.

2. Is CKEditor using React?

  Nope. It is however using similar concepts in its editing engine. The internal data model is first rendered to a virtual DOM which is later compared with the real one and minimal changes are done in there.

**Comment by JLRishe** [comment]
I'm not using react, but I am running into problems with using Matt Esch's virtual-dom with CKEditor. The issue is like this:

Let's say I create a div with id rt1 and attach a CKEditor to it.

````
<div>
    <div id="rt1"><!-- this has a CKEditor --></div>
</div>
````

Now I want to add a new CKEditor before `rt1`, so I have the virtual-dom render that:

````
<div>
    <div id="rt2"> </div>
    <div id="rt1"> </div>
</div>
````

However, I encounter an error when I try to attach the CKEditor to `rt2` because a CKEditor is already attached to it, and the CKEditor is no longer attached to the current `rt1`. What has happened is that the virtual-dom added `rt2`s attributes to `rt1` and created a new `rt1` after it.

I realize this isn't CKEditor's fault and the issue is with how virtual-dom is designed to work, but can you suggest any way to work around this behavior? If I have to detach and re-attach all of the views CKEditors on each render, I can live with that, but is there an easy way to do that?

**Comment by Reinmar** [comment]
Hi JLRishe,

Sorry to hear that. This perhaps isn't the best thread to ask this question, because it's about something else (future support for React by CKEditor **5**), but your case is something that we'll need to remember. I don't know virtual-dom and I'm not sure I understand your problem, but the only reasonable solution to me would be preventing touching a specific element, so you don't have to re-attach all the events. If that's impossible, then it sounds like a strong limitation of that library.

Anyway, you should ask this question on SatckOverflow or some more appropriate place, because this is off-topic.

**Comment by Reinmar** [comment]
A CKEditor 5 React component is currently being developed in https://github.com/ckeditor/ckeditor5-react. That will be the easiest way to include CKEditor 5 in a React app.
