### ISSUE TITLE
CMD + Click on a link = opens the link in a new tab

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#1381]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Insert a link in the editor.
2. Hold CMD and click on the inserted link.

## ✅ Expected result

Editing link toolbar should appear. The link shouldn't be opened in a new tab.

## ❎ Actual result

Clicked link is opened in the new tab.

## 📃 Other details that might be useful

I am not sure it is a bug or not. If not, the ticket is invalid.

**Comment by pomek** [comment]
I forgot to mention about browsers… I can reproduce it on Firefox. On Chrome this behaviour does not occur. So it seems to be a bug.

**Comment by oleq** [comment]
I confirm that but...

...I also noticed this is a native feature of FF called "Open in Background Tab" https://support.mozilla.org/en-US/kb/mouse-shortcuts-perform-common-tasks, which can also be triggered by middle-clicking a link. I checked CKEditor 4 and it allows this behavior. I don't remember any bug reports concerning it in the past.

Anyway, neither <kbd>Ctrl/Cmd</kbd>+left click nor plain middle-click opens a new tab in Chrome. I checked that using plain `contenteditable` so it's not precisely about CKEditor 5.

TBH, I wouldn't be worried about that. Even if a user uses this shortcut accidently, the link opens in a background tab which does not disrupt the editing process. What's more, instead of disabling it in FF, I'd rather consider implementing the feature for Google Chrome because it feels like a nice UX to me.

cc @Reinmar

**Comment by dkonopka** [comment]
> What's more, instead of disabling it in FF, I'd rather consider implementing the feature for Google Chrome because it feels like a nice UX to me.

👍  👍  👍

**Comment by mlewand** [comment]
I know this has been requested feature back in CKE4 (not the most popular one, but the kind that is asked every 2 months or so) and we made unofficial plugin on my account that people were happy with https://github.com/mlewand/ckeditor-plugin-openlink

**Comment by Reinmar** [comment]
Note: If we'll work on this, let's make sure we don't introduce any XSS issues.
