### ISSUE TITLE
Images and tables are automatically selected after CKEditor initialization

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5#1384]
🐞 Bug report

## 💻 Version of CKEditor

11.1.1 custom balloon build

## 📋 Steps to reproduce

1. Initialize CKEditor 5 instance with text containing either image or table
2. No user interaction is done with the editor instance
3. Call following plugin code:

```javascript
printSelectedHtml() {
	const model = this.editor.model;
	const document = model.document;

	const content = this.editor.data.toView(model.getSelectedContent(document.selection));

	console.log(this.htmlDataProcessor.toData(content));
}
```

## ✅ Expected result

"" (empty string)

## ❎ Actual result

```
<figure class=\"table\"><table><thead><tr><th>&nbsp;</th> [actual table content] <td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table></figure>
```

## 📃 Other details that might be useful

This doesn't happen when content is just (formatted) text - the method above correctly returns empty string.

**Comment by Reinmar** [comment]
It works this way because the editor needs to have any selection set at all time (including, right after the initialization). There can be no selection before that image/table (at least, in the current state of things) and therefore the first selectable thing is that image/table itself. This may change once we'll resolve https://github.com/ckeditor/ckeditor5/issues/407 (we may create some magic space before/after such objects), but for now, that's the behaviour.

I understand this may be surprising/unwanted, but I don't consider this a bug, so I'm closing this ticket.
