### ISSUE TITLE
[Docs] Update the migration guide

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#1410]
This page became outdated after the last releases: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html

For example paste from word is mentioned there as "planned", "Media embedding is not supported yet, but it is planned." and so on.

**Comment by mlewand** [comment]
@pomek also hinted couple of examples in #1566:

| CKEditor 4                                      | CKEditor 5                                                                                                                                                                                           | What did we change?                                                                                                                                                                                                                         |
|-------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `autoEmbed_widget`                              | Media embedding is not supported yet, but it is planned.                                                                                                                                             | [Media-embed](https://github.com/ckeditor/ckeditor5-media-embed) plugins is available.                                                                                                                                                      |
| `coreStyles_subscript` `coreStyles_superscript` | Planned.                                                                                                                                                                                             | [Already available](https://github.com/ckeditor/ckeditor5-basic-styles/tree/b96cf6d17a48127a17bbe3d2f4ba9d5a709c0dd8/src) but they aren't a part of CKEditor 5 builds. The entire section could be even merged with `coreStyles_underline`. |
| `enterMode`                                     | CKEditor 5 always creates a new paragraph (`<p>` element) as specified by Editor Recommendations - Enter key. `Shift + Enter` support is handled in https://github.com/ckeditor/ckeditor5-enter/issues/2. | Support for `Shift+Enter` is already available.                                                                                                                                                                                             |
| `shiftEnterMode`                                | N/A. `Shift + Enter` support is handled in https://github.com/ckeditor/ckeditor5-enter/issues/2                                                                                                        | See: `enterMode`                                                                                                                                                                                                                            |

**Comment by Reinmar** [comment]
> 1. `allowedContent`: Should we mention the conversion guides?

It's worth to do that. To explain very briefly that only content which is explicitly converted between M<->V by plugins is preserved. And that one can extend those conversion rules.

> 2\. `autoGrow_*` - Should we mention that CKEditor 5 (by default?) automatically grows with content?

Yup. That there's no need for such an option.

> * `bodyClass`: What about document/decoupled editor?

In the decoupled editor you initialize the editable on a passed element, so you have control over that. The same for inline and balloon ones. The only problematic one is the classic which creates its own container. However, one can wrap the editor with their own container and define the class they want there.

Also, please note that all editor types use `.ck-content` on their main root editable elements. So, this class can also be used to write stylesheet rules for editor content.


> * `disableNativeSpellChecker`: What about document/decoupled editor?

This is fine now, but perhaps a bit unclear:

![image](https://user-images.githubusercontent.com/156149/68039676-f0809f80-fccc-11e9-8dd9-9539ba82df50.png)

In case of editors such as balloon or inline you can set the attribute directly on the element on which you setup the editor (before initializing it). But you can also use the given snippet which will work on all types of editors.


> * `fillEmptyBlocks` - Should we mention how CKEditor 5 behaves by default? We get asked about why `<p>&nbsp;</p>` is needed quite often.

We can mention that blocks are always filled because that ensures that the intention of the content author (who left such empty lines) will be preserved in the output data.

> * `height`, `width` - What about other editors?

EEee... the mention of `.ck-editor` (in the current state of this guide) makes no sense, IMO. I'd say that the `.ck-editor__editable_inline` rule should be used in case of all types of editors. cc @oleq to confirm.



> * `linkDefaultProtocol` - Can you use link decorators to set the default protocol or force a protocol?

Nope. There's no trivial way now.





> 8\. `menu_groups` - Can/should we add something about balloon/contextual toolbar configuration in CKEditor 5?

Link to config.toolbar + a mention that features such as table and image come with their own toolbars (that you can configure) would be enough.



> * `pasteFilter` - Any reference to Paste from Word, dropping unsupported formatting/styling?

Hum... It's hard to mention anything here. The thing is that we indeed don't allow to easily filter pasted data only.

But we can somehow mention that and add that such an option doesn't seem to be necessary in today's reality where the editor always trims the pasted content to match what the available plugins can handle. But if anyone would like to filter pasted content even further, please report a ticket.


> * `resize` - Any suggestion on how to resize the editor or why it is no longer possible in a similar way that was available in CKEditor 4?

First of all, it's not necessary in most cases. Just leave the editor's editable styled with `min-heigth` and `max-height` or `height` if you want to somehow limit the height. In special cases where you really need to allow users changing the height, you will need to implement it yourself..

We can also add that the resizing was necessary in the past since the editable height's defaulted to... 300px. Once that's gone the requirement to make the editable resizable didn't appear (I think I remember just one question about this).



> * `sharedSpaces` - We mention document editor here, but perhaps [multi-root editor](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html) is a better example?

Both are fine. The document editor allows controlling where precisely is the toolbar located (and that's what for most people used sharedSpaces in the past :D) but using multi-root can help in some scenarios too.

> 12\. `stylesSet` - This was an important CKE4 feature. We should direct users to anything relevant somehow.

Not really available yet, without writing a custom feature. I'd say that we can direct them to https://github.com/ckeditor/ckeditor5/issues/648 or a newly opened https://github.com/ckeditor/ckeditor5/issues/5700.

**Comment by oleq** [comment]
> EEee... the mention of `.ck-editor` (in the current state of this guide) makes no sense, IMO. I'd say that the `.ck-editor__editable_inline` rule should be used in case of all types of editors. cc @oleq to confirm.
> 
> >

Yeah, editors like inline or balloon have no UI element with `.ck-editor` class. All they have are editables with `.ck-editor__editable_inline`.

**Comment by AnnaTomanek** [comment]
Updated the PR with your comments. Also, fixed formatting and links. What sort of review you two did that you did not see that? 😉

**Comment by Reinmar** [comment]
I didn't do any review so far ;) I replied to questions :P

**Comment by jwylarsen** [comment]
> > * `fillEmptyBlocks` - Should we mention how CKEditor 5 behaves by default? We get asked about why `<p>&nbsp;</p>` is needed quite often.
> 
> We can mention that blocks are always filled because that ensures that the intention of the content author (who left such empty lines) will be preserved in the output data.

Why are you assuming the intent of the author? I have JS plugins that are broken by nbsp entities inserted into empty table cells.
