### ISSUE TITLE
Uploading a file with a "variable" upload url (S3 Presigned URL)

### ISSUE THREAD

**Issue by ile** [ckeditor/ckeditor5#1417]
🆕 Feature request

## 💻 Version of CKEditor

CKEditor5
```
│ ├─┬ @ckeditor/ckeditor5-core@11.1.0
│ │ ├─┬ @ckeditor/ckeditor5-engine@12.0.0
│ ├─┬ @ckeditor/ckeditor5-editor-balloon@11.0.2
```

## 📃 Other details that might be useful

I need to upload a file using the [AWS S3 Presigned URL](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html). This url is different for each files and contains authorization info etc. that S3 needs.

The url is created right after the file is dropped into the editor.

I was looking at the upload adapter, and it didn't seem instantly obvious if this is possible. I would probably need to intercept the upload process after the file is dropped (or pasted or selected from the file system) into the editor, then fetch the presigned url with aws sdk, and then continue the upload process.

I could probably attach the url into the file object, so that could be how the adapter knows about the url. **BUT** I don't know how to intercept the upload process (after file is dropped) and fetch the url.

Any help? Thanks.

**Comment by ile** [comment]
Maybe I have to fork `@ckeditor/ckeditor5-image/src/imageupload` and add this functionality there.

Maybe you could think of some method to intercept/continue the upload process tight after the file is selected/inserted into the editor?

**Comment by ile** [comment]
I could perhaps do this in the upload adapter, but I would need some way to inform the outside world that the upload url is needed. 

That could be done with an event and an API that receives the url, for example.

**Comment by f1ames** [comment]
Hello @ile,
I would go with the custom upload adapter in this case so it should be straightforward to add _Presigned URLs_ logic there. You can check the docs on [creating custom upload adapters](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html). And also take a look at existing [CKFinder](https://github.com/ckeditor/ckeditor5-adapter-ckfinder/blob/master/src/uploadadapter.js) and [Easy Image](https://github.com/ckeditor/ckeditor5-easy-image/blob/master/src/cloudservicesuploadadapter.js) adapters.

As `Adapter.upload` method have access to a `File` instance which is being uploaded you may generate the URL there. The method should return a `Promise` instance so if presigning URLs process is async it should also work without any issues (btw. I haven't found if there is a way to presign URLs in JavaScript AWS SDK, but I hope it would not be an issue here).

**Comment by ile** [comment]
Yes, there doesn't seem to be any problems here.

One thing is that I want to use the websocket transport (to access the server from the client) that lives outside the editor, but since the upload adapter can access the editor object and o can the outside world, I think I will just pass that websocket with the editor object.

I think I will just close this question since there wasn't any problem after all. 

Thanks!

**Comment by rivernews** [comment]
Since this is the first result I found on Google, so I'm posting this question here - how to let Ckeditor display image that needs a presigned url?

I understand that I can write custom image uploader to allow CKeditor to upload and retrieve the presigned url **for the first time**. I see we can even [pass additional data](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html#passing-additional-data-to-the-response) from the server to the editor, and use that to [set custom attributes](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageupload_imageuploadediting-ImageUploadEditing.html#event-uploadComplete) on the `<img />` tag.

But what I don't understand is how can we instruct CKeditor to request presigned url, for existing images? 

Say you uploaded an image, got the presigned url (w/ 10min expire time) and image displayed; then you saved and closed the doc. Tomorrow, you open the editor again, now - how to display the image you previously upload yesterday? If you simply use `<img src="presigned_url_here" />` to display images, that presigned url you retrieved yesterday has already expired!

The Ckeditor "[image feature](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-overview.html)" doc does not mention any ways to customize any image loading behavior. Does anyone know how to do this (without setting bucket to public - the image uploaded is private)? I was confused that this issue seems that it solved the upload part - @ile  I wonder how you solved the image display part? Some guidance would be greatly appreciated.

**Comment by biku1998** [comment]
@rivernews did you find any solution to the above? I have a similar use case.

**Comment by SlawomirMazgaj** [comment]
It's been a while, but @rivernews, @biku1998 did you find any solution or did you end up with public bucket?
