### ISSUE TITLE
`{#if condition}` statement in code block breaks documentation

### ISSUE THREAD

**Issue by filipsobol** [ckeditor/ckeditor5#14189]
The documentation I'm writing for the Svelte integration contains several code samples that use `{#if condition}` statements. Unfortunately, it breaks the documentation and doesn't render the code block completely or anything after it.

See [this document](https://github.com/ckeditor/ckeditor5/blob/add-documentation-for-Svelte-integration/docs/installation/frameworks/svelte.md) (still a work in progress) on the [`add-documentation-for-Svelte-integration`](https://github.com/ckeditor/ckeditor5/blob/add-documentation-for-Svelte-integration) branch.

Note that in the document linked above, I replaced `{#if editor}` and `{/if}` with `{{}#if editor}` and `{{}/if}` just to be able to render the page.

**Comment by pomek** [comment]
What does it mean "break documentation"?

**Comment by filipsobol** [comment]
> doesn't render the code block completely or anything after it.

Nothing after `{#if}` statement renders on the page.

**Comment by filipsobol** [comment]
I did and unfortunately it doesn't help.

**Comment by psmyrek** [comment]
It turns out that the reason for this behavior is that Hexo supports [tags](https://hexo.io/docs/tag-plugins) in the [Nunjucks templating language](https://mozilla.github.io/nunjucks/). They allow to quickly add specific content to the generated pages. The `{#` token starts a Nunjucks comment. Since there is no closing `#}` token, the rest of the page is truncated.
