### ISSUE TITLE
[GHS/Style] List styles preserves itself and spreads to other list types and blocks.

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#14216]
## 📝 Provide detailed reproduction steps (if any)

1. Have a style defined for the `ul`
2. Apply the style to the list.
3. Two enters.
4. Create an `ol` list.
5. The class and style are there and it's not possible to disable it.

https://github.com/ckeditor/ckeditor5/assets/9881379/0d20a7d4-34e3-4fa9-ab48-a0cd06719796

### ✔️ Expected result

`ol` doesn't have the style.

### ❌ Actual result

`ol` has the style.

### ❓ Possible solution

1. Clear the `htmlListAttributes` on non-list blocks.
2. Allow deleting the style even if it's on the wrong element! That would be at least some better UX for handling situations like this.

## 📃 Other details

Workarounds: delete the class via the Source mode or turn to a different list, disable the style turn back to the list type you wanted to have.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
1. Research changing `htmlAttributes` to `htmlXAttributes` defined for each element (`X`). That would be a generic fix.
2. On rename/change of the element remove the `htmlXAttributes` if they don't belong to the element.

**Comment by filipsobol** [comment]
This task was split into 3 PRs:

* Change `htmlAttributes` to `html*Attributes`, where `*` represents the name of the view element, e.g.: `htmlDivAttributes` - https://github.com/ckeditor/ckeditor5/pull/14271.
* Remove unrelated `html*Attributes` from elements, e.g.: `htmlDivAttributes` from `paragraph` - https://github.com/ckeditor/ckeditor5/pull/14307.
* Change `htmlListAttributes` to `htmlUlAttributes` and `htmlOlAttributes` depending on the list type - **WIP**.

**Comment by filipsobol** [comment]
Since styles leaking to other elements is a recurring problem, we decided to look at it more broadly and fix it so that it doesn't happen in any case, not just the one described in this ticket.

We decided to rename the attribute created by GHS (General HTML Support) that the `style` plugin depends on from a generic `htmlAttribute` used by all elements to a unique name `html*Attributes` for each element type, where `*` is the name of that element, e.g: `htmlDivAttributes` or `htmlH1Attributes`. This allows us to filter out unwanted attributes from the elements.

This way, when we:
* insert an H1 element and press Enter at the end, the newly created paragraph will not inherit H1's HTML attributes (previously, this case required a special handler),
* change the list type from ordered to unordered or vice versa, the old style will be removed,
* Follow the steps described in this ticket, paragraph and subsequent lists will not inherit styles from the first list.
