### ISSUE TITLE
An error occured during the build: Error: EMFILE: too many open files 

### ISSUE THREAD

**Issue by Tiru150837** [ckeditor/ckeditor5#14260]
While I am running ng build command , I am getting this error

An error occured during the build:
Error: EMFILE: too many open files, open '..\dist\assets\ckeditor5-28.0.0\packages\ckeditor5-build-classic\node_modules\esprima\bin\esvalidate.js'
EMFILE: too many open files, open '..\dist\assets\ckeditor5-28.0.0\packages\ckeditor5-build-classic\node_modules\esprima\bin\esvalidate.js'

How to resolve this issue?

**Comment by Reinmar** [comment]
I'm sorry but the issue doesn't seem to be related to CKE5.

If anything I could recommend, it'd be bumping up the dependencies of your project, cleaning them up from old stuff and reinstalling everything. I'm mentioning this because I can see esprima inside your build-classic and that you use 28.0.0 of CKE5 (couple years old). The easiest way out may be migrating to new versions across your stack.

**Comment by Tiru150837** [comment]
Actually after deleting the node_modules in ckeditor-build-classic, that error is gone. My application is running fine. 
Is there any chances of any problems by removing node_modules ?

**Comment by Tiru150837** [comment]
Reinmar, Thanks for suggestions
