### ISSUE TITLE
Color inputs in table show both hsl an hex values when using color picker

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#14288]
## 📝 Provide detailed reproduction steps (if any)

1. Open all features manual test on `ck/2978-integrate-new-color-picker-with-CKE5-features` branch
2. Try using color picker with table

### ✔️ Expected result

Not sure but I'd assume that if color picker shows hex, then other inputs will also show hex values.

### ❌ Actual result

Color picker shows hex but input in properties panel shows hsl:

![Screenshot 2023-05-30 at 14 33 56](https://github.com/ckeditor/ckeditor5/assets/34380544/d3581943-10cd-4b82-8fba-042415af8385)

## 📃 Other details

* Browser: any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Good catch @FilipTokarski.

I think in this case we could actually hide the hex field, as text input is already visible above the picker.

However, we'd need to ensure that the field in table balloon is bound and updates along with the changes in picker.

---

And the input field should keep the format as it has today (so hsl by default). It's ugly, but it's backward compatible.

**Comment by Dumluregn** [comment]
> I think in this case we could actually hide the hex field

I think it could and should be configurable per color picker component. Then it could be disabled by default for table, and enabled for font, but without the need to differentiate the code (which we're trying to undo).

**Comment by oleq** [comment]
Together with @mlewand we made a decision to make the color picker view configurable so that the input can be hidden

<img width="419" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/1099479/1727bbc8-2c1e-4ede-9029-d5bab81f2b08">

This should address all UX concerns.

**Comment by oleq** [comment]
* There must be a config option in `ColorPickerView` that prevents rendering the input (`hideInput?: boolean`?).
* There must be a config in `ColorTableView` that gets passed down to the `ColorPickerView` so that the table UI can declaratively hide the input.
* We hide the `ColorPickerView#hexInputRow` as simply as possible: whether by not adding it to the parent collection or by binding `.ck-hidden` class on the template. Whatever works and does not break the component is the right way to go. It does not matter that the component may still get updated in the background (value bindings, etc.).
* The format of the config and the TS typings are left to the developer.
