### ISSUE TITLE
Design the show blocks feature

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#14290]
Design the feature described in https://github.com/ckeditor/ckeditor5/issues/9398.

Key points:
* The blocks should show related elements in data pipeline.
* It must be possible to nest blocks (e.g. div > div > blockquote > p - all blocks need to be visible).
* Enabling the feature should be same as in CKE4 - just a toggle button in the toolbar.
* Nice to have: would be great not if it didn't change geometry so that it doesn't affect features like pagination.
* Nice to have: Widget handling.

**Comment by oleq** [comment]
# The proposal 

We're mostly replicating the look of the feature from CKEditor 4. I took the liberty of proposing some improvements, though.

<img width="1168" alt="light-mode" src="https://github.com/ckeditor/ckeditor5/assets/1099479/53202d02-0754-4cff-94fc-52622ec10925">

* I prepared two icons: one that is a copy of the icon from v4 and a new one that I hope is less ambiguous.
   * Let's have a vote.
* The contrast ratio between the dashed border (`#757575`) and the white bg passes WCAG AA. The color could be even slightly brighter and still pass the recommendations. There's room for adjustment, we can experiment with it.
* The label is 8px monospace font text (`#000000`).
* The contrast between label bg and text passes WCAG AA (`#EAEAEA` vs `#000000`). 
* Unlike the implementation in v4, I added 8px padding to the top of the blocks only (v4 adds it to the left too). Let's see how it works out with live content. 
   * I suppose we'll fine-tune the looks of the feature live in CSS anyway.

## Dark mode

**Note**: CKEditor 5 does not officially support dark mode. This is not an official integration, it's just a showcase of what it will look like if somebody uses this feature in dark mode.

I figured I can design the feature so that at least it does not look awful in the dark mode. That's why I went with the background for the labels: they will stay readable no matter what. The dashed border will lose accessibility but there's no quick win here unless we properly discover dark mode and provide an alternative.

<img width="1168" alt="dark-mode" src="https://github.com/ckeditor/ckeditor5/assets/1099479/52d2a253-cebb-4469-b7f5-04e2a03506b1">

**Comment by mlewand** [comment]
Good call with bg for labels. Everything except the icon looks nice.

Regarding the icon, neither looks intuitive to me 😕

*   The new proposed icon has this diagonal line, for some reason it makes me think of "no color" UI.

![](https://github.com/ckeditor/ckeditor5/assets/5353898/e9f7d190-5af8-4ca5-9710-4cbd5bc0d04b)

*   The old icon indeed is ambiguous, it focuses more on solid border blocks, rather than dashed. And the structure of these blocks could be equally something related to column charts if you ask me 🙈
*   How about showing just two dashed blocks?

![](https://github.com/ckeditor/ckeditor5/assets/5353898/49aa99b5-682a-4794-b5eb-7c6c054a7c33)

**Comment by pszczesniak** [comment]
Personally i like the new icon design, but yes, it's similar to "no color" icon.

Maybe somthing like this :point\_down: 

![Screenshot 2023-06-02 at 14 51 48](https://github.com/ckeditor/ckeditor5/assets/7074833/01dafedc-d3f4-4918-b928-aa00d68003be)

or similar?

**Comment by mlewand** [comment]
We have the design complete, the only thing we talk about is the icon.

I'm extracting the icon to #14342 so that we can proceed with the implementation.
