### ISSUE TITLE
New ColorPicker submits form

### ISSUE THREAD

**Issue by The-io-dev** [ckeditor/ckeditor5#14361]
## 📝 Provide detailed reproduction steps (if any)

1. Have an editor with color picker inside a <form>
2. open the color picker, and validate a color

### ✔️ Expected result

The validation of the color should only update the color defined within ckeditor perimeter.

### ❌ Actual result

it also submits the form

#### 🩹🩹🩹 A workaround is available until fix is released: https://github.com/ckeditor/ckeditor5/issues/14361#issuecomment-1582231287 🩹🩹🩹

the button being of type="submit" it is expected behavior from HTML.

the switch to a type="button" should correct it.

## 📃 Other details

It might have sens to add an eslint rule to enforce type="button" on all <button>, since the default type value is submit, but i don't know the whole project.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Thanks for a report! We were clearly doing smoke tests outside of a `form` element thus we missed this important bug.

I'm adding it to our sprint backlog and we'll release the fix in June release.

---

Fixing the issue is one thing but I'd like us to avoid having such issues in the future.

Thanks for suggesting linter rule for submits, however we have a good portion of abstraction over the buttons.

Precisely speaking, this is the line where the issue is: [https://github.com/ckeditor/ckeditor5/blob/72e979b16a7f0b679a313a8638623349d274c36d/packages/ckeditor5-font/src/ui/colortableview.ts#L1005](https://github.com/ckeditor/ckeditor5/blob/72e979b16a7f0b679a313a8638623349d274c36d/packages/ckeditor5-font/src/ui/colortableview.ts#L1005)

I actually find submit type to be a value here (it adds proper semantics). So what we need here is to properly prevent default's `button[type=submit]` action.

**Comment by mlewand** [comment]
Until we release a proper fix, you can add the following code in your app:

```javascript
window.setInterval( () => {
	Array.from( document.querySelectorAll( '.ck.ck-color-table .ck-color-picker-page-view [type="submit"]') ).forEach( button => {
		if ( button.dataset.ckeSubmitWorkaround ) {
			return;
		}
	
		button.addEventListener( 'click', event => event.preventDefault() );

		button.dataset.ckeSubmitWorkaround = true;
	} )
}, 300 );
```

Since it's polling the structure it's not super effective, however there's a simple safeguard to make sure this code is taxing as little as possible.

**Comment by illia-stv** [comment]
Taken over by https://github.com/ckeditor/ckeditor5/pull/14275 .

**Comment by Dumluregn** [comment]
There are more buttons that may have the same side effect - e.g. "Save" buttons in table properties and table cell properties. Let's make sure they work as expected too.

**Comment by AliaksandrBortnik** [comment]
We faced the same issue related to our form submissions due to the submit button of color picker.
