### ISSUE TITLE
Review CKEditor 5 UX/UI

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#14363]
## Provide a description of the task

Review our existing features in CKEditor 5 (including Collaboration & Premium features).

What we're looking for is to:

*   list inconsistencies across features,
*   find design flaws in UIs,

Best place to start looking at it is:

*   [https://ckeditor.com/docs/ckeditor5/latest/features/index.html](https://ckeditor.com/docs/ckeditor5/latest/features/index.html) (to check feature-by-feature)
*   [https://ckeditor.com/ckeditor-5/demo/feature-rich/](https://ckeditor.com/ckeditor-5/demo/feature-rich/) - demo that has many features (though not all of them)

**Comment by dagdzi** [comment]
Results: [CKEditor – inconsistencies](https://www.notion.so/a58a13cb57bd4524afb2db8c007a901a?v=7bab2b35a2a844c0a71564e32daa9d54&pvs=4)

**Comment by Dumluregn** [comment]
@oleq will take a look at the results and reforge them into tickets. Let's have a meeting with product guild to discuss the details.

**Comment by Witoso** [comment]
Before generating numerous tickets, could we consider categorizing them into 'Splash zone,' 'Impact,' or 'Confusion Factor' to prioritize our discussions in the product/design guild? This way, we can focus on addressing the most significant issues first. Rather than creating tickets upfront, we could aim to identify the most actionable items. Creating a smaller number, 5ish? issues, will help prevent decision paralysis that may arise from a larger volume of tickets :D

**Comment by oleq** [comment]
> Before generating numerous tickets, could we consider categorizing them into 'Splash zone,' 'Impact,' or 'Confusion Factor' to prioritize our discussions in the product/design guild? This way, we can focus on addressing the most significant issues first. Rather than creating tickets upfront, we could aim to identify the most actionable items. Creating a smaller number, 5ish? issues, will help prevent decision paralysis that may arise from a larger volume of tickets :D

I second this approach.

**Comment by Dumluregn** [comment]
There will be cyclical meetings where these tasks will be gradually refined.
