### ISSUE TITLE
How can catch highlight change event in Angular2+ CKEditor5?

### ISSUE THREAD

**Issue by avaiyahardik** [ckeditor/ckeditor5#1436]
## Is this a bug report or feature request? (choose one)
Other

## 💻 Version of CKEditor
CKEditor 5

## 📋 Steps to reproduce
NA

I am evaluating CKEditor for my use case where I want to highlight content in the editor with a different color each and mark that highlighted content for some roles in my organization. When a user logs in he/she should see content were his/her role was marked in those highlights.

So I am looking for a way where on each highlight/updates to highlight I should receive event in which I shall save position/range of content being highlighted.

Thank you!

**Comment by oleq** [comment]
So you'd like to get a very specific diff (only the highlights) of the document each time it is loaded from the database?

**Comment by avaiyahardik** [comment]
Not exactly.. there will be roles associated to each highlighted content
and the idea is that highlighted conte t should be visible to the roles
associated by admin.

Let me know if this helps.

Hardik

**Comment by avaiyahardik** [comment]
Yes. It is similar and not exact to comments feature hence I am asking for
source code so that I can customize as per my scenario.

**Comment by oleq** [comment]
What you'd like to have is possible with CKEditor 5 but we're not able to provide an out-of-the-box solution for you here on GitHub because:
* there's no such feature in CKEditor 5 as of yet,
* this would be some serious piece of code to develop. 

But if you'd like to develop it on your own, you should definitely get familiar with the [markers API](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_markercollection-Marker.html#), the same we use for highlighing text in our [comments feature](https://ckeditor.com/collaboration/comments/). 

You can create different markers for different roles (`role:reviewer:3`) and group them using the name prefixes. Then you can decide which markers to display for which user roles and what CSS styles they will get. Check out the [markers manual test](https://github.com/ckeditor/ckeditor5-engine/blob/master/tests/manual/markers.js) to get a grip on the very basic API.

If you need a dedicated support for your product, please [contact us](https://ckeditor.com/contact/) directly.

**Comment by avaiyahardik** [comment]
I understand we need to create a new plugin for this use case, but it is pretty much similar to comments feature so I was thinking if part of source code can be availed then it will save a lot of time for me.

**Comment by oleq** [comment]
CKEditor 5 comments feature is [available on npm](https://www.npmjs.com/package/@ckeditor/ckeditor5-comments) but licensed under a commercial license and I cannot share the source code here with you, sorry. You can [contact](https://ckeditor.com/contact/) our support team and learn more.
