### ISSUE TITLE
Pasting lists with soft breaks from Google Doc break the list

### ISSUE THREAD

**Issue by julien-mamalian** [ckeditor/ckeditor5#14405]
📝 Provide detailed reproduction steps (if any)

1. Create a list with soft breaks in Google Docs or Word
2. Paste the full list in CKEditor

✔️ Expected result

The soft break content should be inside the <li></li>

- First item
- Second item
- Third item
   Soft break content 

❌ Actual result  (the soft break content is separate from the parent list element)
- First item
- Second item
- Third item

Soft break content

 📃 Other details

- We got the issue when pasting from Word and Google Docs
- We have DocumentList installed

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Hey @julien-mamalian, thanks for the report. I reproduced this issue [with our demo editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) but got a bit different result:

![](https://github.com/ckeditor/ckeditor5/assets/9881379/6478f981-ba65-4cc2-913a-e4b4a8ca5972)

 Interestingly, when you copy the list with the empty paragraph after it, it works correctly. 

![](https://github.com/ckeditor/ckeditor5/assets/9881379/f76e927a-53a2-4d5a-b8ac-23c06ab78059)

We will add it to our bug-fixing queue.

**Comment by mabryl** [comment]
I encountered this issue as well and did some extra testing, so I'm sharing my findings as well.

If you create a new line in a list by pressing `Shift+Enter` in Word, and copy that list, it will be correctly rendered by the editor. The issue seems to appear only when you create the new line by pressing just `Enter`, and then manually remove the list marker that was automatically inserted.

Take a look at the attached files to see which lists work and which don't.
[soft-break-broken.docx](https://github.com/ckeditor/ckeditor5/files/13841613/soft-break-broken.docx)
[soft-break-works.docx](https://github.com/ckeditor/ckeditor5/files/13841614/soft-break-works.docx)

**Comment by Witoso** [comment]
@mabryl I think it's an entirely different case that we have, related more to detecting list continuation #11210. When enter is there, AFAICS the Word just gives us a paragraph with indent. But we fail to recognize the continuation of the list.

As for this issue, I no longer can reproduce for Word or GDocs the issue with soft break on the production docs demos. Closing.
