### ISSUE TITLE
Remove `editor.ui.view` (and `editor.ui.view.editableElement`) from the interface

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#1445]
[Defining editor interface](https://github.com/ckeditor/ckeditor5/issues/302) we agreed that [the editor class](https://github.com/ckeditor/ckeditor5-core/blob/dcf66835b9be1772162e711b1658a1e1b57ddf5a/src/editor/editor.js) defines the "editing" part of the editor interface and [the EditorWithUI interface](https://github.com/ckeditor/ckeditor5-core/blob/dcf66835b9be1772162e711b1658a1e1b57ddf5a/src/editor/editorwithui.jsdoc), so basically [editor UI class](https://github.com/ckeditor/ckeditor5-core/blob/dcf66835b9be1772162e711b1658a1e1b57ddf5a/src/editor/editorui.js), defines the UI part. This is the nice part.

And then there is `editor.ui.view.editableElement`, which is smelly (see https://github.com/ckeditor/ckeditor5/issues/882 or https://github.com/ckeditor/ckeditor5-ui/issues/343).

Now, [we introduced the editor with multiple root editable elements](https://github.com/ckeditor/ckeditor5-editor-decoupled/issues/21), which does not have a single `view.editable`. It has `view.editables` collection and... it works fine. When I was looking for `view.editable.element` and `view.editableElement` usage, excluding build classes, there are only 3 matches across 2 files (1 in balloon toolbar and 2 in block toolbar). I am sure that all of them can be replaced with root element taken for the current selection (not only can, but also should to make these features works fine with the editor with multiple editable roots).

Then, there is `editor.element` which is [defined in the EditorWithUI](https://github.com/ckeditor/ckeditor5-core/blob/dcf66835b9be1772162e711b1658a1e1b57ddf5a/src/editor/editorwithui.jsdoc#L45) but most probably is simply outdated since the only note about is I found was that it was renamed to `sourceElement`. I believe that `sourceElement` should not be part of the base editor interface since some editor may not have it.

Various editors can be built on top of the editor framework. The editing part is usually similar, but the UI part can come in many shapes. It is fine for the specific build to define any properties it likes. However, plugins should assume that only most common parts are available, like `editor.ui.componentFactory`, `editor.ui.focusTracker` and  `editor.uiReady` event. The part which we are not sure about should not be an interface as long as it is possible to write a plugin without it.

This is why I believe that `editor.ui.view` should not be a part of the interface.

At the end of the day, you can always get corresponding DOM element from engine view root elements. You will find there information if there are multiple roots and which one is the main root.

**Comment by oleq** [comment]
>  It has view.editables collection and... it works fine. When I was looking for view.editable.element and view.editableElement usage, excluding build classes, there are only 3 matches across 2 files (1 in balloon toolbar and 2 in block toolbar). I am sure that all of them can be replaced with root element taken for the current selection (not only can, but also should to make these features works fine with the editor with multiple editable roots).

I think I agree (assuming I got your idea correctly 😛) that `editableElement` makes little sense when we started implementing editors with multiple roots. 

I'm not so sure about removing `editor.ui.view` from the `EditorUI` interface, though. For instance, how to access the "body" UI collection when there's no direct access via `editor.ui.view.body`? Lots of features dump their (floating) UI components there.

**Comment by pjasiun** [comment]
This is the commit which inspired me to create this ticket: https://github.com/ckeditor/ckeditor5-editor-decoupled/pull/22/commits/7859875fc83e1e3975b39023769a9e816f300135. Note that editor works fine after these changes.

**Comment by Reinmar** [comment]
1. First of all – there's no `editor.ui.view.editableElement`. There's `editor.ui.view.editable.editableElement`! Or at least that's how it was supposed to be because AFAICS in the code it got messy.

   The point was that from `EditableUIView` consumer's perspective it's not clear how to access the editable host element (it may not be `editableUIView.element`). However, this property will be used nearly exclusively by `*EditorUI` and `*Editor` classes which need to bootstrap the UI and the engine. Which means that it's quite unnecessary because implementers of those classes will know how to access the editable element of the specific `EditableUIView` they use. Therefore, I'd be ok with removing it. However, it can stay there as well because **it does not collide in any way with the multi-root thing**.

   PS. If you'll be touching it remember about the migration guide which uses it.

2. Once again, there should be no `editor.ui.view.editableElement` – if it's defined anywhere it should most likely be removed because there's a big chance that it's a mistake.

3. > Then, there is editor.element which is defined in the EditorWithUI but most probably is simply outdated

   I'll fix it. That's a leftover, indeed.

4. `editor.ui.view.editable`... We could remove it but it won't be that easy (mind the docs). Also, I'm quite sure that it will hit us and the community back in the future because it's an integration layer API. If some editors will have `editor.ui.view.editable` and some `editor.ui.view.editables.someName` that will be messy, especially when porting some code between editor types.

   What do you think about aligning this to the engine's `getRoot()` which supports well single and multi-root scenarios? In this case we'd have `EditorUIView#getEditable( name = 'main' )`. We could introduce this API next to `editor.ui.view.editable`, switch to it completely and deprecate it (log a warning on access).

5. As for `editor.ui.view.body`... We were asked to make its placement configurable, so perhaps it's high time to improve this piece of code and wrap it in some nicer API? It could indeed end up in `editor.ui`.

**Comment by f1ames** [comment]
> I was confused about it in the past. All of `editor.ui.view.editableElement`, `editor.ui.view.editable.editableElement` and `editor.ui.view.editable.element` (in case of the `ClassicEditor`) points the same editable element.

Yes, it was a little confusing for me too. From what I have checked in all builds `editor.ui.view.editable.editableElement` and `editor.ui.view.editable.element` points to the same element. What's more there is also an `element` getter (e.g. `ClassicEditor#element`) which also points to `editor.ui.view.editable.element` (except `ClassicEditor` where it points to `editor.ui.view.element`) which is yet another way to access those elements.

> What do you think about aligning this to the engine's `getRoot()` which supports well single and multi-root scenarios? In this case we'd have `EditorUIView#getEditable( name = 'main' )`. We could introduce this API next to `editor.ui.view.editable`, switch to it completely and deprecate it (log a warning on access).

☝️Makes sense, I'm for `EditorUIView#getEditable( name = 'main' )` or maybe even `Editor#getEditable( name = 'main' )`? The `getBody()` method also seems reasonable for me 👍

**Comment by pjasiun** [comment]
I checked our API what and how we used. Here are some conclusions. Keep in mind that, specific builds may have any properties they want. What I consider here is: what should be part of the editor API.

I checked `EditableUIView` and `InlineEditableUIView` and what it has is:
 - `isReadOnly` - observable property,
 - `isFocused` - observable property,
 - `element` = `editableElement` - property.

Analyzing it, one by one.

## isReadOnly

In the current editor API, focused on the single editable, I can not imagine the scenario where `editor.isReadOnly` != `editable.isReadOnly`. I think this is just a redundant property.

## isFocused

It is possible that the editor is focussed because the toolbar or a dialog is focused, but the editable is not focused. And I can imagine usage of such property, for instance in balloon or block toolbar. However, I checked, what these toolbars are listened to and block toolbar uses:
```
this.listenTo( editor.ui.focusTracker, 'change:isFocused', ... );
```
and balloon toolbar uses:
```
this.editor.editing.view.document.isFocused 
```
and:
```
editor.once( 'uiReady', () => {
	this.focusTracker.add( editor.ui.view.editableElement );
	this.focusTracker.add( this.toolbarView.element );
} );
```
So `editableElement` is manually added to the custom focus tracker.

`editable.isFocused` is never used outside builds and I think it does not need to be exposed.

## editableElement

This is the only property used in our code (actually `view.editableElement ` instead of `view.editable.editableElement` what is wrong, but still). Getting DOM corresponding element form `editor.editing.view` roots are not the easiest path. I believe we could expose it somehow, and I like the idea of exposing it in the way similar to `getRoot`.

As I mentioned before, I also think, we should flatten the API a little bit, so I think we could have something like:
```
editor.ui.getEditableElement( name = 'main' );
editor.ui.addEditableElement( DOMElement, name = 'main' );
editor.ui.addEditableElementNames // not sure if needed
```

## Conclusion

 - `editor.ui.view.editable` is never used in our code outside builds and I think we should remove it,
 - `editableElement` is useful in some cases and could be exposed better (now it is used in a different way than it is defined),
 - we need some API around the "body collection".

**Comment by Reinmar** [comment]
There's quite a lot of confusion in this ticket (regarding `editabeElement`, `isReadOnly/isFocused` properties, `EditorWithUI` props, etc.) so I reported a fresh ticket with the list of changes that we defined on a call: https://github.com/ckeditor/ckeditor5/issues/1449.

I'm closing this ticket. Let's continue discussion in the new ticket.
