### ISSUE TITLE
Docs: Create a feature (plugin) development guide showcasing an advanced feature

### ISSUE THREAD

**Issue by iridescentapps** [ckeditor/ckeditor5#1446]
## Is this a bug report or feature request? (choose one)

 Other

## 💻 Version of CKEditor

CKEditor 5

## 📋 Steps to reproduce

Hi Colleagues, 
More than bug, this is a "how to do"  Request. We have a requirement to render HTML5 tags like input, dropdown, calender pick up and build extra label divs around it. ( as if custom controls) . I went through the CKeditor documentation, And tried to understand the architecture and design. I really appriciate the details provided. 

But I would be of great help if one sample is available for the above scenarios as an example for people who want to extend the CKeditor5. Also mentioning as in which files to change and where to add the custom views would help in building it correctly. 

Thanks in advance for your guidance.
Also if any such github or solution is available, please point me to them.

**Comment by oleq** [comment]
What you need is a set of custom plugins for each kind of content you'd like to use in the editor. Each plugin (feature) will have 2 parts:
* `FeatureEditing` in this part you will define the content in the model's schema and define the converters from the model to the data and view (downcast) and from the data to the model (DB to model – upcast). You should also get familiar with the [editing engine architecture](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html) to understand what you do.

* `FeatureUI` in this part you will define toolbar buttons, dropdowns, balloons (whatever you want) that will allow you to insert and edit the content you declared in the `FeatureEditing` part.

A  very simple example of the plugin can be found [here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html#creating-a-simple-plugin), although it doesn't define the editing part and it will not be enough in your case.

I assume that the controls you want to insert are not editable in the editor content, so they will probably be [widgets](https://ckeditor.com/docs/ckeditor5/latest/api/module_widget_utils.html#static-function-toWidget). What you should do is analyze out the code of 2 core features that use widgets: [image](https://github.com/ckeditor/ckeditor5-image) and [media–embed](https://github.com/ckeditor/ckeditor5-media-embed) to learn how to use widgets in you plugins. You'll copy&paste a lot from those plugins.

**Comment by chimon2000** [comment]
Personally, I find the simple example leaves **a lot** to be desired because it just reuses another plugin that does all of the grunt work. 

- There's no clear direction on how to use Widget without scouring thru code code.  

- No explanation of why plugins are broken up into 2 parts (UI/Editing).  I am assuming separation of concerns.

I know v5 is new so it's understandable.  That said, it'd be nice if an advanced example was broken down fully, similar to what Quill [does](https://quilljs.com/guides/how-to-customize-quill/).  Preferably it'd also be nice to see an example without Widget for comparison sake.

**Comment by oleq** [comment]
> * No explanation of why plugins are broken up into 2 parts (UI/Editing).  I am assuming separation of concerns.
> *

[It's explained here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/core-editor-architecture.html#plugins). 

Other than that, I agree that this must be a journey down the rabbit hole for the outsiders because CKEditor 5 is no longer a standalone app but a framework allowing to do a lot of crazy stuff and with a hight level of complexity exactly for that reason.

**Comment by chimon2000** [comment]
I stand corrected @oleq thanks for the link.

**Comment by Reinmar** [comment]
BTW, some good news in https://twitter.com/reinmarpl/status/1085204333350842369:

![image](https://user-images.githubusercontent.com/156149/51193579-77ed5580-18e9-11e9-8a05-9f358f078fdc.png)

**Comment by Reinmar** [comment]
Two new tutorials were published:

* https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html
* https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

They cover many advanced topics around widgets (the most often implemented type of plugin). There's still a lot to cover, of course, but for that we need more specific tickets.
