### ISSUE TITLE
Cleanup EditorWithUI, EditorUI, EditorUIView, and EditableUIView classes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1449]
In https://github.com/ckeditor/ckeditor5/issues/1445 we started a discussion regarding removing some properties from the editor/editable-related UI classes. It soon turned out that there's a lot of confusion which properties exist for a reason and where they are supposed to be used and whether they really need to be exposed.

We discussed it F2F and focused on two aspects:

* Removing some properties from interfaces (but not their subclasses) – this is meant to define clean API for plugin developers (which should only use properties defined in base interfaces) while still keeping the API open for integration developers.
* Making the API multi-root-ready by replacing singular `#editable` with a plural-ready API.
* Cleaning some other pieces on this occasion (e.g. `EditorWithUI`).

Those changes are all breaking changes and quite significant ones. Therefore, to not blow up many editor integrations, we'll deprecate the API marked for removal and turn properties (and, if possible, events too) into getters which on access will log warnings.

# `EditorWithUI`

* move `#element` to `EditorUI`
* move `#uiReady` event to `EditorUI`

# `*EditorUIView`

* ~remove `#editable {EditableUIView}`  (from the interface, keep in subclasses)~ it's defined in subclasses only already, so it's fine
* from all `EditorUIView` subclasses: remove `#editableElement`  (it's a mistake anyway)

# `EditorUI`

* add `#getEditableElement( root = 'main' )` and complementory methods
* remove `#view` (from the interface, keep in subclasses)

# `EditableUIView`

* make `#externalElement` protected – it's used in this class only

# TODO

* Review the body collection. One thing is that we'd rather move it to `EditorUI`. The other is that we need to make its placement configurable as well as think how to make it work in shadow DOM.

**Comment by f1ames** [comment]
> # `EditorWithUI`
>
> * move `#element` to `EditorUI`
> * move `#uiReady` event to `EditorUI`

I wonder, should we also deprecate the `uiReady` event (which will mean having two events `editor#uiReady` and `editor.ui#ready` for some time) or just remove it from `EditorWithUI`.

**Comment by pjasiun** [comment]
It would be great to keep both but console warning if one add a listener to the `uiReady` event (not sure if possible) :/

**Comment by f1ames** [comment]
> It would be great to keep both but console warning if one add a listener to the uiReady event (not sure if possible) :/

I came up with the code like this for now:

```js
const ObservableMixinExtended = Object.assign( {}, ObservableMixin, {
	_on: ObservableMixin.on,
	_once: ObservableMixin.once,
	on( event, callback, options ) {
		if ( event === 'uiReady' ) {
			log.warn( 'deprecated-editor-event-uiReady' );
		}

		this._on( event, callback, options );
	},

	once( event, callback, options ) {
		if ( event === 'uiReady' ) {
			log.warn( 'deprecated-editor-event-uiReady' );
		}

		this._once( event, callback, options );
	}
} );

mix( Editor, ObservableMixinExtended );
```

It's kind of ugly so I'm not sure if we want to introduce something like this to show deprecation warnings? But without deeper changes, I'm not sure if it will be possible to create anything much more elegant 🤔

**Comment by pjasiun** [comment]
Considering it will be there only for a while (until we remove that event), I am fine with such a solution as long as it works with all ways of listeners attaching (for instance with `listenTo`).

**Comment by f1ames** [comment]
> Considering it will be there only for a while (until we remove that event), I am fine with such a solution as long as it works with all ways of listeners attaching (for instance with listenTo).

That's a valid point. Since you mentioned `listenTo` it can be done the same way as with `on`/`once`. From what I see `listenTo` is internally called by `on` and `once` so it seems the above code can only "extend" `listenTo` and it will also cover `on` and `once` 👍

**Comment by Reinmar** [comment]
Yes, we've rewritten the `EmitterMixin` implementation ~2y ago to have just one entry point exactly for reasons like this one :) Glad it paid off.

**Comment by f1ames** [comment]
Since this refactoring introduces a lot of small changes in many places it might be a little difficult to grasp what changes is responsible for what part of refactoring. I was thinking of adding each class/interface changes in a separate branch/PR but it will probably created a messy pile of related PRs which is not helpful. Instead I have decided to have all the refactor in a single PR but each commit will relate to a single class/interface refactor so it is easy to see which code changes are related to specific part of the refactor. I will put the summary below.

# `EditorWithUI`

* https://github.com/ckeditor/ckeditor5-core/commit/6a2e47dc388f03024ec5f14f868905d866177d41
* https://github.com/ckeditor/ckeditor5-ui/commit/6722c78068ba7b77f9aa542adf1e4eced151c3c0
* https://github.com/ckeditor/ckeditor5-editor-balloon/commit/5a121964477430c104ea710fa6650e0906bb70c3
* https://github.com/ckeditor/ckeditor5-editor-classic/commit/a2ee2867b72a3595cb04168594402b00dfadf907
* https://github.com/ckeditor/ckeditor5-editor-decoupled/commit/e8e28d0c8bfb4d5eea623bb112f0b79b28fa0b83
* https://github.com/ckeditor/ckeditor5-editor-inline/commit/2ffe486ca9f08bf6eec0dfea296e1d486d56c50e

**Comment by f1ames** [comment]
> # `EditorUI`
>
> * remove `#view` (from the interface, keep in subclasses)

@Reinmar I wonder how do you properly can deprecated this one? It is [used in a constructor](https://github.com/ckeditor/ckeditor5-core/blob/bf774c692bf80d59e77f27e7b0fbdc6f4ff8536d/src/editor/editorui.js#L28) and held as [readonly property](https://github.com/ckeditor/ckeditor5-core/blob/bf774c692bf80d59e77f27e7b0fbdc6f4ff8536d/src/editor/editorui.js#L43).

It can be renamed to `this._view` and accessed via getter `get view() { ... }` which logs deprecated warning. And then subclasses will use `this._view` to access it?

Or removing from the interface means it should also not be present in a constructor (so passing it would also log a deprecation warning) or at all in this class.

**Comment by pjasiun** [comment]
I am for option 2. It should not be there at all. It should be defined by subclasses.

**Comment by f1ames** [comment]
I have finished the main refactoring part (PRs soon). There are two things left:

> add #getEditableElement( root = 'main' ) and complementory methods

What should _complementory methods_ cover? I assume it could be `#setEditableElement`, but since editables are only setup on editor creation, does it make sense? It will be just extracting the part of the `#init` code in each editor creator. Unless, it should also work in a way that you may add editable any time, but I assume it's not the point here?

> Review the body collection. One thing is that we'd rather move it to EditorUI. The other is that we need to make its placement configurable as well as think how to make it work in shadow DOM.

Could we move it to a separate ticket? It can be done separately from this issue and as there are a lot of small changes here it will be easier to process as separate tickets.

**Comment by pjasiun** [comment]
> What should complementory methods cover?

I think that base `EditorUI` should have `getEditableElement` defined which uses some a protected map `_editableElements`. Since subclasses can add items directly to this map we do not need a setter here. However, `getEditableElementNames` similar to `[model.document#getRootNames](https://github.com/ckeditor/ckeditor5-engine/blob/master/src/model/document.js#L251)` could be useful.

**Comment by pjasiun** [comment]
> Could we move it to a separate ticket?

Fine for me.

**Comment by oleq** [comment]
@f1ames Can we have a CI branch with mgit configuration for the PR constellation in `ckeditor5` repo? ATM:
* there's no way to tell whether changes make sense as a whole,
* there's no easy way to test it,
* there's no easy way to rebase upon it.

**Comment by f1ames** [comment]
> Can we have a CI branch with mgit configuration for the PR constellation in ckeditor5 repo? 

@oleq sure it makes sense. You mean to create a branch in `ckeditor5` repo pointing to specific commits/branches in modified repos?

**Comment by jodator** [comment]
@f1ames yep, something like this: https://github.com/ckeditor/ckeditor5/commit/5f53344ee37bd3e5ba4f89fcf03704eca1591609.

It runs the test for all changed repos.

**Comment by oleq** [comment]
How come you lived without it so far? 🤯

**Comment by pjasiun** [comment]
After the F2F talk, we agreed that there are too many changes to keep the backward compatibility, so we will release breaking change and remove deprecated methods.
