### ISSUE TITLE
Use CKEditor5 as dependency

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#145]
As the project will be used by others it would be nice to have:
- [x] installing ckeditor5 with currently "dev" dependencies as regular dependencies for `gulp buil`
- [x] making `gulp build` aware of directory structure (as for now it assumes that all `ckeditor5-*` repositories are in `node_modules` folder of `ckeditor5` repository)
- [x] making some `gulp` tasks optional (ie. currently some tasks reads `.gitignore` file that is not present when ckeditor is installed as some project's dependency via `npm install`)

**Comment by Reinmar** [comment]
* We should add `--build-dir` param to the command, but the default should be set as you coded it now,
* Not loading some of the gulp tasks when in dev mode is generally a good idea, however, we could go step further (if you wish to spend time on this) and move `require()` calls to the places where they are used. I've read on gulp's issue tracker that the performance issues that we have with it (bootstrap time) are caused by the fact that we always require dozens of modules, even though a currently run task needs a small subset of them. OTH, this is kind of a separate issue.
* `let isDev = !json._id;` – this should be a const.
* I think we don't use almond anywhere now, so you can remove it from `package.json`.
* Just a note for clarity – the package directories finding logic will need to be much more complex than what we have now, because the deeps tree will at some point become deeper. ckeditor5's dependencies which are installed in a dev mode (as a linked repo) will have their own dependencies inside themselves. This is absolutely not covered now, so we build from a flat tree. 

That would be it I guess. Don't forget about tests (`npm test`) and this will be ready for a merge.

**Comment by jodator** [comment]
Thanks for the insights. I'll get them when beautifying PR.

**Comment by jodator** [comment]
Finally checked. Both builds are equal for `gulp build:js --formats=cjs`.

**Comment by jodator** [comment]
@Reinmar I've just fund that guppy or dev/tasks are too aggressive. They installed hooks in top-level repo (probably before I've made changes in t/145 branch). I'll check that also.

**Comment by Reinmar** [comment]
Can't this ticket be closed now after https://github.com/ckeditor/ckeditor5/issues/262?
