### ISSUE TITLE
Columns width for tables pasted from MS Excel are not conveyed properly

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#14521]
## 📝 Provide detailed reproduction steps (if any)

1.  Download [Excel (3).xlsx](https://github.com/ckeditor/ckeditor5/files/11935759/Excel.3.xlsx) file & open it in Excel.
2.  Select last three columns, like so:

![](https://user-images.githubusercontent.com/5353898/250528101-e935700d-cf84-4838-a8ea-b77a44da43f4.png)

1.  Paste it into [https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)

### ✔️ Expected result

Cell widths are preserved (cell with "color on text and row" is wider than the other two).

Example, see [34.2.0 full featured editor example](https://ckeditor.com/docs/ckeditor5/34.2.0/examples/builds-custom/full-featured-editor.html):

![](https://user-images.githubusercontent.com/5353898/250528528-4cbcfe88-d92d-4960-849f-b72267a75072.png)

_Note it doesn't retain styles, but that's not the scope of this issue. We care only about widths here._

### ❌ Actual result

Depending on version results were bad over time.

With column resize enabled it started to set wrong column widths, see [table column resize demo in **35.0.1**](https://ckeditor.com/docs/ckeditor5/35.0.1/features/table.html#table-column-resize):

![](https://github.com/ckeditor/ckeditor5/assets/5353898/2692d814-c565-4ff7-9224-b15e62ede113)

[**38.1.0**](https://ckeditor.com/docs/ckeditor5/38.1.0/examples/builds-custom/full-featured-editor.html) due to #14516  it looks even worse:

![](https://github.com/ckeditor/ckeditor5/assets/5353898/5076904a-e62a-4fae-9d63-d4405b88ac21)

## 📃 Other details

*   Browser: Any
*   OS: Any
*   First affected CKEditor version: 35.0.1
*   Installed CKEditor plugins: TableColumnResize

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
It's safe to assume that column resize implementation is causing these problems.

### Cols have invalid widths

For some reason each col has same width:

![](https://github.com/ckeditor/ckeditor5/assets/5353898/171d8792-346d-4eb7-9d06-eea4a078bc78)

### Individual cells _do have_ proper widths

The widths here are looking fine, both format in points (`style` attr) and in px (`width` attr).

![](https://github.com/ckeditor/ckeditor5/assets/5353898/67a2b386-2007-4386-a891-d16b06f80d54)

**Comment by Dumluregn** [comment]
## What happens here

Pasting the table from the first comment:

![](https://github.com/ckeditor/ckeditor5/assets/10883184/2649e5b4-2d02-4946-b989-cf107ec04127)

produces the following markup:

```html
<table align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:267pt" width="357">
	<colgroup>
		<col span="2" style="width:53pt" width="71">
		</col>
		<col style="mso-width-alt:6869;mso-width-source:userset;width:161pt" width="215">
		</col>
	</colgroup>
	<tbody>
		<tr height="35" style="height:26.0pt">
			<td class="xl66" height="35" style="height:26.0pt;width:53pt" width="71">size</td>
			<td class="xl65" style="border-left-style:none;width:53pt" width="71">all</td>
			<td class="xl69" rowspan="2" style="width:161pt" width="215">color on text <font class="font11">and row
				</font>
			</td>
		</tr>
		<tr height="39" style="height:29.0pt">
			<td class="xl67" colspan="2" height="39" style="border-right:.5pt solid black;height:29.0pt">
				<font class="font5">a</font>
				<font class="font6">ll </font>
				<font class="font7">m</font>
				<font class="font8">i</font>
				<font class="font9">x</font>
				<font class="font10">ed</font>
			</td>
		</tr>
	</tbody>
</table>
```

The `width` attribute is set correctly on `<td>` elements. So why doesn't it work?

### 1\. `<colgroup>` has priority over inline widths

If the `<colgroup>` element is specified for the table, setting the inline widths will be ignored by the editor (such an integration is another story). The `<colgroup>` element was introduced specifically for table column resize feature in `35.0.1`. So in the earlier versions, the `<colgroup>` was trimmed from this markup and it worked properly due to inline widths set. But `<colgroup>` with `<col>`s is also set in this markup, so why it doesn't work as expected?

### 2\. `pt`s are not converted in `col[style[width]]` 

As can be seen [here](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.ts#L409C3-L428C7), in the `col[style]` upcaster all non-percentage width values (pts, pxs etc) are converted to `auto`. That means they are later automatically calculated based on the remaining %. So if all of our widths are in `pt`, they are all turned into `auto` and set to be equal to each other, which results in what can be seen below:

![](https://user-images.githubusercontent.com/5353898/250558771-2692d814-c565-4ff7-9224-b15e62ede113.png)

Turning on the `pt` unit handling results in an improvement, but still not exactly what we'd expect:

![](https://github.com/ckeditor/ckeditor5/assets/10883184/1097d676-b697-4563-af07-dacb4f1680b2)

What happened? We have three columns, but in the markup there are only two `col` elements. The last column receives the minimal width.

### 3\. `col[span]` is not supported

The first `<col>` element in the markup has `span` attribute: `<col span="2" [...]>`. In tables pasted from Excel, if two or more adjacent columns have the same width, the `<col>` elements are merged together using the `span` attribute. And that's what happened in this example - the first two columns have the same width, so they have one `<col>` element. The editor doesn't handle it, so it's dropped during the upcast and tries to automatically calculate the missing widths (which fails).

## The fix

We need to:

1.  Provide support for `pt` unit in defining `col` element width.
2.  Translate the `col[span]` attribute to multiple `tableColumn`s during the upcast. 

We'll not fix the inline widths integration with table column resize in this issue. It's a separate, quite a large topic I suppose.

**Comment by dufipl** [comment]
An alternative scenario that is still not fixed within https://github.com/ckeditor/ckeditor5/pull/14720
### Steps
1. Open http://localhost:8125/ckeditor5-table/tests/manual/tablecolumnresize.html
2. Paste the table from the Excel file attached
[Table Excel.xlsx](https://github.com/ckeditor/ckeditor5/files/12248418/Table.Excel.xlsx)
Crucial is the part containing the "bg" cell, eg. this selection:
![image](https://github.com/ckeditor/ckeditor5/assets/32898551/695bac83-a04b-44cf-87f7-6244f83839e3)

### Result:
![image](https://github.com/ckeditor/ckeditor5/assets/32898551/6f489085-0ef2-4cf0-96b0-f51e9aa3dd52)

**Comment by charlttsie** [comment]
Here's one more scenario not fixed by https://github.com/ckeditor/ckeditor5/pull/14720:

### Steps
1\. Open a manual test, e.g. http://localhost:8125/ckeditor5-table/tests/manual/tablecolumnresize.html is used in the example
2\. In Excel, create a table that contains 3 rows and a few columns (or use [table.xlsx](https://github.com/ckeditor/ckeditor5/files/12248625/table.xlsx) and skip this one and the next two steps)
3\. Merge all cells in the upper and bottom row 
4\. Merge only a few cells in the middle row 
5\. Paste the table into the editor
### Result
The table looks differently than in Excel - there is an additional cell on the right:

<img width="1332" alt="actual-vs-expected" src="https://github.com/ckeditor/ckeditor5/assets/132071257/7f1d530b-7f6b-4063-9be2-4e9e78f4060d">
