### ISSUE TITLE
Add a callback after adding or selecting a mention

### ISSUE THREAD

**Issue by jobejas** [ckeditor/ckeditor5#14539]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_
In ckeditor5-mention, I should be able to use a callback after adding a mention in the editor.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
To listen on mention command execution, we will have to leverage [the CKEditor5 event system](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/event-system.html#listening-to-events). While the CKEditor5 does not provide a direct event for the mention command, you can use its underlying events, particularly **`execute`**.

First, it's important to know that CKEditor 5 has a command architecture where each action that can be done (like typing, deleting, etc.) is encapsulated as a command. You can listen to the execution of these commands through the editor.

Here is a sample code snippet:

```javascript
editor.commands.get('mention').on('execute', (eventInfo, args) => {
    const [mentionData] = args;
    console.log('Mention command executed with', mentionData);
});
```

In this case, `mention` is the name of the command to listen to.

The 'execute' event will be fired when the command is executed. The callback function you provide will then be invoked with the event data.

Please note that due to the command architecture in CKEditor 5, commands are often the result of a user action but can also be triggered programmatically.
