### ISSUE TITLE
Online Builder - include a JS plugin in TS build

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#14553]
## 📝 Provide a description of requested docs changes

Online Builder will produce a TypeScript source file and an executable JavaScript with typings. Changes are merged and accepted by the @ckeditor/qa-team team but have yet to be released.

We need to figure out how to document a case if somebody wants to include a JavaScript plugin (without typings) in its build.

Also, where to document it? So far, Online Builder does not contain any documentation for itself.

---

### Internal notes

* Check if the community provides types for your package.
	* When `tsc` cannot find the declaration, it suggests installing them from the `@types` organization from npm.
* Create custom declarations.
* Disable `tsc` for the given import (`// @ts-ignore`).
* Consider reporting an issue for providing types.

**Comment by apadol-cksource** [comment]
We're planning to consolidate contents related to the build customization in one guide: cksource/ckeditor5-internal#1868. This may be a good place to document that case.

**Comment by Reinmar** [comment]
We need this documented somewhere now as this is blocking the release of TS to OB. Can we please find a solution that would be somehow applicable to the current content or prioritize the other changes to unblock this?

I think we can wait 2 weeks with OB, so that would be the deadline.

**Comment by psmyrek** [comment]
Below is a raw guide on adding JavaScript plugin to a TypeScript build produced by Online Builder.

---

You may import JavaScript files and packages inside your TypeScript project downloaded from Online Builder. However, compiling the project will result in an error. To remedy this, here are the steps to follow:

1. First, check if there are community types for a package in JavaScript you would like to use. Try installing them via command: `npm i --save-dev @types/<package name>`, where `<package name>` is the name of the JavaScript package. An example for the [Express](https://expressjs.com/) framework would look like this: `npm i --save-dev @types/express`. If there are types, nothing more needs to be done and your project should build without a problem.

2. If there are no types prepared by the community for the package you would like to use in your project, you can try creating custom declarations by introducing an [ambient module](https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules) for the imported package. It's purpose is to describe the shape of imported package (that is the API that is exposed) which is not written in TypeScript. To do that:

   - Create a `.d.ts` file in your project.
   - Define the module with the quoted name which you import into your project:

      ```ts
      declare module '<module name>' {
          // API exposed by the <module name>.
      }
      ```

      Example for the `path` module from Node.js:

      ```ts
      declare module "path" {
          export function normalize( path: string ): string;
          export function join( ...paths: string[] ): string;
          // ...and so on.
      }
      ```

   - Make sure that the created `.d.ts` file is loaded by `tsc`: in the `tsconfig.json` file, in the `"include"` field, there should be a path to the directory where the ambient module declaration is located.

3. Otherwise, if creating a custom declaration is not an option, suppress all errors that originate from the imported package. Add `// @ts-ignore` comment above the line where you import the JavaScript package to your project.

      ```ts
      // @ts-ignore
      import foo from 'package-in-javascript';
      ```

No matter which solution you choose, consider reporting to the package author that the types are missing, so integrating the package with the project in TypeScript is problematic.

**Comment by pomek** [comment]
Closing as it is already on the production docs: https://ckeditor.com/docs/ckeditor5/latest/installation/plugins/installing-plugins.html#custom-declarations.
