### ISSUE TITLE
[Safari] Tripple-click in a nested editable selects the whole widget

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1463]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Master

## 📋 Steps to reproduce

1. Open https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html in Safari
2. Scroll the content to the image.
3. Place the caret in the caption.
3. Tripple click there.

## ✅ Expected result

![image](https://user-images.githubusercontent.com/156149/51211045-a2a0d380-1914-11e9-9279-0e530a84bd64.png)

## ❎ Actual result

![image](https://user-images.githubusercontent.com/156149/51211013-8c931300-1914-11e9-8ee5-239dd6186299.png)

## 📃 Other details that might be useful

Which is even/also very uncool – this leads to excessive scroll jump.

**Comment by pomek** [comment]
The `MouseEvent` defines the `detail` property which describes how many clicks a user did.

https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-MouseEvent

We could observe the whole editable area and prevent the event if `details` value is higher than 2.

**Comment by pomek** [comment]
Unfortunately, preventing the event or/and stopping propagation didn't work. Seems like the selection is being modified before firing the `click` event.

**Comment by Reinmar** [comment]
> Unfortunately, preventing the event or/and stopping propagation didn't work. Seems like the selection is being modified before firing the `click` event.

Can't we simply handle this event and set selection ourselves? We know the event target, right? So we know where the user was clicking so we can select the right content. Am I right?

**Comment by pomek** [comment]
Because I don't have an idea on how to select a line which was triple clicked by a user, I selected the whole `figcaption` element. Unfortunately, it blinks. Safari modifies selection earlier than me. It looks very weird. See the attached GIF.

![Blink selection GIF](https://user-images.githubusercontent.com/2270764/52629232-895e5900-2eb9-11e9-9c72-ee01b0ad4d66.gif)

**Comment by Reinmar** [comment]
> I selected the whole `figcaption` elemen

The selection should be put inside the `<figcaption>` element. In fact, inside the `<caption>` element because this should be done on the model.

**Comment by pomek** [comment]
I changed it but it still blinds. The worst thing is that is blinds randomly.

**Comment by Reinmar** [comment]
No code, no comments.

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5-image/commit/6819f4b3126da920c272fb6b24ebbfd04bdbc3b0

**Comment by oleq** [comment]
I did a quick research and this is what I found:
* listening to `click`  makes little sense as the selection is made upon `mousedown`
* the issue also happens when `domEvent.detail > 3`

I created a solution draft which is as simple as 

```js
view.addObserver( MouseObserver );

view.document.on( 'mousedown', ( evt, data ) => {
	console.log( 'mousedown', data.domEvent.detail );

	if ( data.domEvent.detail >= 3 && data.target.is( 'figcaption' ) ) {
		data.domEvent.preventDefault();

		view.change( writer => {
			writer.setSelection( data.target, 'in' );
		} );
	}
} );
```

and it seems to be working. All we need now is:
* a check that makes sure this covers affected browsers
* more general element discovery, probably it concerns all nested editables, not just `<figcaptions>`,
* tests

![2019-02-19 11-37-43 2019-02-19 11_38_45](https://user-images.githubusercontent.com/1099479/53009055-eff3f180-343a-11e9-8ab4-91fcb3552fa0.gif)

**Comment by oleq** [comment]
This issue must be fixed at the widget–level (not image–level) so I'm afraid https://github.com/ckeditor/ckeditor5-image/pull/280 will not do.
