### ISSUE TITLE
Image jumps when resizing with percent as resize unit

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#14698]
## 📝 Provide detailed reproduction steps (if any)

1. Open any demo, where there is Image resize plugin with percent resize unit included (i.e. https://ckeditor.com/docs/ckeditor5/latest/features/pagination/pagination.html#demo)
2. Resize the image a bit

### ✔️ Expected result

The resize will be smooth

https://github.com/ckeditor/ckeditor5/assets/66953380/25b66883-e8e9-467b-9d7e-901b12359629

### ❌ Actual result

Upon resize, the size jumps immediately to a lower size.
It does slightly jump when units are set to pixels as well, but percents produce a much worse result.

https://github.com/ckeditor/ckeditor5/assets/66953380/3e409fab-a8de-4767-9b0c-ac3dac2284c7

## 📃 Other details

* Browser: All
* OS: MacOS
* First affected CKEditor version: earliest I checked was 34.0.0, possible it was like this even earlier

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@Acrophost I couldn't reproduce it [in the test that has %](https://ckeditor.com/docs/ckeditor5/latest/features/images/images-resizing.html) (first example). Could you dive a bit deeper where it occurs? Maybe it's related to the decoupled editor?

**Comment by Witoso** [comment]
I cannot reproduce (MacOS 13.3 + magic trackpad, external or internal).

https://github.com/ckeditor/ckeditor5/assets/9881379/46d36ea0-cffd-4922-aff1-422911c873e1

@Acrophost, please check.

**Comment by dtdesign** [comment]
@Witoso Actually, you just reproduced it and uploaded the evidence. Slow down your recording to 50% speed and watch what happens when you start resizing. Your movements are quite fast which is why you might not be aware of the initial jump.

Once you click to activate the resize mode, move your cursor every so slightly and you will see what I mean. This is what it looks like when you do very small **initial** movements:

https://github.com/ckeditor/ckeditor5/assets/208610/3cbf455c-4ce3-4a48-8df4-301a6727b598

**Comment by Witoso** [comment]
But there's a difference in initial jump of ~3-5% (which is negligible and low priority), and ~25% presented in the OP.
