### ISSUE TITLE
Wrong CDN links in nightly docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#14728]
E.g. here: [https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/installation/getting-started/quick-start.html](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/installation/getting-started/quick-start.html)

We show such a snippet:

```
<script src="https://cdn.ckeditor.com/ckeditor5/0.0.0-nightly-20230803.0/classic/ckeditor.js"></script>
```

Which doesn't work actually.

**Comment by pomek** [comment]
### Plan

* When preparing a nightly release, do not commit changes (to revert https://github.com/ckeditor/ckeditor5/commit/ccff374f9b1311eab3f7691e432beec25ae7ce48 and a similar commit in CC)
* Move the "resetting phase" from publishing nightly script to installing nightly packages (to revert https://github.com/cksource/ckeditor5-integration-ci/commit/8f905ea6c7f81f4200e2d09786b7242bdd55f928)

### Notes

* Due to building Letters, we needed to keep the obfuscated code in the `packages/` directory after preparing the nightly release.
* To invoke the `git reset --hard` command (to restore TypeScript sources), we had to commit changes to have a breakpoint.
* As the Letters package is no longer maintained, we do not have to do this.
