### ISSUE TITLE
ckeditor 5 starts ckeditor 4

### ISSUE THREAD

**Issue by alpha-and-omega** [ckeditor/ckeditor5#1485]
## 💻 Version of CKEditor
5.* and 4.*

## 📋 Steps to reproduce

1. Create this simple test page with both ck5 and ck4 on the same page:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<script src="//cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>
	<script src="//cdn.ckeditor.com/ckeditor5/11.2.0/classic/ckeditor.js"></script>
</head>
<body>
<textarea id="editor"><h2>Sample</h2></textarea>
<script>
	ClassicEditor.create( document.querySelector( '#editor' ) )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );

	CKEDITOR.on( 'loaded', function( evt ) {
		console.log("loaded");
	} );
	CKEDITOR.on( 'instanceReady', function( evt ) {
		console.log("ck4 loaded too", CKEDITOR.instances);
	} );
</script>
```

2. script starts ck5 only, but ck4 instance starts too (mistery) and ck4 panel appears on edit

## ✅ Expected result
ck4 should not be started by ck5, we use ck4/ck5 alternatively on the same page

**Comment by Reinmar** [comment]
![image](https://user-images.githubusercontent.com/156149/51804451-55e8c100-2261-11e9-8551-114d75296cc6.png)

This is fun indeed 🤣 

But CKE4 does not get started by CKE5. CKE4 gets started automatically because it can automatically detect textareas called `editor`.

Add this to your `<script>` tag to prevent this:

```js
	CKEDITOR.disableAutoInline = true;
```

**Comment by alpha-and-omega** [comment]
Haha, thanks!
