### ISSUE TITLE
Upgrade husky in all pkgs and make sure hooks are installed

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1492]
I've just checked that hooks are not installed now in `packages/*`.

**Comment by Reinmar** [comment]
@jodator @ma2ciek what did we have to do regarding hoisting?

**Comment by ma2ciek** [comment]
We need to prevent `husky` from being installed only once because it's needed to be installed inside every package `node_modules` in order to work (see https://github.com/typicode/husky/issues/417).

`yarn` similarly to the `lerna` allows it by adding the package and its dependencies (as `package/**`) to the `nohoist` field:

```
"workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/husky",
      "**/husky/**"
    ]
  }
```
