### ISSUE TITLE
TS2322: Type  (feedItem: MentionMember) => HTMLDivElement  is not assignable to type  ItemRenderer 

### ISSUE THREAD

**Issue by paradox37** [ckeditor/ckeditor5#14927]
## 📝 Provide detailed reproduction steps (if any)

I am using custom build of CKEditor 5 with Angular. Here is the function I use for custom renderer:

```
interface MentionMember {
  id: string;
  name: string;
  image: string;
  avatarName: string;
  sasImageUrl: URL;
  organizationName: string;
}

// adding MentionMember does not work here, I have to use MentionFeedObjectItem, which does not allow my additional properties.
// I have to cast to unknown and then to MentionMember inside the function as a workaround.
private customCkeMentionRenderer(feedItem: MentionMember) {
   ...
}

// this is the feed function
ckeMentionMeed = (queryText: string): Promise<MentionMember[]> => {
   ...
}
```

`MentionMember `is a custom interface which I use as a return of mention feed function. But when I try to use the same interface as input for `itemRenderer`, it throws the error from title.

### ✔️ Expected result

_What is the expected result of the above steps?_
It should not show the error `TS2322: Type  (feedItem: MentionMember) => HTMLDivElement  is not assignable to type  ItemRenderer 
Types of parameters  feedItem  and  item  are incompatible.
Type  MentionFeedObjectItem  is missing the following properties from type  MentionMember : name, image, avatarName, sasImageUrl, organizationName`

### ❌ Actual result
It shows `TS2322: Type  (feedItem: MentionMember) => HTMLDivElement  is not assignable to type  ItemRenderer 
Types of parameters  feedItem  and  item  are incompatible.
Type  MentionFeedObjectItem  is missing the following properties from type  MentionMember : name, image, avatarName, sasImageUrl, organizationName`

### ❓ Possible solution
I guess input for itemRenderer should be the same as the output of the feed.

## 📃 Other details

* Browser: Chrome
* OS: Windows 10
* First affected CKEditor version: Not sure, probably since typescript is introduced to custom build.
* Installed CKEditor plugins: Autoformat, AutoImage, Autosave, BlockQuote, Bold, Essentials, FontSize, Heading, Image, ImageUpload, Indent, Italic, Link, List, Mention, Paragraph, PasteFromOffice, SimpleUploadAdapter, TextTransformation, 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by arkflpc** [comment]
@paradox37, I haven't found a way to change the typing so it supports your use case.
In the current types, we have (much simplified, illustration only):

```ts
interface MentionFeed {
  feed: FeedCallback;
  itemRenderer: ItemRenderer;
}
type FeedCallback = ( query: string ) => Promise<Array<MentionFeedObjectItem>>;
type ItemRenderer = ( item: MentionFeedObjectItem ) => HTMLElement;
type MentionFeedObjectItem = { id: string };
```

I can see your `MentionMember` is compatible with `MentionFeedObjectItem`, so your `ckeMentionMeed` is compatible with `FeedCallback`. That's because the functions are covariant on their return types. However, `customCkeMentionRenderer` is not compatible with `ItemRenderer`, because it contains type `MentionMember` as a parameter type which is in contravariant position.

I know both functions are coupled in a way that one uses the output of another, and your use case is valid. But I don't know to express this on type-level. I tried to make `MentionFeed` generic, i.e.:

```ts
interface MentionFeed<TFeed extends MentionFeedObjectItem>  {
  feed: FeedCallback<TFeed>;
  itemRenderer: ItemRenderer<TFeed>;
}
```

But it failed to work with the syntax we want to support:

```ts
ClassicEditor.create( element, {
  mention: {
    feeds: [ /* your feeds are here */ ];
  }
} );
```

How to type `mention.feeds` config so that it allows `MentionFeed`s where each one may be parametrized differently (not all of them has to be based on `MentionMember`)? Making `EditorConfig` generic over feed object is not an option for us.

You can solve this on your side using cast to `ItemRenderer`:

```ts
ClassicEditor.create( element, {
  mention: {
    feeds: [ {
      feed: ckeMentionMeed,
      itemRenderer: customCkeMentionRenderer as ItemRenderer,
     /* other fields */
    } ];
  }
} );
```

If you find a better way, please share it with us and reopen this ticket.
