### ISSUE TITLE
CKEditor 5 + Grammarly Performance

### ISSUE THREAD

**Issue by slotterbackW** [ckeditor/ckeditor5#15073]
## 📝 Provide detailed reproduction steps (if any)

We've received reports that CKEditor's performance, especially while using the Grammarly extension, is significantly degraded for our users with less powerful machines.

I can reproduce the issue by using Chrome's performance profiling tools to throttle my laptop's CPU and typing in the CKEditor + Grammarly demo available [here](https://codesandbox.io/s/github/grammarly/grammarly-for-developers/tree/main/examples/editor-sdk-react-ckeditor?file=/src/Editors.js). (This demo is linked from [this page](https://developer.grammarly.com/docs/editor-sdk-react))

In my testing, Grammarly is taking around 40-60% of the total keypress processing time:

<img width="618" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/14916556/cee2feea-ea28-41cb-a6f7-6c7811ca76e2">

**Reproduction steps:**

1. Run a performance profile on the CKEditor + Grammarly [demo page](https://codesandbox.io/s/github/grammarly/grammarly-for-developers/tree/main/examples/editor-sdk-react-ckeditor?file=/src/Editors.js). The results are more noticeable on a throttled CPU. I used 6x. 

### ✔️ Expected result

I'm hoping to find some way to improve the performance when using these two tools as it's a popular combination for our users.

### ❌ Actual result

Grammarly takes up 40-60% of the total keypress processing time, which causes typing in the editor to feel sluggish.

## 📃 Other details

* Browser: Chrome
* OS: MacOS

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by slotterbackW** [comment]
I wanted to add that I understand that this is not just a CKEditor issue. I'm not sure if you're in communication with Grammarly as well, but I can also report this issue to them?

I'm just looking to find out if there are any recommendations you have, or work planned, to improve this performance? Thanks!

**Comment by Reinmar** [comment]
Thanks for letting us know. 

I have no data to prove this but from my experience (I have Grammarly installed) it significantly slowed down recently. And the UI/UX got more intrusive with the messy large balloon :( 

I recorded the profile myself to play a bit with it:

![](https://github.com/ckeditor/ckeditor5/assets/156149/8a0fe1c8-1f51-4a60-ac2d-56d8eb81bb88)

The 4 green and blue blocks (the selected one + 3 to the right) in my case are Grammarly. So, from the total 48ms that the keydown took, 31ms is taken by Grammarly. A bit more than 60%.

I noticed, though, that you used a very old CKEditor version there. For some reason, codesandbox didn't let me test above 36.0.1 (39.0.2 is the latest version now). So I tested it locally with a vanilla JS CKE5 installation:

![](https://github.com/ckeditor/ckeditor5/assets/156149/f9ea0528-787b-4231-8d60-e1074c94744c)

The selected block + the t.flush() is again Grammarly.

This is really bad, and I'm quite sure it wasn't that heavy in the past. We've seen hiccups caused by Grammarly on larger pages (e.g. when using CKE5 for GitHub reviews), but if it was that bad, I guess it would be brought to our attention.

So, I think it's definitely worth reporting this issue to Grammarly. It seems to be a regression so perhaps it's relatively simple to revert.

@arkflpc @Witoso, did Grammarly respond to the last issue that we reported to them?

**Comment by Witoso** [comment]
We already have an issue related to the upstream problem on their side (#14278), and created a support request. The answer could be found there (investigation needed).

**Comment by Reinmar** [comment]
Let's do the same about the performance report, then 🙏

**Comment by Witoso** [comment]
Support request #6336623.

**Comment by Witoso** [comment]
I received a response today, asking us about the degradation time.

> Could you please help us understand when you first noticed the degradation? 

@slotterbackW is there any particular moment that you could share when this started to be noticeable on your side?

**Comment by slotterbackW** [comment]
Unfortunately I don't have an exact time when the performance became noticeably worse. The reason it came up is that we have a customer who was using an old editor experience that does not use CKEditor + Grammarly, and they migrated to a new experience that does, and that's when they experienced the performance issues.

So, I don't have a time when Grammarly's performance got worse, we're just aware that the current performance with CKEditor is bad.

**Comment by Witoso** [comment]
> I am mindful that this is taking a bit longer than anticipated, and I sincerely apologize for the delay.  
> Our engineering team is still trying to test the issue, and I will get back to you as soon as I hear from them.

It looks like the Grammarly team is investigating :crossed\_fingers:

**Comment by Witoso** [comment]
Got another answer, doesn't sound promising:

> Unfortunately, our engineers don't currently have a quick fix for the reported issue, but we have logged the issue and notified our product team, who is now working on scheduling a more in-depth investigation. It seems that the issue is not isolated to our compatibility with CKEditor 5.  
>    
> I can't provide you with an estimated timeframe right now because the developers need some time to analyze the cause of the issue.  
>    
> In the meantime, we recommend that the users in question use Grammarly for Windows and Mac, which integrates with multiple applications and websites. This app appears as a floating widget when you start typing and a Grammarly icon in the menu bar located at the top of your screen.

**Comment by slotterbackW** [comment]
We've been in contact with the Grammarly team, and they've recently rolled out a number of performance fixes which have mitigated this issue, so I think it's safe to close :)

Thanks for all your help!

**Comment by Witoso** [comment]
Thanks @slotterbackW!
