### ISSUE TITLE
When in an list-item <li> you can choose a style that's only meant for <p>

### ISSUE THREAD

**Issue by tohett** [ckeditor/ckeditor5#15206]
1. make a list 
2. click in a list-item that is NOT formated as a <p>
3. use the style-dropdown and you can chose a style for a paragraph

### ✔️ Expected result

The styles for paragraphs should not be applicable in a list-item

### ❌ Actual result

After chosing the p-style inside the list-Item there's now a nested <p> with the chosen class

## 📃 Other details

CKE5 in TYPO3 12

**Comment by tohett** [comment]
FE I have these style-definitions:

- { name: 'Abstand unten: halb (P)', element: 'p', classes: ['halber_unterer_Abstand'] }
- { name: 'Abstand unten: halb (UL)', element: 'ul', classes: ['halber_unterer_Abstand'] }

So I would expect that I could chose the second one for UL when I click inside an <li> because the <li> is a child for <ul> but in fact I can chose BOTH, the style <ul> AND for <p>, even tough there is no <p> present.

**Comment by Witoso** [comment]
Hi, if TYPO3 uses [document lists](https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html), then this is a feature rather than a bug. Document lists allow keeping paragraphs and other elements inside list items, and therefore it's possible to style a paragraph inside a list item. In `v40` we introduced [a configuration option](https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html#simple-lists) which disables multiple blocks in a list, and styling a `p` is blocked then.

**Comment by tohett** [comment]
I see! Now I just have to find out how and where to configure this thing in the typo3 YAML.
Thanks

**Comment by Witoso** [comment]
The reason is that the editor operates on an internal data model, not HTML. This is how document lists are reflected :)

![](https://github.com/ckeditor/ckeditor5/assets/9881379/6637ef4c-0990-469d-a609-77221db4da15)

**Comment by tohett** [comment]
Ah!! Thanks!
