### ISSUE TITLE
Caption field is not displayed inside an image when in a table

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1524]
There should be a caption field visible:

![image](https://user-images.githubusercontent.com/156149/52643008-67c29900-2edc-11e9-9134-9d2fb333e82e.png)

Most likely related to https://github.com/ckeditor/ckeditor5/issues/1523 and issues with fake selection.

**Comment by jodator** [comment]
So the problem is with the image caption postfixer has limited information about inserted nodes from the differ. Differ returns change for whole tree, ie `type="insert" name="table"` so image caption feature must look not only for inserted nodes but also check if some of the children aren't images.

The same thing happens with `<blockquote><image /></blockqoute>` when parsing or pasting content.
