### ISSUE TITLE
Resolve exports conflicts in `ckeditor5` package.

### ISSUE THREAD

**Issue by pszczesniak** [ckeditor/ckeditor5#15511]
In the new installation methods, the `ckeditor5` package will be used to re-export content of all open source packages. We have found that there are name conflicts that need to be resolved first.

| Export name | Package 1 | Package 2 | Suggestions |
| --- | --- | --- | --- |
| `icons` | `core` | `ui` | Move `colorPaletteIcon`, `previousArrow`, and `nextArrow` icons from `ui` to `core`. These icons should be added to the `icons` object exported from the `core` package. |
| `Model` | `engine` | `ui` | In `ui`, rename to `ViewModel` (only re-export). |
| `View` | `engine` | `ui` | In `engine`, rename to `EditingView` (only re-export). |
| `Position` | `engine` (class) | `utils` (interface) | Rename interface to `DomPoint`. |
| `findOptimalInsertionRange` | `engine` | `widget` | Move implementation in `engine` to the `Schema` class as `findOptimalInsertionRange` method (add `@internal`). |
| `UploadAdapter` | `upload` (interface) | `adapter-ckfinder` (class) | Rename re-export to `CKFinderUploadAdapter`. |

**Comment by pszczesniak** [comment]
Unfortunately, suggested way of resolving name conflict with `findOptimalInsertionRange` has failed. 

After merging `findOptimalInsertionRange` from `widget` and `engine` package and moved it to the `Schema` as a method, one more function ( `getTypeAroundFakeCaretPosition` ) was needed to be imported from `widgettypearound/utils`. 
After createing an export in `index.ts` in `widget` package:
```
export { getTypeAroundFakeCaretPosition } from './widgettypearound/utils';
```
and trying to import it in `Schema` we get an errors (unable to run anything with `widget`) - it was caused by that `widget` has imports from `engine` and `engine` has imports from `widget`.

We decided to change the way how we will handle it: move `findOptimalInsertionRange` from `engine` to the `Schema` as a method, but leave `findOptimalInsertionRange` in `widget` but not import it from `engine` but use `model.schema.findOptimalInsertionRange()`. 👉 https://github.com/ckeditor/ckeditor5/commit/7875f7f5321e3f0d8c015869d296ca854989a98e

**Comment by filipsobol** [comment]
We needed to move more icons that we initially expected, because they are used by more than one package.

Icons moved to the `@ckeditor/ckeditor5-core` package:
* `undo.svg` and `redo.svg` from the `undo` package.
* `bulletedlist.svg`, `numberedlist.svg`, and `todolist.svg` from the `list` package.
* `codeblock.svg` from the `code-block` package.
* `browse-files.svg` from the `ckbox` and `ckfinder` packages.
* `heading1.svg`, `heading2.svg`, `heading3.svg`, `heading4.svg`, `heading5.svg`, and `heading6.svg` from the `heading` package.
* `horizontalline.svg` from the `horizontal-line` package.
* `html.svg` from the `html-embed` package.
* `indent.svg` and `outdent.svg` from the `indent` package.
* `table.svg` from the `table` package.

Icons moved to the `ckeditor5-collaboration` package:
* `robot-pencil.svg` from the `ai` package.
* `table-of-contents.svg` from the `document-outline` package.
* `paint-roller.svg` from the `format-painter` package.
* `template.svg` from the `template` package.
