### ISSUE TITLE
Certain list structures cause the editor to crash when using Document lists alongside GHS

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5#15527]
## 📝 Provide detailed reproduction steps (if any)

1. Create a build that utilizes Document lists alongside GHS with support enabled for `<div>` elements
2. Provide the following HTML to the editor:
```
<div><ol><li>asd</li><li><div><ol><li>asd</li></ol></div></li></ol></div>
```
3. Try removing the sublist `a` item in the second list item

### ✔️ Expected result

The editor shouldn't crash.

### ❌ Actual result

The entire tab freezes, no error thrown in the console:

https://github.com/ckeditor/ckeditor5/assets/72079603/75e57be9-f1dc-45a7-bfdb-f321f2a59164

### ❓ Possible solution

It looks like something weird is happening with the second `<div>` because removing it from the markup resolves the issue.

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS
* First affected CKEditor version: N/A
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
@mabryl could you check if how turning on the `AdjacentListsSupport`  plugin influences this scenario?

**Comment by mabryl** [comment]
@Witoso just checked it and there seems to be no difference in behavior, unfortunately:

https://github.com/ckeditor/ckeditor5/assets/72079603/ba165ad3-96f5-4004-acc6-1ec07faca1b6

**Comment by Witoso** [comment]
Thanks for checking, we will take a look at this! One important thing to mention is that it's highly unadvisable to use div's like that, as it's not possible to escape them when writing (rel: #6462).

**Comment by FilipTokarski** [comment]
Related https://github.com/ckeditor/ckeditor5/issues/15565 ?

**Comment by niegowski** [comment]
This was a post-fixer loop. Two post-fixers were fixing each other changes. One was removing GHS-related list attributes (and it was doing it too greedy) and the other was adding them since they were expected.

This problem was caused by: 

https://github.com/ckeditor/ckeditor5/blob/b9fb73aa42beef5ad6275cd169682336b6b26a79/packages/ckeditor5-html-support/src/datafilter.ts#L464

It was trying to iterate the attribute change "shallowly" but for attribute change on an element the range starts before an element and ends just inside it and the walker with the `shallow` option does not stop properly and follows the document until its end.
