### ISSUE TITLE
Paste from word does not retain some formatting options

### ISSUE THREAD

**Issue by chetan-rflx** [ckeditor/ckeditor5#1564]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  

## 💻 Version of CKEditor

ckeditor5

## 📋 Steps to reproduce

1. Copy text from word document having formatting like text with background color, text with different types of font.
2. Paste the content in ckeditor5
3. See that the background color of is not retained. Some of the fonts are not retained.

## ✅ Expected result
The formatting done in word documents should retain as is

## 📃 Other details that might be useful
Our users copied some of the content from well formatted in word document. But when pasted in ckeditor5 the these formatting are not retained. They will have to struggle again doing that formattin in ckeditor5

**Comment by Mgsy** [comment]
Our [Paste From Office](https://github.com/ckeditor/ckeditor5-paste-from-office) plugin is still under development and currently handles only basic formatting, such as bold, italic, lists or images. It means that text formatted i.e. with background colour won't be pasted to our editor (even with the highlight plugin enabled). 

Your issue is more like a feature request, than a bug report, so I'll close it and if you feel that this one is important for you, please open a new feature request in the [Paste From Office repository](https://github.com/ckeditor/ckeditor5-paste-from-office/issues/new).

**Comment by ankitcodefarm** [comment]
Hi, @Mgsy is this "Paste From Office" plugin is still under development? 
Because I am facing the styling issue regarding the background color of font and some other font (text) related issue when I paste form word.

**Comment by Adebisi01** [comment]
I gave a detail account of what worked for me in this stackoverflow thread.
 I hope this helps someone
https://stackoverflow.com/questions/45187943/ckeditor-does-not-keep-word-font-and-size-after-paste

**Comment by Witoso** [comment]
Hey @Adebisi01, thanks for contributing but the solution you provided is for CKEditor 4, and this repo is dedicated to CKEditor 5.
