### ISSUE TITLE
Missing features from ckeditor4

### ISSUE THREAD

**Issue by chetan-rflx** [ckeditor/ckeditor5#1565]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request

## 💻 Version of CKEditor

ckeditor5

## 📋 Steps to reproduce

1. Maximize ckeditor window option is missing. It was present in ckeditor 4. There used to be a button which when clicked shows the ckeditor window covering maximum area of sceen. This was very helpful feature for our users since they were able to view the maximum content in the ckeditor window and get to see what exactly formatting of text is being done. (We tried to find this option in ckeditor5 if we are missing it somehow please update us)
2. Indentation menu option is missing
3. Menu option for adding horizontal line is missing.

## ✅ Expected result
Can these options be provided (or any other alternative) since these were present in older version i.e. ckeditor4 and our users are used to these options?

**Comment by Reinmar** [comment]
Those options are not available yet and they will be implemented in CKEditor 5 with time. 

Please check the issue tracker for existing issues because all of the features mentioned by you were already reported:

* full screen: https://github.com/ckeditor/ckeditor5/issues/1235
* horizontal rule: https://github.com/ckeditor/ckeditor5/issues/1365
* tab key (or more generally – the indent feature): https://github.com/ckeditor/ckeditor5/issues/1197
