### ISSUE TITLE
ckeditor Character count does not match with Google docs, Grammarly and Microsoft word

### ISSUE THREAD

**Issue by Prince890840** [ckeditor/ckeditor5#15669]
@Reinmar 

My Question is when i integrate ckeditor into our Project then there is a task about to show character count whatever'd content paste into ckeditor then i saw a difference between the Microsoft word and Ckeditor which has too much difference.

Here I posted the difference of both, can anyone give solution how can i overcome this problem ?
1.  ![image](https://github.com/ckeditor/ckeditor5/assets/77726300/13c69838-900d-44d8-9f3f-5533a16ce2c5)
2.  ![image](https://github.com/ckeditor/ckeditor5/assets/77726300/82355299-7f98-4110-9b01-e55b720ad4de)
3.  ![image](https://github.com/ckeditor/ckeditor5/assets/77726300/a55076ce-07e5-4ee9-942e-d349a43d0361)

In above I pasted same content in ckeditor, Google Docs and Microsoft word , every editor has different result.

below is my code for the reference.

![image](https://github.com/ckeditor/ckeditor5/assets/77726300/0472525d-5cbc-40f7-98b5-deeb9e427b01)
![image](https://github.com/ckeditor/ckeditor5/assets/77726300/a61593fa-e4c4-4a6d-9aaf-556bb03c27eb)

**Comment by Witoso** [comment]
Hi! As you already noticed, each editor shows a different count because, as I imagine, each may be using a different heuristic. Currently, we don't plan any enhancements on our side in the word count. If you'd like, you could try to write your extension, [the plugin's code is open source](https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-word-count).
