### ISSUE TITLE
Stale bot - find and close `pending:feedback` issues

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#15697]
## 📝 Provide a description of the improvement

The goal is to mark as `status:stale` issues lacking the requested feedback. An example use case:

* a user creates an issue,
* we add a label `pending:feedback` as something is unclear,
* no response.

Right now, the stale bot closes such an issue after 13 months. 12 months after the last comment, then one month after the lack of action.

After implementing the requested improvements, such issue should be closed within a month and a half. 2 weeks for determining if the pending-issue is stale, then a one month for closing the staled issue.

So, the stale bot should accept a few new options:

* an array of labels describing a pending-feedback issue,
* a number of days without activity in the pending-feedback issue.

Questions:

* Should the bot remove the `pending:feedback` if the last comment was created by a community?
	* Let's do it. ([answer](https://github.com/ckeditor/ckeditor5/issues/15697#issuecomment-1893293973))
* Should the bot verify stale issues?
	* No, as they are treated anyway. This improvement modifies applying the stale label for issues requiring additional feedback.
* What should we do with a support issue marked as requiring feedback?
	* Issues containing the `status:*` label **must not** be processed.

**Comment by Reinmar** [comment]
> *   Should the bot remove the `pending:feedback` if the last comment was created by a community?

What happens if we don't remove it?

I'm asking because having this label even on closed issues might be useful in the future to filter them out (when doing some research).

> *   What should we do with a support issue marked as requiring feedback?

The `support:*` label has precedence over all other states. Those need to be excluded from any automatic grooming.

---

Anyways, nice catch. It's a bit tricky to decide automatically whether we still need some information or not.

cc @Witoso What would be sustainable when triaging issues? I'm thinking about an issue like [this one](https://github.com/ckeditor/ckeditor5/issues/15509) where our response is the last one, the user provided all the information, but the issue still has a "pending:feedback" label.

Should we remove it automatically upon user reply? (Note: I was also thinking about automatic Slack pings to maintainers when a user responds to a "pending:feedback" ticket. From my experience, it's easy to miss those in the notifications after a while. WDYT?

**Comment by Witoso** [comment]
> cc [@Witoso](https://github.com/Witoso) What would be sustainable when triaging issues? I'm thinking about an issue like [this one](https://github.com/ckeditor/ckeditor5/issues/15509) where our response is the last one, the user provided all the information, but the issue still has a "pending:feedback" label.

Either it will be automatic, and will make mistakes, or it will be manual, and will make mistakes. If you ask me, I would prefer an automatic removal, as I think it will be much more diligent, as us humans can miss the notifications easily or forget about label removal.

**Comment by pomek** [comment]
> What happens if we don't remove it?

The bot will be processing the issue within the next day, and another, and on and on. Instead of increasing costs (GH API rate limit), I would search for reductions.

**Comment by pomek** [comment]
When implementing the new feature, ensure the entire program is backward compatible. If the new options are available, use them.
