### ISSUE TITLE
How can I listen color change/select color event on FontColor, BackgroundColor?

### ISSUE THREAD

**Issue by minhnhat2807** [ckeditor/ckeditor5#15732]
## 📝 Ask a question

Hi, I try to listen event on select/change the FontColor, BackgroundColor

I tried some ways but seem it's wrong

> editor.plugins.get("FontColor").on('execute', (evt, data) => { }, {priority: 'low'});

please let me know how to do that 

Thanks.

**Comment by Witoso** [comment]
Hi!

To listen for events related to font color or font background color changes in CKEditor 5, you should attach an event listener to the `command` that is executed when these properties are changed, rather than directly to the plugin. Typically, the events you're interested in are fired when the `execute` event of a command occurs.

For CKEditor 5, each formatting feature like `FontColor` or `FontBackgroundColor` has an associated command. You can listen for changes to these commands using the editor's `command` collection. Here's how you can do it:

```
editor.commands.get('fontColor').on('execute', (evt, data) => {
    console.log('New font color:', data);
});
```

**Comment by minhnhat2807** [comment]
thanks @Witoso
