### ISSUE TITLE
Promote the Essentials plugin across docs and samples (the Accessibility help dialog promotion)

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#15749]
## Provide a description of the task

`Essentials` loads `AccessibilityHelp`. If we ensure the former is popular in our docs/snippets, the latter will get more popularity.

**Comment by godai78** [comment]
Pretty much over 95% demos uses the docs build equipped with `essentials`. Below follows a list of demos that do not display the help dialog at this moment:  
  
Examples:

*   Inline editor build
*   Balloon editor build
*   Balloon block editor build
*   Multi-root editor build
*   Them customization works but is broken - white text on white background CC @oleq 
*   Custom UI with bootstrap

Features

*   Comments outside the editor (mostly because there is no content in it
*   Read-only support demo in the read only mode (which is legit, actually)

Framework

*   TBD

**Comment by godai78** [comment]
Summary:

*   the predefined builds example should not be changed due to their nature,
*   we may try to update the custom UI demos,
*   theme customization demo is OK, but the help dialog needs a fix for potential dark themes.

My assessment is that current state of affair is good enough for our needs.
