### ISSUE TITLE
Stale bot does not remove the stale label from pending issues

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#15812]
## 📝 Provide detailed reproduction steps (if any)

The new feature in the stale bot (#15697) does not remove the `status:stale` label if an issue is stale and requires feedback simultaneously. 

1. Sep 25, 2023: add label - `pending:feedback`
2. Oct 3, 2023: last comment, it's our
3. Feb, 6 2024: stale bot marks the issue as stale (invalid message)
4. Feb, 6 2024: add label - `status:stale`
5. Feb 7, 2024: last comment, it's from the community

Example issue: https://github.com/ckeditor/ckeditor5/issues/15046.

### ✔️ Expected result

1. We need to update the message if an issue is stale due to missing feedback. You can find a proposal below:
	```md
	The issue lacks the feedback we asked for two weeks. Hence, we've marked it as stale and will close it in 30 days. We understand it may still be relevant, so if you're interested in the solution, leave a comment or reaction under this issue.
	```
2. Both labels (feedback and stale) should be removed.

### ❌ Actual result

The `status:stale` label is still attached.

**Comment by pomek** [comment]
Another issue: https://github.com/ckeditor/ckeditor5/issues/13370.

**Comment by psmyrek** [comment]
You are right that in the issue #15046 the `status:stale` label should be removed by stale bot. But #13370 is actually stale and the `status:stale` label should not be removed.

The problem is caused by the initial date from which issues are searched. For non-pending issues to stale, the bot starts searching from the `DAYS_BEFORE_STALE` from the config (365 days by default), because we know that no other issues could be identified as stale ones. This is OK. But for pending issues we should not set the initial search date at all, because any issue created at any time may have a `pending:feedback` or `status:stale` labels. And this condition should be fixed in the stale bot.
