### ISSUE TITLE
adding underline and horizontalrule

### ISSUE THREAD

**Issue by vespino** [ckeditor/ckeditor5#15829]
I would like to upgrade to version 5 since the security issue of version 4.22.1 and below is the only features I need:

```
<div id="editor"></div>

<script src="ckeditor.js"></script>

<script>
	ClassicEditor
		.create( document.querySelector( '#editor' ), {
			toolbar: [ 'bold', 'italic', 'underline', '|', 'undo', 'redo', '|', 'numberedlist', 'bulletedlist', '|', 'horizontalrule' ]
		} )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );
</script>
```

The only problem is that I'm getting the following errors:

```
toolbarview-item-unavailable Object { item: "underline" }
toolbarview-item-unavailable Object { item: "horizontalrule" }
```

I have found a way of creating a custom build, but this really isn't necessary for me and it will also delay the update process in the future.

What would be the easiest solution for adding **underline** and **horizontalrule**?

**Comment by Witoso** [comment]
Hi! The easiest/fastest way would be to use [superbuild](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html#superbuild) from the predefined builds (horizontal rule is only there), and [removing](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/configuration.html#removing-features) not needed plugins. But it will result in a pretty big package, that's why the custom builds are recommended.
