### ISSUE TITLE
Tab navigation wrong behaviour

### ISSUE THREAD

**Issue by illia-stv** [ckeditor/ckeditor5#16071]
## Provide a description of the task

After merging to the master https://github.com/ckeditor/ckeditor5/pull/16070 there is no possibility to navigate with tab in the editing root ( browser helped us as default functionality but not yet ), except cases when we handle it with our own logic ( e.g. in restricted mode ). 

**Problem**

When focus is on the image and pressing `tab`, expected behaviour is focus moving inside caption, but we have got focus on the table. Look example below.   

[screen-capture (3).webm](https://github.com/ckeditor/ckeditor5/assets/47000454/d657be81-24db-4328-b0e4-339772a88797)

This is happening because we delegate tab navigation functionality to browser. While in CKE5 focus is on the image In DOM activeElement is editing root, so next in the queue to focus is actually table. 

So we assigned for all editable widget elements `tabindex="-1"` to prevent browser focus them.

**Consequnses**

Pressing `tab` impossible get to the caption.

[caption videos](https://github.com/ckeditor/ckeditor5/assets/47000454/bac6ab14-f006-4e8b-8d27-5aa73b512966)

**Suggestions**

Maybe it could be nice to handle tab navigation in these case. When widget is focused and there is editable elements inside ( like caption ) we could get there by pressing `tab`. Additionally we could handle `escape` by pressing `esc` button. 

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by niegowski** [comment]
A rough PoC how this could be handled: https://github.com/ckeditor/ckeditor5/compare/master...ck/16071-poc

Pressing the `Tab` key while a widget is selected -> selection is moved to the first nested editable.
Pressing the `Esc` key while inside a nested editable -> selection is moved to the closes ancestor widget.

Listeners are set on the `low` priority to avoid interference with the dedicated keystroke handlers (for example in the table feature). There is no solution for entering the table caption since there is a handler for the `Tab` key in tables and it should be customized to handle table caption case.

**Comment by niegowski** [comment]
Follow-ups:
* Linked block image is hijacking focus, the selection is not changed but the viewport is scrolled to the linked image.
* The tab key handling in a table does not support the caption element.

**Comment by niegowski** [comment]
Closed by https://github.com/ckeditor/ckeditor5/pull/16188.
