### ISSUE TITLE
Paste content to ckeditor 5, how to retain class and bookid attributes in < p class= "book" bookid= "123"> </p>.

### ISSUE THREAD

**Issue by gongzhiq** [ckeditor/ckeditor5#1615]
Paste content to ckeditor 5, how to retain class and bookid attributes in < p class= "book" bookid= "123"> </p>.

**Comment by Mgsy** [comment]
Hello, your attributes are stripped because the paragraph in the editor doesn't support those. Please, read about [Schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and [attribute to attribute conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html#function-attributeToAttribute).
