### ISSUE TITLE
Getting out of a single table

### ISSUE THREAD

**Issue by kl3sk** [ckeditor/ckeditor5#1621]
## Is this a bug report or feature request? (choose one)
🐞 Bug report
## 💻 Version of CKEditor
v12.0.0
All version, even on the documentation

## 📋 Steps to reproduce

1. Create a single table (just a table nothing else) with any rows et columns you want

## ✅ Expected result
Get out of the table
## ❎ Actual result
Impossible to get out

**Comment by kl3sk** [comment]
Sorry for the dup of https://github.com/ckeditor/ckeditor5-table/issues/177 but Github has remove my issue after show it again.

**Comment by scofalik** [comment]
It is actually possible to leave the table but the discoverability of this feature is low. Select the whole table (clicking selection handler - the square in the top left corner) and press <kbd>Enter</kbd> to create a paragraph below, or <kbd>Shift + Enter</kbd> to create a paragraph above.

The general issue for this problem is still open: https://github.com/ckeditor/ckeditor5/issues/407. We want to work on a better solution, but we cannot give you any ETA.

**Comment by kl3sk** [comment]
Ok, I didn't know/found this trick. Happy to listen you are working on it.
