### ISSUE TITLE
ContentToolbar popup doesn't translate

### ISSUE THREAD

**Issue by gastonmunoz** [ckeditor/ckeditor5#1641]
🐞 Bug report

## 💻 Version of CKEditor

CKEditor 5, Angular Component.

## 📋 Steps to reproduce

1. Create a component and embed a ckeditor node:
```
                <div [ngClass]="designerClass()">
                    <ckeditor
                        [config]="config"
                        [editor]="editor"
                        [formControlName]="control.key">
                    </ckeditor>
                </div>
```
2. Use this config:
```
    public config = {
        toolbar: {
            items: ["heading", "|", "alignment", "bold", "italic", "undo", "redo", "insertTable"]
        },
        image: {
            toolbar: ["imageStyle:full", "imageStyle:side", "|", "imageTextAlternative"]
        },
        language: "es",
        table: {
            contentToolbar: ["tableColumn"],
            tableToolbar: [ "blockQuote" ]
        }
    };
```

## ✅ Expected result
All the text in the component must be spanish language.

## ❎ Actual result
The contentToolbar language is english.
![issue](https://user-images.githubusercontent.com/38219335/54710245-ff438900-4b25-11e9-8b7d-62a476042b79.jpg)

**Comment by ma2ciek** [comment]
Hi @gastonmunoz.

Did you follow the [localization section in the Angular integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#localization)?

**Comment by gastonmunoz** [comment]
Yes, my code have this line: 
`import "@ckeditor/ckeditor5-build-classic/build/translations/es";`

**Comment by ma2ciek** [comment]
That's because not all strings are translations yet on the [Transifex service](https://www.transifex.com/ckeditor/ckeditor5/language/es/).

The CKEditor 5 is an open-source project supported by the community, we'd be glad if you could help in translation those strings so they can be reused by other people later too. Note that once the strings are being translated on the Transifex, they will be available in the next release which will happen within ~3 weeks.

**Comment by ma2ciek** [comment]
Until the next release, you can feed the global `CKEDITOR_TRANSLATIONS.es` by your own with missing translations.
