### ISSUE TITLE
It's impossible to import `ckeditor5` package using `require` on Node LTS.

### ISSUE THREAD

**Issue by Mati365** [ckeditor/ckeditor5#16510]
## 📝 Provide detailed reproduction steps (if any)

1. Install Node 20.x (LTS)
2. Create `package.json` with this content:

```json
{
  "dependencies": {
    "ckeditor5": "^42.0.0-alpha.1",
    "ckeditor5-premium-features": "^42.0.0-alpha.1"
  }
}
```

3. Run `npm install`
4. Create `index.js` file with this content:

```js
const ckeditor = require( 'ckeditor5' );

console.log( ckeditor );
```

5. Run this file `node ./index.js`

### ✔️ Expected result

Prints all exported plugins from `ckeditor5` or info about such errors in docs.

### ❌ Actual result

`No "exports" main defined` exception is raised.

### ❓ Additional information

1. This error might happen in `jest` and other older tools that were created before `ESM` era and are configured to use `CJS`. 
2. There is no information about that the `ckeditor5` package is the `ESM` module in docs: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/getting-started/installation/quick-start.html#using-ckeditor-5-builder
3. There should be an sections in our docs describing what should I do when I want to use such package in older environment:
3.1. `What should I do to make it work in older CJS environment?` 
3.2. `Why type: module is needed in my package.json in order to import `ckeditor5`?`
3.3. `Why ckeditor5 is ESM module?`

## 📃 Other details

* OS: Fedora 40
* Node v20.12.2

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by filipsobol** [comment]
From my point of view, there's no reason to support `require()`-ing CKEditor because (1) we never did and (2) our packages are only meant to be used in browser environments. There may be setups in the wild that try to test CKEditor using Jest (or similar libraries) together with libraries that mock the browser environment (like `jsdom` or `happy-dom`), but we actively discourage this because CKEditor uses many browser APIs that the mocking libraries don't support well or at all. Essentially, running CKEditor with `jsdom` only confirms that CKEditor works with `jsdom`, not that it works in the browser.

If someone still tries to use CKEditor in a CommonJS project, they basically have two options:
1. Use dynamic import (`await import('ckeditor')`), which can be done from within the CommonJS file.
2. Upgrade to Node 22, which has [support for `require()`-ing synchronous ESM](https://nodejs.org/en/blog/announcements/v22-release-announce#support-requireing-synchronous-esm-graphs).

**Comment by Mati365** [comment]
Gotcha, thanks!
