### ISSUE TITLE
How do I get access to the 'FileRepository' plugin when I am hooking the editor via CDN for a Laravel project as mentioned in the doc?

### ISSUE THREAD

**Issue by NafiurSiddiqui** [ckeditor/ckeditor5#16705]
## 📝 Ask a question

_What is your question? Please be as specific as possible to help us understand it._

How do I get access to the 'FileRepository' plugin when I am hooking the editor via CDN for a Laravel project as mentioned in the doc [here](https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/laravel.html)?
I am using the `Custom Image Upload Adapter` as mentioned in the doc [here](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/upload-adapter.html)

Here is the code inside a `blade.php` file - 

```
<script type="importmap">
        {
            "imports": {
                "ckeditor5": "https://cdn.ckeditor.com/ckeditor5/42.0.0/ckeditor5.js",
                "ckeditor5/": "https://cdn.ckeditor.com/ckeditor5/42.0.0/"
            }
        }
    </script>


<script type="module">
    import {
        ClassicEditor
    } from 'ckeditor5';



    document.addEventListener('DOMContentLoaded', function() {
        class MyUploadAdapter {
            ....
            _initRequest() {
                const xhr = this.xhr = new XMLHttpRequest();
                xhr.open('POST', '{{ route('admin.images.store') }}', true);
                xhr.setRequestHeader('x-csrf-token', '{{ csrf_token() }}');
                xhr.responseType = 'json';
            }

          // Exactly the way the documentation shows
        }

        function MyCustomUploadAdapterPlugin(editor) {

            editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
               //HERE is where plugins can't find the 'FileRepo'
                return new MyUploadAdapter(loader);
            };
        }

        ClassicEditor
            .create(document.querySelector('#editor'), {
                // toolbar: ['strikethrough'],
                extraPlugins: [MyCustomUploadAdapterPlugin],
            })
            .catch(error => {
                console.log(error);
            });
    });
</script>

```
**NOTE** - If I do not use the `type="module"` on the script and just add a `<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>` link, everything works fine other than the fact that I cannot add any other plugins but what comes with the link by default. 

_**Question**_ -
if I use the script with type module and import the plugins, how do I get the `FileRepository` plugin.
Else, how do I get the rests of the plugin with a CDN link?

**Comment by Reinmar** [comment]
> ClassicEditor  
> .create(document.querySelector('#editor'), {  
> // toolbar: \['strikethrough'\],  
> extraPlugins: \[MyCustomUploadAdapterPlugin\],  
> })

You don't load any plugins except your custom adapter. In other words, this code makes you load a bare editor without any plugins.

This is something that has changed recently, with v42.0.0.

Before v42.0.0 a concept of editor builds existed. Editor build would have a certain plugins "built into" itself. And then was enough to do empty `ClassicEditor.create( element )` to start the editor. You'd use `extraPlugins` to add more on top of that.

With v42.0.0 we removed that concept because it was causing tons of confusion. Right now, everytime you call `create()` you need to provide all the necessary plugins. You'd find them in `builtinPlugins` array of the source of your old editor build.

The code above does not work because when you create that editor instance it does not have any plugins. Which means `editor.plugins.get( 'FileRepository' )` returns null.

Once you'll add the missing plugins to your `create( element, { plugins: ... } )` call all should work fine.

There are several migration guides available when you migrate to v42.0.0. This one for instance may be of help: https://ckeditor.com/docs/ckeditor5/latest/updating/nim-migration/customized-builds.html

**Comment by NafiurSiddiqui** [comment]
> > ClassicEditor
> > .create(document.querySelector('#editor'), {
> > // toolbar: ['strikethrough'],
> > extraPlugins: [MyCustomUploadAdapterPlugin],
> > })
> 
> You don't load any plugins except your custom adapter. In other words, this code makes you load a bare editor without any plugins.
> 
> This is something that has changed recently, with v42.0.0.
> 
> Before v42.0.0 a concept of editor builds existed. Editor build would have a certain plugins "built into" itself. And then was enough to do empty `ClassicEditor.create( element )` to start the editor. You'd use `extraPlugins` to add more on top of that.
> 
> With v42.0.0 we removed that concept because it was causing tons of confusion. Right now, everytime you call `create()` you need to provide all the necessary plugins. You'd find them in `builtinPlugins` array of the source of your old editor build.
> 
> The code above does not work because when you create that editor instance it does not have any plugins. Which means `editor.plugins.get( 'FileRepository' )` returns null.
> 
> Once you'll add the missing plugins to your `create( element, { plugins: ... } )` call all should work fine.
> 
> There are several migration guides available when you migrate to v42.0.0. This one for instance may be of help: https://ckeditor.com/docs/ckeditor5/latest/updating/nim-migration/customized-builds.html

Hey Reinmar, I am not using no builds. I directly pulling it down from CDN as mentioned [here](https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/laravel.html) and above. Also notice in the code that I provided, I am using `v42.0.0`. 

At the bottom, I mentioned the ` <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>` is where I tried to use it with the module and failed because of the reason you just well clarified. 

Since I am not using any builds, how do I get the `FileRepository` plugin?

**Comment by Reinmar** [comment]
> Hey Reinmar, I am not using no builds. I directly pulling it down from CDN as mentioned [here](https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/laravel.html) and above. Also notice in the code that I provided, I am using `v42.0.0`.

I know you use v42.0.0. But you use it incorrectly.

You must import all the plugins that you need and pass it to the editor config. You do not do that. You pass just one plugin.

Your code should look more like this:

```
import { ClassicEditor, AccessibilityHelp, Autosave, Bold, Essentials, Italic, Paragraph, SelectAll, Undo } from 'ckeditor5';

const editorConfig = {
	plugins: [
		AccessibilityHelp, Autosave, Bold, Essentials, Italic, Paragraph, SelectAll, Undo,
		
		// AND MANY MORE, including e.g. ImageUpload which then loads FileRepository automatically.
	],
};

ClassicEditor.create(document.querySelector('#editor'), editorConfig);
```

> At the bottom, I mentioned the `<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>` is where I tried to use it with the module and failed because of the reason you just well clarified.

That made me think that you're migrating from a version below v42.0.0.

If you're setting up a new installation, make sure to use the builder [https://ckeditor.com/ckeditor-5/builder/](https://ckeditor.com/ckeditor-5/builder/.) and use the snippets that it generates. As you will see, you will get all the necessary plugins in your editor config and your `MyCustomUploadAdapterPlugin()` will start working just fine.

**Comment by filipsobol** [comment]
I'll add my two cents to hopefully clarify a few things.

@NafiurSiddiqui If I understand correctly, you used to use `<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>` to get the editor code. This URL contains what we called a "predefined build", which is an editor preconfigured with a bunch of commonly used plugins, toolbar, etc. However, since this approach didn't work well and didn't give developers enough control over the editor configuration, we decided to abandon the idea of such builds.

Instead, in the new installation methods, the editor comes out-of-the-box without any plugins, and therefore you can't load the `FileRepository` plugin.

If you want to get the exact same editor you had with the old installation methods, you can follow this migration guide: https://ckeditor.com/docs/ckeditor5/latest/updating/nim-migration/predefined-builds.html. You can skip the `npm` section and follow the `CDN` section instead. There you will find the exact code you need to add to your project to replace the old `Classic Editor'.
After you done that, you should be able to access the `FileRepository` plugin.

**Comment by NafiurSiddiqui** [comment]
> > Hey Reinmar, I am not using no builds. I directly pulling it down from CDN as mentioned [here](https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/laravel.html) and above. Also notice in the code that I provided, I am using `v42.0.0`.
> 
> I know you use v42.0.0. But you use it incorrectly.
> 
> You must import all the plugins that you need and pass it to the editor config. You do not do that. You pass just one plugin.
> 
> Your code should look more like this:
> 
> ```
> import { ClassicEditor, AccessibilityHelp, Autosave, Bold, Essentials, Italic, Paragraph, SelectAll, Undo } from 'ckeditor5';
> 
> const editorConfig = {
> 	plugins: [
> 		AccessibilityHelp, Autosave, Bold, Essentials, Italic, Paragraph, SelectAll, Undo,
> 		
> 		// AND MANY MORE, including e.g. ImageUpload which then loads FileRepository automatically.
> 	],
> };
> 
> ClassicEditor.create(document.querySelector('#editor'), editorConfig);
> ```
> 
> > At the bottom, I mentioned the `<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>` is where I tried to use it with the module and failed because of the reason you just well clarified.
> 
> That made me think that you're migrating from a version below v42.0.0.
> 
> If you're setting up a new installation, make sure to use the builder [https://ckeditor.com/ckeditor-5/builder/](https://ckeditor.com/ckeditor-5/builder/.) and use the snippets that it generates. As you will see, you will get all the necessary plugins in your editor config and your `MyCustomUploadAdapterPlugin()` will start working just fine.

Well, I followed as you said so. Issue was I still had the same issue because I was directly importing `FileRepository` and adding it inside the plugin-ins, failing to understand your hint of the `ImageUpload`. It started working as I added `ImageUpload` instead, which makes sense now that how `ImageUpload` makes a call to the `FileRepository` API. 

Highly appreciate your time and patience bruh.

**Comment by NafiurSiddiqui** [comment]
@filipsobol Ya, it all makes sense now. Did not have to update, just made a fresh installation and there were some issues like, I kept trying to load `FileRepo` API as a plugin but what I needed was the `ImageUpload` plugin. Thank you so much for dropping by and put a good explanation on how the new version is working.
