### ISSUE TITLE
(PLEASE HELP) Need to add/update id and style to an element created using createAttributeElement in the downcaster.

### ISSUE THREAD

**Issue by DebjaniMallick** [ckeditor/ckeditor5#16784]
**PLEASE HELP**

I am trying to add a custom plugin where we are trying to create a tag with multiple attributes like href, onmouseover, onmouseout, id, style. I am using createAttributeElement in the downcaster to add the href, onmouseover and onmouseout attributes to the custom tag. For id and style, I am using options.id and setStyle to add those attributes but when I try to edit the same link, my existing tag gets wrapped around with another tag instead of editing the existing one.

This happens only when I add the id and style attributes. If I dont add those, it works fine.

Please help on how to be able to successfully add/edit those attributes (id and style).

**Comment by vyom-verma** [comment]
Add screenshots please

**Comment by Witoso** [comment]
Hi! Some code for reference would be ideal. Please remember if you're adding with [`createAttributeElement`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_downcastwriter-DowncastWriter.html#function-createAttributeElement) do this with the priority, the `a` will be split otherwise: 

```
// Make `<a>` element contain other attributes element so the `<a>` element is not broken.
writer.createAttributeElement( 'a', { href: 'foo.bar' }, { priority: 5 } );
```

When the same priority is used for adding or modifying attributes, the editor will merge attributes into a single `<a>` element instead of creating multiple elements, thereby preventing the `<a>` tag from breaking.

I assume the `setStyle` may be using some default priority, that's why the `a` tag is split. But @niegowski could tell more for sure :)

**Comment by DebjaniMallick** [comment]
Making all the attributes have the same priority did the trick. Thank you for the help.
