### ISSUE TITLE
gulp update does not work on Node 4.4.4

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#172]
```
(master 2fdb98c) ~/workspace/ckeditor5/ckeditor5> gulp update
/Users/pjasiun/workspace/ckeditor5/ckeditor5/dev/tasks/test/tasks.js:86
				...benderSrc,
				^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pjasiun/workspace/ckeditor5/ckeditor5/gulpfile.js:21:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by Reinmar** [comment]
Sorry, CKEditor 5 requires Node 5+. It's configured in `package.json`.

**Comment by oleq** [comment]
Do we really need to support 4.x? I know it's LTS at the moment but `gulp update` is strictly dev task and we can enforce other versions.

**Comment by oleq** [comment]
@Reinmar Lightning fast.

**Comment by pjasiun** [comment]
I see, and already updated Node. But that's a pity we do not support LTS. Agree that we need to check if our code works on the newest version of the Node, but since the newest version does not work very well I do not see a point for the whole teem to deal with these bugs. This is why me and @scofalik were using LTS, as we were mostly users of gulp tools.

**Comment by Reinmar** [comment]
I'd be ok with supporting LTS if 4.0 had ES6 support. But it doesn't of course, and it was very strange that we've been using ES6 in the source code but not in Node.JS code.

Maybe, once the project is stable, we can support next LTS version. I think that this is an interesting idea. But for now, it just didn't make sense. And of course, someone needs to check our tools on newest Node versions as well, because other developers will do this, so we need to know about all issues. For instance, installing Node 6 showed us that Bender became a problem. Sooner we address that, the better.
