### ISSUE TITLE
Configuring DataProcessor

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5#173]
When using `StandardCreator` class it is impossible to set data processor when initializing it as a plugin. It takes instance of data processor as constructor's second argument - which is not set by `PluginCollection` during initialization (only editor instance is passed).
`ClassicCreator` is setting this when calling `super()` so everything is fine there.

Was talking with @Reinmar abut this: new idea is to move data processor to configuration.

**Comment by Reinmar** [comment]
Currently, this makes StdCreator kinda abstract. You can't use it directly. You need to subclass it. It's okeyish, but I think that your idea with making the `HtmlDataProcessor` a default value will solve this in a simplest possible way.

Another thing is that currently the data processor is only configurable through using a different creator. This is a much bigger problem, because you need to subclass one creator to change that value... A bit irritating.

So, I think that what we need is also making the data processor configurable through config setting. We can for now support only the "value by constructor" way (as opposed to the string format which we support for features and creators). It should be possible to make it later configurable by string – the value will need to be read in creator's `init()`, use `load()` and delay the `init()`'s promise resolution.
