### ISSUE TITLE
Rebuilded old CKEditor 5 builds crash

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#1746]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

`ckeditor/ckeditor5-build-classic@10.0.0` and others

## 📋 Steps to reproduce

```
> git clone https://github.com/ckeditor/ckeditor5-build-classic.git
> cd ckeditor5-build-classic
> git checkout v10.0.0
> npm install
> npm run build
> open sample/index.html
```

## ✅ Expected result

The editor builds and shows up correctly.

## ❎ Actual result

The build is incorrect and modules are duplicated.

The `@ckeditor/ckeditor5-easy-image` package is loaded at version `10.0.4` (`^10.0.0`)

It has the following deps:

```
"dependencies": {
    "@ckeditor/ckeditor-cloud-services-core": "^2.0.0",
    "@ckeditor/ckeditor5-cloud-services": "^10.1.1",
    "@ckeditor/ckeditor5-core": "^11.1.0",
    "@ckeditor/ckeditor5-image": "^12.0.0",
    "@ckeditor/ckeditor5-upload": "^10.0.4"
  },
```

The `@ckeditor/ckeditor5-classic-editor` is loaded at version `10.0.1` (`^10.0.0`).

It has following deps:

```
"dependencies": {
    "@ckeditor/ckeditor5-core": "^10.1.0",
    "@ckeditor/ckeditor5-engine": "^10.1.0",
    "@ckeditor/ckeditor5-theme-lark": "^10.1.0",
    "@ckeditor/ckeditor5-ui": "^10.1.0",
    "@ckeditor/ckeditor5-utils": "^10.1.0"
  },
```

So the `@ckeditor/ckeditor5-core` is loaded twice in different versions.

**Comment by ma2ciek** [comment]
Actually, the problem is described here: https://github.com/ckeditor/ckeditor5/issues/1692, but I'm not sure if the `duplication check` is enough - it can warn developer, but that's not the fix for the real issue.

The issue is that when you install deps today the editor works correctly and if you install tomorrow it might stop working.

**Comment by ma2ciek** [comment]
If all CKEditor 5 plugins would be listed in the top level `package.json` file of the app we could force the webpack resolution system to use only the top level ones.

And this problem brings also the need for package-lock.json files in `@ckeditor/ckeditor5-build-*` packages.

**Comment by ma2ciek** [comment]
And this would probably also fix the issue: https://github.com/ckeditor/ckeditor5/issues/988#issuecomment-482072208, but this we can do only in our builds, we can't force people to hardcode version of editor plugins.

**Comment by ma2ciek** [comment]
cc @pjasiun @Reinmar @mlewand

**Comment by ma2ciek** [comment]
ping

**Comment by Reinmar** [comment]
Wait... so you say that a single list of packages, with non-conflicting package versions is installing some packages more than once? I'm 99% sure we tested it and it was fine in the past. That npm was able to find the list of packages without any conflicts. Doh :< Gotta test it myself.

**Comment by Reinmar** [comment]
You're right. Both npm and yarn duplicate some packages. So I guess our tests were insufficient and perhaps we didn't cover some more complex scenario. 

We'll have to talk about it because I don't see any simple solution.

**Comment by ma2ciek** [comment]
I guess that the easiest solution might be to align the major versions of all packages we release at some point. This would be a huge task and It'd come with its cons. I don't see any easier solution now.

But OTOH this will be a safe solution because in this versioning approach there is no point at which the `packageA@n` requires `packageB@n+1`. So all packages will be in sync after years and won't break suddenly. The other big advantages that come to my mind are following:
- easier installation and updates of CKEditor 5 packages for people building editor from sources (see https://github.com/ckeditor/ckeditor5/issues/1722#issuecomment-490167752) and the huge list of CKEditor 5 deps
- easy versioning system for us when it comes to marking breaking changes in API docs

**Comment by ma2ciek** [comment]
I was thinking for a while about this problem. Let's check the simplest scenario when this error occurs:

Let's create 3 packages, `A`, `B`, and `C` that will be required by both `A` and `B`

```
ROOT
 - A
 - B

A
 - C

B
 - C
```

Then, initialize them at version 1.0, so we have `A 1.0`, `B 1.0`, `C 1.0`.

```
ROOT
 - A^1.0 -> 1.0
 - B^1.0 -> 1.0

A 1.0
 - C^1.0 -> 1.0

B 1.0
 - C^1.0 -> 1.0
```

Then, let's make a BC in package `A` and package `C` and a minor change in package `B`, so `A 2.0`, `B 1.1`, and `C 2.0` are released. (We release the `C` package first and then update its version in package `A` and `B` before the release. 

With the same dependencies for the previous `ROOT` package the following packages will be installed:

```
ROOT
 - A^1.0 -> 1.0
 - B^1.0 -> 1.1

A 1.0
 - C^1.0 -> 1.0

B 1.1
 - C^2.0 -> 2.0

-----

ROOT
 - A^1.0 -> 1.0
   - C^1.0 -> 1.0
 - B^1.0 -> 1.1
   - C^2.0 -> 2.0
```

Now, the C package will be duplicated because both `A` and `B` requires it but in different versions that can't be satisfied at the same time by the `^` range operator. I wondered if we can do extra minor bumps before major ones, in this scenario imagine, that we extra release the `A` package in `1.1` version that requires `C^2.0`

With that approach, the duplication problem would be fixed:

```
ROOT
 - A^1.0 -> 1.1
 - B^1.0 -> 1.1

A 1.1
 - C^2.0 -> 2.0

B 1.1
 - C^2.0 -> 2.0

--- 

ROOT
 - A^1.0 -> 1.1
   - C^2.0 -> 2.0
 - B^1.0 -> 1.1
   - C^2.0 -> 2.0
```

However... We can't assume that the `A 1.0` (or `1.1`) can require the `C 2.0` as it contains breaking changes that might be not compatible with the `A` package in the 1.0` (or `1.1`) versions.

So we end up with the situation in which we can't load two packages at different versions (because of plugins that are singletons, `instanceof` checks, etc.), we can't use only the `C 1.0` because the `B 1.1` won't be compatible with it, nor we can't use only `C 2.0`, because the `A 1.0` won't be compatible with it.

IMO the Angular (that release all packages with the same version) or [Babel](https://github.com/babel/babel/tree/master/packages) (that release all major versions once) versioning could only help here.

The `package-lock.json` / `yarn.lock` files would help but for CKEditor 5 builds only 😞

**Comment by Reinmar** [comment]
# Problem

- Builds
- Any custom installation 😞

# Options

## Using strict versions

- Between packaged and from ckeditor5-build-*, everywhere else
- Would solve the situation with builds
- We would have to educate everyone outside to not use caret ranges ([https://stackoverflow.com/questions/30656189/make-npm-install-save-add-a-strict-version-to-package-json](https://stackoverflow.com/questions/30656189/make-npm-install-save-add-a-strict-version-to-package-json))
- Also: what's the point of semver at this point?

## Deduping on runtime level (global namespace)

- Not reallly a solution, more of a workaround
- May still not work (there may still be a mismatch between packages and they may not work together). It's just less probable that problems will occur.
- Duped packages lead to 2x bigger builds.
- This solution has to consider more problems (e.g. styles).

## Babel/Angular way

- **General rule of thumb: If any package has a major release, entire project has a major release**
- Next release: v15.0.0 in all packages. From now on, the entire project and all its packges will share the same **major** version. Minor and patches may differ.
- Changelog generation:
    - (MAJOR BREAKING CHANGE) Breaking change in public API – has to bump major in **all packages**
    - (MINOR BREAKING CHANGE) Breaking change in private API – bumps minor in **this package only**
    - Today, we'll be making the decisions based on gut feeling
- New changelog rules:
    - minor: feature, breaking change in private API
    - major: breaking change in public API
- Current `ckeditor5` changelog:
    - Major (breaking changes)
    - Minor (feature, breaking change in private API)
    - Patch (...)
- New `ckeditor5` changelog:
    - Major releases (due to major braking changes)
    - Minor releases (containing minor breaking changes)
    - Minor releases (new features, no breaking changes)
    - Patch releases (bug fixes, internal changes)
- New `ckeditor5-*` changelog:
    - MAJOR BREAKING CHANGES
    - MINOR BREAKING CHANGES
    - NOTES
    - Features
    - Bug fixes
    - Other changes
- Idea: write all this down into a "Versioning" guide and link from "major breaking changes" and "minor breaking changes". Whatever terms we'll find, they'll be confusing.
- NOTE: Since a single major breaking change in a single package leads to all bumps being major, this **must not** affect CKEditor 5's changelog. The
- DANGER: CKE5 doesn't have major, CF, has. What's now?

## peerDependency solution

- [https://medium.com/@jacob.h.page/common-npm-mistakes-51bf8989079f](https://medium.com/@jacob.h.page/common-npm-mistakes-51bf8989079f)
- In line with the solution that we proposed for 3rd party packages
- The used ckeditor5-editor-* package will be the only one requiring ckeditor5-core, ckeditor5-engine, etc.
- Plugin packages will use peerDependencies with a permissive `>=` version selector

    > Mistake 6: being overly-specific with peerDependencies
    If you’re authoring a module that has peer dependencies, be as loose as possible with your version requirement; don’t just blindly use the latest version of those dependencies. Remember that the consuming application may be reconciling multiple version requirements; the less specific you are, the better.

- Problem: ckeditor5-widget – how should it be references? `peerDependency` too, or a direct dependency? In both cases: use `>=` version selector.
- If 3rd party packages will use `>=` version selector, then do they have to use `peerDependencies` at all? No. But if they'd use `>=` together with `<`, then yes. If two packages have incompatible ranges, then you'd clearly see that when installing them (TODO: check if this is true), that their deps cannot be met with a single package. However, how frequent problem will this be? Will anyone spec the upper limit in practice?
- This solution makes sense only for 3rd party packages.

## Concept: public vs private API

- Not an option per se, but rather a complementary solution.
- API levels:
    - Public/integrational: integration API, most important and popular parts
    - Private/internal: tuning plugin behaviour, lower level utils, hacking, closer customization
- TODO: Better names needed, to avoid confusion with private/protected/public API levels.
    - Since we already have private/protected/public, doesn't this mean that we just need one level on top of this or something between protected and public?
- New change types:
    - Major breaking change: breaking change in the public API.
    - Minor breaking change: breaking change in the private API.
- Goal: reduce the frequency of major releases of all packages.
- Required by: external systems which cannot allow major upgrades frequently (e.g. Drupal).
- Requires work in the API docs, Umberto, etc. Major effort will have to be put into writing down rules and reviewing the entire API.
- For now, we'll follow gut feeling when making decisions about minor and major breaking changes.
- [https://wimleers.com/talk/bc-evolvability-maintainability](https://wimleers.com/talk/bc-evolvability-maintainability)

# TODO

- Update commit message guide.
    - Mention "MINOR BREAKING CHANGE" and "MAJOR BREAKING CHANGE"
    - What about "BREAKING CHANGE"? Let's treat it as "MAJOR BREAKING CHANGE".
- Release tool:
    - No changes needed.
    - It uses CHANGELOGs. If CHANGELOGs are updated, then nothing else is needed.
- Package changelog generator:
    - If any of the packages will have a major release, all other packages must have a major release as well. Even empty ones.
    - After scanning all packages, print out all major breaking change notes. Ask if they are really breaking. If the user will choose yes (default option), then we'll do major updates in all packages. If not, none of the breaking changes will be treated as major.
    - The tool should still ask to confirm each version number. Still useful, e.g. when we want to skip one version number (e.g. right now to 15.0.0).
    - Needs to introduce the new `ckeditor5-*` changelog structure described above.
- Build (and `ckeditor5)` changelog generator:
    - Scan commits. Generate the typical part the changelog (local changes).
    - First, compare latest tag with the newest version in the CHANGELOG in every package repo. Check which packages should be released. Generate the dependencies section with the new type of categories (see "New `ckeditor5` changelog" above).
    - It does not have to propose the new version number. It's ok if it asks and only prints the current one. PK usually enter the new version number manually anyway.
- Other requirements:
    - Whenever there's a major release, ALL packages (even those without changes) must be released.
- How does it affect ckeditor5-dev, integrations and other tools?
    - Let's see. We can change the current behaviour for ckeditor5-dev but don't have to. Both are fine.

**Comment by ma2ciek** [comment]
> Concept: public vs private API

An idea came to my mind recently:

What if we start exporting public / stable API via the main package? For example we could create such file:

```js
// ckeditor5-core/src/index.js:
export { Command } from './command';
export { Plugin } from './command';
```

And make it the entry point of the `ckeditor5-core` package so the following import will be available:

```js
import { Command, Plugin } from 'ckeditor5-core';
```

Actually, this pattern is rather common in libraries. So the library code can be split into the API surface and files that are treated as private. The tree shaking should work here thus the build sizes should remain the same. The biggest issue is that our docs are currently file-based so this approach won't fit there and we'd need a huge amount of time to implement it.

**Comment by pomek** [comment]
> New `ckeditor5` changelog:
> * Major releases (due to major braking changes)
> * Minor releases (containing minor breaking changes)
> * Minor releases (new features, no breaking changes)
> * Patch releases (bug fixes, internal changes)

Because minor releases have two sections, I will apply the same rule to major releases. If major was picked up because of the major release by other packages, let's group those into a single group. But if it was picked because it really contains those breaking changes, let's add it into another group. So we will end with 5 entries:

* Major releases (due to major breaking changes)
* Major releases (due to updates in other packages; in fact, there wasn't any a major breaking change)
* Minor releases (containing minor breaking changes)
* Minor releases (new features, no breaking changes)
* Patch releases (bug fixes, internal changes)

An interesting thing – we will never print all of those entries in a single release/changelog:

* if there was a `major` bump in `ckeditor5-*` package – all packages will be marked as "Major releases" (no minor, no patch)
* if there was a `minor` bump – packages can be releases as minor (both variants) or patch

**Comment by ma2ciek** [comment]
Isn't the issue solved by our new versioning policy? I mean starting from the latest build we should no longer have this issue.

**Comment by Reinmar** [comment]
> What if we start exporting public / stable API via the main package?
> 
> Actually, this pattern is rather common in libraries. So the library code can be split into the API surface and files that are treated as private.

I was thinking about a similar thing in the context of extending builds. However, instead of having those things exported, I wanted to have them on the global `CKEDITOR` object (or `CKEDITOR_PKGNAME` objects). Then, similarly, things that are exposed on this object would be the plugin API and things that are not (and have to be imported from source packages) would be the private API layer. 

I  actually like the concept that you presented more as its cleaner than the global object, but at the same time, it does not solve the problem with extending builds. So, I wonder if we could have those nice imports in the code and use a global object in builds and perhaps published packages. I guess this should be doable and may bring many benefits. 

Let's keep this in mind.

> Isn't the issue solved by our new versioning policy? I mean starting from the latest build we should no longer have this issue.

I kept it open to get back to your comment :D Now, I can close it.
