### ISSUE TITLE
`ckeditor5-premium-features` does not include `src/`

### ISSUE THREAD

**Issue by bendemboski** [ckeditor/ckeditor5#17576]
This is related to #17575.

I believe all packages in the CKEditor5 ecosystem publish `src/` folders (even the closed-source collaboration plugins like `@ckeditor/ckeditor5-comments`) except `ckeditor5-premium-features`. This means that, for the reasons described in #17575, importing from `ckeditor5-premium-features` is risky, as it has the potential to make the module graph "hop over" from `dist/` to `src/` because even though all of its imports from `@ckeditor/ckeditor5-*` packages are from their `dist/` folders, as #17575 describes, importing from their `dist/` folders can cause the module graph to "hop over".

My workaround, as described in #17575, is to import from `src/` folders and not consume `dist/` until #17575 is addressed. This means I can't use `ckeditor5-premium-features` at all because it does not publish a `src/` folder.

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by filipsobol** [comment]
The `src` folders in other packages are only there for backward compatibility with the legacy installation methods and will be removed in the future. Because the `ckeditor5-premium-features` package was specifically created for new installation methods and doesn't need to be backward compatible, it doesn't have the `src` folder.

See my reply in the issue you linked for more information.
