### ISSUE TITLE
Align emoji picker to match CKEditor 5 design

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#17573]
## Provide a description of the task

* Input styles
    * Compare the plugin view and a link UI.
    * ![Image](https://github.com/user-attachments/assets/9af39aab-47d9-4f7d-8bb9-45fddee440b2)
    * ![Image](https://github.com/user-attachments/assets/68702aaf-6b4b-4222-8ec2-18f0356fbdbc)
* Mouse over an emoji
    * Compare the _onhover_ styles.
    * ![Image](https://github.com/user-attachments/assets/a9a8e1f8-d78f-4774-be3b-d624bd5ece88)
    * ![Image](https://github.com/user-attachments/assets/965c0733-3d72-4b21-b0a4-055e39b8bc69)
* Active category tab color
    * Let's use CKEditor 5 color theme.
    * ![Image](https://github.com/user-attachments/assets/202fafcf-83e9-462b-bed9-9ea343d4a8ce)
    * ![Image](https://github.com/user-attachments/assets/45ae7c9c-f482-4e55-8780-18302e6b0e67)

**Comment by dwandeljanicka** [comment]
- According to decision made during [design guild](https://www.notion.so/Headers-or-not-to-headers-changes-in-balloon-design-rotators-106bb9a672328009933dd2478bc415e9) we decided to add headers to balloons. 

Example: Bookmark

![Image](https://github.com/user-attachments/assets/8fefda34-f195-4396-8b30-ea8273f633ad)

**Comment by dagdzi** [comment]
1. In the search components we have both a magnifying glass icon and an "x" icon. So there is more going on here than in our regular text field.

<img src="https://github.com/user-attachments/assets/3b26b3dc-fd5e-4ef7-8a63-a144c554df8b" width=50% height=50%>

<img src="https://github.com/user-attachments/assets/e3383340-3ae8-44ab-bb3f-a3a0d25af8f1" width=50% height=50%>

2. When there are no results, we inform the user about it.

<img src="https://github.com/user-attachments/assets/89801e8a-a416-4119-8151-eeaae8bc266d" width=50% height=50%>

3. One thing is the shape and color of the hover, and another is the lack of blue focus. What about navigating through icons using the keyboard? Now you can do it using TAB, but in Special Characters feature you do it using arrows. We probably should make it consistent if possible.

https://github.com/user-attachments/assets/8e060147-46b6-465d-b561-3d5694cb859d

4. I have some problem with displaying skin tone icons.

<img src="https://github.com/user-attachments/assets/46c8f37d-baab-4f78-8706-e03a1ceb728e" width=50% height=50%>

5. In the Uploadcare feature, we have similar tabs with underline. Now the underline is black, because it is hard to style this feature for us. But I designed it in our active color (our active elements are blue, see screen below the video). What should we do here, and how can make it consistent?

https://github.com/user-attachments/assets/5d91562d-2c73-49dc-8f1d-e8ebf708533c

<img src="https://github.com/user-attachments/assets/d5f7bb45-ef54-4c99-bbbf-41a1ad662b9e" width=75% height=75%>

6. Previously, we used blue active list items in every list. Then we introduced the menu bar and refreshed how the lists look. Now we mark selected items with a check, or we don't use the check at all. But somehow we forgot to revise the mention-based lists. We should come back to them someday, because now it's the only place with active/selected elements which look like that.

https://github.com/user-attachments/assets/2c122b56-33d4-4045-8421-a0d8f1916a05

7.  The mechanism for inserting emojis is not always very intuitive for me. When inserting an icon, the selection disappears (sometimes we use a fake one in such a case). If I select some text, I would expect it to be replaced by the icon, not for the icon to be inserted before the selection.

https://github.com/user-attachments/assets/0f9d92da-8480-4eb0-8221-b2ee184a2f23

**Comment by pomek** [comment]
As we decided to implement a custom UI (#17596), there is the initial work that we will aim to improve.

<img width="411" alt="Image" src="https://github.com/user-attachments/assets/c82c978a-8b64-467a-a852-120624e374cc" />

So, the issue is no longer valid in the context of the component we discussed.
