### ISSUE TITLE
Remove build step to customize CKEditor

### ISSUE THREAD

**Issue by chimon2000** [ckeditor/ckeditor5#1774]
## Is this a bug report or feature request? (choose one)

🆕 Feature request 

## 💻 Version of CKEditor

CKEditor5

## ✅ Expected result

Ability to add plugins to CKEditor w/o needing to drastically alter application architecture or create separate packages just to build CKEditor.

## ❎ Actual result

Using a React application as an example, you need to eject from CRA and add build configurations for CKEditor along with your plugins, or you need to create a separate project for the CKEditor build either in a separate repository or a monorepo.

## 📃 Other details that might be useful

For context, there are quite a few rich editor libraries that allow you to extend them without adding significant overhead to the process:

[Editor.js](https://editorjs.io/the-first-plugin)
[QuillJS](https://quilljs.com/guides/how-to-customize-quill/)
[TinyMCE](https://www.tiny.cloud/docs/advanced/creating-a-plugin/)
[Rooster.js](https://github.com/microsoft/roosterjs)
[ProseMirror](https://prosemirror.net/)

**Comment by Reinmar** [comment]
Hi! Sorry for not replying for over a month – many of us were in a holiday mode.

The short answer for what are the reasons why adding plugins to CKEditor 5 cannot be achieved by a simple concatenation is that our experience from the past (CKEditor 3-4 allows that). There are significant tradeoffs when you try to enable that – you either build your own module system (and sometimes a bundler) with lost of hacks under the hood (which sometimes backfire at you) or you create a code in a monolithic way, with little code reuse and finally make your builds extremely bloated (containing a lot of unnecessary code).

I haven't yet seen an elegant solution to that other than keeping your code modular and involving a bundler (like webpack).

That said, we faced the "can't easily add plugin to a build" issue ourselves and we know tgat it affects a part of our community too. Not everyone, because in many projects webpack is a standard, but still some significant part. The problem here turns out to be not the legacy envs where people don't yet use webpack, but rather frameworks envs because they come with an already really complicated webpack configs and developers are not happy to change those.

Therefore, we'll be looking for solutions in #667 very soon. This is a big priority for us and there's a chance that we'll be doing significant changes to workaround those issues. We still want to stay as modular as possible, but perhaps we can do something to reduce the pain significantly. That said, it will take some time for us to implement the solution.

I'm closing this ticket in favor of #667.
