### ISSUE TITLE
Remove all mentions of <textarea> from the docs

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1806]
Extracted from https://github.com/ckeditor/ckeditor5/issues/1591#issuecomment-470471820 to not loose track of it.

Also, I'd remove all mentions of `<textarea>`from the docs, except two pages where it makes sense: 

* https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html#automatic-integration-with-html-forms
* https://github.com/ckeditor/ckeditor5-code-block/blob/dbbe7627cd9877b7c6dd9468fa3d010aaaed9ed4/docs/_snippets/features/code-block.html#L1 (workaround for cksource/umberto#838)

**Comment by mlewand** [comment]
Recently we added a second case where it was intentional: https://github.com/ckeditor/ckeditor5-code-block/blob/dbbe7627cd9877b7c6dd9468fa3d010aaaed9ed4/docs/_snippets/features/code-block.html#L1 that is till cksource/umberto#838 is resolved.

**Comment by wwalc** [comment]
Humm instead of removing all mentions of `<textarea>` from docs, shouldn't we make it clear/warn users in the documentation, e.g. in places such as:

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html

that the only editor that supports replacing textareas is the ClassicEditor?

and maybe in `create()` API docs for all editors make it clear what elements can be replaced and that textarea is not suported, e.g.:
 * https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-inline_inlineeditor-InlineEditor.html#static-function-create
 * https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-decoupled_decouplededitor-DecoupledEditor.html#static-function-create (see what the user linked in https://stackoverflow.com/questions/55142625/creating-decouplededitor-passing-textarea-as-parameter)
?

What I'm afraid of is that at least until 2023 (or even longer) it may be quite a common case that people will be upgrading from CKEditor 4 and replacing a textarea will be one of the use cases. CKEditor 4 had an inline editor, some may confuse their document-targeted CKEditor 4 setup with a decoupled document editor build (because it has more features by default) and so on.

If this information is deeply hidden (e.g. https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html#automatic-integration-with-html-forms is the 8th article in the documentation, and it will be read by users after they actually initialized the editor, definitely after quick start and installation/basic API), then they will simply make this mistake all the time.

**Comment by mlewand** [comment]
@wwalc I don't think this is a necessity as we have pretty decent error explicitly saying what's wrong. See this ["Error shown when creating CKE5 balloon editor on top of textarea" codepen](https://codepen.io/mlewand/pen/MWYggvY).

I doubt that someone porting CKE4 to CKE5 will just swap the API (which is different) and will not open a webpage to see that everything works. And if he or she will do that, the error will be right there.

We need to balance simplicity of the documentation and the amount of aside notes/remarks.

The only thing that I would change is [error-editor-wrong-element error code docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-editor-wrong-element) to mention a possible solution, which is that you can simply change `textarea` to a `div`. Because right now it goes to great lengths to explain what the problem is, but doesn't mention the obvious solution.
