### ISSUE TITLE
How can I insert link at cursor position use the insertContent

### ISSUE THREAD

**Issue by hhlingyoko** [ckeditor/ckeditor5#1811]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

v5, DecoupledEditor

## 📋 Steps to reproduce

I'm trying to  insert link to the document , but i don't want  to use the toolbar‘s’ link .

```
             this.editor.model.change( writer => {
               const link = writer.createElement('link', {
                 href: info.file_path,
               });

              writer.insertText( info.file_name, link );
              this.editor.model.insertContent( link, this.editor.model.document.selection );
            });
```

Why it doesn't work ? I also want to  insert code to  the document, can i use this way to insert ?
 Thanks

**Comment by Mgsy** [comment]
Hello, your code doesn't work, because you try to create a `link` element which is not a proper element. In CKEditor 5 links are represented in the model as `linkHref` attributes, so this attribute should be set on the text.

Please, try this:

```js
this.editor.model.change( writer => {
    const link = writer.createText( info.file_path );

     writer.setAttribute( 'linkHref', info.file_path, link );
     this.editor.model.insertContent( link, this.editor.model.document.selection );
} );
```

> I also want to insert code to the document, can i use this way to insert ?

Currently, it's not possible to insert code blocks to the editor, but there is an [open discussion](https://github.com/ckeditor/ckeditor5/issues/436) about this feature, feel free to jump in and write about your expectations for this feature. However, you can use [inline code feature](https://ckeditor.com/docs/ckeditor5/latest/api/module_basic-styles_code-Code.html).

**Comment by hhlingyoko** [comment]
@Mgsy  thank you very much
