### ISSUE TITLE
Cant understood how to fix model-nodelist-offset-out-of-bounds

### ISSUE THREAD

**Issue by nikitalarionov** [ckeditor/ckeditor5#1837]
💻 Version 12.1.1 of CKEditor

I have this simple plugin, a modified version of example from CKEditor5 documentation:
[Source code](https://gist.github.com/nikitalarionov/61d56a0dacf8d63d8474854938b94643)

I tried to use helper viewToModelPositionOutsideModelElement, but it disallows me to edit text inside inline widget block (DailyNoteText). Error still occurs, i don't know how to fix that.

Example:

![image](https://user-images.githubusercontent.com/1798035/60186239-0cae9480-9834-11e9-8b4c-7409dd79a547.png)

Maybe someone can help? How to fix this problem?

**Comment by Mgsy** [comment]
Hello, it's hard to spot the cause of your issue without seeing the code. Please, attach a code sample of your plugin.

**Comment by Mgsy** [comment]
@jodator, can you investigate the problem?

**Comment by jodator** [comment]
> I tried to use helper viewToModelPositionOutsideModelElement, but it disallows me to edit text inside inline widget block (DailyNoteText).

I don't think that we have a clear solution to this. AFAIR we are aware of typing inside inline widget issue. The only use case that we have tested and validated is an inline widget that is not editable.

ATM you can try to change the UX of editing such note in a different way - balloon, some popup, etc.

Other than that this error is due to improper position mapping and some helper method is needed to be added for your inline widget:

```js
editor.editing.mapper.on( 'viewToModelPosition', ( evt, data ) => {
    const viewPosition = data.viewPosition
    // Map position inside editable inline widget based on viewPosition
    data.modelPosition = ... ;
} );
```
