### ISSUE TITLE
Review editor creation and base architecture

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#185]
Because engine introduced both data (https://github.com/ckeditor/ckeditor5-engine/issues/432) and editing (https://github.com/ckeditor/ckeditor5-engine/issues/288) controllers, all creators need to be updated so the editor will use engine for real.

I am not sure if it makes sense to update creators, they need to be changed anyway. We could take this opportunity to apply change introduced here: https://github.com/ckeditor/ckeditor5-design/issues/140

**Comment by Reinmar** [comment]
One followup reported: https://github.com/ckeditor/ckeditor5/issues/188.

**Comment by Reinmar** [comment]
During the course of action we were able to plug all engine controllers, but we weren't really able to clean up the picture. We decided that it's a high time to do the bold move and we begun working on https://github.com/ckeditor/ckeditor5-design/issues/140 – the editor class must be subclassable and creators must be removed. 

The outcome is really great. No more code smell... but now we need to update lots of tests in multiple repositories :).

**Comment by Reinmar** [comment]
OK... this issue required a huge amount of changes all across our code base. The `package.json` configuration shows this quite well, but even more issues has been closed than that, because we managed to close some already:

```js
    "ckeditor5-basic-styles": "ckeditor/ckeditor5-basic-styles#t/1",
    "ckeditor5-creator-classic": "ckeditor/ckeditor5-creator-classic#t/9",
    "ckeditor5-delete": "ckeditor/ckeditor5-delete#t/6",
    "ckeditor5-engine": "ckeditor/ckeditor5-engine#t/452",
    "ckeditor5-enter": "ckeditor/ckeditor5-enter#t/12",
    "ckeditor5-paragraph": "ckeditor/ckeditor5-paragraph#t/1",
    "ckeditor5-theme-lark": "ckeditor/ckeditor5-theme-lark",
    "ckeditor5-typing": "ckeditor/ckeditor5-typing#t/1",
    "ckeditor5-ui": "ckeditor/ckeditor5-ui#t/37",
    "ckeditor5-ui-default": "ckeditor/ckeditor5-ui-default",
    "ckeditor5-undo": "ckeditor/ckeditor5-undo#t/5",
    "ckeditor5-utils": "ckeditor/ckeditor5-utils",
```

Nevertheless, it's time to conclude this. I really think that this was a massive success. Not only had we initialised a real editor finally, with all the components in place, but also we significantly improved the architecture.

The status of things is that:

1. Editor works (see e.g. http://tests.ckeditor.dev:1030/build/amd/tests/creator-classic/manual/classic):

![editor2](https://cloud.githubusercontent.com/assets/156149/15681830/32363fc0-275b-11e6-929c-252d9831889a.png)

There's basic typing, delete, enter, bold, italic, formats (not added to the sample yet) and undo (although, not functional at the moment). The editor is not yet usable, because there are at least 4 or 5 important issues to iron out, but we'll focus on that during the next 2 days.
2. The changes made in other repositories are not complete yet. Some misses tests (undo, typing). Some tests are failing (engine tests need to be updated). Some just don't work properly (undo). We'll work on this during the next 2 days as well.
3. Most features are incomplete (or in other words – very simplistic), because initially we focused on a very basic implementations. This will be improved in the future.

However, I feel that it's high time to merge this branch anyway, so we can all finally see and feel the new code and real editor. I'll be merging this branch to master in a couple of minutes. Part of the reviews were already done by @pjasiun because we worked on most changes together and the rest will be done later on.

Thanks guys for all the work! And huge thanks for @pjasiun for all the ideas (and of course work :P) which made the API so much nicer.
