### ISSUE TITLE
Custom plugin cursor at wrong index

### ISSUE THREAD

**Issue by MBERoxit** [ckeditor/ckeditor5#1913]
## Is this a bug report or feature request? (choose one)

Bug

## 💻 Version of CKEditor

ckeditor5

## 📋 Steps to reproduce

Im building a new plugin and im having an issue with the cursor/selection.
I used the SimpleBox tutorial and altered it to my needs

The simplebox plugin is using 1 inputfield per line. 2 fields: title and description
Each inputfield is translated in the view into a "div" or a "h1".
No cursor problems here.
When "jumping" from the title to the description the cursor will be positioned at index 0 (description)

What I really want is 2 inputfields at a row.
Instead of creating "div/h1" elements I specified in the conversion functions to use a "span"
Thats works perfectly fine.
The issue that arrises here, is when "jumping" from from title to description, the cursor will be positioned at index 1 (instead of 0)
I cannot set the cursor to position 0 in description, because it will jump back to the previous field title.

When using divs, there are no issues

**Comment by Mgsy** [comment]
Hello, can you share you code, so we'll be able to see what's going on?

**Comment by MBERoxit** [comment]
Hi Mgsy

I followed the tutorial
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html

I changed the html-elements for title and description into a span

        conversion.elementToElement( {
            model: 'simpleBoxTitle',
            view: {
                name: '**span**',
                classes: 'simple-box-title'
            }
        } );

        conversion.elementToElement( {
            model: 'simpleBoxDescription',
            view: {
                name: '**span**',
                classes: 'simple-box-description'
            }
        } );

With help of the ckeditor5-inspector you can easily spot the cursor position (selection).
When switching from title to description(with arrow-keys), the cursor will not start at index zero, but index 1 in the description field

**Comment by Mgsy** [comment]
@jodator, can you take a quick look at it?

**Comment by jodator** [comment]
@MBERoxit  I think that you shouldn't use inline elements (`<span>`) for block but nothing prevents you from doing it :) I've tested this by changing the implementation of sample from `<div>` to `<span>` by replacing all `div` to `span` in existing upcast and downcast converters. It looks like everything works (I had to add `display: block` to the `<spans>`):

![Peek 2019-08-05 14-36](https://user-images.githubusercontent.com/247363/62465194-9ab06000-b78e-11e9-875a-624009f2c4bd.gif)

It looks like you replaced the implementation of downcast converters with a two-way helpers which add a downcast and upcast converter (`conversion.elementToElement()` instead of `conversion.for( 'upcast')`). When using widgets with editable fields you must use the widget helpers to properly initialize them:
Below is the code changed for title (the description was changed the same way):

```js
conversion.for( 'upcast' ).elementToElement( {
	model: 'simpleBoxTitle',
	view: {
		name: 'span',
		classes: 'simple-box-title'
	}
} );
conversion.for( 'dataDowncast' ).elementToElement( {
	model: 'simpleBoxTitle',
	view: {
		name: 'span',
		classes: 'simple-box-title'
	}
} );
conversion.for( 'editingDowncast' ).elementToElement( {
	model: 'simpleBoxTitle',
	view: ( modelElement, viewWriter ) => {
		// Note: You use a more specialized createEditableElement() method here.
		const span = viewWriter.createEditableElement( 'span', { class: 'simple-box-title' } );

		return toWidgetEditable( span, viewWriter );
	}
} );
```

**Comment by MBERoxit** [comment]
@jodator 

`display:block` doesnt work for me, because I'd like to have two input fields in a row.
I also used the same conversion code like you did

I solved my issue, by adding a space into the 2nd inputfield. It feels like a workaround, but the custom plugin works fine now

Thanks for your answer.
