### ISSUE TITLE
How to add or customize classes to editor component?

### ISSUE THREAD

**Issue by keatwei** [ckeditor/ckeditor5#1966]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 💻 Version of CKEditor 5 v 12.3.1

Only able to add html classes to heading only
https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#configuring-custom-heading-elements

1. How do I customize and add class to blockquote, image, table, list, and etc?

`blockQuote:{
		view: { name: 'blockquote', classes: 'blockquote' }
	},
	heading: {
        options: [
			{ model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
			{ model: 'lead', view: { name: 'p', classes: 'lead' }, title: 'Lead', class: 'lead' },
			{ model: 'heading1', view: { name: 'h2', classes: 'h2' }, title: 'Heading 1', class: 'h2' },
			{ model: 'heading2', view: { name: 'h3', classes: 'h3' }, title: 'Heading 2', class: 'h3' },
			{ model: 'heading3', view: { name: 'h4', classes: 'h4' }, title: 'Heading 3', class: 'h4' },
        ]
    },`

**Comment by Mgsy** [comment]
@jodator, is there a quick way to achieve it?

**Comment by jodator** [comment]
There's no such quick setup for other features like we have for headings in most cases.

- For image, there's [image styles plugin](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#configuring-image-styles) which allows adding custom styles.
- for tables it is a bit trickier but you can for instance preserve existing classes: https://github.com/ckeditor/ckeditor5-core/blob/poc/customfigureattributes/tests/manual/customfigureattributes.js#L26
- for other features it would require to write custom converters for each case, ie:

```js
editor.conversion.elementToElement( { 
	model: 'blockQuote', 
	view: { 
		name: 'blockquote',
		classes: 'blockquote' 
	} 
} );
```

but since some converters do more than that I think that safer would be "incremental" converter for already converted elements:
```js
editor.conversion.for( 'downcast' )
	.add( dispatcher => dispatcher.on(
		'insert:blockQuote',
		( evt, data, conversionApi ) => {
			const viewElement = conversionApi.mapper.toViewElement( data.item );

			if ( viewElement ) {
				conversionApi.writer.addClass( 'foo', viewElement );
			}
		},
		// Use the lowest priority to make sure that this will be run
		// after default converters.
		{ priority: 'lowest' }
	) );
```
