### ISSUE TITLE
Update "bugs" in package.json to point to ckeditor5

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1988]
We plan to merge issue trackers into one. Let's do this change in package.jsons already so it's up to date on npm.

**Comment by Reinmar** [comment]
@pomek, let's have a quick call about this.

**Comment by pomek** [comment]
After introducing proposed changes, the changelog generator will contain invalid URLs to issues in changelog entries.

https://github.com/ckeditor/ckeditor5-dev/blob/28e3b533d9667cbfda45f09a37e103f171649ff0/packages/ckeditor5-dev-env/lib/release-tools/utils/transform-commit/transform-commit-utils.js#L80

Instead of parsing `pkg.bugs` entry, we can take the value from `pkg.repository`.
