### ISSUE TITLE
Link is removed from a to-do list after transforming it to a list

### ISSUE THREAD

**Issue by RyszardB** [ckeditor/ckeditor5#2009]
🐞 Bug report

## 💻 Version of CKEditor

CKEditor 5 v12.14.0

## 📋 Steps to reproduce
1. Select the whole to-do list item.
1. Add a link.
1. Select the whole to-do list.
1. Transform it into a regular list.

## Current result
The link has been removed; after clicking on the item with the removed link, the editor crashes.

## GIF
![bug1](https://user-images.githubusercontent.com/17498197/63944465-d67ad480-ca71-11e9-9e82-fda7c771fead.gif)

**Comment by Mgsy** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/1980.

**Comment by jodator** [comment]
@Mgsy I think that this is a different issue (maybe fixing #1980 will fix this to - and vice versa). Here you have an error when todo list is changed to a normal list. The #1980 was solely about ballon triangle thingy location).

**Comment by Mgsy** [comment]
>@Mgsy I think that this is a different issue (maybe fixing #1980 will fix this to - and vice versa). Here you have an error when todo list is changed to a normal list. The #1980 was solely about ballon triangle thingy location).

Okay, so this issue should be checked while fixing #1980.

**Comment by jodator** [comment]
There's something wrong going on when the first element in the todo-list is not a `<label>`. The converters/logic expects that the first child of a `<li>` is a `<label>` while due to the conversion of text attributes (bold, link, etc) it might be something different (like `<strong>`).

This causes also this funny bug (typing at the beginning of list item):
![Peek 2019-09-16 13-58](https://user-images.githubusercontent.com/247363/64956207-5edae100-d88a-11e9-9e19-437f16062130.gif)
