### ISSUE TITLE
Inline editor not working when rendered inside an iframe rendered by VueJS

### ISSUE THREAD

**Issue by ligne13** [ckeditor/ckeditor5#2023]
Hi,

please check this fiddle : https://jsfiddle.net/djsuperfive/Lujk9xb6/51/

This is a Vue app showing 3 examples of CKEditor integrations : 

1. standard inline editor using the officialVueJS component (working)
2. classic editor rendered inside an iframe rendered within the Vue app using this method : https://jsfiddle.net/djsuperfive/L7dvm1rb/1/ (working)
3. inline editor rendered inside an iframe also rendered within the Vue app. (NOT working)

The 3rd example is not working: the inline menubar is not displayed when clicking into the editable area.
The focus does not seem to be detected when clicking the are (the ck-blurred class is not replaced by the ck-focused class, like in the 1st example).

Any idea why ?

thanks

**Comment by Mgsy** [comment]
cc @oleq

**Comment by oleq** [comment]
[The Inline Editor works just fine in an iframe](https://codepen.io/anowodzinski/project/editor/ZPWdKG). So we know there's something wrong with Vue here.

I'm not sure how this `<i-frame class="my-frame">` works but IMO the problem is it touches (probably re-renders) the editable area of the editor **after** the editor initializes on it. This explains why Classic Editor works just fine – it creates own editable element and just hides the original element used to load the initial content.

Could you use the official CKEditor component for Vue in a standard scenario (no Vue–generated `<i-frame>` but plain HTML `<iframe>` like in my sample) and see if that helps, @ligne13?
