### ISSUE TITLE
Cannot set property 'enumerable' of undefined

### ISSUE THREAD

**Issue by winzig** [ckeditor/ckeditor5#2040]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

We are seeing this error a lot: **Cannot set property 'enumerable' of undefined**

We were also seeing this as far back as 11.2. 

Sentry.io shows the stack as follows:

<img width="686" alt="Screen Shot 2019-09-11 at 2 43 13 PM" src="https://user-images.githubusercontent.com/127062/64738114-3f674100-d4a3-11e9-83f0-502715092ff3.png">

## 💻 Version of CKEditor

12.4 Balloon build (same error was also happening in 11.2)

## 📋 Steps to reproduce

I am not able to reproduce it myself, but we have thousands of users on our site, and via Sentry.io, we are able to see the error happening quite a lot, thousands of times. We've seen it on multiple browsers, but mostly Safari.

**Comment by winzig** [comment]
Here's the Sentry stack trace with the last frame expanded:

<img width="683" alt="Screen Shot 2019-09-11 at 3 12 58 PM" src="https://user-images.githubusercontent.com/127062/64739333-a63a2980-d4a6-11e9-81d3-43c21c27b843.png">

**Comment by Reinmar** [comment]
The `mix()` function is only used right after a class definition to mix in a mixin into it. So, it's never used with any params – anything that's variable. It's only used with imported values.

Did you, perhaps, made webpack split the code somehow?

**Comment by winzig** [comment]
Any other ideas?

**Comment by Reinmar** [comment]
Hm... no, unfortunately not. The existence of the `translations` folder makes no difference. We don't hotload anything. No magic involved. 

Unfortunately, I really can't tell more. Without being able to reproduce this it's just a super weird thing that shouldn't ever happen.

**Comment by ma2ciek** [comment]
> The mix() function is only used right after a class definition to mix in a mixin into it. So, it's never used with any params – anything that's variable. It's only used with imported values.

The whole stack trace looks correct to me.

`view/node.js call at line 388` points to the `mix( Node, EmitterMixin );` so to the real execution of the `mix` function. And the function is correct from my point of view.

@winzig, Do you transpile the code of the CKEditor 5 build? I guess that an incorrect traspilation of ES6 features can easily point to such weird errors. Or maybe some of your libraries override JS native functions like `Object.getOwnPropertyDescriptor()` / `Object.getOwnPropertyNames()`.

 > I am not able to reproduce it myself, but we have thousands of users on our site, and via Sentry.io, we are able to see the error happening quite a lot, thousands of times. We've seen it on multiple browsers, but mostly Safari.

Does it happen on the latest browser versions?

**Comment by winzig** [comment]
I would estimate 95% of the errors are occurring on Mobile Safari running iOS 12. I also saw some from Chrome on iOS (i.e. using Safari's rendering engine under the covers). 

@ma2ciek We reference CKEditor.js directly from our page with no transpiring, manipulation, packing or anything. However, we do use [BuildBundlerMinifier](https://www.nuget.org/packages/BuildBundlerMinifier/2.8.391) to bundle/pack most of the rest of our JS, including: jquery, font awesome, jQuery plugins, bootstrap, a bootstrap theme, is.min.js, vue.js, clipboard.js, video.js, moment.js, and a few others. 

Is there something I should look into further to address your idea regarding:

> Or maybe some of your libraries overrides JS native functions like Object.getOwnPropertyDescriptor() / Object.getOwnPropertyNames().

**Comment by Reinmar** [comment]
> I would estimate 95% of the errors are occurring on Mobile Safari running iOS 12. I also saw some from Chrome on iOS (i.e. using Safari's rendering engine under the covers).

So, to me, the biggest chance is that this is a browser bug. This code is executed immediately when you load the file. There's no logic involved. So, it's run on every client that opens your app. If there would be a problem on CKEditor 5 side, then it would crash on all browsers.

If you want to debug it further, I think you need to find a way to reproduce and isolate the issue. Did you try opening the page on iOS 12 and checking how it works? That would be the very first thing to do here.

The second step would be to add `try/catch` around this bit of code and in `catch()` log the context. What's `sourceDescriptor`, `mixin`, `key`, etc. This may shed some light on this.

Finally, since this is the only report about this issue, I'm afraid that there's something specific in your app which triggers it. Can be some other dependency. Can be the way home some things are loaded. Can be your code. It's really hard to tell. If you'll be able to reproduce the issue you can start isolating it by disabling other things and leaving CKE5 alone with a simple HTML. At this stage, we could reproduce it.

**Comment by Reinmar** [comment]
> Is there something I should look into further to address your idea regarding:
> 
> > Or maybe some of your libraries overrides JS native functions like Object.getOwnPropertyDescriptor() / Object.getOwnPropertyNames().

The easiest way is to check what you can see on the console when you do this:

![image](https://user-images.githubusercontent.com/156149/65114497-33b9d400-d9e7-11e9-8a84-0e31af32572b.png)

**Comment by winzig** [comment]
@Reinmar Thanks for the reply. In regards to `getOwnPropertyDescriptor` and `getOwnPropertyNames`, they both are indicating they are still native code. 

I will move forward with trying to debug via the try/catch wrapper, as I'm unable to reproduce the problem so far using iOS 12.

**Comment by winzig** [comment]
@Reinmar After wrapping with try/catch and logging sourceDescriptor, mixin, and key to Sentry, I now get this additional info:

<img width="645" alt="Screen Shot 2019-09-19 at 8 51 07 AM" src="https://user-images.githubusercontent.com/127062/65260154-ebc4ab00-dad3-11e9-8281-715154836887.png">

The JSON from the mixin variable:

```
{
  "on": "[Function: on]",
  "off": "[Function: off]",
  "stopDelegating": "[Function: stopDelegating]",
  "fire": "[Function: fire]",
  "stopListening": "[Function: stopListening]",
  "delegate": "[Function: delegate]",
  "listenTo": "[Function: listenTo]",
  "once": "[Function: once]"
}
```

**Comment by winzig** [comment]
I take it the issue here is for some reason `key` is an `Object` and not a `string` name of a property that should be in `mixin`.

**Comment by Reinmar** [comment]
Keys are a concatenation of strings returned by [`getOwnPropertyNames()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames) and symbols returned by [`getOwnPropertySymbols()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols). So there should be values of type `string` and `symbol`. Nothing else.

Also, since we just used `getOwnProperty*`, then using `getOwnPropertyDescriptor()` on the same key **must work**.

So, the last thing you need to check is whether `Object.getOwnPropertySymbols` is also a native function. There's actually a bigger chance here that you have it overriden by some polyfill. In which case, that would be this polyfill's bug.

If it's a native function, then you're hitting a browser bug. And there's nothing else you can do than wrapping this with `try/catch` and just "muting" the issue.

**Comment by winzig** [comment]
Thanks @Reinmar, I revised the debugging code to also dump what is being returned for  getOwnPropertyNames() and  getOwnPropertySymbols() for `mixin`, and trying to get it to JSON.stringify() `key` so that I can see what's inside it. 

Unfortunately that dumped so much that it looks like Sentry truncated it. However, based on what I did see, it's possible that `key` is not an `Object`, but rather is a string with the value `"Object"`:

<img width="650" alt="Screen Shot 2019-09-19 at 1 20 38 PM" src="https://user-images.githubusercontent.com/127062/65278131-6eac2c80-daf9-11e9-8876-4c91967759fe.png">

I've confirmed that the `getOwnProperty*` methods in use all report as using native code. So in that case, I guess it is a browser bug. I'll close the for now, unless I'm able to obtain any other useful info.

**Comment by winzig** [comment]
I've seen another trace came in with more info. I can confirm that `key` is not an Object, but a string with value of `"Object"`. The `getOwnPropertySymbols(mixin)` is returning an empty array. And the first element coming back from getOwnPropertyNames is the string `"Object"`.

I'm still struggling to understand exactly what the browser bug is here. Is it that `getOwnPropertyNames` for `mixin` is returning `"Object"`, but `getOwnPropertyDescriptor` doesn't have a descriptor for `"Object"`? I don't know enough about these JS methods.

I'm also surprised this isn't affecting more CKEditor5 users given the popularity of mobile safari 12.

**Comment by ma2ciek** [comment]
Interestingly these are the keys of the `window` object. So the `Object.getOwnPropertyNames( mixin )` for a mixin, which is the following object:

```json
{
  "on": "[Function: on]",
  "off": "[Function: off]",
  "stopDelegating": "[Function: stopDelegating]",
  "fire": "[Function: fire]",
  "stopListening": "[Function: stopListening]",
  "delegate": "[Function: delegate]",
  "listenTo": "[Function: listenTo]",
  "once": "[Function: once]"
}
```

returns rather `Object.getOwnPropertyNames( window )`.

Even for a browser bug this behaviour is super strange. But IDK if this could be caused by something else.

**Comment by ma2ciek** [comment]
I'd check also a simpler version of the mix function, maybe the bug is caused by the rest parameter or some other things:

```js
function mix( baseClass, mixin ) {
	for ( const key of Object.getOwnPropertyNames( mixin ) ) {
		if ( key in baseClass.prototype ) {
			continue;
		}

		const sourceDescriptor = Object.getOwnPropertyDescriptor( mixin, key );
		sourceDescriptor.enumerable = false;

		Object.defineProperty( baseClass.prototype, key, sourceDescriptor );
	}
}
```

**Comment by winzig** [comment]
@ma2ciek I'm going to try these changes in series to see which, if any, resolves it. First I'll just eliminate the use of the `...mixins` and `forEach` patterns and see what happens.

**Comment by winzig** [comment]
We continue to see this error from ckeditor (via Sentry logs) to this day, and have yet to figure out the cause.

**Comment by LeComptoirDesPharmacies** [comment]
Hi @winzig @Reinmar @ma2ciek,

Same error here logged by Sentry for a user on Safari 13.5.1.
![image](https://user-images.githubusercontent.com/25615113/93364618-0ea1b080-f849-11ea-9e7e-ce64319d006f.png)

Yours faithfully,
LCDP
