### ISSUE TITLE
Generate documentation using Docs-Builder

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#243]
At this moment, works on [Docs-Builder](https://github.com/cksource/docs-builder) are still in progress. 

That package is being tested with CKEditor5 all the time, so I've decided to create a ticket for that. It allows creating a branch and pushing the latest changes.

### [How does Docs-Builder work?](https://github.com/cksource/docs-builder/issues/1#issue-161850553)

The whole mechanism isn't too complicated but can be a little large. We assume that each repository contains two directories:

1. `docs/samples` - Sample which are files with extensions: `*.html`, `*.md`, `*.js`. Sample files are similar to manual tests. The `*.js` files contain part of test and part of code which initializes the editor,
2. `docs/guides` - Guides which are files with extension `*.md`.

Before starting `docs-builder`, we have to collect all these files to one place. Module for collecting files will be used few times:

- From `build` an editor point of view: collect samples and run them as automated tests (in a local environment),
- From `bundler` point of view: collect samples, make a configuration object for bundler (based on collected files) and build a bundled editor. It allows testing samples in a production environment.

When all files are collected, `docs-builder` will do a magic stuff. The whole concept of `magic stuff` will be described in the future in `docs-builder` repository.

Related tickets:
* https://github.com/ckeditor/ckeditor5-design/issues/150
* https://github.com/cksource/docs-builder/issues/1

**Comment by pomek** [comment]
After extracted packages (from the main repository to smaller ones), I have some troubles with Bundler.

Before my changes, the Bundler worked on hardcoded paths. It didn't allow running the mechanism a few times at the same time. I decided to rebuild it. After some changes, the mechanism could be running multiple times and the built editors won't overrides themselves. 

Unfortunately, after extracting to smaller packages, I have to figure out one more time the way for the idea above.

**Comment by oskarwrobel** [comment]
According to https://github.com/ckeditor/ckeditor5/blob/de3325ac20ac488de59b334806cb368494b978fd/dev/tasks/bundle/tasks.js#L43-L331. I think we should not mix sample generator with bundling. Bundle tasks after extracting to separate repository are no longer a gulp tasks. I understand it as a set of utils for bundling and minifying. In `ckeditor5` we register those utils as a gulp tasks, but sample generator could require it and use like it want.

I mean something like that:
```javascript
const bundleTasks = require( 'path/to/bundle/tasks.js' );
let bundles = [];

function createBundle( config ) {
    return bundleTasks.generate( config ).then( bundleTasks.minify( config ) );
}

for ( let sampleConfig of samples ) {
    bundles.push( createBundle( sampleConfig ) );
} 

return Promise.all( bundles );
```

But first bundle output needs to be configurable :) and you already did it.

**Comment by pomek** [comment]
The whole problem with building editors for samples has been resolved. 

Smaller tasks from `ckeditor5-dev-bundler-rollup` repository:

- https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/issues/8 - https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/issues/9

Allowed to transform sample for bundle's configuration and use them for bundler.

**Comment by Reinmar** [comment]
We need to decide how to split the functionality into multiple packages. 

The packages:

* dev-compiler
* dev-bundler-rollup
* dev-docs
* dev-tests

The functionality to cover:

1. Creating editor bundle configurations based on passed sample files.
2. Bundling editors:
  1. for release testing purposes,
  2. for production version of documentation.
3. Preparing HTML of samples (e.g. for documentation, JSFiddle, other websites which will want to use those samples):
  1. in dev mode – using source editor,
  2. in production mode – using bundled editor,
4. Building documentation (combining samples, guides and API).
5. Compiling release tests.

Proposal:

1. -> dev-docs. Bundler shouldn't know about it. Will be used by dev-docs (for *2.2.*) and dev-tests (for *2.1.*).
2. -
  1. -> dev-tests
  2. -> dev-docs
3. -> dev-docs
4. -> dev-docs
5. -> dev-tests. Though decision because compiler already compile normal tests as this is simply parts of its job. But running release tests require knowledge of the bundler and the compiler should not have it.

Dependency tree:

* dev-compiler: dev-utils
* dev-bundler-rollup: dev-utils
* dev-docs: dev-compiler, dev-bundler-rollup, dev-utils
* dev-tests: dev-docs, dev-compiler (in the future, once it will contain the whole test env), dev-bundler-rollup, dev-utils

**Comment by Reinmar** [comment]
So, there are 2 packages to create: dev-docs and dev-tests. The second one right now will not be used because it will contain only the code for testing releases, which we created to prove that this is doable at all. We will start using this package when we'll work on porting the testing env to Karma, which will require some additional code.

**Comment by Reinmar** [comment]
OK, first version of docs builder integration landed on master. Now, the work on the docs builder will continue.
