### ISSUE TITLE
Manual test for editor-classic

### ISSUE THREAD

**Issue by seasonxuan** [ckeditor/ckeditor5#259]
I manually test classic editor with bender in browser.
The url is `http://localhost:1030/build/amd/tests/editor-classic/manual/classic` .
I init editor twice, and then I expect to destroy both two editor. But actually,  just the first one will be destroy!

**Comment by Reinmar** [comment]
Thanks for the report. I've noticed it myself too, but that's only because this test's code is very simple. However, the TC says: "click init, click destory". This test doesn't check what happens if you click init more and its code doesn't have to behave reasonably in this case.

In other words – it's not an editor bug, it's just how this test is coded.
