### ISSUE TITLE
The output HTML should use <figure>

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#3194]
The output should match the format proposed by http://ckeditor.github.io/editor-recommendations/features/table.html

**Comment by shamseerahammedm** [comment]
@Reinmar `figure` tag is adding `extra margins`, is there any way to `add inline styles` to figure tag ? the extra styles are added by the browser and its breaking my markup because of the weird spacing 
![Capture](https://user-images.githubusercontent.com/20143226/107637674-865af680-6c94-11eb-86de-a3fabb01f931.PNG)

**Comment by shahzebgit** [comment]
@Reinmar @jodator I have some inline styles on `<table>` and they're getting applied on `figure` while `editingDowncast`  which are not supported on `<figure>` I assume 
So is there anyway that I can get those styles at-least on table tag after `EditingDownCast`?

example:
After editingDowncast(getData)
```
 <figure class="table" style="font:10pt Times New Roman, Serif;width:100%;" cellpadding="0" cellspacing="0">
```
Loading the data as(setData)
```
<table style="font:10pt Times New Roman, Serif;width:100%;" cellpadding="0" cellspacing="0">
```

**Comment by MoiseScalzo** [comment]
> @Reinmar @oleq @jodator `figure` tag is adding `extra margins`, is there any way to `add inline styles` to figure tag ? the extra styles are added by the browser and its breaking my markup because of the weird spacing.
> 
> Since im taking the output and sending it as a mail, i cant remove style it with `class` , so i need to add `inline` styles or Is there any way to `disbale` wrapping with figure tag?
> 
> Browser : Chrome ![Capture](https://user-images.githubusercontent.com/20143226/107637674-865af680-6c94-11eb-86de-a3fabb01f931.PNG)

Any solution for this?

**Comment by jeremylcarter** [comment]
I am looking for a solution to these margins as well.

**Comment by raul-rtl** [comment]
@Witoso do you know how can I set PlainTableOutput on the strapi plugin?

**Comment by Witoso** [comment]
@raul-rtl you would need to modify the Strapi's integration code and add the plugin to the plugins lists:

 https://github.com/ckeditor/strapi-plugin-ckeditor/blob/a30d17e8155df0e6cfd4915d09981125fd015262/admin/src/components/CKEditorInput/Configurator.js#L29C1-L52

**Comment by i14pl** [comment]
> If someone is struggling with `figure` in email editing for example, we have a [PlainTableOutput](https://github.com/ckeditor/ckeditor5/blob/a0c1777438/packages/ckeditor5-table/src/plaintableoutput.ts#L18) plugin which outputs only the `table` in `getData` pipeline without `figure`.

Can I enable plugin PlainTableOutput for ckeditor5 built with the online builder (https://ckeditor.com/ckeditor-5/online-builder/)? I tried add it in config by: "extraPlugins" settings - but it doesnt work.

**Comment by Witoso** [comment]
Modify the `src/ckeditor.ts` in the folder that you got in the online builder (you need to have `Table` plugin), and add `PlainTableOutput` to the plugins list.

**Comment by goetsu** [comment]
Hello,

I'm sorry but regarding html5 spec and accessibility guidelines the semantic way to mark up table caption is a <caption> element inside the table not to use a figure and ficaption
see : 
https://html.spec.whatwg.org/multipage/tables.html#the-caption-element
https://www.w3.org/WAI/tutorials/tables/caption-summary/

**Comment by Witoso** [comment]
We've done our [research](https://ckeditor.github.io/editor-recommendations/features/table.html), and `figure` is: _the standard way to express self-contained non-textual additional content_. As we use `figure`, the `figcaption` is used according to the spec. This specified as the Approach 3 in the w3 document you linked.

**Comment by goetsu** [comment]
yes but as explained in the approach 3 you must in that case use aria to markup the table using aria-labelledby (for the caption)and aria-describedby (for the summary, currently not managed in ckeditor I think) and also this isn't the recommanded technique **Note: This HTML5 feature may not be as widely supported by assistive technology than other approaches for summaries on this page.**

**Comment by Witoso** [comment]
> you must in that case use aria to markup

Quoting: _(...) can be explicitly associated to the table (...)_ so I don't see a "must" recommendation, but this is worth checking for sure. I wonder if this is something you @Comandeer found in the latest review.

That's why [PlainTableOutput](https://github.com/ckeditor/ckeditor5/blob/a0c1777438/packages/ckeditor5-table/src/plaintableoutput.ts#L18) exists, which AFAIK Drupal uses, if someone wants to have a different output.

**Comment by Comandeer** [comment]
> Quoting: (...) can be explicitly associated to the table (...) so I don't see a "must" recommendation

Yes, but there is also a previous sentence:

> Screen reader users navigating in “Tables Mode” are usually unable to identify a table by a caption applied like this.

So I agree that linking a table with its caption with ARIA is recommended (as I even [noted earlier](https://github.com/ckeditor/ckeditor5/issues/3194#issuecomment-397245583)).

Probably the output from the `PlainTableOutput` is better for accessibility (as it uses a standard, dedicated element to mark up table caption) and we could rethink making it the default one.

**Comment by Witoso** [comment]
Tracking in: #15979.

**Comment by KirkMunroSagent** [comment]
> We've done our [research](https://ckeditor.github.io/editor-recommendations/features/table.html), and `figure` is: _the standard way to express self-contained non-textual additional content_. As we use `figure`, the `figcaption` is used according to the spec. This specified as the Approach 3 in the w3 document you linked.

You may have done your research, but the outcome of that research is questionable.

In a formal document, a figure is typically identified with a caption, centered on a page, accessible via a figure index, etc.

Why would you presume that CKEditor is being used to create formal documentation in all cases?

In some cases, it's just being used to edit existing content used for email messages, or perhaps used as part of a form designer, or one of many other possible scenarios where you don't want a figure element wrapping a table. If you're only ever creating new content in CKEditor, you can get away with forcing tables to be wrapped in figure elements. But for customers that have pre-existing content, you can't get away with that same decision.

There are scenarios where customers may be adopting CKEditor with existing HTML content already in place, where that content is well formatted and known to produce a certain expected result, but if that content contains tables, any modification of that content in CKEditor produces different HTML, which produces different, undesirable results because the content renders differently by default, with tables that were left justified suddenly appearing centered due to the default justification of figures. Modifying the default justification isn't desirable in this case either, because there may be places where figure elements are in use where you want the content centered, with a caption, mixed in with other content where you use a table to represent some structured data to the reader that you don't want treated as a figure.

Ultimately, the content author must own the decision to wrap or not wrap a table in a figure element, not an interpretation of the HTML 5 standard, and not an HTML editor.

Any argument against this implies that anyone using CKEditor _must_ be prepared to re-verify and update their content because of an interpretation of the HTML 5 standard made by CKSource. This isn't always possible as content may be owned by customers of a product that is considering adopting CKEditor, where the way customer-owned content is rendered must be preserved no matter what.

**Comment by KirkMunroSagent** [comment]
> > every code listing, image, quote, table etc. should be treated as self-contained and meaningful
> 
> With such reasoning we should put into figure virtually everything, lists, blockquotes, not just tables. Not sure if it isn't an overkill since the table tag itself already has a precise meaning.
> 
> For me using `<figure>` for tables and so on makes sense only with the combination of `<figcaption>`.

This was the right take. Figured may contain tables. Tables are not figures.

**Comment by wloeer** [comment]
@KirkMunroSagent is right. Nowhere in table-specs does it say, that wrapping it in figure is mandatory - and I believe from the examples it should be obvious that it is optional. Also in figure specs it is described, what proper figure-content should be like - it does not say, that all content fitting that description needs to be wrapped in figure. I believe this is the main misinterpretation, that lead to the wrong assumption: 
> The figure element MUST be used to represent the Table feature as it is the standard way to express self-contained non-textual additional content.

Figure specs even say:
> "For example, each sentence in a paragraph is self-contained"

Which by this logic would mean, that every sentence needs to be wrapped in figure, which would obviously be absurd.

Even without the figure-problems outlined in previous posts I would recommend to produce the simplest best markup by default: table (with caption instead of figcaption). Being able to optionally nest it in figure or only div (for mobile scrolling) would be nice though. Old content which already has figure around tables should retain the figure of course, to not break the layout.

Thus I recommend to follow this path:
> Probably the output from the PlainTableOutput is better for accessibility (as it uses a standard, dedicated element to mark up table caption) and we could rethink making it the default one.
