### ISSUE TITLE
Implement table captions

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#3204]
Tables need to be captioned. Most likely, we can implement this just like in the image feature. It'd be also good to extract pieces of shared logic so #1065 is resolved.

Related comments:

*   https://github.com/ckeditor/ckeditor5/issues/610#issuecomment-339661146
*   https://github.com/ckeditor/ckeditor5-table/issues/51#issuecomment-397245583

---

If you'd like this feature implemented, please react with :+1: to this post.

**Comment by alexander-schranz** [comment]
I hope this is the right issue to post this. The currently behaviour with adding a figure is from my side more annoying then good:

```
<figure class="table">
     <table>
         <!-- ... -->
     </table>
</figure>
```

The table itself does not need a figure because it is by itself like a figure it has its own `<caption>` tag. So this behaviour should definitly be changed or configureable that the real `<caption>` tag is used and not some wrapping with a figure tag some class name.

**Comment by Reinmar** [comment]
@alexander-schranz, we based on the research that's described in https://ckeditor.github.io/editor-recommendations/features/table.html. If you're still unsure, please open a ticket in https://github.com/ckeditor/editor-recommendations/issues.

**Comment by marcellofuschi** [comment]
Any plans to implement?

**Comment by marcellofuschi** [comment]
I need table captions for a project I'm working on. Shall I try to implement it and send a PR? You aren't working on it right now, are you?

**Comment by alexander-schranz** [comment]
@Reinmar The standard of the figure and figcaption tag is sure correctly interpreted, but for a table itself a figure and figcaption in html is not needed as the table itself has a caption tag which should be used instead of wrapping the table in a figure and add a caption. Would really be great to get rid of the figure around the table and use the real table caption instead.

**Comment by marcellofuschi** [comment]
@alexander-schranz I think the rationale for using `<figure>` is well-explained here: https://github.com/ckeditor/ckeditor5/issues/3194#issuecomment-397234125

**Comment by alexander-schranz** [comment]
@marcellofuschi thats sentence is definitly true for any textuel content, for the table itself it just doesn't make sense as the table itself is like a figure tag and have its own caption. Wrapping it again into a figure and caption should not be done aslong you don't have more then a table tag inside this figure tag.

**Comment by ktwbc** [comment]
Has there been any further work on this? We are failing accessibility testing because of this.

**Comment by Reinmar** [comment]
Some notes:

*   Adding toolbar button (could be moved from the image caption),
*   Adding/removing element to the model + conversion,
    *   note: caption can only be the first element in a table, so we may simplify its conversion and any model rules with that rule in mind,
    *   note: in the upcast conversion we need to support figure>figcaption and table>caption,
    *   note: we want to follow editor recommendations (figure>figcaption); see: [https://html.spec.whatwg.org/multipage/tables.html#the-caption-element](https://html.spec.whatwg.org/multipage/tables.html#the-caption-element)
*   Updating algorithms,
*    Selection (multi-cell),
*   Copy/cut/paste,
*   Update styles,
*   Documentation

**Comment by Reinmar** [comment]
> Has there been any further work on this? We are failing accessibility testing because of this.

We've just started working on this :+1:

**Comment by ktwbc** [comment]
Not sure if this is in scope or not but if captions are being added as part of accessibility then scope=row and those attributes are in that same wheelhouse would be beneficial as well.
