### ISSUE TITLE
Check automated and manual tests compatibility with IE11

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#329]

**Comment by Reinmar** [comment]
What about manual tests? It's worth to check both things in one place.

**Comment by maxbarnas** [comment]
Somehow I thought about manual tests as part of automated procedure. I'll fix the title.

**Comment by maxbarnas** [comment]
### Unit tests
**229** failed tests, many of which are totally broken (unable to run at all). Errors exist in almost every package. Severity of problems suggests it would take considerably more time than other browsers to make it work.
### Manual tests
Unable to run the editor at all. Consecutive tries to init the editor locks the browser.

**Comment by Reinmar** [comment]
So I guess this is enough for now. It's bad, we know it :D. We can either close this ticket or spend few more minutes on trying to understand what's stopping editor from work at all. In both cases, we also need a ticket for working on IE11 compat in the future.

**Comment by maxbarnas** [comment]
Everything depends on the priority of running CKE5 in IE11. I would postpone it until we have the editor up and running in other browsers. But @fredck might have different opinion and goals.

**Comment by Reinmar** [comment]
It's not a matter of goals. The goal is pretty clear – we want to understand something now, to know how bad it is. You mentioned that the editor doesn't even start, so I'd be curious if this is something that we can understand in couple of minutes and perhaps even fix to continue the research. Because 200 failed tests may mean that editor is functional, but a bit buggy in some cases, or, absolutely unusable. But right now we don't know this because the editor doesn't even start (which can be a small, unrelated issue).

**Comment by maxbarnas** [comment]
By goals I meant how important is to have IE11 working. Other that that I understand and agree with you.

**Comment by Reinmar** [comment]
It's pretty important (see discussion in https://github.com/ckeditor/ckeditor5-design/issues/156).

**Comment by fredck** [comment]
I agree that this is enough for now.

Let's just hope that we just have a few tricky blockers which are breaking most of the code execution. But we gonna handle this in the future.

Thanks for the research @maxbarnas ;)

**Comment by oskarwrobel** [comment]
I've just noticed that we are using not supported by IE `Event()` constructor for dispatching events in tests (it might be helpful for the future).
