### ISSUE TITLE
All buttons should focus the editor before executing their commands

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#353]
Otherwise, the command will be applied, but it may look odd or be invisible to the user because there won't be a blinking caret. For example, bold may be applied on a collapsed selection and that won't have any effect in fact.

Note: this will be consistent wth CKE4, but with that difference that now it's not the command's role to focus the editor. The UI (button) cares about its action which consists of two things – UI (focus) and document action (command).

**Comment by oleq** [comment]
Most likely https://github.com/ckeditor/ckeditor5-ui/issues/138 will need this to work properly.

**Comment by oleq** [comment]
A problem was also spotted when reviewing https://github.com/ckeditor/ckeditor5-ui/pull/523. 

It is more visible now since we have toolbars within dropdowns. It also got more complicated:

* Some plugins like `HighlightUI` [make sure the editing view is focused when executing](https://github.com/ckeditor/ckeditor5-highlight/blob/824dcc18e7ac818d4c028b836a3d6af8f36110e8/src/highlightui.js#L150-L153).

   ![Kapture 2019-10-15 at 10 33 18](https://user-images.githubusercontent.com/1099479/66814638-3a306280-ef37-11e9-8fd6-b2d0ad3ab792.gif)

* Some plugins like `BoldUI` [don't focus](https://github.com/ckeditor/ckeditor5-basic-styles/blob/d91773f1b7fa6214a2eb8d35e591e37e0e72e1f2/src/bold/boldui.js#L46). It is weird because the visual selection in the view disappears and the toolbar remains focused.

   ![Kapture 2019-10-15 at 10 34 46](https://user-images.githubusercontent.com/1099479/66814807-7ebbfe00-ef37-11e9-8f41-4dbf8cd98b86.gif)

* And in the case of the toolbar inside the drop-down (which is the same as `HighlightUI` but `HUI` takes care of the focus), by default [drop–downs close upon any execute coming from the inside](https://github.com/ckeditor/ckeditor5-ui/blob/2a2fe4ad83cb738ebf376ba57047ace2fa9dddb1/src/dropdown/utils.js#L254-L261) of the panel and they do not care about what happens to the selection (it is completely lost in the screencast below, editor is blurred).

   ![Kapture 2019-10-15 at 10 36 27](https://user-images.githubusercontent.com/1099479/66815007-d3f80f80-ef37-11e9-813d-51f73a2e8d07.gif)

We need to sort this out because it is getting out of control.

**Comment by oleq** [comment]
cc @mlewand

**Comment by Reinmar** [comment]
Moved to the "next" milestone. It's relatively cheap to fix.

**Comment by panr** [comment]
Ready to review. As this is my first multi-repo task, probably PR naming and commit msgs are too generic... If so, please let me know and I'll fix it.
