### ISSUE TITLE
Timeline to 1.0?

### ISSUE THREAD

**Issue by benjismith** [ckeditor/ckeditor5#386]
Would it be possible to post a rough estimate of the project timeline leading up to 1.0?

For example, it would be very helpful for external project planning to know whether to expect CKeditor 5 to arrive in 2017 Q2 or 2017 Q4.

Thanks! I'm really looking forward to it!!

**Comment by Reinmar** [comment]
Hey, Benji!

I totally agree. It was too early previously (https://github.com/ckeditor/ckeditor5/issues/24) to start planning things far into the future, but since we're getting close to 1.0.0 we should define a clearer roadmap.

How I see it is that we define at least this:

1. What will be included in 1.0.0 (the scope).
2. The ETA for 1.0.0.
3. What's next?

The scope of 1.0.0 is already pretty clear, but we need to sum it up. The ETA for 1.0.0 is, right now, early Q2 2017 and should not be delayed, because what's left now is just a few smaller features, documentation, cleanup, release tools and work on stability.

As for "what's next?", we'll need to bootstrap a discussion about this. 1.0.0 will miss some features, naturally, and we need to prioritise them. Community's feedback will be greatly welcomed here.

We'll open tickets in https://github.com/ckeditor/ckeditor5-design for these things. I'll let you know once we do it.

**Comment by benjismith** [comment]
Awesome! Thanks for the reply!

**Comment by Reinmar** [comment]
Done https://github.com/ckeditor/ckeditor5-design/issues/172 :).
