### ISSUE TITLE
Setting data doesn't clear undo stack

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#4060]
1. Open any sample.
2. Type few letters (or do any other change).
3. Call `editor.setData( '<p>foo</p>' );`
4. See that undo is enabled.
5. Undo. Error is thrown.

We have two things here:

* It should be possible to manage whether setting data resets the history (whether it's undoable or not) or not. Or, like in CKE4, there should be a way to tell whether `setData()` should create undo step and a way to clear the stack. This is more granular but boils down to the same story.
* If `setData()` was meant to create an undo step then undoing shouldn't throw an error.

   I also thought that features like typing may need to reset their stored batch on such actions. I think that `ChangeBuffer` should be doing this reliably now but it may be good to write a test for it (if there's none).

**Comment by baturian** [comment]
Any changes in that issue? Still can't clear undo stack by public API. And `setData()` still doesn't clear undo stack as well.

**Comment by Reinmar** [comment]
@baturian not yet, but we've just added this ticket to the sprint so most likely it will land at the end of July.

The decision was to have `setData()` always clear the undo stack. We can't really think about valid use cases for not clearing it.

We want to implement a solution described by https://github.com/ckeditor/ckeditor5/issues/4060#issuecomment-484808750. It's not yet clear whether `DataController#set()` should fire a new event or whether it's enough if it will be decorated (as `DataController#init()` is already).

**Comment by adamerose** [comment]
> We can't really think about valid use cases for not clearing it.

@Reinmar 

My project autoformats the document by passing the contents from `editor.getData()` through [Prettier](https://prettier.io/docs/en/api.html#prettierformatsource-options) and then passing the result back to `editor.setData()`. I would like to be able to still undo this autoformat step and keep the full undo/redo history. Is there a better way to do this or am I the first person with a use case like this?

Is there any way I can apply `setData` as a change that becomes part of the undo history instead of clearing it?
