### ISSUE TITLE
Responsive toolbar

### ISSUE THREAD

**Issue by SammyM** [ckeditor/ckeditor5#416]
## Is this a bug report or feature request?

🆕 Feature request

## 💻 Version of CKEditor

CKEditor v5 @ 12.4.0

## 📋 Steps to reproduce

Currently the toolbar gets a little ugly in narrow viewports. Namely it flows into two, disorganized lines.

Example below:

<img width="320" alt="screen shot 2017-03-21 at 15 44 26" src="https://cloud.githubusercontent.com/assets/1324289/24156122/9cfbaaaa-0e4d-11e7-864c-aab844154170.png">

A solution for this would be to collapse overflowing buttons.

---

If you'd like to see this feature implemented, add 👍 to this post.

**Comment by fredck** [comment]
Hey @SammyM, can you elaborate a bit, guiding us on your expectations on this? How do you think CKEditor should behave when it comes to responsive design?

**Comment by fredck** [comment]
I mean, we know there’s work to be done, and we have plans for it, but I would love to hear your expectations, because it may point us to things we didn't take in consideration so far.

**Comment by SammyM** [comment]
I've not spent a lot of time playing with the new version of CKEditor so I'm not sure of all the functionality yet, but I've noticed that the popups/tooltips can't fully be seen on smaller viewports. For example:

<img width="320" alt="screen shot 2017-03-21 at 15 44 26" src="https://cloud.githubusercontent.com/assets/1324289/24156122/9cfbaaaa-0e4d-11e7-864c-aab844154170.png">

I'm glad to hear it's in your plans.

**Comment by HassanAmmori** [comment]
Well, I am sure these are minor things that I wouldn't be worried about. Most of the elements act really well already

**Comment by SammyM** [comment]
Is there an update on this at all? I know the UI of CKEditor has changed a bit since I last raised this issue, but the popups still go off the screen.

![screen shot 2018-09-07 at 16 44 02](https://user-images.githubusercontent.com/1324289/45229289-5d60fb00-b2bd-11e8-8b3e-c96375fcd614.png)

**Comment by oleq** [comment]
I proposed 2 improvements to the UI:

## Responsive in–balloon forms

This [feature](https://github.com/ckeditor/ckeditor5/pull/1299) is on review now.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/1099479/46874026-761e7c80-ce38-11e8-9a7b-e3fc61a556ed.png">

<img width="343" alt="image" src="https://user-images.githubusercontent.com/1099479/46874059-8a627980-ce38-11e8-91d1-38d7fdc384ac.png">

## (WIP) Dynamic items grouping for overflowed toolbars

The PoC can be found in [the PR](https://github.com/ckeditor/ckeditor5-ui/pull/451) but it's not finished yet.

![kapture 2018-10-16 at 15 16 18](https://user-images.githubusercontent.com/1099479/47019335-19cc9d00-d157-11e8-9c15-58bf85c00719.gif)

<img width="493" alt="image" src="https://user-images.githubusercontent.com/1099479/47019760-1dacef00-d158-11e8-9d82-d65d95d62920.png">

### Why not a scrollable toolbar instead?

It sounded like a great plan and at first. In fact, I tried to implement a scrollable toolbar. Like when it overflows, the scrollbar appears and it is possible to reach the rest of the items easily (at least on mobile). But my PoC failed because of the following reasons:
* The solution is OK for mobiles (touch devices) but not necessarily on desktops. We'd need to implement grouping soon anyway, e.g. in the [document editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html) where we struggle to find a space for more feature buttons.
* When the toolbar gets any `overflow`, all children are cropped (e.g. dropdown panels, tooltips),
* To fight the above, I tried to rewrite dropdown panels to balloon–like components (with `position: absolute` + our positioning heuristics) and I found multiple issues with that approach:
   * The dropdowns were hit by the "position delay syndrome" ![kapture 2018-10-15 at 13 10 45](https://user-images.githubusercontent.com/1099479/47020352-77fa7f80-d159-11e8-85df-1a50c2385ce7.gif)
   * I found out our API is not ready for any UI component using `BalloonPanelView` or anything that goes into the "body" collection. ATM only plugins can use these things because to work with them, we need to know about the editor (`EditorUI`), which is impossible in plain UI components:
       * Where to insert it in DOM (`editor.ui.view.body`)
       * How to handle the focus (`editor.ui.focusTracker`)
   * Because of the above I had to rewrite `createDrodpown` so it gets both the reference to the body collection and the focus tracker so the dropdown can put the (now floating) panel in the right place in DOM and register it in the FC (the panel no longer belongs to the toolbar which is in the FC by default). That's quite a mess.
   * When the dropdown panel is no longer in the same tree as its button (in the "body" collection), when suddenly the toolbar changes its position (e.g. sticky panel is no longer sticky because of focus loss), we must update the position of the panel too. The dropdown has no idea what happens to the toolbar, it doesn't know anything about that (it's encapsulated as a `View`) so there's no way to tell the dropdown to update the position of its panel except from the outside. That would require a very weird API.
![image](https://user-images.githubusercontent.com/1099479/47021092-0e7b7080-d15b-11e8-8503-61997e71104a.png)
![image](https://user-images.githubusercontent.com/1099479/47021106-1509e800-d15b-11e8-8ff4-3ff792c85f02.png)

I figured we'd need a massive refactoring to deal with these issues that we cannot afford ATM.

**Comment by Reinmar** [comment]
The first part of the changes mentioned by @oleq in https://github.com/ckeditor/ckeditor5/issues/416#issuecomment-430246472 are merged:

![image](https://user-images.githubusercontent.com/156149/47567718-9fa6d000-d92f-11e8-8eef-f3f3c267870d.png)

We still need your feedback on the "(WIP) Dynamic items grouping for overflowed toolbars" part though.

**Comment by mlewand** [comment]
It's about time to focus this issue. Issue with balloons out of view have been fixed with ckeditor/ckeditor5#1299, the only outstanding problem is the toolbar responsiveness, and let's track it in this issue.

**Comment by nusagates** [comment]
![Screenshot_20200906-055855](https://user-images.githubusercontent.com/16206306/92314751-2d60a580-f006-11ea-9208-fa23db74de43.png)
Unable to scroll toolbar. So the invisible toolbar item could not be used on mobile phone.

How to resolve this issu?

I am using Ba

**Comment by oleq** [comment]
@nusagates Please leave a :+1: in #5586.
