### ISSUE TITLE
[Chrome/Safari] The selection moves to the beginning of the editor after collapsing it in read only mode

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#4199]
## Steps to reproduce
1. Create the `Header 1` and the paragraph.
2. Enter `read only` mode.
3. Select part of the paragraph.
4. Click on the selection to collapse it.

## Current result
The selection moves to the beginning of the editor (you can see that dropdown points to the `Header 1`).

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31712957-f010efc0-b3fc-11e7-8273-6e7c436f995c.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Opera
Release: 1.0.0-Alpha1

**Comment by scofalik** [comment]
This incorrect behavior is causing bugs in comments in read-only mode.

**Comment by scofalik** [comment]
Sorry, I didn't read the issue just looked at the gif :D.

The problem, in overall, is caused by the fact that in the read only mode, the selection is always converted, no matter if it ends up in the editable or outside or is removed at all (like in the case above). This is caused by an incorrect condition in selection observer.

So, when the incorrect DOM selection is mapped to view, there are no ranges in the view that can be mapped with DOM selection ranges. So an empty view selection is upcasted, which causes the bug.
