### ISSUE TITLE
Clipboard & Editor editor.setData issues

### ISSUE THREAD

**Issue by deanvaessen** [ckeditor/ckeditor5#422]
Hello everyone,

Back for a (hopefully last :) ) round of questions.

I'm currently encountering 2 issues:

1. Copy & Paste doesn't work as I expected. I notice the following:
* I **can** copy from inside the editor and paste inside the editor
* I **can** copy from outside the editor and paste inside the editor
* I **cannot** copy from inside the editor and paste outside the editor

In the cases where I **can** copy/paste,  I can only use small bits, large bits just don't work at all.

I am also getting this error message in the console on ctrl+v:
```
domconverter.js?7bb5:359 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at DomConverter.domToView
```

2. I am having an issue where things that I convert to markdown and back to HTML are squashed and linebreaks are not remembered. To test, try the "toMarkdown" button.

I suspect however, that this is not an issue in the conversion but rather some sort of strange conflict with the editor (maybe a height of the editor issue that squashes everything? Though it is strange that it is loading the demo I included below just fine while using the absolute same libraries). I say this because I use the two libraries (marked.js and toMarkdown.js) also in to convert to and from markdown for the reader part of this application.

To demonstrate, try clicking submit on the demo and you will see. It converts the html on the page to markdown and then posts it, reader gets the markdown and converts to html. This works.

I'm stumped what the issue could be. 

I have included my configuration here:
https://gist.github.com/deanvaessen/2794433f1b6e2fe4dc7c1e839efea9ac

Demo (I did not include the clipboard in this version yet):
http://swarm-gateways.net/bzz:/ff56ac14b754f1f97044e9d724ab4e5351c3513febb9162794812871751435df/edit.html#02e8ec3b6faa879d6288c2b8a2f4053ac21da328a92b2dfab0e8f6be3f343a79

Could I ask for a bit of help with this?

Cheers!

**Comment by Reinmar** [comment]
> I cannot copy from inside the editor and paste outside the editor

Did you perhaps try to paste to a plain-text editor, like code editor? That's a small feature we forgot to implement: https://github.com/ckeditor/ckeditor5-clipboard/issues/11 because pasting to an app which supports `text/html` would work. It's definitely on our radar.

> I am also getting this error message in the console on ctrl+v:
>
> domconverter.js?7bb5:359 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined at DomConverter.domToView

We'd a stack trace at least and perhaps an info what was actually passed to this method. My guess for now is that it's an HTML comment. For now, this method supports only elements, texts and doc fragments. There's a ticket for it: https://github.com/ckeditor/ckeditor5-engine/issues/647. Could you try to confirm that it's it?

**Comment by Reinmar** [comment]
> To demonstrate, try clicking submit on the demo and you will see. It converts the html on the page to markdown and then posts it, reader gets the markdown and converts to html.

I submitted the content and edited it back – all line breaks were preserved, so I'm not sure what do you mean.

One thing which comes to my mind is that perhaps you mean soft line breaks (`<br>`) for which we haven't yet developed a feature but those are also rarely used in MD, so I don't think that you meant them.

**Comment by deanvaessen** [comment]
Thanks for the speedy reply!

> Did you perhaps try to paste to a plain-text editor, like code editor? That's a small feature we forgot to implement: ckeditor/ckeditor5-clipboard#11 because pasting to an app which supports text/html would work. It's definitely on our radar.

No, just out of the editor at all. I am noticing however, that in my demo (that does not have the clipboard added as a plugin) does not have this issue and I can copy from inside the editor to outside (but then I can't copy/paste inside the editor)

> We'd a stack trace at least and perhaps an info what was actually passed to this method. My guess for now is that it's an HTML comment. For now, this method supports only elements, texts and doc fragments. There's a ticket for it: ckeditor/ckeditor5-engine#647. Could you try to confirm that it's it?

To be completely honest, I am not sure how I would do that (have never done a stack trace, ha). But I can try to figure it out.

Also, maybe it has something to do with the way I am importing the plugin? I tried to do it logically like I did the other plugins.

> I submitted the content and edited it back – all line breaks were preserved, so I'm not sure what do you mean.

Apologies, I wasn't clear. Yes, submit works. And that's the funny part because it's the same library. But with the "toMarkdown" button that I added, things go wrong.

**Comment by Reinmar** [comment]
> No, just out of the editor at all

I can copy to CKEditor 4 or other editor, so, as I wrote – it works when `text/html` is used by the target editor. If `text/plain` then it doesn't work but for that we have the ticket.

> I am noticing however, that in my demo (that does not have the clipboard added as a plugin) does not have this issue and I can copy from inside the editor to outside (but then I can't copy/paste inside the editor)

That's because the editor handles copy/cut operation by itself when the plugin is loaded. Without it you'll have the default copy/cut behaviour, but no ability to paste because the plugin is also handling this when enabled.

> Or do you mean this?

Yep, that's it. Thanks. Unfortunately, this stack trace doesn't answer all the questions. So, the next step would be to check what kind of node is passed to this function: https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/domconverter.js#L349

You could locate this file in your `node_modules` and just put there a `console.log()` and rebuild the app.

> Also, maybe it has something to do with the way I am importing the plugin? I tried to do it logically like I did the other plugins.

I don't think so. There are more plausible explanations. We just need to verify this.



> Apologies, I wasn't clear. Yes, submit works. And that's the funny part because it's the same library. But with the "toMarkdown" button that I added, things go wrong.

For me the "toMarkdown" button crashes the browser :D. There's some infinite loop happening. I'm afraid you have some kind of issue in your code.

**Comment by deanvaessen** [comment]
> I can copy to CKEditor 4 or other editor, so, as I wrote – it works when text/html is used by the target editor. If text/plain then it doesn't work but for that we have the ticket.

Gotcha, that seems to be it.

> You could locate this file in your node_modules and just put there a console.log() and rebuild the app.``
That yields this: http://i.imgur.com/1uoAynI.png

>For me the "toMarkdown" button crashes the browser :D. There's some infinite loop happening. I'm afraid you have some kind of issue in your code.

Odd, it does crash in Edge. Chrome or Firefox don't crash for me though, for you?

**Comment by Reinmar** [comment]
> Odd, it does crash in Edge. Chrome or Firefox don't crash for me though, for you?

The second time I tried it didn't crash. Strange.

I checked your code and now I understand what you tried to do. The "to markdown" button is supposed to load a markdown content to the editor so it's still a markdown when editing it (so the user sees `## Headings` etc.). Yes?

Unfortunately, this is not going to be super easy. Currently, you load such a content to the editor:

```md
# Heading

Paragraph
```

For the editor, which is configured to accept HTML, this is just a plain text which renders as "# Heading Paragraph" and this is more or less how it loads to the editor.

I don't know what you try to achieve but it'd make more sense to load this content to a textarea. CKEditor is not meant to edit plain text, at least, not yet. You'd need to write a data processor which converts a plain text to a proper editing view (lines need to be separated by some elements), add support for soft line breaks and perhaps something more. This is all doable, but with lack of docs that's pretty much hardcore :).

Another option, if not textarea, could be preformatting content of the editable (with `white-space: pre` os something). However, the editor will right now wipe out whitespaces anyway because it doesn't recognise yet that you want to load a content to a preformatted element.

So, really – it's best to load a plain text markdown to a normal textarea.

**Comment by deanvaessen** [comment]
Thanks, that clears it all up a bit better. Was the screenshot for the copy error enough for you also? Is that an issue that is solvable?

> You'd need to write a data processor which converts a plain text to a proper editing view (lines need to be separated by some elements), add support for soft line breaks and perhaps something more. 

Would the following qualify perhaps? https://github.com/ckeditor/ckeditor5/issues/417

**Comment by Reinmar** [comment]
> Was the screenshot for the copy error enough for you also? Is that an issue that is solvable?

Yes, it's either trivial or quite simple. There are comments in your clipboard and the DOMConverter needs to handle them somehow. You can follow https://github.com/ckeditor/ckeditor5-engine/issues/647.



> Would the following qualify perhaps? #417

Yes, although #417 is not something to be fixed. We just discussed there the architecture of data processors and the engine. My comment there may help you understand how editor loads the data.

I'd like you to give more details on how to implement support for plain text editing in CKEditor, but this is a deep topic. It crosses several layers – from data processing, through the view layer to the model and its features.

Besides, I'm still not convinced that it's worth it. It's an interesting exercise but it may be too much at the current stage. And loading plain text markdown to the editor seems like unnecessary. Perhaps you could tell us more about your use case?

> @fredck wrote something like this from the sound of it, as mentioned in the final post of that thread.

Fred mentioned the https://github.com/ckeditor/ckeditor5-markdown-gfm package. It contains a Markdown data processor for the editor. If you plug it into the editor it will be able to load Markdown and output Markdown.

So, .e.g if you do:

```js
editor.setData( '# Heading\n\nParagraph' );
```

You'll have this content in the editor:

```html
<h2>Heading</h2>

<p>Paragraph</p>
```

And `editor.getData()` will return the exact string you passed to `setData()`.

**Comment by Reinmar** [comment]
I posted a sample code how you can enable any DP right now: https://github.com/ckeditor/ckeditor5/issues/417#issuecomment-293198175.

**Comment by deanvaessen** [comment]
> Fred mentioned the https://github.com/ckeditor/ckeditor5-markdown-gfm package. It contains a Markdown data processor for the editor. If you plug it into the editor it will be able to load Markdown and output Markdown.

Aha, OK then that's different behaviour I think, yes.

> Perhaps you could tell us more about your use case?

Simply that we store markdown files, that we want to edit with a WYSIWYG editor and toggle a markdown mode to view the actual markdown also, like we did in CKEDITOR4 with:
https://github.com/hectorguo/CKEditor-Markdown-Plugin

> Fred mentioned the https://github.com/ckeditor/ckeditor5-markdown-gfm package. It contains a Markdown data processor for the editor. If you plug it into the editor it will be able to load Markdown and output Markdown.

If I understand correctly, that won't help then for the behaviour that I am looking for, right?

The only solution I can think of is to hide the CKEDITOR field on markdownmode activation, then show a textarea field, put the markdown in there and when the markdownmode is deactivated, show the CKEDITOR field again and plug in the data converted to HTML.

**Comment by deanvaessen** [comment]
I am closing this as we have moved to using a text field, this works OK for now. Thanks for the input and clarification on the clipboard also :)
