### ISSUE TITLE
ckeditor cannot load assets in production 

### ISSUE THREAD

**Issue by eugened19** [ckeditor/ckeditor5#424]
Hey guys,

Just ran into exactly the same issue as described for Ruby here:
https://github.com/AgileVentures/shf-project/pull/222

Running version 5.2.2

Any help?

Thanks!

**Comment by Reinmar** [comment]
Hi eugened19, from what I see in https://github.com/AgileVentures/shf-project/pull/222 you're using CKEditor 4 and this issue tracker is for CKEditor 5 (a totally new version).

CKEditor 4's issue tracker is on http://dev.ckeditor.com. However, you'd need to provide more information because the team can't debug an issue which occurs in other projects.
