### ISSUE TITLE
Writing a custom upcast converter is cumbersome

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#4511]
I want to write a custom element upcaster which will ignore all children of this element. `for( 'upcast' )elementToElement()` doesn't allow that. So I need to use `UpcastDispatcher#element`. However, to ensure that my converter is as good as the default ones, I need the entire logic of [`prepareToElementConverter()`](https://github.com/ckeditor/ckeditor5-engine/blob/master/src/conversion/upcasthelpers.js#L514) which is nearly 80 lines of code. What's even worse than its length is that it may change in the future – it's just changed very recently too.

Similar story with `prepateToAttributeConverter()`.

I think we should either document this and hope that those things won't change frequently, or expose a couple more utils which you can use to make your converter callbacks shorter.

cc @pjasiun @scofalik

**Comment by Discordius** [comment]
I would definitely appreciate a `ignoreChildren` option, since I just wanted to filter out `style` tags on upcast (since I am taking in some HTML with embedded style tags), but apparently have to create a whole UpcastDispatcher to make that happen, which requires me to learn a new API.

**Comment by jodator** [comment]
> I would definitely appreciate a `ignoreChildren` option, since I just wanted to filter out `style` tags on upcast (since I am taking in some HTML with embedded style tags)

Could you write more about that use case? I'm not sure what you need to filter out in a converter. The `ignoreChildren` would skip whole tree under some element if I get that correctly.

**Comment by Discordius** [comment]
It turned out that for my use-case, the existing consume children option was actually totally sufficient, though it took me like 4 hours to figure that out. Here is the code that I ended up writing: 

```javascript
export function CleanStyleTags( editor ) {
	editor.conversion.for( 'upcast' ).add( dispatcher => {
		dispatcher.on( 'element:style', ( evt, data, conversionApi ) => {
			const styleElement = data.viewItem;
			conversionApi.consumable.consume( styleElement, { name: true } );
		} );
	} );
}
```

Without this plugin, if you have a style tag in the HTML you are initializing from, its content just get spewed into a paragraph in CKEditor, which seems very rarely like what's intended. 

The consume API worked pretty well here. I would have still preferred a `ignoreChildren` option so that I could have stayed within the `elementToElement` helper function, but given that the above function is only two lines, I really can't complain too much.

**Comment by Reinmar** [comment]
We're working on this topic in #7336 (which turns out to be a DUP of this ticket).

**Comment by Reinmar** [comment]
@Discordius, we're gathering feedback in https://github.com/ckeditor/ckeditor5/issues/7336#issuecomment-649538681.
