### ISSUE TITLE
Balloon Toolbar Editor drop-down

### ISSUE THREAD

**Issue by wojtekidd** [ckeditor/ckeditor5#455]
How about making small buttons for Paragraph, H1, H2 etc.. instead of having the formatting drop-down menu? It would make this toolbar much lighter.

**Comment by wwalc** [comment]
I was about to report the same in https://github.com/ckeditor/ckeditor5-heading
I agree that the current ballon toolbar looks heavy because of that dropdown element. As an end user, when looking for a light editor with such contextual toolbar, I'd prefer to use something that has just "H1"/"H2"/"H3" buttons which require one click to set. A dropdown UI element fits only feature-rich editors with fixed UI.

**Comment by pjasiun** [comment]
I created a more technical ticket: https://github.com/ckeditor/ckeditor5-heading/issues/75.

**Comment by wojtekidd** [comment]
I understand, though thinking about the CKEditor 5 Builds (and Balloon Toolbar being one of them) I would personally go for having separate buttons in the build we present on our website.

**Comment by Reinmar** [comment]
👍 

However, we have the dropdown already and just removing it now to have separate buttons is not a good idea. At some point, someone will ask how to group those buttons into one toolbar anyway, so this is a bit deeper topic – how to make this configurable.

I explained possible options in https://github.com/ckeditor/ckeditor5-heading/issues/74#issuecomment-305224952. We need to understand the priority of this topic now.

**Comment by Reinmar** [comment]
Such an editor will be added in https://github.com/ckeditor/ckeditor5/issues/1112.

And we're not considering changing the balloon editor for now.
