### ISSUE TITLE
Feature request: tab support

### ISSUE THREAD

**Issue by vernjensen** [ckeditor/ckeditor5#457]
Without going into describing our application a lot, let's just say that we're "hiding" the fact that it's really running in a web browser. As part of this, we want tabs to behave as they do in Microsoft Word (or Google Docs!) where you can press tab on a blank line and have the cursor move to the right.

We do NOT want to ever have tab result in focus moving away from ckeditor's document body. We don't want tab to result nothing happening, either.

I realize there are reasons ("accessibility") that tab support in this way hasn't been added in the past, but at a minimum at least having an option to  enable this behavior, if desired, would be great.

If this is done in ckeditor 5 vs. 4 doesn't matter to me too much. I plan to upgrade to 5 once it is released.

**Comment by Reinmar** [comment]
Hi @vernjensen! Thanks for the ticket.

I understand your use case because it's quite common. Basically, there are two main use cases:

* an editor as one of a form's (or app's) inputs,
* editor as the main input of the app (in which case, the app is usually built around the editor – like in Google Docs).

In the first case, it's usually expected that the <kbd>Tab</kbd> key leaves the editor so it doesn't disturb the navigation through the form/app. In the second case, the <kbd>Tab</kbd> should be handled by the editor (it should either indent the line, insert tab character or simply do nothing).

Which option CKEditor 5 implements? None of them ;). CKEditor 5 simply does nothing with the <kbd>Tab</kbd> key. What you can observe is simply what the browser does. 

Now, should we make it configurable? I don't think so. What <kbd>Tab</kbd> does is an integration logic and, as such, it should rather be handled by the application with which the editor is integrated. We should just make sure that this is easy to achieve. 

(Note: the below code snippet may not work in the future because keystroke API is may change).

So, how could you do it now, in CKEditor 5? This should work:

```js
editor.keystrokes.set( 'Tab', ( data, cancel ) => {
     cancel();
} );
```

I hope this satisfies you. I'd also like to hear @oleq and @fredck opinions.

**Comment by oleq** [comment]
> Now, should we make it configurable? I don't think so. What Tab does is an integration logic and, as such, it should rather be handled by the application with which the editor is integrated. We should just make sure that this is easy to achieve.

So much 👍. The editor should neither interfere with the environment nor disrupt the default accessibility features offered by the web browser. The <kbd>Tab</kbd> key navigation is an integration–level thing, and it's up to the app/webpage/form to make sure it works properly.

> So, how could you do it now, in CKEditor 5? This should work:

A native DOM listener should also do the trick, provided it's attached after the editor is initialized, so it's last to respond to the event – it should not block things like list indentation and navigation within the UI of the editor then.
