### ISSUE TITLE
Rewrite widget resizer unit tests

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#4614]
## Is this a bug report or feature request?

Task

## 📋 Steps to reproduce

Currently widget resizer is tested solely by image resizer integration tests.

There are couple of issues with that:

* Since we're using [initEvent](https://github.com/ckeditor/ckeditor5-image/blob/eea68b7629be0a040821127bb344f9e50d9b82c3/tests/imageresize.js#L601-L606), the mouse coordinates gets floored. This means that it's impossible to write reliable tests for hidpi env.
* It would be great being able to mock (externally trigger) events [subscribed by WidgetResizer](https://github.com/ckeditor/ckeditor5-widget/blob/1a31082d815adf144dc154c1cf564b91bd20294e/src/widgetresize.js#L58-L62).
* We skipped 100% CC, but we want to have it.

**Comment by mlewand** [comment]
@Reinmar Just one thing needs to be clarified before we go further:

* Currently the resize feature is heavily dependent on DOM, should I:
	* Tests things that use DOM heavily (computed rects, events) in a more of integration test-spirit? So pretty much the way it is done for [imageresizing](https://github.com/ckeditor/ckeditor5-image/blob/11c9f395e9562e1773f4ee6a75fe48507fe01035/tests/imageresize.js) and add unit tests for these parts that can be easily tested alone.
	* Mock all the possible dom-related things. This option would require _a lot_ of mocking.

**Comment by Reinmar** [comment]
Mock mouse movements in a safe and stable way. The rest can come from the browser. The problem with the current tests is that to workaround the hidpi/lowdpi issue you created tests which sometimes give X, sometimes X+1 results which made them far more complex than what they need to be.

Currently, every time when you could've used a simple `expected === actual` checks for data/model layers, you're doing pattern matching because some width/height values can be either 50px or 51px.

The goal is to make tests simple. Abusing mocks don't make them simple and/or realistic. Agreeing to browser's inconsistencies or the effect of the environment also makes things complex. The choice needs to be pragmatic and based on what can simplify tests as simple and as realistic as they can be.
