### ISSUE TITLE
CTRL + A on selected image moves the caret to the beginning of the editor

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#465]
## Steps to reproduce
1. Open a sample with an image.
2. Select the image.
3. Press <kbd>CTRL</kbd> + <kbd>A</kbd>.

## Current result
Selection shows up for a moment, then breaks and the caret moves to the beginning of the editor.

## GIF
![bug](https://user-images.githubusercontent.com/20988892/26925383-e9200306-4c49-11e7-8680-d8f770efb037.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Firefox, Edge, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
That's because when the user presses <kbd>Ctrl</kbd>+<kbd>A</kbd> the browser creates such a selection:

```html
<p>[foo</p>
<image/>
<div hidden-selection-container>image widget]</div>
```

And then we remove the hidden selection container because we notice that the fake selection is gone.

I can imagine a couple of solutions:

* Intercepting the keystroke early and handling it on our own. This will be needed for https://github.com/ckeditor/ckeditor5-image/issues/55 anyway, so maybe we should handle it everywhere just to make it consistent. We'll also need to handle selecting the entire content when widget is the first/last element in the editable (I can't find a ticket for it now ;|).
* Fixing the selection which ends in/after the hidden selection container when removing it.
* Some hybrid solution combining intercepting the "select all" action and fixing the selection.

**Comment by szymonkups** [comment]
Moved to https://github.com/ckeditor/ckeditor5-widget/issues/23.
