### ISSUE TITLE
Duplicated imports issue in watchdog

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#4699]
Because Watchdog is using CKEditor 5 events it will cause "duplicated imports" error if not build together with the editor. It means that you can not use watchdog with your build without rebuilding it, what is a shame. It also means that you can not use watchdog with available CKEditor 5 builds.

I think we have 2 options here:
 - [solve "duplicated imports" problem globally](https://github.com/ckeditor/ckeditor5/issues/667#issuecomment-483677298), I believe that importing event utils should be safe, does not matter how the editor is built,
 - change watchdog that way that it will not use CKEditor events, but a very similar API. This would be a simpler, but more "hacky" solution.

**Comment by ma2ciek** [comment]
> I think we have 2 options here:
> * solve "duplicated imports" problem globally, I believe that importing event utils should be safe, does not matter how the editor is built,
> * change watchdog that way that it will not use CKEditor events, but a very similar API. This would be a simpler, but more "hacky" solution.

Since the `EmitterMixin` and the `ObservableMixin` operate on symbols, the first option won't be available soon (https://github.com/ckeditor/ckeditor5/issues/667#issue-274205782), so I'll implement a very simple EmitterMixin-like class that will expose a similar API.

Unfortunately, it means a minor (?) BC in this plugin as a part of the Watchdog API (the part from ObservableMixin) won't be available or will be behaving slightly different. This part is rather rarely used and not mentioned in the [feature docs](https://ckeditor.com/docs/ckeditor5/latest/features/watchdog.html).

cc @Reinmar @mlewand.

**Comment by ma2ciek** [comment]
Closed by ckeditor/ckeditor5-watchdog#34.
