### ISSUE TITLE
Implement configurable editor's placeholder

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#479]
We could support:

* [ ] `config.placeholder = 'Type here...'`,
* [ ] and even reading the `placeholder` from the editor element if the editor was initialised on a textarea.

We should also:
* [ ] Find a decent name for the utility https://github.com/ckeditor/ckeditor5-engine/issues/899
* [ ] Address the a11y contrast issue https://github.com/ckeditor/ckeditor5-theme-lark/issues/213
* [ ] Update documentation with the information about placeholders
    * [ ] A placeholder feature guide with a couple of editors?

Of course, it will depend on editor creator how to set the placeholder (e.g. some creators may have multiple editables and then they will have to support setting multiple placeholders in `config.placeholder`).

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/notes/issues/405

**Comment by Reinmar** [comment]
BTW, I forgot to mention that @alexeckermann wrote a simple plugin which adds a placeholder to the editor: https://github.com/alexeckermann/ckeditor5-emptyness ❤️

**Comment by vladikoff** [comment]
@Reinmar Awesome! We are gonna try using that!

**Comment by kirk-quinbar** [comment]
Is this still a TODO item? status?

**Comment by alexeckermann** [comment]
Look as though from the tags above that its been pushed to a future milestone but not any known milestone in the pipeline.

The emptyness plugin mentioned above is what I am using in production at the moment as a solution. It will also be greatly improved soon pending some pull requests in CK5 to fix some integration issues. If you need any help with that just let me know.

**Comment by kirk-quinbar** [comment]
alexeckermann,

I took a look at the overview of your plugin and did have a question. Your overview talks about making a custom build of ckeditor to pull that plugin in, but I was wondering if there is a way to just do that at runtime.  There is a plugin for CKEditor v4 that is commonly used to provide this same type of html5 placeholder.  It was written by a guy named alfonsoML. His plugin you could just load at runtime when the editor instance was created similar to this:

https://github.com/AlfonsoML/confighelper

` //ckeditor plugin placeholder text plugin, pulled from placerholder="" on #ReplyTextArea
  CKEDITOR.plugins.addExternal( 'confighelper', '/ckeditor/confighelper/');
  CKEDITOR.config.extraPlugins = 'confighelper';`

Not sure if that was a v4 feature that isnt in v5 as i didnt dig that far yet, but I was hoping that maybe your plugin could just be loaded at the time the instance is created to and how I could go about doing that?

The other thing that was nice about his was that you could just set the standard html5 placeholder property on the textarea and it would read that one instead of having its own property. not a big deal but kept the coding standard for how placeholders are typically added to textboxes and textareas.

**Comment by Reinmar** [comment]
> Not sure if that was a v4 feature that isnt in v5 as i didnt dig that far yet, but I was hoping that maybe your plugin could just be loaded at the time the instance is created to and how I could go about doing that?

It depends on a plugin. Technically speaking, some can be loaded on runtime. But it's safer to assume that it cannot be loaded on runtime. We wrote more about it in https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/installing-plugins.html

**Comment by alexeckermann** [comment]
@kirk-quinbar The emptiness plugin will need to be loaded with the editor during its initialisation, it can't be loaded thereafter because of view extension restrictions after rendering. Moreover, because of duplicated dependencies it would get out of hand really quickly.

I would highly recommend setting up a custom build, even if its to add one or two plugins to a base editor. If thats not possible or unsuitable let me know (email in my profile) and I can help put something together for you.

Since the editor uses `contenteditable` there is no possibility to have a native placeholder attribute supported. Additionally, it has to be added so that it doesn't interfere with the content structure in the editor.

**Comment by kirk-quinbar** [comment]
That would be awesome if CKEditor could support the html5 placeholder attribute by default just like textbox and textarea. seems like something that should be standard in this type of control. :)

**Comment by robclancy** [comment]
This should have been a default feature? Pretty standard...

**Comment by michaeldjeffrey** [comment]
@mrinaljain I didn't need a placeholder with anything like headings, so I scraped together a simple one. This is what I'm using until something official comes out.
It does rely on Emptyness though.
https://gist.github.com/michaeldjeffrey/46b7556b901a1abe593384ed68f9302d

**Comment by tovic** [comment]
> Is there any temporary solution available to get a placeholder in CKEditor 5 ?

@mrinaljain Here&rsquo;s my quick and dirty hack using plain JavaScript and CSS:

~~~ .js
ClassicEditor.create(document.querySelector('textarea')).then(function(editor) {
    var source = editor.sourceElement, // `<textarea>`
        editable = editor.ui.view.editable.editableElement; // `<div contenteditable>`
    // Set `placeholder` attribute to `<div>`
    editable.setAttribute('placeholder', source.placeholder);
    function isEmpty() {
        var v = this.textContent.trim(); // Get editor content without HTML tags
        this.classList[v ? 'remove' : 'add']('ck-editor__empty'); // Add or remove the `ck-editor__empty` class
    }
    isEmpty.call(editable); // Trigger check on initiation
    editable.addEventListener("blur", isEmpty, false); // Trigger check on editable blur event
});
~~~

CSS to show the `placeholder` attribute in editable element:

~~~ .css
.ck.ck-editor__editable.ck-editor__empty:not(:focus)::before {
  content: attr(placeholder);
  display: block;
  opacity: .5;
  pointer-events: none;
}
~~~

**Comment by oleq** [comment]
I tried to use the [`attachPlaceholder`](https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/placeholder.js#L25) helper that we use for image caption placeholders like this:

```js
attachPlaceholder( editor.editing.view, editor.editing.view.document.getRoot(), 'foo' );
```

but it fails, ditching all attributes except `data-placeholder` of the editable

![image](https://user-images.githubusercontent.com/1099479/51038910-a0f1ab80-15b4-11e9-9c36-3878b8d77cb3.png)

There are no errors, the editor runs but for obsious reasons (no `contenteditable="true"`) it's useless.

I figured that because in a view post–fixer we [set the `data-placeholder` attribute](https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/placeholder.js#L101) on a root element (normally it would be some child), when it is being (re–)rendered by the engine, all the DOM attributes (`class`, `contenteditable`, etc.) [set by the `EditableUIView`](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/editableui/editableuiview.js#L46) are forgotten. 

We have an [issue](https://github.com/ckeditor/ckeditor5/issues/798) for that and I'm afraid we must address it before we can properly attach placeholders to the root view elements.

cc @pjasiun @scofalik

**Comment by alexeckermann** [comment]
> > Is there any temporary solution available to get a placeholder in CKEditor 5 ?
> 
> @mrinaljain Here’s my quick and dirty hack using plain JavaScript and CSS:

If you want to use something in the mean time that is less of a 'hack' then check out [ckeditor5-emptyness](https://github.com/alexeckermann/ckeditor5-emptyness) (see README for example).

I'm maintaining it whilst the offical implementation is underway.

cc @tovic @mrinaljain

**Comment by oleq** [comment]
We should respond to https://stackoverflow.com/questions/48052905/how-to-add-a-placeholder-in-ckeditor-5 once the official implementation is ready.

**Comment by oleq** [comment]
@Mgsy Could you take a look at the `t/479` constellation (in ckeditor5)? 

There are some new manual tests (called "placeholder" in ckeditor5-editor-*) but also some serious changes were made to the architecture and it would be great if we knew that the editor is still rock–solid in other, normal, non–placeholder use cases.

**Comment by Mgsy** [comment]
>@Mgsy Could you take a look at the `t/479` constellation (in ckeditor5)?

I was playing with those changes and found a problem in Edge. The editor doesn't initialize and throws the error (works fine on the master):

```
 TypeError: Object doesn't support property or method 'Symbol.iterator'
   at View.prototype.attachDomRoot (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:77674:3)
   at ClassicEditorUI.prototype.init (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:38984:3)
   at Anonymous function (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:38844:19)
```

**Comment by oleq** [comment]
It looks like Edge does not offer DOM element attributes as iterable. Curious... it passed CI. Don't we run tests on Edge in CI?
