### ISSUE TITLE
Inserting image UI/UX

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5039]
https://github.com/ckeditor/ckeditor5-image/issues/6 started general discussion about image feature UI/UX. In this ticket, I'd like to start a discussion about the details of inserting images.

There are 4 ways of inserting images:

* via URL (e.g. you want to share an image from imgur.com),
* from a native file browser,
* by dropping,
* from a custom system.

**Note**: This, in fact, can be generalised to any media/files. We're talking here about images because that's the first kind of media which we'll support. In the future, this system can be extended to any embeddable file.

After a short discussion in the office, we have two proposals.

## Minimal

In this approach, there will be an "insert image" button (in the toolbar or wherever someone wants it), but it will have a minimal behaviour – i.e. it will open the native file browser. You can pick the file and it will be uploaded and inserted into the editor.

Inserting images via URL would be solved by handling pasting URLs into the editor.

And dropping images into the editor will also be handled.

There will be no support for custom systems (like CKFinder). Those systems will need to bring their own integrations – e.g. a new button.

* Advantages:
  * Light.
  * Easy to develop.
* Disadvantages:
  * Potential discoverability issues (how to insert image via URL?).
  * Handling pasting image URLs is tricky to implement. If an URL doesn't end with some known extension, then we won't be able to recognise whether this is an image (can't do cross origin request) without hacks. In such case, the user won't be able to insert that image at all.
  * Every external system may propose its own integration, potentially leading to N different designs and compatibility issues.

## Image insert panel

In this approach, there will be an "insert image" button which will open a panel in which 3 options will be available: the user will be able to either chose a file from disk, drop it into the panel, paste URL (into an input). Also, other systems will be able to integrate themselves with this panel.

Besides that, the user will also be able to drop files into the editor content and paste URLs directly into the content, like in the minimal approach.

* Advantages:
  * Good discoverability.
  * Handles all cases gracefully.
* Disadvantages:
  * Requires more coding.
  * It's hard to design external systems integration with this panel in a way to satisfy everyone.

## RFC 

Waiting for your feedback 📻 !

**Comment by robclancy** [comment]
Is this still a thing? The first thing we have had with the new editor is people uploading and saving before it is complete because the UX isn't very noticeable about the upload progress.

I'm going to disable the form submit while uploading and also (if I can with CSS) make the image fade until uploaded. But the suggestions in here for progress seem far better than what we have now.

**Comment by oleq** [comment]
We're revisiting this issue! 🎉

The main goal is allowing users to insert images via URL but also we may bring other improvements to the UX.

At this stage, we're going to drop the "placeholder" UX (first insert the placeholder, then upload/specify the URL) because:

*   once inserted, the placeholder will split paragraphs (the content in general) and removing the placeholder will not "repair" the content if the user decided:
    *   they don't want an image,
    *   they want to move it somewhere else.
*   it's a massive problem for the collaboration because for proper handling a placeholder would need to exist in the model layer of the engine and it would be shared with collaborators (what should they see? etc.)

So, at this moment there are 2 kinds of UI/UX we consider:

## Split dropdown with a menu

*   the main button face opens the native file browser for upload,
*   the dropdown section introduces a few options:
    *   inserting via URL → opens an URL form similar to media embed
    *   inserting from CKFinder → opens CKFinder
    *   other options could be configurable and developers could use them to open their own file browsers/UI

![](https://user-images.githubusercontent.com/1099479/85136546-0df48080-b240-11ea-9d0f-33a23b848049.png)

### Pros:

*   easy to implement,
*   easy to extend (possible configuration, independent integrations with a 3rd-party software),
*   we can easily re-use the "Insert via URL" ("à la media embed") UI when the user wants to do the same from the image toolbar

### Cons:

*   low discoverability – lots of features will be hidden under a small triangle next to the "Insert image" button in the toolbar,
*   multiple clicks to reach the image source URL input,
*   it looks... dated,
*   pretty hard to click the small split drop-down arrow on mobile devices (you have to zoom a lot or get lucky)

## All–in–one panel

*   UX similar to the [old mockups](https://github.com/ckeditor/ckeditor5/issues/5039#issuecomment-267009350),
*   possibility to extend the panel with 3rd-party integrations (configurable accordion items)

![](https://user-images.githubusercontent.com/1099479/85136561-1351cb00-b240-11ea-984a-069cb927fa7f.png)

### Pros

*   looks modern,
*   fewer clicks to insert an image via URL,
*   better discoverability,
*   easier on mobiles,
*   encourages users to drag&drop (some may not figure out that it is possible straight into editable)

### Cons

*   more clicks to upload an image from the hard drive,
*   way harder to extend (e.g. to add a button to open a 3rd-party file browser), a simple menu with options gives developers freedom of choice,
*   consumes more space; especially when more (custom) options will be enabled

## Important things to consider

*   The main editor toolbar may not be accessible in balloon editor then the image (widget) is selected. So there's no way to reach the main UI in this situation and some subset of features should probably (also) land in the image toolbar.
*   Before we start the implementation we need to **list all the actions** the user can take in all editor states (selected image, image not selected).
*   For consistency, the "Edit image URL" button should probably exist next to the "Link image" button we introduced in v20.0.0.

![](https://user-images.githubusercontent.com/1099479/85136578-1947ac00-b240-11ea-9e23-c712c8d80faa.png)

**Comment by panr** [comment]
Drag and drop works as expected in the editor content, so there's no need to have this inside a popup.
Also, I think that dragging an image to a popup is not a good idea (you have to handle the visibility of the popup, but you're loosing the context of the place where you want to upload an image). I would replace that area with a simple `browse images` or `click to upload` button.

**Question**
Do we consider enabling the image plugin for introducing the **replace image** option? ATM when image is selected, the toolbar option is disabled. 
  - So when you want to replace an image, you have to delete it first, then upload another image in the same place. 
  - Leaving this as it is, the only way to change an URL for the selected image is using image toolbar (with the additional option for it).

**Comment by oleq** [comment]
> Do we consider enabling the image plugin for introducing the **replace image** option? ATM when image is selected, the toolbar option is disabled.

Yes, I think we should consider this option. IMO it's a valid use–case especially when the existing image:

*   has styling that would need to be re-applied,
*   has a caption that would need to be re-typed,
*   is linked and the new one would need to be re-linked,
*   has a size that would need to be re-adjusted.

Replace image saves a lot of :point\_up:  work.

**Comment by Reinmar** [comment]
Let's conclude this topic in #7439
