### ISSUE TITLE
Dynamic content in contextual panel

### ISSUE THREAD

**Issue by kikkauz** [ckeditor/ckeditor5#520]
Hello

first of all, feel free to stop me if you think I'm running to fast.
That is to say, there is a big project to start here and ckeditor5 is the preferred candidate (I don't want to use ckeditor 4 for a project that will take months to be developed!), but I have to be sure we can do what we want.
So in a previous ticket you told me that now contextual panel is the way to go - no more panel.
I'm then trying to use them and I'm a little lost.
This is the use case: I have an external database of terms and definition and I want to add links to my document to the definition. So imagine that I type a work and then I open a contextual panel with a search input. I click on "search" and this start an ajax request to the external DB and returns me one or more result. I click on the chosen result and I have my link in the text.
So no problem opening the contextual panel, no problem running the ajax request (I'm doing it in vanilla javascript - is there any preferred method foreseen), but then how do I input the result of the ajax request in the contextual panel?
Just to give you more details, I'm following how the "link" plugin works. So I added an empty template with a div ready to be filled with the results, but I cannot fill it.

Any hint?

Thanks in advance and have a nice weekend.

Kikkauz

**Comment by Reinmar** [comment]
Hey,

Your pace is amazing and you're definitely going in the right direction :) However, it's a bit too fast for us because the UI framework's documentation will perhaps be the last part of the docs on which we'll be working.

First of all, you need to use the latest [dev version of CKEditor 5 packages](https://github.com/ckeditor/ckeditor5/wiki/Development-environment). The ones published on npm use an old API and I don't even know how it worked any more :D.

Then, you need to use the [`ContextualBalloon`](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_ui_panel_balloon_contextualballoon-ContextualBalloon.html) plugin. It manages the main editor's balloon (because there can be multiple features trying to add something to it.

ContextualBalloon accepts instances of [`View`]((https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_ui_view-View.html). Now, there are two paths:

1. You can either try to create a simple view which will become a container to which you can insert any content using any UI framework you want.
2. Or you can try to use CKE's UI framework to render everything.

Taken the early stage, missing UI components, missing docs, etc. I recommend the first approach. You can use React or Vue or whichever (light) framework you like and simply render some form into that container.

@oleq and @oskarwrobel (who know our UI lib best) are on holidays today (it's a long weekend in Poland) so I'll need to try to guess how the code should look like :D I'm copying it more or less from the `Link` feature:

```js
class MyPlugin extends Plugin {
	get requires() {
		return [ ContextualBalloon ];
	}

	init() {
		const editor = this.editor;
		const ctxBalloon = editor.plugins.get( ContextualBalloon );

		const containerView = new ContainerView( editor.locale );

		// View#element is a native HTMLElement so no magic here.
		// You can add there whatever you like.
		containerView.element.appendChild( yourUIGoesHere );

		// Show the balloon (e.g. when user clicks something):
		ctxBalloon.add( {
			view: containerView
		} );

		// Hide the balloon (e.g. when user submitted the form in that balloon):
		ctxBalloon.remove( containerView );
		// Focus the editable if the action should do so:
		editor.editing.view.focus();
	}
}

ContainverView extends View {
	constructor( locale ) {
		super( locale );

		this.template = new Template( {
			tag: 'div'
		} );
	}
}
```

In the `Link` plugin it's far more complex than this because it handles multiple weird states such as repositioning when content has changed when you're editing link's URL :D

I keep my fingers crossed for the above code to work :D Sorry if it doesn't.

**Comment by Reinmar** [comment]
I think that so much has changed since this ticket was reported that we can close it. If there are any other doubts or problems, please report new tickets.
