### ISSUE TITLE
Balloon panel sticks out of the limiter element while scrolling

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#5328]
Follow-up of: ckeditor/ckeditor5#5320 

![mar-31-2017 12-37-33](https://cloud.githubusercontent.com/assets/1057056/24547209/ec6978b0-160e-11e7-98d8-dec905b55dbc.gif)

**Comment by oleq** [comment]
The issue also appears when h–scrolling some wide content

![image](https://user-images.githubusercontent.com/1099479/66916528-ae443680-f01b-11e9-8ac7-ef259904d0da.png)

**Comment by dungkvy** [comment]
I still got this bug. How about the solution that we can hide ck-ballon-panel when scroll?

<img width="776" alt="Screen Shot 2020-02-17 at 10 02 13 PM" src="https://user-images.githubusercontent.com/54826652/74665068-82a3a980-51d1-11ea-8b59-ba8b9cbb4b41.png">

**Comment by jswiderski** [comment]
![](https://user-images.githubusercontent.com/5314687/142996605-6488c879-0ce3-4172-a61c-5d13414d5f1d.gif)

**Comment by albertfdp** [comment]
👍 We're seeing this issue at Zendesk too for image resize toolbar

**Comment by lslowikowska** [comment]
Hey @albertfdp, thank you for your comment. Would you get in touch with us at support@cksouce.com? We might have more questions for you regarding this issue. Hope to hear back from you soon 👋

**Comment by Dumluregn** [comment]
Let's start with creating a PoC according to @oleq 's guidelines that will appear below soon.

**Comment by oleq** [comment]
I think there's an alternative solution to what I proposed in https://github.com/ckeditor/ckeditor5/issues/5328#issuecomment-294888313.

* We could replicate the powered by logo logic to **some** extent https://github.com/ckeditor/ckeditor5/blob/01ea41e10e296ba2c64afd896f1168ba4e7e2e8c/packages/ckeditor5-ui/src/editorui/poweredby.ts#L321-L327
* The idea is not to hide the element if it becomes "unpositionable" but position it far away from the viewport.
   * 👍 The element retains focus, so we don't have to worry about focus management. The change is also transparent to screen reader users.
   * 👎 In theory, the user could do something by accident because the positioned UI is still there and have focus, so typing in it or pressing enter could execute some actions.
* We could incorporate this into the `getBestPosition()` helper https://github.com/ckeditor/ckeditor5/blob/01ea41e10e296ba2c64afd896f1168ba4e7e2e8c/packages/ckeditor5-utils/src/dom/position.ts#L152-L155
* The helper would yield a far-off-the-screen position if none of the available ones would guarantee that the positioned element is not cropped.
* This way we spare ourselves the hassle of hiding and showing the positioned element (balloon), which includes focus management and such (see my previous attempt from 2017).
   * Note that if you hide a balloon that has a focused input, the focus must return to the editing root. Otherwise, the editor will lose focus altogether which is unacceptable. Managing this would require a communication bridge between `getOptimalPosition()` helper and every UI controller (e.g. `LinkUI`, `TableToolbar` etc.). I'd like to avoid that because this would require a lot of work.

**Comment by mlewand** [comment]
## Problems that we have today

<table><tbody><tr><td>Screen</td><td>Reason</td><td>Solutions</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/32898551/256222062-82dfa3a0-a496-4928-8429-4d4d42d33766.png"></figure></td><td><a href="https://github.com/ckeditor/ckeditor5/issues/14668">Balloon leaking outside of a browser viewport.</a></td><td><ul><li>Account for browser viewport (or parent viewport?) to be a limiter too</li></ul></td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/32898551/256219465-4b87b7bf-fe0d-46d9-9c6e-588b652ac6cf.png"></figure></td><td><a href="https://github.com/ckeditor/ckeditor5/issues/14667">The balloon overlays the caret.</a></td><td><ul><li>Selection edge caret should be considered a blocker.</li><li>Make a common rectangle of all selected ranges to be a blocker.<br><span>:point_up:</span>&nbsp;This could be too generous,think of long content where you use "select all" feature.</li></ul></td></tr></tbody></table>

**Comment by oleq** [comment]
@mlewand What we need here is a complete understanding of all use cases that we have to address. These two only prove that we're missing the big picture. There could be more.

There are two options used in `getOptimalPosition()`: `limiter` and `fitInViewport`. They are used by different editor features in different ways to satisfy different user stories. https://github.com/ckeditor/ckeditor5/pull/14630 proved that we don't understand these user stories well and we're shooting in the dark. We focused on a manual test with specific corner cases and we missed the others.

Let's aggregate all user stories somewhere first (Figma?). That will help us understand and rethink the concepts of limiters and fitting in the viewport. My gut tells me they don't mean the same thing when we start making sure balloons get hidden when their target gets out of sight.

**Comment by oleq** [comment]
Yet another related issue https://github.com/ckeditor/ckeditor5/issues/7388#issuecomment-1663423751
