### ISSUE TITLE
Remove @ckeditor/ckeditor5-build-balloon-toolbar from npm

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#549]
A follow up for #548.

Now we have this:

![screen shot 2017-09-07 at 20 31 35](https://user-images.githubusercontent.com/545175/30179178-cc3f7910-940b-11e7-8454-edc20bf3a6ff.png)

Proposed steps:
 - remove `ckeditor5-build` keyword from it immediately
 - add meaningful description that it has been renamed to (...)
 - drop completely once the next version of CKEditor 5 is out, I guess it has not been adopted widely yet ;)

Alternative steps:
 - drop now

![screen shot 2017-09-07 at 20 33 50](https://user-images.githubusercontent.com/545175/30179226-efd7a28a-940b-11e7-9048-7c64c3d2adb4.png)

**Comment by pomek** [comment]
In order to remove package, the owner (a person who pushed it) must send a message to npm. I had to do the same when I pushed 'ckeditor5' to npm by mistake.

**Comment by Comandeer** [comment]
Maybe instead of totally removing it, just use [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) to add warning about rename for every user installing this package via npm?

**Comment by Reinmar** [comment]
Removing is indeed complicated and leave an empty package page where, I think, you can't leave any info. Additionally, removing is more problematic for us because it makes installing some past versions impossible.

I'd check `npm deprecate`. And I'll add warnings and stuff to those renamed/removed packages (this also includes the old ckeditor5-dev-* ones and ckeditor5-presets in a moment).

**Comment by Reinmar** [comment]
I deprecated and marked as removed these packages:

* https://www.npmjs.com/package/@ckeditor/ckeditor5-build-balloon-toolbar
* https://www.npmjs.com/package/@ckeditor/ckeditor5-editor-balloon-toolbar
* https://www.npmjs.com/package/@ckeditor/ckeditor5-dev-compiler
* https://www.npmjs.com/package/@ckeditor/ckeditor5-dev-bundler-rollup

For the future reference, I've been deprecating them e.g. with:

```
npm deprecate @ckeditor/ckeditor5-dev-bundler-rollup "☠ This package is not supported anymore. See https://github.com/ckeditor/ckeditor5-dev/issues/268. ☠"

npm deprecate @ckeditor/ckeditor5-build-balloon-toolbar "☠ This package was renamed to @ckeditor/ckeditor5-build-balloon. ☠"

npm deprecate @ckeditor/ckeditor5-presets "☠ This package is not supported anymore. Use @ckeditor/ckeditor5-essentials instead. ☠"
```

**Comment by Reinmar** [comment]
BTW, since I published empty `ckeditor-build-balloon-toolbar` (using an empty `package.json` as shown below), those packages are also out of:

![image](https://user-images.githubusercontent.com/156149/32889052-9830dc78-cac9-11e7-89ff-265a0114b2e3.png)

And it's nicely marked on the list:

![image](https://user-images.githubusercontent.com/156149/32889068-a6e69dac-cac9-11e7-8a5d-e24926bfc5da.png)

Sample `package.json`:

```
{
  "name": "@ckeditor/ckeditor5-dev-bundler-rollup",
  "version": "6.0.0",
  "description": "☠ This package is not supported any more. See https://github.com/ckeditor/ckeditor5-dev/issues/268. ☠",
  "author": "CKSource (http://cksource.com/)",
  "license": "(GPL-2.0 OR LGPL-2.1 OR MPL-1.1)",
  "homepage": "http://ckeditor.com"
}
```
