### ISSUE TITLE
contextualToolbar -> balloonToolbar?

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#550]
_I edited my initial, longer report as I realised I was wrong regarding the lack of possibility of setting the toolbar of balloon editor via config.toolbar_

----

A detail, but I wonder whether `config.contextualToolbar` shouldn't be renamed to `config.balloonToolbar` (same with the class name - ContextualToolbar). I think at some point we came to a conclusion that the toolbar isn't actually contextual.

**Comment by Reinmar** [comment]
> I edited my initial, longer report as I realised I was wrong regarding the lack of possibility of setting the toolbar of balloon editor via config.toolbar

Yes, this is something which was tricky for us. The `BalloonEditor` uses `ContextualToolbar` plugin to implement the toolbar. That's because that functionality was only exposed in form of a plugin which can only be configured through the config option.

To straighten this up we'd need to split the plugin to `ContextualToolbarController` (ekhm for the "controller") and `ContextualToolbar` which only glues a couple of things together. This is in line with https://github.com/ckeditor/ckeditor5/issues/425.

After such refactoring, this will be the state of things:

* `BalloonEditor` will use `ContextualToolbarController` and will not have to silently load the plugin and fill `config.contextualToolbar` with what's in `config.toolbar`.
* There will still be two options in `EditorConfig` – `toolbar` for the "editor toolbar" configuration and `contextualToolbar` for the plugin configuration. This is still a bit problematic, but it's hard to resolve. Perhaps we should've had defined plugin configs completely separately from editor config, but that was far beyond our perspective inherited from CKE4.

   However, one thing we can do here now is to extract `config.contextualToolbar` to a separate interface, just like with `config.image` and `config.heading`. This will, hopefully, better indicate that this is separate plugin's config.

---

Regarding renaming... definitely. I've just noticed that `ContextualToolbar` uses `BalloonPanel` and is used in `BalloonEditor` :D. The `Ctx` prefix made sense only when it was related to the editor name.
