### ISSUE TITLE
Cleanup modules in CKEditor 5 (?)

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#556]
Not sure if it's by design :-o or just an overlook. API docs for utils already look like that:

![screen shot 2017-09-11 at 22 08 35](https://user-images.githubusercontent.com/545175/30294875-f7726eae-973e-11e7-9d65-f4e02d1e4809.png)

I wonder what's the reasoning for keeping e.g. nth, first, isiterable in separate modules. Same with e.g. comparearrays, diff.

The issue is also present in other packages, e.g. link/findlinkrange looks weird.

**Comment by oskarwrobel** [comment]
Related https://github.com/ckeditor/ckeditor5-utils/issues/12.

**Comment by Reinmar** [comment]
I'm afraid that while looking bad initially, this is correct. I mean – there are reasons to keep these utils in separate files (grouping them in meaningful files would be a never ending problem and a reason for constant breaking changes). And since they are in separate files, they are separate modules, and hence are displayed in our docs like this. We'd need to be inconsistent to display them differently.

One thing which might be considered is having separate files like we have now, but just one entry point with multiple exports. However, this wasn't a reasonable solution in the past taken that tree-shaking wasn't available in Webpack which would result in bigger output.

Anyway, I don't think that we have a big problem here. We could try to improve how we render the docs, but I would not change the code because of the docs.
