### ISSUE TITLE
CKeditor uploaded image selected by default makes users remove the image if they type anithing after insert the image

### ISSUE THREAD

**Issue by awill2** [ckeditor/ckeditor5#5567]
When a user send or insert an image, this image by default get selection, this is a big problem to me because if a user insert a image and type anithing, because the image is selected, the image is removed. The user doesnt know they need to click outside the image after insertion, this is annoying. Is there a way to prevent this?

**Comment by mlewand** [comment]
This behavior is actually by design, and we want to stick to this behavior. It has several benefits:
* it allows you to edit images right after it was inserted (alignment, alt, catpion etc),
* it also provides better accessibility e.g. screen readers announce that now the image is focused, thus user gets a feedback that image has been inserted correctly.

There are ways to get around this conveniently, for instance there's a feature that if you press `enter` key while having an image focused, you'll get a new paragraph below the image with the selection moved there - and you can start typing.

Also you can simply press left/right arrow and continue from there.

**Comment by awill2** [comment]
Is there anyway to circunvent this behavior? Like send an enter keypress event or call this function that add this paragraph when image is ready? How can i do that?

Thank you.
