### ISSUE TITLE
Table styles output: collapse or to not collapse?

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5575]
## 📝 Provide a description of a problem

We want to introduce styling tables in the #3287 which will include styling table cells' borders. Unfortunately, HTML/CSS does not have the best control over this when you wish to have collapsed borders.

With `boder-collapse: collapse`:
- tables are generally prettier
- you have 1px borders between cells
- to style visually borders on the cell you have to style `border-bottom` of a cell above and `border-right` of a cell on the left
- if border width is bigger then default (adjacents' cells) it wins

With `border-collapse: separate`:
-  tables have a retro look
- minimum width of a border (with cell spacing set to 0) is 2px (1px from adjacent cells' borders)
- styling visually borders is pretty straightforward: you setting collor only for the selected cell

To visuallise this:

setting | 
same width: `1px` | blue border: `2px` 
---|---|---
`border-collapse:collapse` | ![Selection_017](https://user-images.githubusercontent.com/247363/66652386-e6bbcd00-ec35-11e9-9987-ecc4199f316e.png)  |  ![Selection_022](https://user-images.githubusercontent.com/247363/66652435-03580500-ec36-11e9-8279-942e45cb1b62.png) 
`border-collapse:separate` | ![Selection_019](https://user-images.githubusercontent.com/247363/66652406-f3d8bc00-ec35-11e9-989e-3ffc831ac043.png) | ![Selection_020](https://user-images.githubusercontent.com/247363/66652459-0ce16d00-ec36-11e9-9088-37daeef18657.png)
`border-collapse:separate` `spacing:0` | ![Selection_018](https://user-images.githubusercontent.com/247363/66652644-782b3f00-ec36-11e9-8d11-fd1680adede0.png) | ![Selection_021](https://user-images.githubusercontent.com/247363/66652651-7ceff300-ec36-11e9-8cf2-31c1779afd00.png)

The problem is with
- what should be the default style
- how to style the content (should we do the trick with coloring adjacent bordres when in collapsed mode?)

Are there any industry standards for sytling table cells' borders? The content paster from other sources would usually have border collapsed and styled borders of adjacent cells and only styled only bottom/right in styled cell (Google docs does both, tyles top,right,bottom,left of the current and bottom/right of adjacent top/left cell).

ps.: disabling border on the table for collapsed borders renders also the left border of first cell in a row: 
![Selection_023](https://user-images.githubusercontent.com/247363/66653283-f5a37f00-ec37-11e9-93a0-e7e2bf61e57e.png) ![Selection_024](https://user-images.githubusercontent.com/247363/66653318-0653f500-ec38-11e9-8731-febf5a652dfa.png)

**Comment by Reinmar** [comment]
All HTML-oriented editors which support styling table cell borders (this will be just two... CKEditor 4 and TinyMCE) that I checked currently don't handle this well. If you try to change the borders of the middle cell to blue, only this `<td>`'s style will be changed leading to a broken visual effect.

At the same time, I can't remember people going mad about this. Why? Because by default in CKEditor 4 we have separate borders. Which, I agree, looks heavy and old. And just unnecessary – table is a table, a grid. Not a "set of cells" like the default browsers styles show it. That's no option for us to have separate styles by default.

Therefore, what I'd do:

1. Go with collapsed borders and this naive border setting behavior. 
   * It will work well for people who don't allow styling table cells (it may be most of them).
   * It will work well for people who only paste tables (e.g. from Word) because pasted content is styled correctly – this is – Word or Google Docs set the `border-bottom` and `border-right` styles of adjacent cells. 
   * We can document that if you plan to enable the TableCellBorder plugin, you should rather consider adding `.ck-content table { border-collapse: separate }` to your stylesheet due to this issue.
2. One day, perhaps we can implement smart styling where in the model we'd have what we have now (border is set only for the cell you modified) but the view would be different.

**Comment by Reinmar** [comment]
I'm moving this to "Ready to start". If you agree with me @jodator and @oleq, let's close this as done.

**Comment by oleq** [comment]
> table is a table, a grid. Not a "set of cells" like the default browsers styles show it. That's no option for us to have separate styles by default.

I agree, no one uses tables with separate cell borders (`border-collapse:separate`) these days. 

> Go with collapsed borders and this naive border setting behavior.

I'm also for whatever is most compatible with the pasted content from GDocs/MS Word.

**Comment by panr** [comment]
https://codesandbox.io/s/objective-haibt-ibx59

This is my POC of how we can replace borders for box-shadow hacks (just in case we need this in the future).

**Comment by jodator** [comment]
What worries me with anything different from `border:` styles is that such content will not be transfered to other editors.

**Comment by Reinmar** [comment]
Final decision: https://github.com/ckeditor/ckeditor5/issues/5575#issuecomment-554408358
