### ISSUE TITLE
Unable to use CKEditor5 Framework in Aurelia Application

### ISSUE THREAD

**Issue by maamirh** [ckeditor/ckeditor5#5639]
## 📝 Provide detailed reproduction steps (if any)
I want to use CKEditor5 in my Aurelia based Application and i followed this guide 
https://ckeditor.com/docs/ckeditor5/latest/framework/index.html

Followed each step by step but getting no result editor is displaying in browser and no error is showing in console.

put a question on stackoverflow too.
https://stackoverflow.com/questions/58475916/how-to-integrate-ckeditor5-in-aurelia-application

### ✔️ Expected result
Kindly give suggestion or introduce special version for Aurelia Framework
*What is the expected result of the above steps?*

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ma2ciek** [comment]
Hi @maamirh,

Thanks for the issue. However, this is not the best place to track it.

I guess that SO is the best place to look for help in case of custom integrations. This is actually neither a bug nor a feature request and it happens probably because of incorrectly used framework or webpack configuration. And, unfortunately, we don't provide any official support for the Aurelia framework.
