### ISSUE TITLE
Inserting a space before a block Element in Firefox will replace it with `@@`

### ISSUE THREAD

**Issue by zireael-0** [ckeditor/ckeditor5#5651]
You need a view-model and DOM that has `[Text, Element]` anywhere with the elements `HTMLElement` conforming to `display: block`.

Moving your caret to the last position within your first Text and appending a space will delete the element and replace it with `@@`.

As far as I can tell, this issue comes from Firefox inserting a `<br />` out of nowhere,  breaking  the CK InjectTypingMutationsHandling module. In it's `handle` method the `containerChildrenMutated` check will somewhat mistakenly succeed and will result in mutating the model incorrectly due to the unexpected new element.

You can observe the differing behavior between Chrome and Firefox with a simple html file and using the inspector of each browser. Placing the caret behind the `t` of the first `text` and hitting space will insert a new `<br />` element.
```
<!DOCTYPE html>
<html>
<head></head>
<body>
<div style="border: 1px solid black" contenteditable="true">
text
<div>text in block</div>
</div>
</body>
</html>
```

I'm not sure if this is expected behavior from Firefox. Maybe it's worth considering to file an issue there, too.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Sorry for the late response. Can you share detailed steps on how to reproduce it in CKEditor 5 with recorded screencast?

**Comment by LinkiPinki** [comment]
Sure thing. I've set up an example editor build [here](https://github.com/LinkiPinki/ckeditor5-firefox-quirk-demonstration).

If you clone the repository and run
```
npm install
npm run build
```
and open the generated `out/index.html` file in firefox, you should see an editor with a single button.

Try typing in some text and click the button when the caret is positioned after the text. It should insert a `<div><img /></div>` constellation, showing an example image from wikipedia.

If you move the caret to the end of the text and insert a space, the container is removed and replaced with `@@`. As far as I can tell this happens due to the `<br />` element Firefox unexpectedly inserts and the `containerChildrenMutated` module not being able to map the DOM correctly anymore. Here is how it looks on my machine:

![atat](https://user-images.githubusercontent.com/20943907/68391121-28716200-0167-11ea-8bc4-5d3085eb9c50.gif)

However (in my example) you can observe a different behavior, when you change the schema in the `blockElementPlugin` I included. Setting the block element schema to `isInline: false` and hitting space at the same position will just do nothing instead.

In chrome both cases work just fine.

**Comment by Mgsy** [comment]
Thanks for a detailed description and live sample! I can confirm this behaviour. 

@jodator, can you investigate it?

**Comment by jodator** [comment]
It's a bit similar to #5613 & #1049. Basically the elements that act as blocks should be blocks (like image) and they shouldn't be nested in other blocks.

If  you change your schema to:

```js
this.editor.model.schema.register( MODEL_ELEMENT_NAME, {
	allowIn: '$root',
	isObject: true,
	isBlock: true
} );
```

and you'd use `model.insertContent()` in your command:

```js
class InsertBlockElementCommand extends Command {
	execute() {
		this.editor.model.change( writer => {
			const modelElement = writer.createElement( MODEL_ELEMENT_NAME );

			this.editor.model.insertContent( modelElement, this.editor.model.document.selection );
		} );
	}
}
```
You'd insert your `<genericBlock>` between paragraphs or you'd split existing ones. Generally the `model.insertContent()` is your friend here ;)

But this would cause other problems with positions mapping (you could place position inside `<div>` in the editing area and the whole thing would blow up.

Bonus: use widget in the editing pipeline (remember to include `Widget` plugin):

```js
this.editor.conversion.for( 'editingDowncast' ).elementToElement( {
	model: MODEL_ELEMENT_NAME,
	view: ( element, writer ) => {
		const containerElement = writer.createContainerElement( 'div' );
		const imgElement = writer.createEmptyElement( 'img' );

		writer.insert( writer.createPositionAt( containerElement, 0 ), imgElement );
		writer.setAttribute( 'class', 'image-container', containerElement );
		writer.setAttribute( 'src', 'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg', imgElement );
		writer.setCustomProperty( 'genericBlockElement', true, containerElement );
		
		return toWidget( containerElement, writer ,{ hasSelectionHandle: true });
	}
} );
```

![Peek 2019-11-13 15-22](https://user-images.githubusercontent.com/247363/68772186-a7fca680-0629-11ea-9782-270541fc8d54.gif)

**Comment by LinkiPinki** [comment]
Thanks for the response. However, I am not sure if I am satisfied with it:

You're correct that this example yields the same behavior when you do not use nested block elements. However that will no longer be the case if you try to let the image `float` around the text using CSS. 

As far as I can tell, moving it out of the paragraph will make the text float around the image, but it becomes impossible to align the image so that it is not at either the very top or very bottom of the paragraph.

Also it's kinda odd that my version works fine in Chromium-esque browsers - I actually though putting blocks between texts would be an okay thing to do.

**Comment by zireael-0** [comment]
Closing this since it's very old and likely doesn't need a fix (anymore)
