### ISSUE TITLE
Autolink selected text on link paste

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5656]
## 📝 Provide a description of the new feature

We have the #4715 (auto-link feature) so this might duplicate in some sense.

While using Notion I've discovered one handy feature by accident:

1. Select a text
2. Paste link
3. The selected text get a link added instead of being replaced by the pasted link text.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
Business context:

*   If clipboard contains URL and text is selected inside the editor, after paste, we want to apply link on the selection instead of replacing the selection with the clipboard content.
*   If the selection includes more than one element, then we want to keep the earlier behavior (selection content is removed, clipboard content is inserted).
*   Images on links are nicely handled, so we can apply the same logic for images (pasting link over image adds link to the image).
*   We will handle just text and images. Tables or other widgets will work as earlier.
*   Clipboard must include link and only link.
*   If formatted link was copied (e.g. a link that had bold, etc.) then we also apply the described behavior.
*   If selected text has link already we replace that link (in other words, it doesn't matter if selected text has a link, we still apply described behavior).

Technical notes:

*   When it comes to checking whether clipboard data is an URL, we have RegExps in Link plugin so we can look there.
*   Clipboard also "saves" plain text contents, in addition to HTML contents, so we don't need to strip formatting on our own (dataTransfer type -> text/plain).
*   The improvement should most probably land in Link plugin as clipboard should not know anything about links or other features.
*   This improvement should use LinkCommand and should be applied only if LinkCommand is enabled. This covers integration with multiple parts of the editor.

**Comment by scofalik** [comment]
Aaaand it appears that our friend @mlewand already prepared a plugin for this some time ago: https://github.com/mlewand/ckeditor5-paste-link
