### ISSUE TITLE
Webpack stops supporting named JSON imports 

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#5660]
## Provide a description of the task

We use it in the [version.js](https://github.com/ckeditor/ckeditor5-utils/blob/b998277f789c94bcb7ff2933b628ddd1ab806e10/src/version.js#L12) to provide the duplication check.

As a solution we could either:

* import the whole package.json and use only the `packageJson.version` field
* dynamically set the constant during the build time

Maybe even the mix of those two as the second solution we could implement in our builds through the `CKEditorWebpackPlugin`, but it would work only for people using the `CKEditorWebpackPlugin`.

See:
* [Webpack migration guide](https://github.com/webpack/changelog-v5/blob/master/MIGRATION%20GUIDE.md#cleanup-code)
* https://github.com/ckeditor/ckeditor5-utils/pull/311

The topic is also connected to the [ability to check the duplication code during the compilation](https://github.com/ckeditor/ckeditor5/issues/1692).

**Comment by ma2ciek** [comment]
cc @Reinmar @mlewand.

**Comment by Reinmar** [comment]
> * import the whole package.json and use only the `packageJson.version` field

How'll that work with tree-shaking? I'd love to avoid bloating the build with the rest of pkg.json.



> * dynamically set the constant during the build time

That's unfortunately, something we don't control. It needs to work without any configuration. So, I'd rather say that it needs to be done on publish to npm, so we've got it set there for `@ckeditor/ckeditor5-utils` and `@ckeditor/ckeditor5-build-*`. But, if we can keep the today's automatic, clean solution, then that'd be preferable.

**Comment by ma2ciek** [comment]
According to https://github.com/webpack/webpack/issues/9802#issuecomment-548143508 an advanced tree shaking mechanism should be available for JSON imports soon, which is great news for us. So once the webpack 5 is available we can change this import without worrying that the code will be bloated.

Thanks @tonykiselis for letting me know about it :)

**Comment by pomek** [comment]
We decided to hardcode the version of CKEditor 5 because Webpack 5 throws a warning when we try to use named JSON imports (as mentioned above).

We could use an extended version of the import (as proposed in https://github.com/ckeditor/ckeditor5-utils/pull/311) but Webpack replaces the entire JSON object with a string and used `JSON.parse()` to read it. It means that the entire content of `ckeditor5/package.json` will be visible in the bundle. I thought that Terser could remove unnecessary entries but unfortunately, it doesn't. 

We also thought about a second way to resolve the problem – set the version during compilation. But it means that users will need to configure one more plugin (in webpack config) and the whole process will be even more complicated.
