### ISSUE TITLE
Enable missing features in CKEditor 5 builds

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#567]
* https://github.com/ckeditor/ckeditor5-adapter-ckfinder
 * The Easy Image plugin once it's open sourced.

**Comment by Reinmar** [comment]
Should the "Insert image" button be available in those builds too? I know that it should not appear automatically in the toolbar, but should the plugin be enabled?

Please note that I'm asking for the future, because by a mistake, `ImageUploadButton` is now automatically loaded by `ImageUpload` plugin. This will change together with https://github.com/ckeditor/ckeditor5-upload/issues/22.

**Comment by wwalc** [comment]
Shouldn't we track it in a separate ticket as it's a completely separate issue?
The original issue was about two particular plugins which were already included, hence this issue could be closed.

The new issue could be about the Image Button and our strategy towards it. For example I have some concerns regarding mobiles. On mobiles the only reasonable way to insert an image is a toolbar button. If it's not available in Builds by default then there is a "?" regarding basic support for mobiles by CKEditor 5 Builds.

**Comment by Reinmar** [comment]
> Shouldn't we track it in a separate ticket as it's a completely separate issue?

If it turns out that complicated choice then yes. Here you are: https://github.com/ckeditor/ckeditor5/issues/570

**Comment by Reinmar** [comment]
Done:

* https://github.com/ckeditor/ckeditor5-build-classic/commit/668691f3d06c0924756228e3cfcf075cd7a6e34b
* https://github.com/ckeditor/ckeditor5-build-inline/commit/d1526fa2abdb1676e128c46e4c7881edeb36ca3d
* https://github.com/ckeditor/ckeditor5-build-balloon/commit/e74806e65ee3dae5da4200bd350db27673210747
