### ISSUE TITLE
Restricted editing

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5683]
## 📝 Provide a description of the new feature

This enhancement would allow to run the editor in two _editing modes_:

* standard mode,
* restricted mode.

The feature would allow to mark editor's content part as an editable part (see _Marking as editable part_).

_Editing mode_ can changed at a ~runtime, via an API call.~ by configuring the editor. The modes should be operated by different users so there is no need to switch it in the same editor.

### UC: Marking as editable part

Marking any part as editable should be possible only while in **standard mode** and it should be doable using a button. Below is an example UC:

1. Select a part of paragraph.
2. Click the "Enable editing" button.

#### ✔️ Expected result

* Selected part is marked as editable in the restricted mode.
* Selected part gets additional styling indicating that it's editable in the restricted mode, let's make it a yellow background with some subtle outline that would differentiate it from yellow text background.

### UC: Editable part toggling

1. Select a part that **is already editable** in the restricted mode (denoted by yellow highlight).
2. Click the "Enable editing" button.

#### ✔️ Expected result

* Selected part is no longer marked as editable in the restricted mode.
* Visual marker is gone.

## 📃 Other details

I intentionally didn't use _full editing_ mode as it might bring up some historical connotations with our lovely full package 🙂

---
Restricted editing mode enhancements (part III - follow-up PRs)
- [x] names of plugins, commands, etc
- [x] review approach of enabling commands - maybe better would be using schema - would be better with clipboard - one configuration).

Follow ups:
- placeholders of editable fields https://github.com/ckeditor/ckeditor5/issues/5804
- enable clipboard: https://github.com/ckeditor/ckeditor5/issues/5802

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by dkonopka** [comment]
## Icon

Two proposals here, I prefer the first one, but it might be confusing for the user because eg. restricted editable won't work for blocks of paragraphs.

![restricted-icon1](https://user-images.githubusercontent.com/10219857/68771291-0f195b80-0628-11ea-8f6c-36e7ad404431.jpg)
![restricted-icon2](https://user-images.githubusercontent.com/10219857/68771292-0f195b80-0628-11ea-8611-05c7021d2074.jpg)

## Dropdown proposal
During the research of restricted editing in the Microsoft Word, I have found a decent improvement of this feature: moving between editables. Maybe it's worth to consider it after MVP implementation.

![restricted-dropdown](https://user-images.githubusercontent.com/10219857/68771507-71725c00-0628-11ea-8ae7-48c2fdcb2821.jpg)

## Highlight color
Word is using light yellow color for their restricted editables and it could work for us too, but we have also comments with a similar color. So I would propose something similar - orangish. In comparison, I'm adding here a "blue mockup" also.

### Orangish
![restricted-orangish](https://user-images.githubusercontent.com/10219857/68771817-02e1ce00-0629-11ea-9ec5-05aeae3c8f8b.jpg)

### Bluish
![restricted-blue](https://user-images.githubusercontent.com/10219857/68771840-0f662680-0629-11ea-8073-b4f95f3d3857.jpg)

## Highlight style

It was a kinda tricky thing because I have been there during research on track-changes / comments & user selection features. To sum up, I'm recommending to mark editable areas similar to the [highlight plugin](https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html#demo) way,  but also Microsoft Word solution ( `[` `]` braces) might work out too.

### Bordered highlight (looks buggy)
![restricted-bordered](https://user-images.githubusercontent.com/10219857/68772619-65879980-062a-11ea-851c-dbb3a64f9fac.jpg)

### Braces highlight (Word solution)
![restricted-braces](https://user-images.githubusercontent.com/10219857/68772661-733d1f00-062a-11ea-8c23-b066fd97c978.jpg)

### Braces solution demo:
<img width="1729" alt="Screenshot 2019-11-13 at 12 53 11" src="https://user-images.githubusercontent.com/10219857/68772689-805a0e00-062a-11ea-8afe-ec6a791f19e0.png">

**Comment by jodator** [comment]
To track the progress of the feature I've added a detailed list with things to do in this task - not that the list may change.

**Comment by jodator** [comment]
After implementing plugins for the "standard" mode - in which content creators will mark parts of the content as "exceptions" in the "restricted" mode - I'm not sure if we should focus on "opening" parts of text rather then "locking".

As for now, I think that the button shouldn't be named "Restricted Edting" and maybe it's UI should be focused on the "opening" (adding exceptions) to the parts of texts.

In the draft PR I've renamed this part of the `RestrictedEditing` feature to `RestrictedEditingException` (the name is still open to change of course).

**Comment by Reinmar** [comment]
Notes from the call about the UI:

---

## Standard mode

- Which icon?
    - When on normal text: `[unlocked lock]`, "Enable editing" title
    - When on exception: `[unlocked lock]` "Disable editing" title
    - Should icon show the state or the action of the button?
        - Answer: the icon should reflect what the "on" state of that button is.
- Highlight styling
    - color
        - follow MS?
            - collides with our comments
        - orange seems fine
    - start/end markers – 👍
        - `[foo]`
        - positioned :after/:before `content:'[/]'`
            - slightly unsafe - because it's a selectable content
        - positioned :after/:before with some borders to pretend `[/]` characters - should be safer
            - will solve the empty element case - it will always be visible
            - such brackets are not selectable - which is good

## Restricted mode

- Dropdown?
    - Easier navigation between editable regions
    - Fine for MVP
    - Should show keyboard shortcuts
    - Future: Balloon with next/prev like in a11ychecker
        - Problem: conflict with link and other balloons
    - Label: "Previous/next editable region"
    - Icon: as proposed – lock next to a text
- How will brackets work here?
    - If we'll choose the :after/before + borders, then it's completely transparent
- Styling when inside a certain editable region
    - Non-MVP: Opacity for non-editable text?
        - Is it technically possible?
        - It seems so - we should be able to easily wrap all non-editable text and blocks with some spans
    - Hover style
        - When outside: cursor:pointer?
        - When hover: cursor:text?
        - No decisions so far – let's test it live
    - Selection inside style
        - No decisions so far – let's test it live
- Conclusion: We'll refine those styles when we'll be able to see this live.
