### ISSUE TITLE
Extracted CSS failed to import at React App

### ISSUE THREAD

**Issue by MahediSabuj** [ckeditor/ckeditor5#5687]
## 📝 Provide detailed reproduction steps (if any)

1. CLone [ckeditor5-build-classic](https://github.com/ckeditor/ckeditor5-build-classic) from GitHub repository
2. Install `mini-css-extract-plugin` and `css-loader` to extract css from the build
3. update `webpack.config.js` as shown [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-extracting-css)
3. Run `yarn build`
4. It creates css file as expected.
5. import the css file at React App.
6. Run `yarn build` at React App.
7. It failed to compile.

### ✔️ Expected result

Successfull build.

### ❌ Actual result

![image](https://user-images.githubusercontent.com/35859676/67803453-41b74600-fab7-11e9-8579-3d028963ac3d.png)

## 📃 Other details

* Browser: … Google Chrome
* OS: … Windows 10
* CKEditor version: … 15.0.0
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @pomek Could you check this?

**Comment by pomek** [comment]
I'm sorry for the late response.

@MahediSabuj, could you share your full webpack config?

**Comment by MahediSabuj** [comment]
@pomek, check the below link

[webpack.config.js](https://github.com/ms-29/ckeditor5-build-classic/blob/2dc114ccaa7b539a93f5953900afae03bc3ac212/webpack.config.js)

**Comment by pomek** [comment]
Ok, I read the issue once again and it's obvious that Webpack works because the file (.css) was generated.

I'm able to reproduce your issue. However, it doesn't seem like CKEditor 5 problem. React-scripts cannot _load_ minified CSS file but they do not throw any error if the same file is not minified.

Works for non minified CSS:

![image](https://user-images.githubusercontent.com/2270764/70215850-a9a81e80-173e-11ea-8f74-f8688330104e.png)

![image](https://user-images.githubusercontent.com/2270764/70215915-cfcdbe80-173e-11ea-8494-684a160cb012.png)

Throws the error for minified CSS:

![image](https://user-images.githubusercontent.com/2270764/70215891-bfb5df00-173e-11ea-8c40-a9692e705e02.png)

If you use the `eject` mechanism (which allows modifying webpack configs), you could disable parsing the file. In other words, webpack instead of loading, parsing, modifying and etc. the file could just put the entire file to bundle.

Generated CSS from our side is a correct CSS file.

**Comment by mlewand** [comment]
Thanks @pomek for explanations.
