### ISSUE TITLE
Create a list of all end-user features

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5702]
Currently, it's a bit hard to quickly skim through all features that we support. There's only the sidebar on https://ckeditor.com/docs/ckeditor5/latest/features/index.html, but it doesn't list all of the options, just categories. Plus, some of those categories are a bit bloated like the collaboration section or image upload.

I'd like to see a better compilation of available end-user features in the content of https://ckeditor.com/docs/ckeditor5/latest/features/index.html.

This list can, besides just listing the names of the features, also list all available plugins. This is actually an idea which I heard from our community – that we don't list somewhere all the available plugins.

**Comment by godai78** [comment]
This will be (at least partially) covered by this issue https://github.com/cksource/content-documentation-proofread/issues/332 aiming at discoverability. In the end the features overview/landing page will be rewritten to accommodate more "tag cloud" to features relations. This is also achieved through the "Related features" block gradually added to all the guides.

**Comment by godai78** [comment]
As for the plugin list, the [https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/features-html-output-overview.html](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/features-html-output-overview.html) kinda covers that scope.

**Comment by magda-chrzescian** [comment]
> As for the plugin list, the https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/features-html-output-overview.html kinda covers that scope.

I'm not sure if it actually covers the scope - it is not really more readable than the table of contents on the left. I feel like we are still missing some kind of table, where all of the features and plugins would be displayed in a more structured way so that you can scan them with your eyes easily.

I would see it as a table with information about each feature, which plugins does it incorporate, in which builds are they enabled by default. There also might be a link to the API docs, configurations, HTML output page, we could show relations between plugins... and many more, I'm not sure how far we can go keeping the table readable - it needs some design.

Also, though we have the plugins list on the HTML output page, I'm not sure if I would think of opening it looking for that list. Also, it is not very clear visually. Moreover, searching for the "plugins list" gets us here:
![image](https://user-images.githubusercontent.com/14334820/125605471-2c2b7a77-972d-4b4b-99d5-f664c67f3a0e.png)
As a follow-up, we need to identify the list of the "most wanted" keywords in our documentation and make sure that they are possible to find easily.

---

We might also think about how the documentation features page refers to the marketing features page (which is actually the second result in the google search for "ckeditor5 features", after our documentation).
* What do we want to say in the documentation other than on the marketing page?
* Do we want to duplicate information?
* Do we want to link these pages? How?

**Comment by godai78** [comment]
I meant more to say, that we have the list, not that this very page can serve the purpose.  
  
Also, how do we group it anyway? Alphabetical is both easiest and most useless. By similarity? Some will overlap several groups. Do we make a tag cloud? :dagger:

**Comment by magda-chrzescian** [comment]
I'm very curious to see it as a tag cloud, however not sure how it would serve the purpose, again. If we don't want to show any other information than the name to the user, it's fine, but only then.

**Comment by godai78** [comment]
This is ALMOST it: https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html#list-of-plugins-included-in-the-ckeditor-5-predefined-builds

**Comment by godai78** [comment]
There is also a full list of features (and subfeatures) currently in development by the website/marketing team, aided by CCX. I believe this would conclude the task.

**Comment by godai78** [comment]
Here we go: https://ckeditor.com/ckeditor-5/features/
