### ISSUE TITLE
WatchDog try-catches make development very tricky

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#5704]
E.g. try-catch inside the `EmitterMixin#fire`.

When you make a simple mistake inside a listener callback (typo or something) it's not easy to find out what happened. The original error is caught, wrapped and rethrown. The stack of the original error is stored as a string inside some nested property.  You can't click it to move the place where the error happened. It seriously decreases DX.

I think It should be a flag to disable WatchDog try-catches.

**Comment by ma2ciek** [comment]
I had some ideas about DX improvements in https://github.com/ckeditor/ckeditor5/issues/5595 My last proposal there should be good enough to track original errors.

The latter seems also doable, but harder and tricker and I think that this shouldn't be needed if the original stack trace would be good.

**Comment by Reinmar** [comment]
I've had really strong doubts about try-catches from the beginning as it just smelled badly. But since you guys were talking about wrapping only some critical parts of the code, I was curious how it will work.

However:

* I didn't expect that we're touching places like `EmitterMixin#fire()`. I thought this was supposed to touch things like `Model#change()`. I'd say that there's a fundamental difference between a util like the emitter mixin and the base engine's class.
* I'm still planning to check @ma2ciek's solution to #5595 but if the results will not feel "native", I'd be for reverting most of try-catch addons.

**Comment by Reinmar** [comment]
I reported a separate ticket for moving the try-catch to some other place than `EmitterMixin#fire()`: https://github.com/ckeditor/ckeditor5/issues/5791.

Other than that, we merged @ma2ciek's https://github.com/ckeditor/ckeditor5-utils/pull/313 so I think we can close this issue too.
