### ISSUE TITLE
Slash commands

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5714]
## 📝 Provide a description of the new feature

This is extracted from #1686 comment:
> A case for autocomplete - almost like Mention plugin but with custom "slash commands":

- JIRA slash commands: https://confluence.atlassian.com/hipchatdc3/keyboard-shortcuts-and-slash-commands-966656108.html
- Notion slash commands: https://www.notion.so/Learn-the-shortcuts-66e28cec810548c3a4061513126766b0#fd1e1bf866f74e1aa95ff8511e1afe25

The feature would provide invokable editor actions with a possibility to customize it further.

General idea:
1. user types `/` + action name
2. the autocomplete feature (just like in the mentions) displays matched commands
3. user selects an action from the list
4. everything typed after `/` is removed
5. some editor action or custom command is executed

Possible actions:
- `/heading2` change current block to a heading 2
- `/bullet` change current block to a bulleted list
- `/table` inserts 2x2 table
- `/delete` remove a current block

Consider also:
- grouping commands
- simple config API to allow defining actions by using existing commands names (also provide values if need)
- similar extensibility for actions list (add image, change text, etc)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by loaibassam** [comment]
The best experience I've ever had with slash commands in editors is on slite.com - would be great if we can have something similar. 

Thanks for your work on CK!

**Comment by alechewitt** [comment]
This would be a really great feature to have.

**Comment by mlewand** [comment]
This feature could be built on top of mentions. I made a simple PoC showing that it works.

https://user-images.githubusercontent.com/5353898/124443924-641a6000-dd7e-11eb-99d1-394c73d8fb1b.mp4

Code pushed to https://github.com/ckeditor/ckeditor5/tree/ck/5714-slash-commands-poc

For anyone dying to have it: you can just port this changeset https://github.com/ckeditor/ckeditor5/commit/865c940598a27d65caab7de506931be2abc20761 assuming that you have mention plugin it should work.

**Comment by mlewand** [comment]
So we had a one day hackathon last week and our team decided to give it another go. We made a [banch `i/5714-slash-command-2021-hackathon`](https://github.com/ckeditor/ckeditor5/tree/i/5714-slash-command-2021-hackathon) with much improved implementation.

Compared to the previous PoC it:

*   Displays an icon.
*   Has a configuration variable that predefines which commands would work.
*   Have a concept of proxied commands which makes it possible to use things like table / media embed.


https://user-images.githubusercontent.com/5353898/145825457-4ad96364-f5c1-410a-ab70-660e41936aac.mp4

Still there are things to be ironed out but I think that it could be even used at this point.

We'll try to publish an unofficial npm package to make installation easier / possible for folks willing to try this out.

**Comment by ctwhome** [comment]
Please give it another try, this is looking already awesome. I was also blown away by how slite.com has developed the "/" feature

**Comment by mlewand** [comment]
Thanks for following up on this @ctwhome. Can I ask you what features are most valuable for you there?

Or maybe I should ask simply for some actual use cases that you'd like to use this feature for. This will help us to shape it better 🙂 (ofc anyone else watching the issue feel free to provide use cases - the more perspectives the better)

**Comment by ctwhome** [comment]
Thank you @mlewand, 
Short answer: it provides a menu with options in the context. 

After two years of using Notion, this has become a must to go with. The "/" tool helps to go beyond markdown native features, it is very intuitive to use since everything is displayed on a list inside the context where you are, not needing to move your eyes somewhere else (normally to the top bar),  and it allows you to not use the mouse when writting. Pretty much the same benefits that markdown shortcuts have.


### This is how Notion does it: 
![Nov-08-2022 13-10-32](https://user-images.githubusercontent.com/4195550/200560996-982cf4ce-0809-4c4d-81f4-bb3c6714ceff.gif)

### Slite.com
![Nov-08-2022 13-11-54](https://user-images.githubusercontent.com/4195550/200561121-f3756113-f79e-4548-89cd-928077660725.gif)


### Or Google Docs (With "@" instead of "/")
![image](https://user-images.githubusercontent.com/4195550/200561395-ed0c0812-948b-4dec-9948-f25a5d727eea.png)


### Obsidian does something similar, but it is called the command palette and it is a bit different from formatting the options. 
<img width="464" alt="image" src="https://user-images.githubusercontent.com/4195550/200561727-82de7363-9569-42d4-adfb-14cb79e249ed.png">

**Comment by loaibassam** [comment]
We actually developed this on Plutio.com <http://plutio.com/> - it looks very similar!

**Comment by mlewand** [comment]
Thanks for noting, like mentioned, the feature has been [shipped in version 37.1.0](https://github.com/ckeditor/ckeditor5/blob/master/CHANGELOG.md#3710-2023-04-19) and is available as a part of productivity pack feature set 🎉

**Comment by jsfgreen** [comment]
This appears partially broken.  When I run my build I get:

    index.js:464 CKEditorError: plugincollection-soft-required {"missingPlugin":"Mention","requiredBy":"SlashCommand"}

Even thought I didn't intend to use `Mention` I still tried to import it and include it with my build, but now I get: 

    CKEditorError: plugincollection-plugin-name-conflict {"pluginName":"ClipboardPipeline"}
