### ISSUE TITLE
toolbarview.js:252 toolbarview-item-unavailable: The requested toolbar item is unavailable.

### ISSUE THREAD

**Issue by ElliotFer2000** [ckeditor/ckeditor5#5727]
## 📝 Provide detailed reproduction steps (if any)

I was adding some elements to the Balloon Blocking toolbar Block Editor but it gives me the error described in the header

I wanted to add some headings and the option to add paragraphs but it gives me the following error:

toolbarview.js: 252 toolbarview-item-novailable: The requested toolbar element is not available.

It's weird because by default when loading the editor and not setting anything I get those options of elements that I said before with others that come by default in the editor and I don't know why when trying to configure a blockToolbar

`<script src="https://cdn.ckeditor.com/ckeditor5/15.0.0/balloon-block/ckeditor.js"></script>
`
```
 const config = {
            blockToolbar: ['paragraph', 'heading1', 'heading2', 'bulletedList', 'numberedList'],
            balloonToolbar: ['bold', 'italic', 'undo', 'redo']
        };
        BalloonEditor.create(document.querySelector('#body-editor'), config).catch(error => {
            console.error(error);
        });
```
I'm using the version 5 of CKEDITOR and I'm using BalloonBlockEditor

**Comment by Mgsy** [comment]
Hi! If you're using the balloon-block build, you won't be able to separate paragraph and heading buttons because the build doesn't contain those by default. 

In your case, you can simply add `'heading'` instead of `'paragraph', 'heading1', 'heading2'` to add a dropdown.

However, if you'd like to split those to separate buttons, you can add the following plugins to your build (but it won't be possible if you use builds served via CDN):
```js
import HeadingButtonsUI from '@ckeditor/ckeditor5-heading/src/headingbuttonsui';
import ParagraphButtonUI from '@ckeditor/ckeditor5-paragraph/src/paragraphbuttonui';
```
Then, you'll be able to add `'paragraph', 'heading1', 'heading2'` items to your toolbar.

Please, see the following documentation:
* [Adding a plugin to a build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build)
* [Block toolbar feature](https://ckeditor.com/docs/ckeditor5/latest/features/blocktoolbar.html)
