### ISSUE TITLE
MS Edge chromium support

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5739]
## Provide a description of the task

Now that MS Edge Chromium is in release candidate phase, and the [official release date has been set to the 15th of January](https://blogs.windows.com/msedgedev/2019/11/04/edge-chromium-release-candidate-get-ready/#SERvfCOZorrWXtWx.97), we can start thinking about the support strategy for Edge.

It make sense to make some sort of compatibility testing. I believe it will act pretty much like Chrome, so it should work well with CKE5.

Surely we'll have to update [desktop and mobile browser support](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/browser-compatibility.html#desktop-environment) (it launches with Android and iOS support) docs accordingly.

I believe Edge (Chromium) and old Edge (IE-based) can exist side by side. But it's unclear to me what will be the default browser be in Win10 - so we should check that too. Knowing that we might determine our support strategy for Edge (IE).

After that we should review existing edge issues and re-triage these accordingly.

**Comment by Mgsy** [comment]
The new Chromium-based Edge will be delivered in Windows Update on 15th January for every PC running Windows 10 version 1709. Feature updates will be released on a 6-week cycle. Security and compatibility updates will be shipped as needed. 

However, Microsoft will allow users to prevent Windows Update from installing a new browser, so some users might still use the old version.

About compatibility with CKEditor 5 - @FilipTokarski has tested the editor in new Edge (preview) and there are no visible issues. Also, he verified that all the existing issues related to old Edge are fixed in the upcoming version.

**Comment by Reinmar** [comment]
Thanks, guys! Thanks for the information and checking the tickets. All clear now. I think we can close this ticket.
