### ISSUE TITLE
[iOS] The selection is visible over editor UI

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#5753]
## 📝 Provide detailed reproduction steps (if any)
**Edit: 15.09.2022**

1. Go to https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html.
1. Create a non-collapsed selection at the beginning of the editable.
1. Open the headings dropdown.
1. Try to click on a dropdown item.

### ✔️ Expected result

It's possible to pick an option from the dropdown.

### ❌ Actual result

The native selection appears and it's impossible to pick an option from the dropdown.

## 📃 Other details

![test](https://user-images.githubusercontent.com/20988892/190392765-45b0a479-215b-41ab-9f57-25f6948db0db.PNG)

* Browser: Safari
* OS: iOS
* CKEditor version: Latest master
---

More examples:

* ckeditor/ckeditor5#7497
* ckeditor/ckeditor5#11217

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
[This is a known bug in iOS](https://stackoverflow.com/questions/19245658/text-insertion-cursor-caret-appears-above-other-elements-in-mobile-browser). The only way to address this is by blurring the text field the selection is rendered in.

@ckeditor/qa-team  Can you confirm this happens less often since ckeditor/ckeditor5#11838? The editing root gets blurred now and the focus moves to the dropdown making the selection disappear.

**Comment by Mgsy** [comment]
> [**@ckeditor/qa-team**](https://github.com/orgs/ckeditor/teams/qa-team)  Can you confirm this happens less often since [#11838](https://github.com/ckeditor/ckeditor5/issues/11838)? The editing root gets blurred now and the focus moves to the dropdown making the selection disappear.

I can't reproduce this issue anymore, after opening the dropdown, the selection moves to it and is invisible in the editable.

**Comment by Reinmar** [comment]
This is awesome news :) I haven't thought about this side-effect of our recent changes.

**Comment by Mgsy** [comment]
Unfortunately, the issue still exists :cry: After moving the focus to the dropdown, the native selection is invisible, but it appears again after clicking on a dropdown item.

**Comment by Witoso** [comment]
The current behavior is a bit different (iOS 16.5). The selection after opening the dropdown is not visible, but you still cannot select options. **Sometimes it works** when I bash multiple times on the screen or probably when the option is above the select (paragraph's case).
Recording:
https://github.com/ckeditor/ckeditor5/assets/9881379/0d5c6ea1-b118-4e69-9c3e-65260e0e63fa

**Comment by Witoso** [comment]
Ideas:
- on the renderer level, remove DOM selection while editable is blurred.
- maybe there are some APIs that we could use?
- higher `z-index` on iOS on dropdown?

**Comment by oleq** [comment]
> * on the renderer level, remove DOM selection while editable is blurred.

We actually do a similar thing in the link feature. The selection that you see on a link when you edit it is a fake marker. You can tell because the selection slightly changes its color and size depending on the OS when you open the link UI. We did that to maintain the UX. Otherwise, the selection in the editing root would disappear (DOM focus goes to the link UI) and, after a short while, it would be hard to tell what is getting linked and where.

This is not a system-wide solution, though (ATM only limited to links). But if we managed to have it available for all features, then we could control the `z-index` of the fake selection marker and probably work around the original issue.

<img width="522" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/1099479/9851b41a-b814-4d9c-86d5-163c6a3627cc">

> * maybe there are some APIs that we could use?
> * higher `z-index` on iOS on dropdown?

Sadly, this whole thing has nothing to do with `z-index`. Rendering the selection over everything is happening on the OS-level and there's nothing we can do about it in CSS.
