### ISSUE TITLE
Separate HTML and XML languages in code blocks?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5794]
They are treated right now as the same thing:

![image](https://user-images.githubusercontent.com/156149/69544243-9acbaa00-0f8f-11ea-94ad-664acae3c0d3.png)

But HTML is not a valid XML and perhaps may break code highlighters. Plus it is not correct to mark HTML as XML semantically.

I'd have two separate positions.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @oleq @jodator

**Comment by Reinmar** [comment]
Let's answer here a question of how do other highlighters treat HTML and XML. As one thing or separate things.

**Comment by Comandeer** [comment]
The rules of these two languages are just too different to be treated in the same way.

Valid HTML, invalid XML:

1.
	```html
	<!DOCTYPE html>
		<title>Test</title>
	</head>
		<p>Test</p>
	```
2.
	```html
	<ImG SrC=https://www.comandeer.pl/images/custom/comandeer.jpg>
	```
3.
	```html
	<p>Paragraph<h1>Heading</h1>
	```

Valid XML, invalid HTML:

1.
	```xml
	<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js" />
	```
2.
	```xml
	<br></br>
	```
3.
	```xml
	<p><div></div></p>
	```

**Comment by oleq** [comment]
highlight.js uses the [same highlighter](https://github.com/highlightjs/highlight.js/blob/69f0c5929fef93b51fdeaaf72eaaf7762ee19a6b/src/languages/xml.js#L2) for HTML and XML. Prism, on the other hand, [separates them](https://prismjs.com/#supported-languages).

FYI, I'm OK with separating them. But I don't think this is a big enough issue since nobody voted for this issue so far. Also, please keep in mind, we're talking about the default configuration here only. Developers who don't like the HTML/XML coupling can create a config on their own with whatever they find necessary.

**Comment by Reinmar** [comment]
OK, let's keep the current defaults and wait for feedback.
