### ISSUE TITLE
The <code> inside editor content should not be styled.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5800]
## 📝 Provide a description of requested docs changes

The `<code>` element inside editor content gets styles from documentation page.

Found on autoformat feature guide:

![Selection_066](https://user-images.githubusercontent.com/247363/69604771-a31ef600-101e-11ea-93d9-66426177e05e.png)

**Comment by oleq** [comment]
I think it's mainly because of Umberto styles, not the feature styles (because it worked fine in a manual test).

**Comment by jodator** [comment]
The autoformatting sample still does not look ok:

![Selection_077](https://user-images.githubusercontent.com/247363/70044733-30d08780-15c3-11ea-9d19-fab7e7382f6a.png)

The conflicting rule comes from Umberto.

**Comment by jodator** [comment]
I'm closing this as a non-ckeditor5 issue.

**Comment by Reinmar** [comment]
Requires: https://github.com/cksource/umberto/issues/840

**Comment by oleq** [comment]
FYI: It works in the Code Block guide thanks to this [tiny fix](https://github.com/ckeditor/ckeditor5-code-block/blob/4515b264c9b86e59cea204064bba4435c82b284c/docs/_snippets/features/build-code-block-source.html#L9-L11) I used when developing the feature. It is not present in other guides (like Autoformatting) because I didn't think this through, hence the problem.

But I totally agree this should be fixed on the Umberto side.

**Comment by oleq** [comment]
I created a [PR](https://github.com/cksource/umberto/pull/842) in Umberto but it needs a thorough review.

**Comment by oleq** [comment]
Since the PR has been merged in Umberto I think we can close it along with https://github.com/cksource/umberto/issues/841.
