### ISSUE TITLE
Create a MathML upcast/downcast pipelines PoC

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5858]
We can certainly improve the way [mathematical and chemical formulas](https://ckeditor.com/docs/ckeditor5/latest/features/math-equations.html) are stored in editor model to make it more reliable and maintainable. To do that, a PoC with conversion pipelines is needed first to verify our data processors can handle MathML structures correctly.

**Comment by oleq** [comment]
And there it is https://github.com/ckeditor/ckeditor5/compare/poc/mathml?expand=1.

**Comment by Reinmar** [comment]
Could you fix one thing in the POC?

You shouldn't use a UI element as a widget. A UI element is transparent to the view. You can use a widgetized container element (span) with a UI element inside. I can see that using a widgetized UI element works fine right now, but I think this is coincident. It shouldn't. For instance, the UI element renders itself. Then, how does it even work that attributes added by `toWidget()` get rendered?

In fact, if you click on the manual test for a bit longer it starts throwing errors or getting unstable. That may be due to the UIElement usage. 

Also, please check out https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#fixing-position-mapping.

As for the future, we are considering introducing a `RawElement` for this case. It will have better semantics. For instance, it will not be treated as "no content" which is important for checking whether the editor is empty or not. But this is a future.

**Comment by oleq** [comment]
I updated the PoC, some thoughts:
* I wrapped the `<math>` (`UIElement`) in a `<span>` (`ContainerElement`) like you asked me to do so now it's the container that gets "widgetized". 
* I figured the data pipeline is broken because it returned... widgets. I fixed it.

    While fixing the data pipeline I tried the following code

    ```js
    const mathElement = viewWriter.createContainerElement( 'math', {
        xmlns: 'http://www.w3.org/1998/Math/MathML'
    } );
    const processor = new HtmlDataProcessor();
    const docFragment = processor.toView( modelItem.getAttribute( 'formula' ) );
    viewWriter.insert( viewWriter.createPositionAt( mathElement, 0 ), ...docFragment.getChildren() );
    return mathElement;
    ```

    but it didn't work because `insert()` has a very limited set of node types it allows to be inserted     (`Container`, `Attribute`, `Text` etc.) and otherwise it throws. In the output of `HtmlDataProcessor`, things   like `<mrow>` become plain `Element`, which isn't allowed to be inserted. I couldn't figure out what to do    about it so I decided to hack things a bit and I decided to return... an `UIElement` in the data pipeline (I   didn't realize it's possible) with the math content injected at the DOM level. Not pretty but it works.
* I also kinda hacked (:P) the way the `<math>` `UIElement` is created and I had to do this to get a nice math preview in browsers that support it (e.g. Safari). Normally, the `UIElement` creates a regular DOM Element but to MathML to start working we need to an element created using `domDocument.createElementNS()`. UI `Template` does support namespaces but not the downcast writer ecosystem so instead of using the DOM element provided by `writer.createUIElement`, I created my own via `domDocument.createElementNS()`. I'm not sure this should be allowed but it does work.

**Comment by oleq** [comment]
Anyway, the current implementation works as follows:

![image](https://user-images.githubusercontent.com/1099479/70139638-2c739f80-1693-11ea-8535-aacc219e4b2f.png)

![image](https://user-images.githubusercontent.com/1099479/70139658-3bf2e880-1693-11ea-8fa7-4c81d901d785.png)

**Comment by Reinmar** [comment]
> * I decided to hack things a bit and I decided to return... an `UIElement` in the data pipeline

That's a very good idea and I'd do the same. That's the easiest way to have an arbitrary thing in the downcasted structure. The other option would be to do "casting" of an unflavored (nonsemantical) view structure returned by the data processor by rewriting it to container elements (with a loop).

**Comment by Reinmar** [comment]
I did a brief check of the code and how it works and didn't see any issues. Thanks, @oleq!
