### ISSUE TITLE
Pasting content does not work in restricted editing fields

### ISSUE THREAD

**Issue by elszczepano** [ckeditor/ckeditor5#5869]
## 📝 Provide detailed reproduction steps (if any)

Scenario 1:
1. Open an editor with created restricted editing standard mode. 
2. Copy some content from the non-restricted area.
3. Paste the content inside the restricted area.

Scenario 2:
1. Open an editor with created restricted editing restricted mode. 
2. Copy some content from the non-restricted area.
3. Paste the content inside the restricted area.

### ✔️ Expected result

Scenario 1:
- Content should be pasted into a restricted area.

Scenario 2:
- Content should be pasted into a restricted area.

### ❌ Actual result

Scenario 1:
- Content splits the restricted area into two.

Scenario 1:
- Content is not pasted.

## 📃 Other details

* Browser: Mozilla, Chrome
* OS: MacOS Catalina
* CKEditor version: Newest
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
There's more work to enable copy&paste and in MVP it is disabled: #5802.

ps.: "restricted area" should be non-restricted area, right? Because you shouldn't be allowed to paste into the restricted area (whole document except highlighted) in restricted editing mode while in standard editing mode you should do everything you want. 

In the standard mode, you should be able to do everything and the "non-restricted" area should work the same as attribute commands (bold, italic, etc). So in standard mode scenario 1 is probably invalid.
