### ISSUE TITLE
Enhance the Document editor build

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5886]
Let's consider replacing the highlight feature with font size and font color.

Let's also consider adding font family.

**Comment by Reinmar** [comment]
cc @wwalc

**Comment by Reinmar** [comment]
I can see @wwalc's 👍 so let's do this.

**Comment by panr** [comment]
@Reinmar I need more info about this issue, because I see that Document Build config already has defined `font-size` and `font-family` and the only missing piece is the `font-color` option... 🤔

**Comment by jodator** [comment]
It looks like this issue is about removing the `Highlight` feature with `FontColor` and `FontBackgroundColor`. I don't recall the intent but adding font color & font background color will make highlight feature in the build obsolete.

Things to check/change:
1. All mentions about highlight feature in this build (or even writing that we replaced highlight with those two plugins in the build).
2. Change `ckeidtor5-editor-decoupled` and `ckeditor5-build-decoupled-document` (if needed):
   - API docs
   - fremework guide
   - example guide + snippets
   - manual tests (source HTML + configuration)

**Comment by mlewand** [comment]
We also prepared \[a small plugin that will automatically convert highlight markup to font color/background specific format\](https://codepen.io/ckeditor/pen/oNXzGeO?editors=1010) - preventing potential data loss.
