### ISSUE TITLE
Can someone explain how 'editor.ui.view.body.add( panelView );' is required for BalloonPanelView to be pinned?

### ISSUE THREAD

**Issue by ConnorSinnott** [ckeditor/ckeditor5#5914]
My current project requires an implementation of BalloonPanelView.

I attempted to implement this by following the examples found at: [BalloonPanelView](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_panel_balloon_balloonpanelview-BalloonPanelView.html). 
```JavaScript
const panel = new BalloonPanelView( locale );
const childView = new ChildView();
const positions = BalloonPanelView.defaultPositions;

panel.render();

// Add a child view to the panel's content collection.
panel.content.add( childView );

// Start pinning the panel to an element with the "target" id DOM.
// The balloon will remain pinned until unpin() is called.
panel.pin( {
    target: document.querySelector( '#target' ),
    positions: [
        positions.northArrowSouth,
        positions.southArrowNorth
    ]
} );
```

Despite my best efforts, I would continuously receive the following error
```
Error: unexpected-error {"originalError":{"message":"t is null","stack":"nn@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:118495\nlistenTo@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:116554\nlistenTo@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:190188\nadd@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:352488\nexecute@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:674148\ndecorate/<@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:132272\nfire@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:117817\ndecorate/this[t]@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:132323\nexecute@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:270471\nexecute@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:350895\ninit/</<@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:674540\nfire@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:117817\nKl/<.on.click<@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:374715\nn@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:361885\nfire@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:117817\ni@https://local.lucidoc.com/s3/dev/v15.0.0/ckeditor.js:5:191010\n","name":"TypeError"}}
```
When invoking the execute function of the following Command
```JavaScript
execute() {
        const editor = this.editor;
        const selection = this.editor.model.document.selection;

        const panelView = new BalloonPanelView(editor.locale);

        const view = new ButtonView(this.locale);
        
        view.set({
            label: 'Test',
            withText: true,
        });

        panelView.content.add(view);

        panelView.pin({
            target: selection,
            positions: [
                 BalloonPanelView.defaultPositions.northArrowSouth,
                 BalloonPanelView.defaultPositions.southArrowNorth
            ]
        });
}
```
Eventually I had to grep the /node_modules/@ckeditor/ directory for an instantiation of BalloonPanelView which revealed to me that I was missing the following code:

```JavaScript
// ckeditor5-ui/src/toolbar/block/blocktoolbar.js 
/**
* Creates the {@link #panelView}.
*
* @private
* @returns {module:ui/panel/balloon/balloonpanelview~BalloonPanelView}
*/
_createPanelView() {
	const editor = this.editor;
	const panelView = new BalloonPanelView( editor.locale );

	panelView.content.add( this.toolbarView );
	panelView.className = 'ck-toolbar-container';
	editor.ui.view.body.add( panelView ); // <= Solves issue
	editor.ui.focusTracker.add( panelView.element );

	// Close #panelView on `Esc` press.
	this.toolbarView.keystrokes.set( 'Esc', ( evt, cancel ) => {
		this._hidePanel( true );
		cancel();
	} );

	return panelView;
}
```
Is `editor.ui.view.body.add( panelView );` required because while I have created a new BalloonPanelView, it is not yet attached associated with the editor view? And because of this cannot be pinned? I attempted to look up `editor.ui.view.body.add` in the documentation but it appears to be undocumented. 

Documentation: 
[Command](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html) > [editor](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html) > ui (missing)

[EditorUI?](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorui-EditorUI.html) > view (missing)

Could someone explain to me what is happening? Or perhaps point me to some documentation that can explain this?

Thank you!

**Comment by Mgsy** [comment]
@oleq, can you take a look at it?

**Comment by oleq** [comment]
Yes, you need `editor.ui.view.body.add( panelView );`. 

`editor.ui.view.body` is a [`ViewCollection`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_viewcollection-ViewCollection.html) which is rendered into a `.ck-body` element in page's `<body>` (inspect your DOM when the editor is running) and it collects all "floating" elements of the UI, like for instance, balloons, floating toolbars, etc.

If you create your own `BalloonPanelView` instance, you have to add it somewhere so it appears in DOM. Until added somewhere, the view has no place in DOM. It's declarative and you have to take care of it. The "body" collection that I mentioned is a natural place to do that because 
* it's already there 
* and it's managed by the editor, so, for instance, your balloon will be automatically destroyed when the editor is destroyed.

BTW, since you're creating your own implementation, take look at https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_panel_balloon_contextualballoon-ContextualBalloon.html. Not sure what you're trying to do because you didn't specify that but `ContextualBalloon` is widely used in the UI of the editor (by `LinkUI`, `ImageTextAlternativeUI`, `MentionUI`, `BalloonToolbar`...) to keep things clean and you could use it too. It's basically a `BalloonPanelView` with an API to manage a stack of child views. If you use it, you don't have to worry about two balloons being open at a time etc. because there's only one (the contextual one) that manages its children.

**Comment by ConnorSinnott** [comment]
Thanks @oleq! That makes sense. I'll certainly look into ContextualBalloon as well, thank you!

**Comment by ConnorSinnott** [comment]
Hey @oleq, ContextualBalloon worked like a charm! Thanks
