### ISSUE TITLE
Script Tag being stripped completely from v5

### ISSUE THREAD

**Issue by aSoskuthy** [ckeditor/ckeditor5#5919]
## 📝 Provide detailed reproduction steps (if any)

1. set the editor data with editor.setData('<script>alert("loaded")</script> any content')

### ✔️ Expected result

Would see "any content" and an alert popup or any script I wish to run 

### ❌ Actual result

any content shows without the script being run

## 📃 Other details

I have read a lot about the ongoing discussion about source mode being stripped out completely from ck5 but I would like to know if there is any way to execute scripts via the editor? For us the source mode version removal is unfortunately a show stopper but if we could at least execute scripts we could upgrade to v5. Is there a plugin for this or a solution? We have a lot of clients who write their content with ckeditor and we let them add scripts so they become quite creative sometimes... 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Your `script` tag is stripped out because CKEditor 5 has a custom data model and accepts only elements/attributes which are allowed in the [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html). To preserve your element, you should introduce it to the schema and provide a proper model <--> view [conversion](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-introduction.html).

The following code introduces the `script` element in the editor:
```js
editor.model.schema.register( 'script', {
	allowWhere: '$block',
	allowContentOf: '$block'
        isBlock: true
} );

editor.conversion.elementToElement( { model: 'script', view: 'script' } );
```

**Keep in mind** that allowing users to insert and execute the code within `<script>` element might lead to some serious security issues, so we don't recommend introducing it to your editor.

To learn more, please read the materials I've provided above.
