### ISSUE TITLE
Incorrect code block label after setting two classes for a language

### ISSUE THREAD

**Issue by iamKyun** [ckeditor/ckeditor5#5924]
Here is my code block config:
```javascript

codeBlock: {
    languages: [
      {
        language: 'plaintext',
        label: 'Plain text'
      },
      {
        language: 'javascript',
        label: 'JavaScript',
        class: 'language-javascript line-numbers' // I added 2 classes for javascript
      }
    ]
  }
```
and I got these contents after inserted a code block and chose 'JavaScript' in editor:
```html
<pre><code class="language-javascript line-numbers">function test(){console.log(1)}</code></pre>
```
when those HTML codes were rendered in the editor , it won't correctly show the 'JavaScript' label ('Plain text' label instead).

PS:It won't happen if use a single class

**Comment by Mgsy** [comment]
Hi! Thanks for the report, I can confirm this behaviour. However, for me, it works if I use a code block feature from the toolbar and fails if I use `editor#setData`.

Scenario:

1. Add the following configuration to your plugin:
```js
codeBlock: {
    languages: [
        { language: 'plaintext', label: 'Plain text', class: '' },
        { language: 'javascript', label: 'JavaScript', class: 'language-javascript line-numbers' }
    ]
}
```
2. `editor.setData('<pre><code class="language-javascript line-numbers">test</code></pre>' )`.

## Current result
The code block has `Plain text` label.

## Expected result
The code block has `JavaScript` label.

cc @oleq

**Comment by oleq** [comment]
The issue is probably somewhere around [here](https://github.com/ckeditor/ckeditor5-code-block/blob/master/src/converters.js#L142). ATM the language is discovered by class as a pure String(class)->String(language) association. When there's more than one class, this fails and this is probably where we should do it better.

**Comment by panr** [comment]
I checked the implementation and have come up with two ideas to solve this problem:

1. **stick to the convention** that the `first class` will be the defining language class, and remaining ones are optional / additional. Technically, we can split that value and pick only a head element (first one). That's the simplest (even if a little naive) way... So, based on @iamKyun config, `language-javascript` will be used to define a javascript language.
2. **change the API** 😅 so that we have two separate keys to declare (both optional) `languageClass` { String } and `extraClass` { String } (or any other matching name). Keep in mind that `extraClass` value has nothing to do with language detection.

Example:

```
codeBlock: {
    languages: [
      {
        language: 'plaintext',
        label: 'Plain text'
      },
      {
        language: 'javascript',
        label: 'JavaScript',
        languageClass: 'language-javascript', // only this one will be used for language detection
        extraClass: 'line-numbers highlight something-else andWhatever'
      }
    ]
}

```

What do you think?

**Comment by oleq** [comment]
> 1. **stick to the convention** that the `first class` will be the defining language class, and remaining ones are optional / additional. Technically, we can split that value and pick only a head element (first one). That's the simplest (even if a little naive) way... So, based on @iamKyun config, `language-javascript` will be used to define a javascript language.

I'm for this one as it is simple to implement and does not change the existing API.

We'd only need to normalize [object here](https://github.com/ckeditor/ckeditor5-code-block/blob/ca5668cdadaf731df58580b8614c3c226675032a/src/converters.js#L143) so that class names that have white spaces in them should be split and only the first should be considered.

**Comment by panr** [comment]
Fix is ready to review 😉

**Comment by oleq** [comment]
@iamKyun Can you confirm https://github.com/ckeditor/ckeditor5-code-block/pull/9#pullrequestreview-337656714 does the trick for you?
