### ISSUE TITLE
Implement `Range.getDifferencesWithMultipleRanges()`

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5998]
There's a need for getting difference of one range with multiple other ranges.

A similar code was created by @scofalik and by me in restricted editing PR.

It looks like a useful API so we should add it.

After: https://github.com/ckeditor/ckeditor5-restricted-editing/pull/8

**Comment by Reinmar** [comment]
It's about https://github.com/ckeditor/ckeditor5-restricted-editing/pull/8#discussion_r359225646.

**Comment by mlewand** [comment]
How about enhancing the existing [`Range.getDifference`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_range-Range.html#function-getDifference) to support an array/set of ranges instead of adding a new method?

So one could use `myRange.getDifference( [ rangeA, rangeB, rangeC ] )`.

**Comment by jodator** [comment]
After trying to find this in our code base I couldn't find it. As it has only one (and "external") use I don't see a need to implement this ATM.

**Comment by Reinmar** [comment]
Bye 👋
