### ISSUE TITLE
insertContent() strips a tag

### ISSUE THREAD

**Issue by cccccccccccccccccnrd** [ckeditor/ckeditor5#6000]
## 📝 Provide detailed reproduction steps (if any)

After executing following script, CKEditor strips the `a` tag. Why does that happen?

```js
const html = '<a href="http://spaces.test/app/uploads/sites/5/2019/12/11z510101522n6-3.png"><img src="http://spaces.test/app/uploads/sites/5/2019/12/11z510101522n6-3-300x208.png" alt="" width="300" height="208" class="alignnone size-medium wp-image-864" /></a>'
const viewFragment = editor.data.processor.toView(html)
const modelFragment = editor.data.toModel(viewFragment)

editor.model.insertContent(modelFragment, insertPosition)
```

### ✔️ Expected result

CKEditor should not remove the `a` tag, but instead wrap the newly created `figure` element.

### ❌ Actual result

CKEditor's data looks the following:

```html
<figure class="image"><img src="http://spaces.test/app/uploads/sites/5/2019/12/11z510101522n6-3-300x208.png" alt=""></figure>
```

## 📃 Other details

* Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
* OS: macOS Mojave 10.14.6
* CKEditor version: [https://github.com/dol-lab/ckeditor5-build-classic](https://github.com/dol-lab/ckeditor5-build-classic)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! Your link is stripped out because CKEditor 5 doesn't support linking images. We have an open feature request for it (https://github.com/ckeditor/ckeditor5/issues/702), feel free to add 👍 to the first post to bump its popularity and join the discussion. 

We're definitely going to implement it, however, due to other priorities, we can't provide any ETA right now.
