### ISSUE TITLE
Selection could be outside of the link after pasting

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#6053]
## 📝 Provide a description of the improvement

*How the feature works now and what you'd like to change*?

When pasting a link the selection (cursor) could be moved outside of the link, so after pasting typing won't extend the pasted link. This behavior doesn't exist in CKEditor 4 and other editors.

## 📃 Other details

* Browser: Chrome
* OS: MacOS
* CKEditor version: 16

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by fredck** [comment]
Actually this issue seems to be related to a yet bigger problem: **unexpected auto-linking when pasting urls**... but just those copied from the browser address bar (Chrome only?).

For example:

1.  [Go to this fiddle](https://jsfiddle.net/b9cL18fs/2/):
    1.  Copy the URL from the browser address bar (not the one in the textarea).
    2.  Paste it inside CKEditor -> **auto-linking DOES happen**.
2.  [Go back to that fiddle](https://jsfiddle.net/b9cL18fs/2/):
    1.  Now copy the URL from the textarea in the results pane.
    2.  Paste it inside CKEditor -> **auto-linking DOES NOT happen**.

We have an inconsistent behavior here. Users may feel that what happens is right but the fact is that CKEditor is having no control of it... and no control is not good.

The fact is that the browser itself is saving in the clipboard the url copied from its address bar in both HTML and plain-text format. The HTML version is something like `<a href="url">url</a>` and that's the one used by CKEditor. When copying from the textarea, the clipboard has plain-text only.

I believe **the proper solution here is not auto-linking** in such situation and leave the auto-linking feature to be handled by a future feature that will do so in all cases, no matter if copied from the address bar or a plain-text source.

**Comment by fredck** [comment]
> just those copied from the browser address bar (Chrome only?)

Tested with Firefox and Safari... these browsers don't put a HTML version in the clipboard so this issue doesn't happen there.

**Comment by wwalc** [comment]
Related: #1016 (see e.g. use case described in https://github.com/ckeditor/ckeditor5/issues/1016#issuecomment-563919956)

**Comment by Reinmar** [comment]
I think that this can be fixed by listening on model#insertContent and changing the gravity of the selection to "right" when we detected that a link was pasted.

**Comment by oleq** [comment]
OK, we have two separate problems in this issue:

1. The gravity of the selection could be improved after pasting a link. https://github.com/ckeditor/ckeditor5-link/pull/260 addresses this problem.
2. There's a discussion about whether links should be pasted as rich or plain text (if data transfer provides an HTML). I'm creating a [follow-up](https://github.com/ckeditor/ckeditor5/issues/6629) for this, so please let's move the discussion there because it's a separate topic.
