### ISSUE TITLE
Check performance after styles handling changes

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6068]
## Provide a description of the task

- Check how [the change](https://github.com/ckeditor/ckeditor5-engine/pull/1807) affected performance with heavily styled documents. (https://github.com/ckeditor/ckeditor5-engine/pull/1807#discussion_r347559008)

**Comment by Reinmar** [comment]
@jodator, @mlewand will work on manual tests for performance-oriented research (#5880) so he can actually verify this case.

@mlewand, I'm sure we have a regression because the new system is quite more powerful than the previous style handling. So, it's not a matter of making sure that we didn't regress, but:

* estimating how big the regression is,
* finding some bottlenecks (some obvious improvements points).

Let's see the results and think what we should do.

PS. Please remember that the new style parser is not automatically enabled yet (I think), so ask @jodator how to actually test it.

**Comment by jodator** [comment]
All the notes below are for the state after merging style processing and table properties features:

So the new style parser is enabled by default and does more things in general. However, I've used `map` instead of events for checking if style processing rules are enabled. So that's one scenario (and looks like the most important one - those paths should be AFAP).

The second scenario is enabling one or more style processing rules (ie by enabling `TableProperties`, `TableCellProperties` or `Indent` plugin) or enabling them manually. So the second path used when fancy colored tables are enabled.

**Comment by mlewand** [comment]
This issue is blocked by #5880 as it will add proper manual tests where performance can be evaluated.

**Comment by mlewand** [comment]
I have verified while doing #5880 that our changes did not affect performance in a notable way.

**Comment by Reinmar** [comment]
> I have verified while doing #5880 that our changes did not affect performance in a notable way.

That's a great news. Thanks!
