### ISSUE TITLE
customize enterMode to BR

### ISSUE THREAD

**Issue by ginzunza** [ckeditor/ckeditor5#617]
In past versions I used to customize enterMode to BR because I don't want a '\<p\>' in every line break.
¿What about this configuration option?. I use in CKEDITOR 4 this plugin https://ckeditor.com/cke4/addon/enterkey.
¿Have you considered developing it or something similar?.
Thanks in advance.

**Comment by Reinmar** [comment]
I'm afraid you're not going to like it, but enter mode BR is the root of all evil. If we were able we'd removed it from CKEditor 4 long time ago and we're definitely not going to implement it in CKEditor 5.

To make it clear – by enter mode BR I understand cases where block features such as lists, headings, tables are used in an editor which doesn't wrap text in paragraphs, but instead separate lines of content by `<br>` elements. There are valid cases for `<br>` elements, such as enabling editors on heading elements (`<h1-6>`), on paragraphs, editing image captions or implementing [<kbd>Shift</kbd>+<kbd>Enter</kbd> support](https://github.com/ckeditor/ckeditor5-enter/issues/2) (which is meant to insert `<br>`s inside paragraphs).

So, what's wrong with enter mode BR?

## Enormous complexity

It mixes inline and block content. Usually, your content will look like this – there's a root, it contains block elements which contain inline elements (actually, it's a bit more complicated, but it's enough for now). If you start using enter mode BR you end up with root that contains inline content mixed with block content. E.g.:

```html
<h2>Line0</h2>
Line1<br>
Line2
<ul>
    <li>Line3</li>
</ul>
Line4
```

Every single algorithm needs to start considering such content. E.g. in CKEditor 4 when you had an algorithm which applies heading to the selected blocks (think – paragraph, list items, etc) it suddenly needs to understand that "Line1" is one block and "Line2" is another. This makes things awfully complicated.

Of course, CKEditor 5 has a custom data model so in that model you could have:

```html
<h2>Line0</h2>
<line>Line1</line>
<line>Line2</line>
<listItem>Line3</listItem>
<line>Line4</line>
```

which you could render to the HTML from which we started. Since most editing algorithms work on the data model they will still get a proper `root > block > inline` structure.

However, editing algorithms are one thing. All that needs to be rendered to DOM and CKEditor 5's engine is not prepared to mix inline stuff with block stuff. Why? Because of the complexity again.

BTW, what should happen if someone wants to apply "text align center" to "Line1"? What if that person wants to remove that style?

## Semantically incorrect

It's semantically dubious to mix block content with inline content. When such features as lists and headings are enabled, you must enable the paragraph feature as well because then the whole content should be made out of blocks.

## Margins between paragraphs are not a problem!

Whenever I ask why someone wants to enable the enter mode BR it turns out that that person doesn't like margins (spaces) between paragraphs. That makes some sense because people used to word processors such as MS Word think about the content a bit differently.

However, that's not a problem. You can remove margins between paragraphs with a simple CSS rule:

```css
p {
   margin: 0;
}
```

And your content will look as if only `<br>`s were used.

## Summary

Enter mode BR makes little sense (in terms of semantics) and is extremely complex to handle. Besides, few people really want `<br>`s – instead, they want not spacing. Therefore, we made a decision to never try to implement enter mode BR.

**Comment by noeltimothy** [comment]
I still want to use enterMode: 2 which is BR. Is there a way to force this?

**Comment by alpesh88ww** [comment]
it will convert P to Div

`<ckeditor name="body" [editor]="ckService.Editor" [config]="ckService.editorConfig" #editor *ngIf="isLayoutReady" (ready)="onEditorReady($event)"/>`

```
onEditorReady(editor: any): void {
        this.editorInstance = editor;
        // 🔧 Replace <p> with styled <div>
        editor.conversion.for('dataDowncast').elementToElement({
            model: 'paragraph',
            view: (_modelElement: any, { writer }: { writer: any }) => {
                return writer.createContainerElement('div', {
                    style: 'font-size:14px;padding-bottom:12px;'
                });
            },
            converterPriority: 'high'
        });
        editor.conversion.for('editingDowncast').elementToElement({
            model: 'paragraph',
            view: (_modelElement: any, { writer }: { writer: any }) => {
                return writer.createContainerElement('div', {
                    style: 'font-size:14px;padding-bottom:12px;'
                });
            },
            converterPriority: 'high'
        });
        console.log('✅ CKEditor now inserts styled <div> instead of <p>');
    }
```
