### ISSUE TITLE
Do execute('enter') after insertContent, content is removed

### ISSUE THREAD

**Issue by bum-hyun** [ckeditor/ckeditor5#6172]
```
this.CKEDITOR.model.change((writer: any) => {
        const image = writer.createElement('image', {src: data});
        writer.appendElement('caption', image);
        if(textAndCaption && textAndCaption!.caption){
          writer.appendText(textAndCaption!.caption, image.getChild(0));
        }
        this.CKEDITOR.model.insertContent(image, this.CKEDITOR.model.document.selection);
});

```

when I did this.CKEDITOR.execute('enter') after insertContent,
Image is removed that I inserted because of paragraph

**Comment by Reinmar** [comment]
Where's the selection placed after you insert the image? If it's on the image, executing enter will delete this image because you override it. That's what enter usually do in editors.

Note: when you press enter in CKE5 right now, it will actually insert a paragraph below an image but that's not related to normal enter handling. It's a workaround for https://github.com/ckeditor/ckeditor5/issues/407 and the command doesn't do that.

So, anyway, what you need to do is to insert the paragraph below an image and put the selection there manually. IDK a quicker method here.
