### ISSUE TITLE
Table props dialog displayed offscreen (while table cell dialog works fine)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6181]
![Feb-03-2020 16-43-29](https://user-images.githubusercontent.com/156149/73667353-6cabca00-46a4-11ea-8172-b07602809f40.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Let's give this thing 2h and see if we see a solution.

**Comment by panr** [comment]
This is weird... I've been seeing this for a very long time, but right now I can't reproduce it... 😅
Do we have established steps for this issue?

**Comment by oleq** [comment]
I think the problem is around here https://github.com/ckeditor/ckeditor5-utils/blob/master/src/dom/position.js#L185-L200. 

When there's both limiter and `fitInViewport`, the algorithm intersects the limiter with the viewport and tries to find the position that fits best in that intersection. And then this actually makes sense: 
![image](https://user-images.githubusercontent.com/1099479/77744256-a6041480-7019-11ea-849e-2d97127cdfbf.png)

Give it just a little bit more space below the widget, and suddenly the opposite position is better:

![image](https://user-images.githubusercontent.com/1099479/77744368-d350c280-7019-11ea-8fb0-4bea15bc319b.png)

I think this logic is just a little naive. I think we should separately check 
* the `intersection( limiter, viewport )`
* but also if the element fits in the viewport. 

For instance, we could loop over the positions and sort them according to the biggest `intersection( elementRect, viewport )`. Then, on those sorted positions, we could do the logic that checks `intersection( limiter, viewport )`. 

It's a 2-D optimization problem. Picture it as the X-axis representing the element/viewport intersection and the Y-axis representing the limiter/viewport intersection. We want to find the (x,y) point in that 2-D space that will create the rectangle of the biggest area [ (0,0), (x,y) ].

**Comment by oleq** [comment]
On the second thought, maybe it's not a plain 2-D optimization after all. We may need to prioritize if fitting in viewport is more important than fitting into the editable (or vice versa). Research...
