### ISSUE TITLE
Should we drop `env.isEdge` from our code base?

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6202]
## Provide a description of the task

Thinking about new Edge - we have some conditional statements in features code and in tests code as well. Dropping this could be fun.

**Comment by Reinmar** [comment]
Oh, definitely. That, plus all occurrences.

**Comment by tomalec** [comment]
I removed all occurrences of `env.isEdge` and tests for specific behavior in case of its presence. 
Run `npm run test` for Firefox, Chrome. I didn't find any manual tests related to it, so I just check a few random ones.

I was not sure, whether I should touch 
1. https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/domconverter.js#L172 
  Was the initial, non-Edge/pre-Edge16 intent to use 
`domElement.childNodes.forEach`? (https://caniuse.com/#search=forEach). I leave it as it is, as it's still uniform cross-browser solution.

2. https://github.com/ckeditor/ckeditor5-engine/blob/master/tests/view/renderer.js#L2059
 I guess Chromium-based Edge is no longer an exception here, but I assume it may be still neded for Safari.
3. https://github.com/ckeditor/ckeditor5-image/blob/master/src/imageupload/utils.js#L96 
 According to https://developer.mozilla.org/en-US/docs/Web/API/File#Browser_compatibility since (Chromium-based) Edge 79 constructor is supported. However, I'm not sure whether it is in the scope of this issue.
4. https://github.com/ckeditor/ckeditor5-link/blob/master/src/linkui.js#L188
 I haven't dive deaper, but assume it's needed for FF and not in scope of this issue.
5. https://github.com/ckeditor/ckeditor5-paste-from-office/blob/master/src/filters/space.js#L43 ...
6. https://github.com/ckeditor/ckeditor5-table/blob/master/tests/converters/upcasttable.js#L207 ...
7. https://github.com/ckeditor/ckeditor5-theme-lark/blob/master/theme/ckeditor5-ui/components/button/switchbutton.css#L93 ...
8. https://github.com/ckeditor/ckeditor5-ui/blob/master/src/inputtext/inputtextview.js#L119 ...
9. https://github.com/ckeditor/ckeditor5-ui/blob/master/tests/icon/iconview.js#L134
 Seems 5-9 could be simplified, but I assume that it is not in the scope of this issue.

And naturally we could consider updating https://github.com/ckeditor/ckeditor5/blob/master/docs/builds/guides/support/browser-compatibility.md#desktop-environment
