### ISSUE TITLE
`editor.getData()` hitting TypeError tm.get(...).indexOf is not a function

### ISSUE THREAD

**Issue by archonic** [ckeditor/ckeditor5#6243]
## 📝 Provide detailed reproduction steps

1. Implement decoupled editor instance v16 with collaborative editing, with blank contents
2. Write any content
3. Use the console to get the output of `editor.getData()`

### ✔️ Expected result

Editor should output HTML of editor contents.

### ❌ Actual result

`editor.getData()` will correctly return "" before there's contents. After there's contents, I get this:
```
parser.js:250 Uncaught TypeError: tm.get(...).indexOf is not a function
    at Function.endParseEditMode (parser.js:250)
    at Im.toData (custommathmldataprocessor.js:49)
    at Rs.stringify (datacontroller.js:171)
    at Rs.get (datacontroller.js:154)
    at HP.getData (dataapimixin.js:28)
    at <anonymous>:1:8
```

## 📃 Other details

* Browser: Chrome 80.0.3987.87 (Official Build) (64-bit)
* OS: Mac OS X Catalina 10.15.3 (19D76)
* CKEditor version: 16.0.0
* Installed CKEditor plugins:
```
Essentials,
Autoformat,
Bold,
Italic,
Underline,
BlockQuote,
Image,
ImageCaption,
ImageResize,
ImageStyle,
ImageToolbar,
ImageUpload,
Link,
List,
Mention,
MathType,
Paragraph,
PasteFromOffice,
Table,
TableToolbar,
TodoList,
RemoveFormat,
Alignment,
FontSize,
FontFamily,
FontColor,
FontBackgroundColor,
Strikethrough,
Superscript,
Subscript,
Heading,
HorizontalLine,
PageBreak,
Indent,
RealTimeCollaborativeEditing,
PresenceList,
TrackChanges
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by archonic** [comment]
Upon actually reading the error (😅), it looked to be the result of using MathType. I don't have a MathType license so I thought that might be causing it, but I removed the MathType plugin and now the error is:
```
util.js:783 Uncaught TypeError: tm.get(...).indexOf is not a function
    at Function.endParseEditMode (util.js:783)
    at Im.toData (mentionediting.js:141)
    at Rs.stringify (datacontroller.js:171)
    at Rs.get (datacontroller.js:154)
    at HP.getData (dataapimixin.js:28)
    at <anonymous>:1:8
```

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I just checked the setup you provided and I had no problems with `getData()` ( with and without MathType ). Seeing your editor configuration may be helpful.
One tip: if you are using `RealTimeCollaborativeEditing`, you should also use `RealTimeCollaborativeTrackChanges` instead of normal `TrackChanges`.

Apart from that, this GitHub issue tracker is mainly for open source community, so if you are using our commercial services and have any problems, please use a [dedicated support channel](https://ckeditor.com/contact/). Our team will try to analyse all issues reported there and will get back to you as soon as possible.
Hope that helps!

**Comment by archonic** [comment]
Ah, didn't realize I'd need `RealTimeCollaborativeTrackChanges`. I'll play around with it and if I have further issues, I'll open a support ticket. Thanks!
