### ISSUE TITLE
Ctrl + Arrow navigation skips period

### ISSUE THREAD

**Issue by hamenon** [ckeditor/ckeditor5#626]
## 🐞 Is this a bug report or feature request?

- [x] Bug report

## 💻 Version of CKEditor
Latest. Tested on the sample site (http://nightly.ckeditor.com/17-10-20-06-05/standard/samples/) 

## 📋 Steps to reproduce

type "this is a sentence one. another word."
hit ctrl+left arrow to move word by word
Navigation is incorrect.

## ✅ Expected result
Stop between e and . in 'sentence'.
## ❎ Actual result
Doesn't stop between e and . in 'sentence'.
## 📃 Other details that might be useful
Check the behavior in google docs, word etc.

**Comment by Mgsy** [comment]
Hi! Thank you for your bug report. The editor on the example site which you've tested on is `CKEditor 4`, which is much different than `CKEditor 5` (you can test it here - https://ckeditor.com/ckeditor-5-builds/). All bugs related to `CKEditor 4` should be reported in proper repository - https://github.com/ckeditor/ckeditor-dev. 

I'd also like to encourage you to read more about difference between `CKEditor 4` and `CKEditor 5`. You can find the comparison here - https://support.ckeditor.com/hc/en-us/sections/115001489149-The-CKEditor-4-and-CKEditor-5-Comparison.

I checked your issue and indeed, the caret doesn't stop on dots while navigating with <kbd>Ctrl</kbd> + <kbd>Arrow</kbd>, but this is not because of the editor. It's a browser issue, which occurs on `Chrome`, `Firefox`, `Safari` and `Opera`. Works fine on `Edge` and `IE11`. You can check it with simple `<div contenteditable="true">` - https://jsfiddle.net/t6zqg28d/. 

As it works properly on `Edge` and `IE11`, is it in our plans to change this behaviour on other browsers? 
cc @Reinmar

**Comment by Reinmar** [comment]
> As it works properly on Edge and IE11, is it in our plans to change this behaviour on other browsers?

Overriding such native behaviours is always risky. The main problem here is the countless languages that we'd need to support (where there are no periods or words are differently separated). So, while this is technically possible, I don't think that we'd like to touch this.

**Comment by Reinmar** [comment]
I think that we can close this bug report with "wontfix", although, it'd be good to check if this is reported for Blink, Webkit and Gecko.
