### ISSUE TITLE
What kind of tool you used to generate this book from md files

### ISSUE THREAD

**Issue by dumindu** [ckeditor/ckeditor5#627]
Hi,

For some open source project, I need to generate a documentation with examples. Currently I am using Gitbook but I like the design and fast response times on your documentation. So may I know the tools you are using to generate https://docs.ckeditor.com/ckeditor5/latest/ ?

Thanks

**Comment by wwalc** [comment]
Hi,

You can speed up the response time of the documentation by making it completely static and putting it into a CDN. Most of the time it helps a lot. 

Regarding  https://docs.ckeditor.com - we created the documentation using our own, custom tool: [Umberto](https://www.npmjs.com/package/umberto) If we get more requests like this one we may try to make it more open, creating a lot of docs for the tool itself and so on. The problem is that we are using our own flavour of JSDoc using [extra plugins](https://github.com/ckeditor/ckeditor5-dev/tree/master/packages/jsdoc-plugins) and without some significant extra effort from our side it may be a bit hard to use it by others. Additionally we'd have to come up with some generic theme for it, so that the current CKEditor documentation had its own, unique look. 

In any case, if anyone reading this is interested in using Umberto, please add 👍

**Comment by dumindu** [comment]
@wwalc about the hexo theme you are using, is it open source? can I use it for a non-profit projects [1](https://dumindu.gitbooks.io/learning-rust/content/), [2](https://dumindu.gitbooks.io/practicing-rust/content/01.%20hello_world.html)
