### ISSUE TITLE
Implement the text alignment feature

### ISSUE THREAD

**Issue by sebszocinski** [ckeditor/ckeditor5#634]
Can we get text alignment for CKEditor5. It's the only missing button in my opinion.

**Comment by oleq** [comment]
We're super excited that developers use the alpha of CKEditor 5 in their projects. This feature is definitely on our roadmap to v1.0.0 so stay tuned!

**Comment by fredck** [comment]
We plan to work on that, but maybe you could share a bit of your experience on this.

What are the use cases for text alignment? I mean, I understand of course what alignment does, but in which specific situations the user would want to do it and for which reason.

I'm asking this because there is little-to-no semantics on this feature. It seems to be the typical formatting-only thing, which is definitely not welcome for the modern web content.

Are you able to list all the possible use cases that came to your mind? It would be wonderful to have such kind of feedback. Thanks!

**Comment by oleq** [comment]
I think @jodator would also be interested in this issue.

**Comment by jodator** [comment]
The ticket will be handled by: https://github.com/ckeditor/ckeditor5-alignment/issues/2.

**Comment by jodator** [comment]
I'm closing this as https://github.com/ckeditor/ckeditor5-alignment/pull/7 was closed yesterday and alignment package was introduced in [packages list](https://github.com/ckeditor/ckeditor5#packages).
