### ISSUE TITLE
Deprecated Comment API

### ISSUE THREAD

**Issue by Paskid** [ckeditor/ckeditor5#6360]
From the documentation https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-integration.html

The comment plugin's API shown contains methods like `getCommentThreads`, the method returns an empty array (at least for me since I upgraded to v17) and a warning appears stating that it is deprecated.

See deprecation errors from here:
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-comments-adapter-deprecated

1. Documentation should indicate that current methods are deprecated and should inform of the new approach to take.
2. The API documentation should reflect the changes.
3. (out of topic) Deprecated methods should still work until they are replaced (at least in the documentation).

**Comment by Mgsy** [comment]
Hi! Thanks for the report. The `Comments` API has changed and now, instead of using it, you should use the `CommentsRepository` API. So, to get all comment threads from the document you should call:
```js
const commentsRepository = editor.plugins.get( 'CommentsRepository' );

commentsRepository.getCommentThreads();
```

The old API is still valid, so you can use it, however, we recommend to use new API, because the old one **will be removed** in the next iteration. We display a warning about deprecated API to prepare users for upcoming changes.

We've released a new version of the documentation, so now, you can find there all the necessary information. Please, see the [Comments API section](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-api.html) to learn more.

Also, please note that this issue tracker is for the open-source part of the project and Comments are our commercial plugin. In case of any further problems related to our collaborative features, please contact us through the [support channel](https://ckeditor.com/contact/), so our team will be able to help you in a more efficient way.

**Comment by Paskid** [comment]
Hi @Mgsy , thanks for the feedback, it helps a ton.

The biggest issue I had was that using the old API didn't work anymore. Since the update, calling `editor.plugins.get('Comments').getCommentThreads()` always returns an empty array for me.

Using the new API does return the comment threads but the issue I am having with the new API is that all new comments have an invalid date at creation. The same behaviour can be seen in the Comments Integration demo:
https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-integration.html#demo

Simply add a new comment anywhere and check the new comment's date.

**Comment by Paskid** [comment]
Sorry I just read the last part of your comment so I'll close this and redirect my inquiry elsewhere. Thank you.

**Comment by scofalik** [comment]
Hello, @Paskid.

This iteration brought a lot of changes to collaboration features and we are aware that it is confusing to the users. This is why, from this iteration forward, we provide a changelog that should make it easier to upgrade your editor version. Changelog is available at: https://ckeditor.com/collaboration/changelog/. The link to the changelog will be soon added to the collaboration features packages websites on npmjs and cross-linked from CKE5 changelog.

Also, we will provide a release blog post, just like the ones we do for CKE5 (https://ckeditor.com/blog/CKEditor-5-v17.0.0-with-table-styles-special-characters-and-performance-improvements/).

However, we are a bit tight on the schedule, hence we were a few days behind with the docs and changelog. Sorry for any inconvenience. All the docs should be updated right now.

As far as your issue is conecnred - old `Comments` API should work as it was, and, also, of course the new API should add comments corerctly. We will look into that issue.

**Comment by Paskid** [comment]
Hi @scofalik ,

Thanks for the feedback. I saw the changelog for the editor, I didn't know there was a distinct one for collaboration. I will keep that in mind the next time a new version comes out.

Thank you very much

**Comment by scofalik** [comment]
I wanted to let you know that we've identified the issue and it will be fixed in the next iteration (the release is planned on 19th March).
