### ISSUE TITLE
Table converters break view mappings when removing multiple rows with headers during a single change transaction

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6391]
## 📝 Provide detailed reproduction steps (if any)

Use a following test code:

```plaintext
it( 'should properly remove mixed header and regular row and allow for changing selection', () => {
	setModelData( model, modelTable( [
		[ '00', '01' ],
		[ '10', '11' ],
		[ '20', '21' ]
	], { headingRows: 1 } ) );

	editor.model.change( writer => {
		const table = model.document.getRoot().getChild( 0 );
		const cellToFocus = table.getChild( 2 ).getChild( 0 );

		writer.remove( table.getChild( 1 ) );
		writer.removeAttribute( 'headingRows', table );
		writer.remove( table.getChild( 0 ) );

		writer.setSelection( writer.createPositionAt( cellToFocus, 0 ) );
	} );

	assertEqualMarkup( getViewData( model ), modelTable( [
		[ '[]20', '21' ]
	] ) );
} );
```

### ✔️ Expected result

The test passes, rows are removed and selection is placed in the first cell of last row.

### ❌ Actual result

An error is thrown:

```plaintext
Chrome 80.0.3987 (Windows 10.0.0) downcast converters downcastRemoveRow() should properly remove mixed header and regular row and allow for changing selection FAILED
        TypeError: Cannot read property 'is' of undefined
            at Mapper._findPositionIn (webpack:///./packages/ckeditor5-engine/src/conversion/mapper.js?:550:19)
            at Mapper.on.priority (webpack:///./packages/ckeditor5-engine/src/conversion/mapper.js?:116:29)
            at Mapper.fire (webpack:///./packages/ckeditor5-utils/src/emittermixin.js?:218:30)
            at Mapper.toViewPosition (webpack:///./packages/ckeditor5-engine/src/conversion/mapper.js?:343:8)
            at DowncastDispatcher.eval (webpack:///./packages/ckeditor5-engine/src/conversion/downcasthelpers.js?:526:45)
            at DowncastDispatcher.fire (webpack:///./packages/ckeditor5-utils/src/emittermixin.js?:218:30)
            at DowncastDispatcher.convertSelection (webpack:///./packages/ckeditor5-engine/src/conversion/downcastdispatcher.js?:279:8)
            at eval (webpack:///./packages/ckeditor5-engine/src/controller/editingcontroller.js?:104:29)
            at View.change (webpack:///./packages/ckeditor5-engine/src/view/view.js?:494:27)
            at Document.EditingController.listenTo.priority (webpack:///./packages/ckeditor5-engine/src/controller/editingcontroller.js?:102:14)
```

Editor can not be operated.

## 📃 Other details

*   Browser: Any
*   OS: Any
*   CKEditor version: latest `master`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
This issue can be worked around by doing the change in multiple `writer.change()` calls, but in that case it creates multiple undo snapshots.

**Comment by jodator** [comment]
I see an option to have one undo step and current downcast converters but I'm not sure what is a best option here.

The problem IMO is that table attribute conversion is done before child modifications. This is somewhat natural but for table case is tricky (damn you `<tbdoy>` and `<thead>`). The proper way of calculating things is to:

1. remove rows
2. update headings sections

Now the current command does it on every row removal and this is a problem because (as for now) all blocks he the same priority (using `model.enqueueChange()` instead of single `model.change()`). Now the code in the snippet will not work because `heading` downcast is done before removing rows and something brokes - not proper rows are removed in the first place.

The simplest fix is to:

```js
editor.model.change( writer => {
	const table = model.document.getRoot().getChild( 0 );
	const cellToFocus = table.getChild( 2 ).getChild( 0 );

	writer.remove( table.getChild( 1 ) );
	writer.remove( table.getChild( 0 ) );

	model.enqueueChange( writer => {
		writer.removeAttribute( 'headingRows', table );
		writer.setSelection( writer.createPositionAt( cellToFocus, 0 ) );
	} );
} );
```

so the nested `enqueChange` in parent `change` block does what is need - moves the downcast of heading attribute to the later stage.

Now. I think that attribute change downcast might do something wrong here but I'm not 100% sure.

**Comment by jodator** [comment]
Unfortunately, we cannot do this in a loop (remove row command). The heading rows must be calculated for the whole operation at once - but this seems pretty straightforward.

**Comment by jodator** [comment]
And the proposed changes landed in `i/6391` branch but waiting for https://github.com/ckeditor/ckeditor5-table/pull/286  PR merge.
