### ISSUE TITLE
In classic ckeditor 5 uploaded image is getting deleted on any key press

### ISSUE THREAD

**Issue by vijay-sahu-xelp** [ckeditor/ckeditor5#6393]
## 📝 Provide detailed reproduction steps (if any)

1.Image is getting uploaded
2. Image is getting delete and replaced by paragraph on pressing any key
3. This function is not present in ckeditor 4 where it ckeditor 5 it is getting deleted.

ckeditor 4 demo: 
https://ckeditor.com/ckeditor-4/demo/ 

ckeditor 5 demo:

https://ckeditor.com/ckeditor-5/demo/

### ✔️ Expected result
Image should only deleted on pressing delete or backspace.

_What is the expected result of the above steps?_

Image should only get deleted on presssing delete or backspace key.

### ❌ Actual result

Image is getting deleted on pressing any key.

_What is the actual result of the above steps?_

## 📃 Other details

* Browser: … Google chrome
* OS: …       Mac or windows
* CKEditor version: … 5
* Installed CKEditor plugins: …. classic ckeditor 5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! Why do you think that the image should be deleted only on backspace/delete? It is deleted by any key in all the editors I know (except CKE4).

**Comment by vijay-sahu-xelp** [comment]
Yes, you are right. Only in CKE4 on selecting image and typing, any alphanumeric character does not delete the image.

I was expecting the same behavior with CKE5.

Can you please help me achieve the same with CKE5???
Thanks in advance.

**Comment by mlewand** [comment]
I don't think this is expected behavior from rich text editor - when pressing a _printable key_ you as and  end user typically mean to insert this character (as long as it is not a keystroke/hotkey).

You can observe analogical situation when selecting some text (e.g. one word) and typing "a" - your selected word gets replaced with "a". The same should happen for image, table or any other content object.

So this question is more of a support question on how to handle such cases.
