### ISSUE TITLE
An example of plugin that allows all the HTML5 elements to be supported

### ISSUE THREAD

**Issue by Nothing-Works** [ckeditor/ckeditor5#6417]
Hi I am reading this [FAQ](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#why-does-the-editor-filter-out-my-content-styles-classes-elements-where-is-configallowedcontent-true) basically I want to do this 

> If you load some content unknown to any editor feature, it will be dropped. If you want all the HTML5 elements to be supported, you need to write plugins to support them. Once you do that, CKEditor 5 will not filter anything out.

I am just wondering is there an example that somewhere in the docs? thanks.

**Comment by Mgsy** [comment]
Hello, CKEditor 5 has a custom data model and recognizes only allowed elements. Each element should be registered in the [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html) and have a proper [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html).

There's no example showing how to enable all elements because some of them should be handled differently (i.e. blockquotes which wrap the content). So, it's up to the developer how he would implement the plugin. The links above will be a good starting point to learn about the editor, you can also check our [Creating a simple plugin guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html).
