### ISSUE TITLE
[Table] Delete row button is enabled and results in crash after splitting cell horizontally and selecting whole column

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6431]
## 📝 Provide detailed reproduction steps (if any)

1. Open some table test
2. Select some cell and click `Split cell horizontally`
3. Select a whole column
4. Click `Delete row`

### ✔️ Expected result

`Delete row` button is disabled, you cannot delete all rows by selecting the whole column

### ❌ Actual result

`Delete row` button is enabled, clicking it results in crash:  
  
![13_table1](https://user-images.githubusercontent.com/34380544/76611460-d7111f00-651a-11ea-8cca-2f13bee3bd75.gif)
  
  
Error:  
  
```js
Uncaught TypeError: Cannot read property 'getChild' of null
    at getCellToFocus (removerowcommand.js:155)
    at Object.callback (removerowcommand.js:77)
    at Model._runPendingChanges (model.js:801)
    at Model.enqueueChange (model.js:227)
    at RemoveRowCommand.execute (removerowcommand.js:73)
    at RemoveRowCommand.<anonymous> (observablemixin.js:255)
    at RemoveRowCommand.fire (emittermixin.js:209)
    at RemoveRowCommand.<computed> [as execute] (observablemixin.js:259)
    at CommandCollection.execute (commandcollection.js:68)
    at ClassicEditor.execute (editor.js:288)
```
### Other info:
Similar: https://github.com/ckeditor/ckeditor5/issues/6401

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
This issue was caused by invalid rows counting. With following structure.  [Currently it accounts for `rowspan` attribute](https://github.com/ckeditor/ckeditor5-table/blob/abe9d05110025616a1a80cd940bf89282ed89cb0/src/tableutils.js#L563-L567) but also adds all rows, without checking whether the tr belongs to (e.g. first column) or "is consumed" by the rowspan.

Based on example, table like this:

![](https://user-images.githubusercontent.com/5353898/76619434-25c6b500-652b-11ea-94ff-503dbc830eb0.png)

Yields 5 rows, which is wrong, it has logically 4 rows.

That's because of extra row where "steamed" and "foam" cells are located is considered to be in the first column too. Here's model dump for reference:

```plaintext
[ {
	"name": "tableRow",
	"children": [ {
		"attributes": {
			"rowspan": "2"
		},
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	}, {
		"attributes": {
			"colspan": "2"
		},
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	} ]
}, {
	"name": "tableRow",
	"children": [ {
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	}, {
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	} ]
}, {
	"name": "tableRow",
	"children": [ {
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	}, {
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	}, {
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	} ]
}, {
	"name": "tableRow",
	"children": [ {
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	}, {
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	}, {
		"name": "tableCell",
		"children": [ {
			"name": "paragraph"
		} ]
	} ]
} ]
```
