### ISSUE TITLE
Table loses geometry after horizontal split and removing column

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6439]
## 📝 Provide detailed reproduction steps (if any)

1. Open some table test
2. Select a cell and split horizontally
3. Click `Delete column`

### ✔️ Expected result

Column is deleted

### ❌ Actual result

Geometry is lost, additional columns inserted, content changes cells:  
  
![16_table2](https://user-images.githubusercontent.com/34380544/76740904-e25c8880-676e-11ea-8e36-5e2559c0c0f9.gif)

## 📃 Other details

It occurs on master, on online docs ( since version 11.1.0 ) it behaves a bit different - after deleting column, you can see there is a ~1px space between the last column and table border highlight ( with a few pixels rendered grey ):
![16_table3](https://user-images.githubusercontent.com/34380544/76741512-f359c980-676f-11ea-932a-31f95c0d5d02.gif)

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
> It occurs on master, on online docs ( since version 11.1.0 ) it behaves a bit different - after deleting column, you can see there is a ~1px

The reason is that there's an empty row (with only a `br`) in the model:

![](https://user-images.githubusercontent.com/5353898/76951076-5b90e280-690b-11ea-996e-a158a7b9cae1.png)

That remind me of "it's highly possible that other commands might produce a markup like this in certain scenario" part in https://github.com/ckeditor/ckeditor5/issues/6422#issuecomment-598224993 :smile:

**Comment by mlewand** [comment]
Potentially related issue: #6406. Moving to nice-to-have milestone, see https://github.com/ckeditor/ckeditor5/issues/6406#issuecomment-600575822.

**Comment by jodator** [comment]
One cannot simply `writer.remove( tableRow )` in tables :/ #6545
