### ISSUE TITLE
Removing complex emojis doesn't work as expected

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#6504]
## 📝 Provide a description of the improvement

<kbd>Delete</kbd> and <kbd>Backspace</kbd> are working as expected on simple emoji (ones that use single code point), but for complex ones it removes one code point at a time (in both directions).

## 📃 Other details
Sample text with different emojis:
* Simple 👩 emoji.
* Simple 👩🏻 emoji with shin color modifier (👩, <code>FITZ-1</code>).
* Emoji sequence 👩‍🦰 with zero-width joiner (👩, <code>ZWJ</code>, 🦰).
* Emoji sequence 👩🏻‍🦰 with zero-width joiner and skin color modifier (👩, <code>FITZ-1</code>, <code>ZWJ</code>, 🦰).

In both cases code points are removed one by one, also <code>ZWJ</code> is removed as a separate code point.

### The <kbd>backspace</kbd> case
![emoji-backspace](https://user-images.githubusercontent.com/1232187/77675494-4eb86280-6f8d-11ea-8164-caceadfd0dc3.gif)

### The <kbd>delete</kbd> case
![emoji-delete](https://user-images.githubusercontent.com/1232187/77675531-5841ca80-6f8d-11ea-95bf-9139768d5f47.gif)
Also in case of <kbd>delete</kbd> cursor seems to jump just after emoji (but when you hit <kbd>delete</kbd> again it removes part of emoji in front of it).

Skin color modifier without meaningful emoji before it tries to apply color on preceding code point (for <kbd>space</kbd> it renders as colored square) and browser treats that code point as part of emoji (you can't place cursor inside).

* Browser: Chrome 80
* OS: macOS 10.14
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
```javascript
'foo🙂👪👪👩🏻‍🦰👩🏻👩‍🦰bar'.match(/\p{Emoji}\p{Emoji_Component}*/gu)
```

**Comment by ymaz** [comment]
Any progress on that issue?

**Comment by Reinmar** [comment]
*   Context: Where does the idea that backspace need to use `codePoint` even come from? Does it work this way in any editor?
    *   Copy some content from [https://en.wikipedia.org/wiki/Zero-width_joiner](https://en.wikipedia.org/wiki/Zero-width_joiner) to Word and it indeed deletes them bit by bit.
    *   Apart from the support for emojis, CKE5 works identical to Word.
*   Finding: It turns out that in our editor, forward delete, even though it uses `options.unit=character`, deletes only a part of 👩🏻 (Simple 👩🏻 emoji with shin color modifier (👩, FITZ-1)).
    *   In Word, every kind of emoji is always treated as a whole, regardless of joiners and direction of deletion.
*   Idea: Add option to `modifySelection():`
    *   `options.treatEmojiAsSingleUnit`
    *   Make sure that when this option is `true`, regardless of the `options.direction`, always entire emoji is consumed.
    *   In which cases (apart from `DeleteCommand`) we should also use this option?
        *   CF: delete command: yep
        *   in all other cases we pass “probe”: nope
*   Before starting this task make sure to read: [https://dmitripavlutin.com/what-every-javascript-developer-should-know-about-unicode/](https://dmitripavlutin.com/what-every-javascript-developer-should-know-about-unicode/)
*   The regexp provided by Kuba in the ticket works in all browsers: [https://caniuse.com/?search=Unicode](https://caniuse.com/?search=Unicode) property escape

**Comment by arkflpc** [comment]
Random links to consider:

[https://unicode-table.com/en/emoji/](https://unicode-table.com/en/emoji/)

[https://unicode.org/reports/tr51/](https://unicode.org/reports/tr51/) (technical standard for emoji)

[https://www.unicode.org/Public/14.0.0/ucd/emoji/emoji-data.txt](https://www.unicode.org/Public/14.0.0/ucd/emoji/emoji-data.txt) (promising one)

**Comment by Reinmar** [comment]
Meeting notes:

*   The proposed solution (the first one) doesn't work. It's too loose.
    *   We need automated tests for those cases with numbers, aterisk, etc (for future safety).
    *   We also need to check that we won't mistakenly delete two emojis at once.
*   We need to better research that the regexps that we will use won’t cover too many characters.
*   The only solution: Check this either by brute force or by analyzing the unicode specs in detail.
*   If we were using beforeInput already, we'd probably found the info what to remove in the range provided by this event :(

**Comment by arkflpc** [comment]
The summary of work done.

1.  The first proposed regex (\\p{Emoji}\\p{Emoji\_Component}\*) gave positive results for sequence of digits (they have Emoji property).
2.  The standard https://unicode.org/reports/tr51/ turned out to be complicated, simpler implementations resulted in false negatives for many scenarios, including those in the ticket description.
3.  Some time was spent trying to implement and test different approaches in the same style as other unicode-related functions like isInsideCombinedSymbol(), i.e. to test each individual code point. It was a dead end. The final implementation is matching the whole string against regular expression and check where are the offsets of each match.
4.  Regular expression that explicitly matches all patterns from https://www.unicode.org/Public/14.0.0/ucd/emoji/emoji-data.txt, like https://github.com/mathiasbynens/emoji-test-regex-pattern was discarded as it takes 17KB (uncompressed).
5.  In order to help to evaluate regular expressions that could give us as few false negatives as possible, a script was created to match it against emoji-data.txt (see below). We found a solution that detects 97% of emojis in emoji-data.txt.
6.  There are no ready files with data for negative scenarios. Manual tests confirmed there are no false positives. We are quite confident with this, assuming that:
    1.  there are only few characters with Emoji property, which are no emoji (digits, (c), (tm), etc.), and
    2.  emoji presentation can be disabled by text presentation selector character.

```javascript
const fs = require( 'fs' );

// File downloaded from: https://unicode.org/Public/emoji/14.0/emoji-test.txt
const TEST_DATA = fs.readFileSync( 'emoji-test.txt', { encoding: 'utf8' } );

let perfectMatches = 0;
let partialMatches = 0;
let noMatches = 0;

const lines = TEST_DATA
	.split( '\n' )
	.filter( line => line.trim() != '' && !line.startsWith( '#' ) )
	.map( line => line.replace( /^.*?# /g, '' ).replace( / E\d.+$/g, '' ) );

const parts = [
	// Emoji Tag Sequence (ETS)
	/\p{Emoji}[\u{E0020}-\u{E007E}]+\u{E007F}/ug,

	// Emoji Keycap Sequence
	/\p{Emoji}\u{FE0F}?\u{20E3}/ug,

	// Emoji Presentation Sequence
	/\p{Emoji}\u{FE0F}/ug,

	// Single-Character Emoji / // Emoji Modifier Sequence
	/(?=\p{General_Category=Other_Symbol})\p{Emoji}\p{Emoji_Modifier}*/ug,
];

const flagSequence = /\p{Regional_Indicator}{2}/ug.source;
const emoji = '(?:' + parts.map( part => part.source ).join( '|' ) + ')';
const sequence = `${ flagSequence }|${ emoji }(?:\u{200D}${ emoji })*`;
const regex = new RegExp( sequence, 'ug' );

const output = lines
	.map( line => {
		const match = Array.from( line.match( regex ) || [] );

		if ( match.length > 1 ) {
			partialMatches++;
			return `${ match.length }\t "${ line }"\t matched as: [` + [ ...match.map( m => `"${ m }"` ) ]  + ']';
		} else if ( match.length === 1 ) {
			perfectMatches++;
			return `${ match.length }\t "${ line }"\t matched as a whole :)`;
		} else {
			noMatches++;
			return `${ match.length }\t "${ line }"\t did not match at all :(`;
		}
	} )
	.filter( v => v )
	.sort()
	.join( '\n' );

console.log( output );
console.log( `We got ${ perfectMatches } perfect matches out of ${ lines.length } (${ perfectMatches / lines.length * 100 }%)` );
console.log( `We got ${ partialMatches } partial matches out of ${ lines.length } (${ partialMatches / lines.length * 100 }%)` );
console.log( `We got ${ noMatches } no matches out of ${ lines.length } (${ noMatches / lines.length * 100 }%)` );
```

**Comment by Reinmar** [comment]
Useful answer on SO:  
https://stackoverflow.com/questions/30757193/find-out-if-character-in-string-is-emoji/59612727#59612727
