### ISSUE TITLE
Alignment plugin set default value

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#6505]
## 📝 Provide a description of the improvement
_How the feature works now and what you'd like to change_?

Be able to set a default values in the editor. Today there is not way to set text-align:left or right, depending on the browser direction.
In my case, I need to set the default alignment to JUSTIFY, but then I cannot set a part of the document as align left.

The plugin could always set the specified values and when a user click the selected value it could then remove the attribute.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. We are aware of this and we know sometimes this might cause problems. This issue is being debated as a part of [broader discussion on default values](https://github.com/ckeditor/ckeditor5/issues/6231). Please follow the ticket from the link I provided and feel free to add your remarks there. I will close this one for now as a duplicate.
