### ISSUE TITLE
The .ck-labeled-input occurrences across the project should be reviewed and replaced with .ck-labeled-view

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6553]
## 📝 Provide detailed reproduction steps (if any)

No idea why but I tried to add link decorators in one of our manual tests and the balloon doesn't have padding:

![](https://user-images.githubusercontent.com/156149/78411061-a9e1f900-760e-11ea-9ae0-ac42ffacfb2a.png)

I saw this bug in the past but I don't know when and how we got rid of it. For some reason, it's back.

For the reference, this is how it should look like:

![](https://user-images.githubusercontent.com/156149/78411167-10671700-760f-11ea-8adc-4bf396530def.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
A regression after https://github.com/ckeditor/ckeditor5/issues/6110. Probably comes down to

```diff
diff --git a/theme/ckeditor5-link/linkform.css b/theme/ckeditor5-link/linkform.css
index 970d54d..a9778cc 100644
--- a/theme/ckeditor5-link/linkform.css
+++ b/theme/ckeditor5-link/linkform.css
@@ -74,7 +74,7 @@
          padding: 0;
          min-width: var(--ck-input-text-width);

-         & .ck-labeled-input {
+         & .ck-labeled-view {
                   margin: var(--ck-spacing-standard) var(--ck-spacing-standard) var(--ck-spacing-small);

                   & .ck-input-text {
```

because it worked for me. Still I see many places across the codebase where `.ck-labeled-input` is used (which should be deprecated as a part of `LabeledInputView`), so I'm lost. How is that things work now? Which is the right class selector, @panr?

----

I just realised that things don't work and we have problems in other places too:

![image](https://user-images.githubusercontent.com/1099479/78531853-870a3d00-77e6-11ea-8dce-b27e6e6b11b9.png)


So all occurrences of `.ck-labeled-input` should be reviewed and fixed.

**Comment by oleq** [comment]
Besides, why is it `.ck-labeled-view` now when the class is `LabeledFieldView`? I couldn't understand where it came from.

**Comment by panr** [comment]
I'll check it.
