### ISSUE TITLE
Code Block with '&' (ampersand) does not work as expected

### ISSUE THREAD

**Issue by hpivanov** [ckeditor/ckeditor5#6563]
## 📝 Provide detailed reproduction steps (if any)

1. Add 'codeBlock' plugin.
2. Set this data to the editor - ```<pre><code class="plaintext hljs">&</code></pre>```

### ✔️ Expected result

I expect to see '&'

### ❌ Actual result

I see '&amp;amp;' - escaped ampersand, which is unexpected.

## 📃 Other details

This occurs only when the ampersand is in code block.

* Browser: Does not matter
* OS: Does not matter
* CKEditor version: Latest
* Installed CKEditor plugins: Does not matter but codeBlock is mandatory

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, we're aware of this issue. Please, see more details [here](https://github.com/ckeditor/ckeditor5/issues/5901).

**Comment by hpivanov** [comment]
@Mgsy Sorry, but is there any quick fix (workaround) for this issue?

**Comment by Mgsy** [comment]
>@Mgsy Sorry, but is there any quick fix (workaround) for this issue?

It's hard to say because we didn't investigate this issue. For sure it's an important problem and we'd like to fix it, however, our capabilities limit us, so we're focused on issues with higher priorities. I'm afraid that the only solution I can recommend is trying to debug it on your own, as we can't promise any date for fixing it.
