### ISSUE TITLE
CKEditor does not detect link

### ISSUE THREAD

**Issue by hpivanov** [ckeditor/ckeditor5#6565]
## 📝 Provide detailed reproduction steps (if any)

1. Open a website.
2. Copy website url.
3. Paste copied url with Ctrl + Shift + V.
4. Copy pasted url with Ctrl + C.
5. Paste copied url with Ctrl + V.

### ✔️ Expected result

Url to be pasted as link.

### ❌ Actual result

Url is pasted as plain text.

## 📃 Other details

* Browser: Chrome (latest version)
* OS: Windows
* CKEditor version: Latest
* Installed CKEditor plugins: Link

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi, auto-linking isn't supported in CKEditor 5. Please, see the [feature request](https://github.com/ckeditor/ckeditor5/issues/4715) to learn more.

**Comment by hpivanov** [comment]
@Mgsy But it is working when I paste the link with Ctrl + V... The problem is do the steps above.

**Comment by Mgsy** [comment]
That's because <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>V</kbd> paste the text as plain text. It means that it removes all the formatting and leaves only text. So, the editor treats inserted link as normal text which shouldn't be converted to link (and the mentioned feature from the request may handle this case).
