### ISSUE TITLE
BlockToolbar looses its position and width

### ISSUE THREAD

**Issue by panr** [ckeditor/ckeditor5#6570]
## 📝 Provide detailed reproduction steps (if any)

💡This issue has been created before the code got merged and it exists only locally in situation where `BlockToolbar` has implemented `shouldGroupWhenFull`. 

The issue is needed only as a reference to possibly existing bug and it is related to https://github.com/ckeditor/ckeditor5/issues/6449.

1. Allow `BlockToolbar` to group items.
2. Show toolbar panel.
3. Hide it.
4. Show it again.

### ✔️ Expected result

Toolbar panel should be anchored correctly to the block toolbar button each time.

### ❌ Actual result

Toolbar panel is anchored correctly only the first time you show it. It resets the position and width only when view has been resized.

![issue](https://user-images.githubusercontent.com/1303365/78672158-8e157600-78e0-11ea-8568-09f937b0995a.gif)

**Comment by oleq** [comment]
This could be either very simple or quite nasty. 

I gave it a quick look. There's this moment when the `ContextualBalloon` shows/hides the toolbar and the native `ResizeObserver` that manages toolbar grouping kicks in. For some reason the latter figures there's no space for the buttons and it groups them all. Then the positioning algorithm (which probably is not the culprit here) sees a toolbar which is maybe 50px wide (all buttons grouped) and uses the very first position that geometrically makes sense for this kind of squashed toolbar, which is something like north-middle-east.

I didn't go deeper but maybe I'll spend and hour or two to debug this.

**Comment by panr** [comment]
Related: https://github.com/ckeditor/ckeditor5/issues/6575
