### ISSUE TITLE
Print Plugin 

### ISSUE THREAD

**Issue by andrewragy** [ckeditor/ckeditor5#6572]
Can you please add the print plugin #1972 to all the other themes

**Comment by Mgsy** [comment]
Hi, we understand that this plugin might be important for you, however, due to other priorities we can't provide any ETA for it. We listen to the community and our decisions about creating features are highly influenced by its voice, so requests with the highest popularity are our priority. 

Please don't open a new issue for the request which already exists. Feel free to add a comment in the mentioned issue and add 👍 to the first post to bump its popularity. Also, you can always try to create this plugin on your own.
