### ISSUE TITLE
CK classic editor || Image upload || Angular

### ISSUE THREAD

**Issue by ThenmozhiD** [ckeditor/ckeditor5#6617]
I have used CK editor in angular application.

The image upload feature is not working. 
Whether we need to include any extra plugins ?? 
Please help me with this.

**Comment by ThenmozhiD** [comment]
I am sorry for creating duplicates. 
I am using CK classic editor. 
On uploading image, the image is not getting inserted into the editor. I am not getting any error as well. Whether we need to include any plugins for image upload ??

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. In order to make [Image Upload](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/image-upload.html) work correctly, you need to have a proper set up not only for front-end but also server side of your app. For this you can use our products like [Easy Image](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/easy-image.html) ( [find out more about Easy Image trial and license](https://ckeditor.com/ckeditor-cloud-services/easy-image/) ) or use your own [custom upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html) ( you will need to set up back-end yourself ).
