### ISSUE TITLE
CommentsRepository removeCommentThread Not Being Called

### ISSUE THREAD

**Issue by zoominGiladSher** [ckeditor/ckeditor5#6633]
## 📝 Provide detailed reproduction steps (if any)

1. Using a classic editor with the comments plugin (and others) I tried to use a code similar to the example that was given by the documentation site in the following URL: [https://github.com/ckeditor/ckeditor5-collaboration-samples/blob/master/comments-integration/samples/comments-adapter.html#L297](https://github.com/ckeditor/ckeditor5-collaboration-samples/blob/master/comments-integration/samples/comments-adapter.html#L297)
2. Every adapter function worked as intended (I'm using an `async addComment(data)` syntax instead of `addComment:data =>` syntax)
3. When I wrote the `removeCommentThread` function nothing happened, I don't even see a `console.log` of the data. I tried writing it in the provided syntax and in an async await syntax to no avail.

### ✔️ Expected result

`removeCommentThread` works as intended.

### ❌ Actual result

`removeCommentThread` doesn't seem to be called at all after being defined in the adapter.

## 📃 Other details
I'm attaching the build I'm using (we have a license key in the company)
If you need me to show the part of the code which isn't working, please let me know.
[ckeditor5.zip](https://github.com/ckeditor/ckeditor5/files/4498510/ckeditor5.zip)

**Comment by Mgsy** [comment]
Hi! As our documentation says:
>Keep in mind that comment thread removal happens only for comment threads created outside of the editor. You do not need to implement this method if you use the comments feature inside the editor only.

Please note that comment threads inside the editor are never removed because of undoing changes - the user should be able to restore removed comment threads. So, `Adapter#removeCommentThread` is called only if a [comment thread attached to some external element](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-outside-editor.html) is removed.

However, if you'd like to listen on comment threads "removal" inside the editor, in fact, you should listen on comment markers removal because only those are removed from the editor. You can get information about changed markers via [`MarkerCollection#event-update`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_markercollection-MarkerCollection.html#event-update).

See the example code below. It checks if `newRange` is defined, if not, it means that the marker has been removed:
```js
editor.model.markers.on( 'update:comment', ( evt, marker, oldRange, newRange ) => {
    if ( !newRange ) {
        const threadId = marker.name.split( ':' ).pop();

        console.log( `The comment thread with ID ${ threadId } has been removed.` );
    }
} );
```

Also, please note that Comments are our commercial plugin and this repository is dedicated to the open-source side of the project, so in case of any further issues, please contact us through our [support channel](https://ckeditor.com/contact/). Our support team will be happy to help you.

**Comment by gsig91** [comment]
@Mgsy I have the same issue and trying to implement the proposed solution but unfortunatelly `markers.on` 'on' does not exist on type 'MarkerCollection'.

I understand that the comment thread is 'hidden' in case the user uses the undo button.

Has anything changed? Is there now a more appropriate solution to the question?
