### ISSUE TITLE
CI tests are failing randomly

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6655]
## Provide a description of the task

From time to time CI randomly fails. If restarted it will pass (at least worked for me).

Unfortunately I didn't back up entire CI stdout, what caught my attention was this warning logged multiple times:

```
Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.
```

## 📃 Other details

More context from discussion:

```
BTW is it a known issue that the CI randomly fails for ckeditor/ckeditor5 ? Had this case a moment ago, didn't back up full stdout log, except for an warning that has been reported multiple times:
Detected `console.warn()`:', 'Selection change observer detected an infinite rendering loop.

jodator:basketball:  1 hour ago
There's something still wrong with the CI. Sometimes restart helps but this is not a solution.

m.lewandowski  1 hour ago
Yup, agree - should be consistent

m.lewandowski  1 hour ago
do you know if there's already a ticket for that?

jodator:basketball:  39 minutes ago
Dunno if other do or do not cover that :/

reinmar:spiral_calendar_pad:  4 minutes ago
I didn’t report this.

reinmar:spiral_calendar_pad:  4 minutes ago
We had these errors since forever. However, recently they are appearing more often.

reinmar:spiral_calendar_pad:  3 minutes ago
They sooooometimes happen locally too. But extremely rarely.
```

**Comment by Reinmar** [comment]
BTW, the number of warnings on the CI is not consistent too. Here there are 3: https://travis-ci.org/github/ckeditor/ckeditor5/jobs/678641599 and here there were like 20: https://travis-ci.org/github/ckeditor/ckeditor5/builds/678586692.

**Comment by Reinmar** [comment]
Interesting. I'm not able to reproduce this locally, although I didn't try it too much.

I focused on the two `hasDomSelection` tests as they seem to do some unsafe things.

One was trying to put the DOM selection into an empty `<p>` element. How did we get an empty `<p>` element from the renderer? Surprise, surprise – if you use the stock `ViewElement` instead of `ViewContainerElement`, the renderer will not fill it with a bogus `<br>`. How's that dangerous? An empty `<p>` element may not be seem as a valid selection container so the browser may try to push it somewhere else. Since the inf selection loop check uses a 1s timer (how many times the selection can fail to render at the specified position within a second), that's prone to performance of the machine. Apparently, it's high on Travis.

The other test was doing something that I consider unsafe too – it was calling `domRoot.blur()`. From my experience, it's better to explicitly tell where the focus should go, otherwise bad things happen to good people.

Let's see if it's going to help.

**Comment by Reinmar** [comment]
Haha, and now I'm able to reproduce this locally. So, one thing's for sure – my changes didn't help.

**Comment by Reinmar** [comment]
I started running these tests in 3 concurrent processes and in a loop and that started triggering two errors:

*   either the one that we saw already,
*   or simply made the tests fail due to an apparent lack of selection.

What I also noticed is that the `domRoot.focus()` that I added previously (I wanted to ensure that focus is moved to the DOM root because moving the selection itself may not actually cause that from my experience) made the tests noticeably less stable. 

I figured out that this may happen due to some async nature of these functions. Again, from my past experience with testing DOM selection and focus, giving the browser time to "think" was helping so I added setTimeouts after each action and that resolved all instabilities for me. I ran the tests 10+ times and they worked fine.

CI passed too.

Interestingly, now these tests take less time. @scofalik used 100ms timeouts and AFAIR he was complaining that he had to increase this number because these tests were failing. I used 3x10ms and got good results so far.

Let's see how it behaves in a longer term. :crossed\_fingers:

**Comment by Reinmar** [comment]
The warning is back. I also got it locally recently :(

**Comment by Reinmar** [comment]
Second attempt in f66cc1a.

This time I tried to debug what's happening precisely. The test was finally failing for me in like 75% runs so I was able to test my hypothesis easily.

What I realised first was that making the timeout longer made the test fail more often.

Then I started logging old and new view selections in the inf sel loop check. It turned out that the old selection was non-existent. It had no range.

That made me realise that since this is a test that checks just a fragment of the view, without the model, there's no back-loop through the selection observer -> model -> view so the view selection was not set based on DOM selection changes.

I added code that keeps the view selection in sync with the DOM one (I set both at once). It's ugly, but I didn't want to think on rewriting these tests, especially that there are probably many more in this file that would require this.

Let's hope it's the last time I need to look into this :D

**Comment by mlewand** [comment]
Unfortunately the issue persists 😟 saw it a couple of times and now it happens in https://travis-ci.org/github/ckeditor/ckeditor5/jobs/700209709

@Reinmar do you want reopen this issue or create a new one not to mess estimate history?

**Comment by Reinmar** [comment]
It's hard to tell whether it's the same test. I'd say – a new ticket would be better this time.

Also, if the frequency will be much lower, we could ignore the problem. It's fine if the CI fails occasionally (let's say, once a week). Let's ask the other folks.
