### ISSUE TITLE
[FF] Editor crashes after applying the block quote to the image 

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#675]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-Alpha2

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Start the selection in the block quote and move it to the `OL List item 2`.
3. Press `block quote` icon.

## ✅ Expected result

Block elements should transform without errors.

## ❎ Actual result

Editor crashes

## 📃 Other details that might be useful
**Error**
```
TypeError: parent is null position.js:145
```

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/33009282-a8a918f8-cdd6-11e7-9ff9-36ce80915500.gif)

**Browser:** Firefox 57 (Quantum)

**Note:** I'm able to reproduce this bug also in Firefox 56.

**Comment by Reinmar** [comment]
It's very weird. It looks as if it was caused by some engine's bug but it can indeed be reproduced only on Firefox.

I can also see that it's reproducible from the very beginning.

Since its severy is rather mild, let's move it to the next iteration.

**Comment by Reinmar** [comment]
It's very probable that this issue is caused by a multi-range selection created by FF. See also https://github.com/ckeditor/ckeditor5/issues/678.

**Comment by pomek** [comment]
I replaced a callback used inside the `Schema#getLimitElement()`:

https://github.com/ckeditor/ckeditor5-engine/blob/2d9f8fa33404e4723cde6240c3157ceb24713a55/src/model/schema.js#L584-L590

with this:

```js
( node, range ) => {
	if ( !node ) {
		return range.getCommonAncestor();
	}

	const rangeCommonAncestor = range.getCommonAncestor();

	// If the node is also the common ancestor for the range, let's use it.
	if ( node === rangeCommonAncestor ) {
		return node;
	}

	return node.getCommonAncestor( rangeCommonAncestor );
}
```

The editor does not crash but the content is not removing:

![image](https://user-images.githubusercontent.com/2270764/35734666-38d700fe-0822-11e8-952d-64c123490fea.png)

Selection contained `OL List item 2` (from the second list) and `Quote` (from the blockquote). After pressing `Backspace`, the text from the list was removed. On Chrome it works fine.

I guess it's something broken with the image because, without the image, it works fine.

**Comment by Reinmar** [comment]
The content is not being removed because `deleteContent()` cares about the first range only. There's a separate ticket for this: https://github.com/ckeditor/ckeditor5-engine/issues/366.

**Comment by scofalik** [comment]
AFAICS this issue is not reproducible anymore. The only bug that is left is that the selection changes after using block quote -- it is trimmed to the original blockquote element. It might be related to multiple ranges. What do we do about it?

**Comment by Mgsy** [comment]
>AFAICS this issue is not reproducible anymore

Yep, I've checked it and it doesn't occur anymore 👍

**Comment by Reinmar** [comment]
I think that @pomek's changes for validating multi-range selection might've fixed it.
