### ISSUE TITLE
Review all the docs and READMes after migration to monorepo

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6767]
TODO:

*   Main pkg pages in API docs.
*   Search for "repository" in feature, build and framework guides and check all these occurrences.
*   Search for "github.com/ckeditor/ckeditor5-"
    *   E.g. README in https://github.com/ckeditor/ckeditor5

**Comment by mlewand** [comment]
Extracted "Custom builds" and "Installing plugins" guides to a dedicated issue: #6770

**Comment by pomek** [comment]
> Main pkg pages in API docs. 

Fixed in  https://github.com/ckeditor/ckeditor5/commit/d73bbd5e0f87a2fa4095b56bc6c553d1e0adc4fd

> Search for "github.com/ckeditor/ckeditor5-"

Fixed in:

* https://github.com/ckeditor/ckeditor5/commit/2fe6543cc036e6756c02fc29529500e9ff75b204
* https://github.com/ckeditor/ckeditor5/commit/8e86e64f8eac697a298a1cfa7ba02c31a83e72dd

All commits were pushed to `release` branch which is already merged with `stable` and `master`.
