### ISSUE TITLE
Revisit "Custom builds" and "Installing plugins" guides

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6770]
## 📝 Provide a description of requested docs changes

*   Custom builds – remove and add a redirect to Installing plugins.
*   Installing plugins – completely rewrite, with the monorepo in mind.

**Comment by davebeyer** [comment]
Posted question ["What is upstream GitHub URL to use for custom builds of CKEditor5 classic editor versions 19.1+"](https://stackoverflow.com/questions/62225924/what-is-upstream-github-url-to-use-for-custom-builds-of-ckeditor5-classic-editor) on stackoverflow but it looks like this may actually be the associated issue report, now targeting iteration 33, so linking my question here.

Is there any ready advice for bringing a custom classic build up-to-date (to v19.1.1) before then?  If not, no problem, we'll await the revised/iteration-33 instructions.

**Comment by Reinmar** [comment]
Yeah, sorry for that. We have a delay with this guide and the amount of updates that we had to do after migrating to a monorepo was burned all our capacity.

I actually don't know if we're going to propose the same way of maintaining builds (via forking). I'm leaning towards removing the mention of this approach completely. It channeled people to a non-optimal solution. 

It requires slightly more work to set up a directory in your project with webpack configuration and main entry point in which you could define the shape of your build than just forking the repository. But then, maintaining a setup that you know would be easier. Maintaining something that you inherited from us (by forking a build repo) turned out to be paralysing for some developers. Plus, it had side effects – people started publishing their builds on npm (which, IMO, is unnecessary) and had problems with updating deps if they added some deps over what an official build provides.

So, the tl;dr is – IMO, it'd be better if you just copy [this](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-classic/src/ckeditor.js) and [this](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-build-classic/webpack.config.js) to an empty directory in your project, add a stock `package.json` (so you can add dependencies) or add them to the root `package.json` if you have one in your project already and fill the deps here. Then, it's a matter of running webpack on that `src/ckeditor.js` and with that config.

I think we're going to document that approach.

**Comment by davebeyer** [comment]
OK, thanks for the update.   For now, given we're pretty slammed here too, I think we'll await your final deliberations and updated instructions.

**Comment by Reinmar** [comment]
WIP: https://github.com/ckeditor/ckeditor5/compare/i/6770

**Comment by Reinmar** [comment]
I got a valuable feedback from @wwalc that the "Installing plugin" guide should be as short and quick to use as possible. I started covering in it creating your own custom build from scratch, as I find this valuable. However, this grew to a size which makes this guide intimidating. I considered some options how to ma make it shorter (e.g. `npx ckeditor5-bootstrap-build`), but instead, it's better to move that part somewhere else.

I'll try to refactor it so the "creating a custom build from scratch" will end up in advanced setup. The "installing plugins" will focus on using one of the builds or a setup produced by the online builder (I'd like both things to be close to identical).

**Comment by mlewand** [comment]
A duplicate #7533 has been reported. It was referenced by mat128@cef7c7f which might also be useful.

**Comment by mgandley** [comment]
Hey @Reinmar & @mlewand.  Somehow I made my way through a breadcrumb trail of issues to this, and it saved me.  Pretty sure that both the online builder and docs are both pointing at the pre-monorepo-migration builds.

In a react integration, using the old builds was leading to some crazy out-of-memory javascript heap errors via babel / sourcemap generation.  Ended up spending quite a bit of time going down rabbit holes on that one.

I was able to create a build using the instructions you linked above in your June 16 post.  That worked perfectly, and I was able to install plugins and create a working build.  Thank you for documenting your suggestions in the post above.

I'm probably going to drop a few references to this issue around just so other people can save themselves some time until the official documentation is corrected.

Best of luck with all the documentation updates... 😆

**Comment by Reinmar** [comment]
I merged #7534 to temporarily resolve the issue. However, I continue to work on [i/6770](https://github.com/ckeditor/ckeditor5/tree/i/6770) to get rid of the "Custom builds" guide and it's 90% done so far so I probably need a couple hours to finish it.

@mgandley thanks for confirming that the instructions make sense. I don't feel entirely confident with them as I'd, in general, loved if no one had to create custom builds. But it's cool to hear that the improved guide resolved some issues.

**Comment by Reinmar** [comment]
I can potentially include #8114 too.

**Comment by pomek** [comment]
Closing in favor of docs revamps that we were working on recently.
