### ISSUE TITLE
CI should build entire docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6788]
## 📝 Provide a description of the improvement

There was a bug on master in the docs that I fixed in d08ce3e. However, the CI for the previous commit passed, which probably means that we don't run entire documentation build on CI.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
CI build that was green even though it should fail: af7928f.

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5/commit/d08ce3e89e6a7c3265a7b9d30519c59a3c514946 fixes a link introduced in https://github.com/ckeditor/ckeditor5/commit/dd70cb844d0b2e72650b8403ef5d1ede273b4d1e.
CI for the later one: https://travis-ci.org/github/ckeditor/ckeditor5/builds/685597023

![image](https://user-images.githubusercontent.com/2270764/81641660-d6650e00-9421-11ea-97a4-3b4dd573f761.png)

From the script point of view, everything is correct. I don't know whether it's true or not. 

But there is also another case:

![image](https://user-images.githubusercontent.com/2270764/81641758-0b716080-9422-11ea-92a6-c3b21ac3f66b.png)

`travis_wait 30 ...` finished with an error and the entire build is still green.

IMO, it should fail because steps are defined as `script`. It means, any exit code different than 0 should break the build.

https://github.com/ckeditor/ckeditor5/blob/dd70cb844d0b2e72650b8403ef5d1ede273b4d1e/.travis.yml#L19-L24

**Comment by mlewand** [comment]
There are multiple minor issues involved in this case:

* It's unexpected that `yarn run docs:api --validate-only` did not caught this error, because the error occurs in the API docs (although it's in the "description" part, so maybe a different parser kicks in there).
* Warnings during the doc build doesn't cause command to return a non-zero exit code.
* `travis_wait` [exit code not being checked by the CI](https://github.com/ckeditor/ckeditor5/issues/6788#issuecomment-627117913) mentioned by @pomek

In order to get this error we have to use a full might of the `yarn run docs` command, only then it produces a warning:

```
mlewand@MARCO-XPS$ yarn run docs
yarn run v1.22.4
$ node --max-old-space-size=4096 ./scripts/docs/build-docs.js
JSDoc started...
No errors found during the validation.
Documented 568 files!
Clean build directory.
Emptying Hexo source directory.
Building API docs of CKEditor 5...
Warning: Invalid link in API docs: {@link module:ui/colorgrid/colorgrid~ColorDefinition#options.hasBorder <code>color.options.hasBorder</code>}. There is no doclet of the link target.
Built API docs in: 15049.143ms
Executing the snippet adapter for "ckeditor5".
Building 127 snippets...
Build completed in 60.259s

Build completed in 5.55s

Finished building 127 snippets.
Running webpack for app.js ...
[Webpack]    34 modules
Symlink for CKEditor 5 ./19.0.0 - created.
Building documentation complete in 2m 53.319802600s.
Done in 220.88s.
```

But still it gives a `0` exit code which will mark the CI process as passed. We either should:

* Make the `yarn run docs` return non-zero value in case of warnings (doesn't seem to be right, as warnings, are not errors).
* Introduce `--strict` flag that would cause warnings and alike to result with non-zero exit code.

Finally the `travis_wait` think, my _guess_ is that in case of a string (`travis.yml#script` value) it doesn't look at exit codes.

**Comment by Reinmar** [comment]
> *   Warnings during the doc build doesn't cause command to return a non-zero exit code.

:+1: 

> *   It's surprising that `yarn run docs:api --validate-only` did not caught this error, because the error occurs in the API docs. The only reason I can think of is that it's in the "description" part of jsdoc, so maybe a different markdown parser kicks in there.

I don't know what `--validate-only` does and I'd remove this flag at all. CI is for validating that you can build all the things. If we run only validation, we don't check whether the thing will actually build correctly. What if there's some error that would pop up when generating one of the files?

**Comment by mlewand** [comment]
Still we need a way to get non-zero exit code when there are warnings.

> *   Introduce `--strict` flag that would cause warnings and alike to result with non-zero exit code.

Proposed `--strict` flag sounds the best to me.

As for the `--validate-only` we need to reach out to more devs to ask whether they are using it / used at all. From what I can see it looks useful for some automated check - like a pre-push or something - but we're not using it 🤷‍♂️ so assuming no one is using it - it's fine to drop it (but it doesn't address this particular ticket).

**Comment by mlewand** [comment]
All right I have verified that changes made in Umberto are working as expected:

*   https://travis-ci.org/github/ckeditor/ckeditor5/builds/701048615 - passes (no mistakes in the api docs)
*   https://travis-ci.org/github/ckeditor/ckeditor5/builds/701048663 - failing with mistakes in api docs

I'll put a PR tomorrow for that.
