### ISSUE TITLE
`normalizeColorOptions` in TablePropertiesUI breaks UX of ColorInputData

### ISSUE THREAD

**Issue by tomalec** [ckeditor/ckeditor5#6791]
## 📝 Provide detailed reproduction steps (if any)

This issue was discovered during the review of https://github.com/ckeditor/ckeditor5/pull/6784

1. Open table properties (or table cell properties).
2. Set border color and background color to any defined value, for example, "Dim grey".
3. Close the toolbar.
4. Reset the state by typing `editor.setData(editor.getData())` in the browser console.
5. Open table (cell) properties once again.

![Animated demo of steps above](https://user-images.githubusercontent.com/17435/81593335-93724e80-93bf-11ea-9260-238ebdef3dd3.gif)

### ✔️ Expected result

"Dim grey" should be shown in both input boxes.

### ❌ Actual result

Border color input shows actual color value: "hsl(0, 0%, 30%)".

## 📃 Other details

After a brief investigation with @Reinmar we discovered that removing `.replace( / /g, '' )`
https://github.com/ckeditor/ckeditor5/blob/3c7c28d3cff978b9efe6e0f748a742939ea22481/packages/ckeditor5-ui/src/colorgrid/utils.js#L73-L85
Solves the problem. 
There is a mismatch between normalized and non-normalized values set by the element, and set by the state restore.
We were not sure why this normalization was there, and what side effect we might introduce by removing it. However, it seems to me that we should use, preserve, and accept values in exactly the same shape as they were given in the initial config.

* Browser: Chrome
* OS: Win10
* CKEditor version: master ([@fbec6b2af](https://github.com/ckeditor/ckeditor5/tree/fbec6b2af7a8a45c189388b537ed48d223b9f18a))
* Installed CKEditor plugins: table

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
@Reinmar & @tomalec I did a _quick_ research and AFAICS there's no "Dim Grey" color in CSS specs :wink: . All [CSS color keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) are single word. So basically "Dim grey" should be treated as an error IMO. 

Additionally the Firefox & Chrome do not support such values (I've checked if maybe they normalize it somehow):

![](https://user-images.githubusercontent.com/247363/81645376-c2250f00-9429-11ea-91dd-2728c4f1b361.png)

ps.: The `isColor()` method do check it as error: https://github.com/ckeditor/ckeditor5/blob/e62c9186d77377920b0dacc05e5f2de3add3258f/packages/ckeditor5-engine/src/view/styles/utils.js#L16-L43 so maybe it should be displayed in this UI as en error.

**Comment by Reinmar** [comment]
@jodator That's not the point. We of course know that "Dim grey" is not a CSS value.

The problem is that _some_ algorithms in the editor work on a normalized CSS color values (with deletes spaces). And some don't. There's a mess now and it leads to the bug reported by @tomalec. We're setting the same color in two inputs and after opening the balloon again it's loaded back in just on of them. WTH, right?

So we tried to debug this and we found out that at one point all spaces are stripped from CSS color values. Why is **UI's** component ColorGrid stripping spaces from values of colors that were passed to it is a mystery to me. The UI should be about displaying the UI, not doing some unnecessary tricks for apparently no reason.  

My proposal is to:

*   Stop normalizing color values passed to the UI. You configure it to use `rgb   (   34, 234, 234)` then let it use that value.
*   Use a better matching algorithm [here](https://github.com/ckeditor/ckeditor5/blob/fbec6b2af7a8a45c189388b537ed48d223b9f18a/packages/ckeditor5-table/src/ui/colorinputview.js#L298) because it's still possible that a normalized or miss-formatted value will come here from the editor data.

**Comment by jodator** [comment]
> @jodator That's not the point. We of course know that "Dim grey" is not a CSS value.

Oh OK - sorry, I was a bit anchored by the value name and mapped it to a CSS values. I see the problem now. The proposal make sense. Hopefully no one will try to use `rgb       (     34, 234, 234)` :D

**Comment by tomalec** [comment]
To clarify on "Dim grey".
Naturally, it's not the CSS value, but it's our feature to support a custom-defined color list. See https://github.com/ckeditor/ckeditor5/blob/3c7c28d3cff978b9efe6e0f748a742939ea22481/packages/ckeditor5-table/src/ui/utils.js#L347-L355

What I was referring to, is that this exact feature is bugged due to OP.
