### ISSUE TITLE
The editing engine guide section about schema needs information about limits and objects

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6829]
## 📝 Provide a description of requested docs changes

When working on #6816 I figured some key concept explanations are missing:

*   What is "limit" element? Why limit is not just closest editable (for instance, `tableRow` is also a limit).
*   What is object?
    *   What's the difference between an object and a limit?
*   API docs for `Schema#isLimit` and `Schema#isObject` are also vague, they explain the implementation not the semantics.

Something else @niegowski?

**Comment by niegowski** [comment]
Maybe it would be good to explain how `isLimit` works with selection [post-fixer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_utils_selection-post-fixer.html#static-function-injectSelectionPostFixer).

**Comment by niegowski** [comment]
I thought that `isLimit` is the opposite to `isObject` but today I realized that `isLimit` is a boundary element on both sides (outside and inside object) and it marks elements that selection can't cross 😀

This wasn't explained anywhere 😕

**Comment by niegowski** [comment]
Given that:

*   `$root`: `isLimit`
*   `table`: `isObject` => `isLimit`
*   `tableRow`: `isLimit`
*   `tableCell`: `isLimit` (currently `isObject` to be able to be selected from outside but this is going to change #6432)

So all of below selections are invalid and fixed by selection post-fixer:

```
<$root>
	<paragraph>
		[foo
	</paragraph>
	<table>]
		<tableRow>
			[<tableCell>
				<paragraph>
					123]
				</paragraph>
			</tableCell>
		</tableRow>
		[<tableRow>
			<tableCell>]
				<paragraph>
					[123
				</paragraph>
			</tableCell>
		[</tableRow>]
	[</table>
	<paragraph>
		bar]
	</paragraph>
</$root>
```

**Comment by oleq** [comment]
cc @Reinmar

**Comment by Reinmar** [comment]
Agree, isLimit definitely needs to be better documented (or – documented at all). It's not the same as "editable element". The concept of "editability" is reserved for the view and expressed by "EditableElement" class (_this can be mentioned in the docs for clarity_).

In the model, we express two things with `isLimit`:

*   this element must not be split by an action happening inside it,
*   the selection cannot start outside and end inside this element,
*   since every object element is a limit element, the limit element can also be understood as an atomic element (from outside) – however, this is a result of the first two rules.

We can also say that since every object is a limit element, object is a special type of limit element. In this case, object adds the "can be selected as a thing" meaning. E.g. we didn't want table rows to be selectable (because wanted to have selection on cells only), so table rows are not objects. However, the other two rules apply to rows.

**Comment by tomalec** [comment]
There is one case, that is still problematic to me, and makes it harder for me to get the full picture and describe it clearly.

Technically, I can define a schema, like:
```js
schema.register( 'foo', {
    isLimit: false,
	isObject: true
} );
```

Then:
```js
schema.isLimit( foo ) == true;
schema.getDefinition( 'foo' ).isLimit == false;
```
Does it have any particular meaning. Or is just a edgecase, that we silently ignore/assume it's equivalent of 
```js
schema.register( 'foo', {
    isLimit: true,
	isObject: true
} );
// ⇕
schema.register( 'foo', {
	isObject: true
} );
```
and `schema.getDefinition( 'foo' ).isLimit` API is for internals only, and should be used by someone aware of such quirks?
