### ISSUE TITLE
How to preserve markup and not have it removed

### ISSUE THREAD

**Issue by figuerres** [ckeditor/ckeditor5#705]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report
- Feature request
not sure which this is yet.

## 💻 Version of CKEditor

classic alpha 2 
## 📋 Steps to reproduce

1. load markup from data
2. look at it in editor

## ✅ Expected result
see <a > tags 

## ❎ Actual result
text only - no <a > tags
## 📃 Other details that might be useful

i am working on a wiki project and seeing if i can use ckedit in place of a text area and markdown.
i have html that has links from one wiki page to another wiki page.
the app is using Angular 5  so the links that are from one article to another article need to be angular router links. apparently ckedit is removing what ever it thinks is invalid markup.
i need to turn that off or have control over it.

**Comment by Reinmar** [comment]
CKEditor 5 implements a custom data model. In order to load data to this model you need to have view -> model converters for each piece of the content that you want your editor to support. Then, you need model -> view converters in order to make this content editable (it needs to be rendered in the editor for editing). Finally, you need to configure the schema and sometimes customize certain features like <kbd>Enter</kbd> so they know the meaning of this content that you loaded into the editor and how to modify it. In other words, because of the data model a feature needs to implement the full life-cycle of a specific piece of content (tag, attribute, etc.) which it handles – from data loading, through rendering for editing, editing itself and data retrieval.

In your case, if what you edit are links but with a different markup, I'd recommend forking the [`@ckeditor/ckeditor5-link`](https://github.com/ckeditor/ckeditor5-link/) package. You can find there the mentioned converters. You can modify them to fit your use case and if you'll keep the rest of the code you'll have the whole UI and the rest of the logic.

Related thread: https://github.com/ckeditor/ckeditor5/issues/592 (I recommend reading it)

**Comment by figuerres** [comment]
thanks for the pointer , that's what i need is some idea of where to start looking.
i understand that my custom needs are my job.

**Comment by jodator** [comment]
@figuerres to start working with writing own features you'd need to familiarize with [CKEditor 5 architecture](https://docs.ckeditor.com/ckeditor5/latest/framework/index.html).

Then depending on what you'd like to develop checkout existing features and how they're implemented as Reinmar pointed out. If you're interested in changing the view output (HTML) check the `Editing` part of a feature.

**Comment by itopen78** [comment]
asdfasf

**Comment by msqxiaoqiang** [comment]
asd
