### ISSUE TITLE
Binding listening events to the editor.

### ISSUE THREAD

**Issue by teoCasasbuenas** [ckeditor/ckeditor5#710]
I found that in the classic editor i haven't been able to use the `e.on('event', ()=>{});` My workaround is to use `e.document.on('event', ()=>{})` Why is it needed to bind it to the `e.document`? Shouldn't it be specified in the documentation?

Thank you.

**Comment by Reinmar** [comment]
Do you mean a specific event? Because, what might not be clear, especially if you're used to CKEditor 4, there are hundreds of events and those events are fired on specific objects. For example, [`Document`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_document-Document.html) fires two events (they are listed at the end of that class's API docs page), the [`Selection`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_selection-Selection.html) fires its own 3 events, etc, etc. And you need to listen on those specific objects. The [editor](https://docs.ckeditor.com/ckeditor5/latest/api/module_core_editor_editor-Editor.html) fires its own small set of strictly editor-related events.

We were actually considering documenting this in a guide listing popular events. But I wonder if your confusion came from the fact that you knew that 99% of events were fired on the editor itself in CKEditor **4**? Or that something else is confusing in the existing CKEditor **5**'s documentation?

**Comment by teoCasasbuenas** [comment]
Ok, I think it's a mixing from the previous knowledge that the events on CKEditor 4 were fired on the editor itself an a little bit of confusion with de CKEditor 5 documentation.

My problem is that I was trying to bind the `change` event to the editor like this: `e.on('change', ()=>{});` following de [documentation](https://docs.ckeditor.com/ckeditor5/latest/api/module_core_editor_editor-Editor.html) with no results, so a I realized that the event must be binded to the `document` attribute of the editor, as I pointed in the initial post. I think that a few examples or specification on which events are handled by de editor an which are handled by the inner attributes would make things clear for everyone. 

Thank you again.

**Comment by Reinmar** [comment]
Cool, so it matches the plan that we had. We'll track this page in https://github.com/ckeditor/ckeditor5/issues/511.

**Comment by Natim** [comment]
It seems that editor.document doesn't exist anymore, what is the new way to catch document.on('change') events?

**Comment by Reinmar** [comment]
We decided to wrap model's things in a new [`editor.model`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_model-Model.html) property. So, now the [`#change`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_document-Document.html#event-change) event is available in `editor.model.document`.
