### ISSUE TITLE
Question:  features in editor build and toolbar buttons

### ISSUE THREAD

**Issue by figuerres** [ckeditor/ckeditor5#711]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report
- Feature request
 X  Question

## 💻 Version of CKEditor
current classic build

## 📋 Steps to reproduce

1.   add to project
2.

## ✅ Expected result
many toolbar buttons shown
## ❎ Actual result
only basic buttons shown

## 📃 Other details that might be useful

trying to sort out the builds and features and what has what.
what do i need to do to get a full set of features and the toolbar buttons that go with them.

do i need to make a custom build or can i add a feature by adding a file and editing the editor config ?
main one is uploading and inserting images  but others also ....

**Comment by Reinmar** [comment]
Adding features may require rebuilding the editor, as mentioned in https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html.

The existing builds are minimal, which means that we included in them only those features which are then used. We implemented features in a very granular way which helps us to keep the code size as low as possible so we also make sure to not bloat builds with unnecessary things.

It's a bit hard for me to answer the question what other features we do have besides those included in the builds because they should be listed in https://docs.ckeditor.com/ckeditor5/latest/features/index.html but they aren't yet. The list is growing pretty quickly too :)

As for uploading images, as you can see on https://ckeditor.com/ckeditor-5-builds/ it's well supported already. The editor there is configured to use the [Easy Image service](https://docs.ckeditor.com/ckeditor5/latest/features/image-upload.html#Easy-Image). You could also use [CKFinder adapter](https://docs.ckeditor.com/ckeditor5/latest/api/adapter-ckfinder.html) or write[ your own upload adapter](https://docs.ckeditor.com/ckeditor5/latest/api/module_upload_filerepository-Adapter.html).

**Comment by oleq** [comment]
I think this issue is strongly related: https://github.com/ckeditor/ckeditor5/issues/672.

**Comment by mlewand** [comment]
@Reinmar explained it well in https://github.com/ckeditor/ckeditor5/issues/711#issuecomment-350992464. Today you'd have to prepare a custom build that contains you pluginset of choice (or use one of our build configurations).

Now we're looking to work on https://github.com/ckeditor/ckeditor5/issues/1174 at some point so that will make obtaining customized build as simple as it is for CKEditor 4 today so make sure to subscribe to this issue.

Another issue that might interest you is #667.
