### ISSUE TITLE
Can't build ckeditor-build in create-react-app project

### ISSUE THREAD

**Issue by 26903651** [ckeditor/ckeditor5#737]
**I used ckeditor-build-classic in my project which create by [create-react-app](https://reactjs.org/docs/installation.html#creating-a-new-application). I run it with source, everything is fine, but when i want to build my project, it show:**
`Failed to minify the code from this file:`

       ./node_modules/ckeditor5-build-classic-xlsys/build/ckeditor.js:5:6185

`Read more here: http://bit.ly/2tRViJ9`

**before I add the ckeditor-build-classic, I can build my project.** 

**And I read the doc, it shows :** 
`npm run build fails to minify`
`Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.`

`To resolve this:`
`Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled.
Note: Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.`
`Fork the package and publish a corrected version yourself.`

`If the dependency is small enough, copy it to your src/ folder and treat it as application code.`

`In the future, we might start automatically compiling incompatible third-party modules, but it is not currently supported. This approach would also slow down the production builds.`
**I don't know what should i do, please help me!**

**Comment by Reinmar** [comment]
CKEditor 5 is published as ES6 (both, the source packages and the builds) because ES6 is supported in all browsers in which CKEditor 5 is supported.

We are aware that some environments did not catch up yet (but they are doing so as we speak). You can read more in https://github.com/ckeditor/ckeditor5-build-classic/issues/24.

The solution for you here will be to modify your build's `webpack-config.js` a bit as explained here: https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#Option-Building-to-ES5-target.

**Comment by Reinmar** [comment]
I'm closing this ticket as DUP of https://github.com/ckeditor/ckeditor5-build-classic/issues/24. Feel free to continue commenting here or there.
