### ISSUE TITLE
Ckeditor-5 react build does not work properly inside iframe

### ISSUE THREAD

**Issue by Sawan1994** [ckeditor/ckeditor5#7382]
## 📝 Provide detailed reproduction steps (if any)

1. install https://www.npmjs.com/package/react-frame-component
2. Put ckeditor-5 react inline editor inside any editable content
3. When you click the editable content the toolbar is not properly aligned and it stays as it is on scroll.

### ✔️ Expected result

The inline editor should be properly aligned to the editable part inside iframe.
The toolbar should scroll with the iframe and be properly aligned to editable content when it scrolls.

### ❌ Actual result

Toolbar not properly aligned and does not scroll inside iframe.

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I checked it both on standalone editor and with React integration, and I can confirm this scrolling issue exists only when using React + the package you linked. Standalone inline editor works ok inside an iframe. So I'm afraid you will need to debug it on your own, since this is some 3rd party package issue and the problem doesn't seem to be on our side.
