### ISSUE TITLE
Is it possible to put Word icon to the toolbar using Classic Build?

### ISSUE THREAD

**Issue by ppazuchowski** [ckeditor/ckeditor5#7392]
Hi,

Pasting from Word works really good, but I would like to have an icon in the toolbar.
Is it possible to put Word icon there, without extending classic build?

Thanks

**Comment by FilipTokarski** [comment]
Hi, I'm not sure what is the use case for needing an icon ( and we don't have an official icon for this plugin ), because this plugin works regardless of having an icon in the toolbar, and also is not toggleable by default.
If you however want to add a custom icon to the toolbar:
- please remember that you cannot just modify editor build, you will need to [build it from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html)
-  you can then [extend existing plugin by adding a button](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html#step-3-registering-a-button). In your case, you can start with code like this:
```js
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';
class ModifiedPasteFromOffice extends PasteFromOffice{
    init(){
        const editor = this.editor;
        editor.ui.componentFactory.add( 'pasteFromWord', locale => {
        const view = new ButtonView( locale );
	
        view.set( {
            label: 'Paste from Word',
            //icon: imageIcon,  <-- put your icon here
            withText: true,    // or just leave a label on the button
            tooltip: true
        } );
        return view;
        } );
    }
}
```

Hope that helps.

**Comment by ppazuchowski** [comment]
Thank you! The reason why I am asking is because I've got a feedback from the user that he didn't know that he can paste directly from the Word.  He said also that it would be nice to have some Word icon in the toolbar, so everybody can know that there is possible to copy and paste from Word.
