### ISSUE TITLE
placeholder text doesnt go away when block-element is inserted

### ISSUE THREAD

**Issue by testbuddy** [ckeditor/ckeditor5#7419]
## 📝 Provide detailed reproduction steps (if any)

1. Editor-data is set to ''
2. Set placeholder text in config
3. Insert block-element like image or custom widget

### ✔️ Expected result

data-placeholder attribute and ck-placeholder class are not set on the first block-element

### ❌ Actual result

data-placeholder attribute and ck-placeholder class are set on the first block-element

## 📃 Other details

* Browser: tested in chrome
* OS: windows
* CKEditor version: 5
* Installed CKEditor plugins: 
      ckeditor5-react'
      inlineeditor'
      essentials'
      heading'
      bold'
      italic'
      underline'
      link'
      table'
      tabletoolbar'
      paragraph'
      image'
      imageupload'
      base64uploadadapter'
      imagetoolbar'
      imagecaption'
      imagestyle'
      imageresize'

**Comment by Mgsy** [comment]
Hi, we're aware of some problems with placeholders, e.g. while inserting a [media](https://github.com/ckeditor/ckeditor5/issues/1684) and [UI elements](https://github.com/ckeditor/ckeditor5/issues/4114). However, I can't reproduce it with images. Could you describe more detailed steps to reproduce and create a screencast showing the issue?

**Comment by testbuddy** [comment]
Hi :)
Unfortunately i cannot showing a screencast cause some private code :(
Instead i try it with cutted screenshoots.

1. The data of the editor is empty ('') and the config object contains the key placeholder with value 'Type some text....'
![start](https://user-images.githubusercontent.com/11924447/84537909-f58cdf00-acf0-11ea-86d2-952592f94af8.png)
2. Then i click the insert image button. This button is not modified. Just from the lib.
![before_insert](https://user-images.githubusercontent.com/11924447/84538062-3dac0180-acf1-11ea-827a-cc1edd13c2e8.png)
3. After the insert the figure element has the data-placeholder attribute.
![after_insert](https://user-images.githubusercontent.com/11924447/84538098-55838580-acf1-11ea-9d60-27f7dc78ffdc.png)
4. When i insert a custom widget it also contains placeholder css class :(
![custom_element](https://user-images.githubusercontent.com/11924447/84538138-70ee9080-acf1-11ea-961e-42e10cc4857c.png)

Hopefully this helps ? This doesnt happend when i add text. Only the first block-element.

**Comment by Mgsy** [comment]
Thanks for the details. As it goes to `data-placeholder` attribute, it's added always to the first element in the editor. `ck-placeholder` class is not added to an image, so the placeholder doesn't display and it works properly.

As it comes to your custom widget, I believe the issue occurs because of problems mentioned in the tickets I've linked above. 

Out of curiosity - can you check if adding a change from ckeditor/ckeditor5-engine#1749 fixes your issue? After migrating to monorepo, this branch might be inaccessible, so you'll need to add a fix manually. Just add this code to `ckeditor5-engine/src/view/placeholder.js` [after this line](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/view/placeholder.js#L149):

```javascript
if ( element.getCustomProperty( 'widget' ) ) {
	return false;
}
```

**Comment by testbuddy** [comment]
Yeah this fix did it :)) Thanks for the fast help :)
