### ISSUE TITLE
How can I just use content styles and remove the Webpack loaders for CKEditor's css?

### ISSUE THREAD

**Issue by aysiscore** [ckeditor/ckeditor5#7421]
I am using CKEditor5 from source within a Vue.js app.

Having read the docs here about [Content Styles](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html), I would much prefer to have all of CKEditor's styles in my `main.css` file that provides styles for my entire application.

The docs say to copy and paste the Content Styles into a css file and place that in the front-end app. This is easy to do, but Webpack is still building css using `test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/` with postcss-loader and style-loader.

Can I cut out Webpack from building CKEditor's css files if I have the Content Styles already in my `main.css` file or are they still required?

**Comment by Mgsy** [comment]
@pomek , can you take a quick look at it?

**Comment by pomek** [comment]
Hi @aysiscore,

I am sorry for the very late response time.

Answering the question:

> Can I cut out Webpack from building CKEditor's css files if I have the Content Styles already in my `main.css` file or are they still required?

I guess you can't because `postcss-loader` prepares CSS required for the editor itself. e.g. the toolbar, tooltips, balloons, etc. If your page loads the editor, those styles must be applied as well. But maybe you can use a plugin that will remove duplicated CSS definitions.
