### ISSUE TITLE
calling setData with an empty string disables editor controls

### ISSUE THREAD

**Issue by thedavidmeister** [ckeditor/ckeditor5#744]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

alpha2

## 📋 Steps to reproduce

1. call setData with empty string
2.

## ✅ Expected result

editor content is the same as deleting all content in the WYSIWYG `"<p>&nbsp;</p>"` and editor buttons display as normal

## ❎ Actual result

getData returns `""` and editor is disabled

## 📃 Other details that might be useful

I will attempt to create a repro case in an example repo

**Comment by thedavidmeister** [comment]
Here is a codepen showing the issue:

https://codepen.io/anon/pen/ZvBJpE?editors=1111

**Comment by thedavidmeister** [comment]
my current workaround is to wrap setData so that an empty string input is replaced with `"<p>&nbsp;</p>"`

**Comment by Reinmar** [comment]
It seems that for this case autoparagraphing didn't work. We need to check this but this is quite weird because https://github.com/ckeditor/ckeditor5-paragraph/blob/9c3edbeb529e7f90957a45f6ec402733086a78d1/tests/paragraph.js#L377-L469 seem to touch this scenario. Although, it's true that there's no test with an empty `setData( '' )` call.

**Comment by Reinmar** [comment]
Turns out I've got a short memory: https://github.com/ckeditor/ckeditor5-engine/issues/939#issuecomment-315056790

cc @pjasiun and @scofalik

This is something we should fix before beta.

**Comment by Reinmar** [comment]
DUP: https://github.com/ckeditor/ckeditor5-enter/issues/49

**Comment by Reinmar** [comment]
For a Markdown data processor empty data string is an empty HTML string. So this is exactly the same situation as with the standard HTML data processor. The fact that empty content is not editable because it lacks a place for the caret is an editor thing and it was fixed in the engine by a post-fixer which always fills an empty root with an empty paragraph. Unfortunately, this post-fixer stopped working for `setData()` and we need to figure out how to make it work with it too.

**Comment by thedavidmeister** [comment]
ah sure, i guess i just had the wrong mental model of where the problem is - which is building output not parsing input

**Comment by Reinmar** [comment]
It's more of an on-going ensuring correctness of the model. It's not a one-time thing because the root may be emptied by more operations. `setData()` is just one of the ways to make the root empty. Selecting all and deleting may be another way (on some browsers).

However, you're right that it's also about the output because that empty paragraph in the model should not be output by `getData()` because developers will rather expect to see an empty string in such a case. So we need kind of a model-trimming for this. There's a ticket for this here: https://github.com/ckeditor/ckeditor5/issues/401.

**Comment by Reinmar** [comment]
It turns out that the post-fixer works fine now, after the refactoring :) It was a nice side effect of the changes that we've done. 

![jan-16-2018 11-15-06](https://user-images.githubusercontent.com/156149/34983671-958df630-faae-11e7-8209-d6f509fe93d6.gif)

**Comment by thedavidmeister** [comment]
@Reinmar ah cool, i'm also seeing weirdness in FF that i haven't started debugging yet, but i suspect might be related to this somehow... i'll keep you posted when i get to it
