### ISSUE TITLE
Help: Determine text caret line

### ISSUE THREAD

**Issue by dikium** [ckeditor/ckeditor5#7460]
Hi! I'm trying to determine when the text caret is on the first and on the last line of editor. Is there a good way to do this?

Now i get a text caret coordinates and can to determine a first line position easy. How can i get the height of the editor area now? Can i get this information from editor instance somehow? Or may be i can get the root DOM Element of the editor?

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 18.0.0
* Installed CKEditor plugins: ckeditor5-classic-build

**Comment by jodator** [comment]
Hi @dikium - the previously linked code is part of detecting first/last line in table cell in order to navigate table cells using keyboard (https://github.com/ckeditor/ckeditor5/blob/d5a86cf762d3294cd90e2657cf04ab988765cdd1/packages/ckeditor5-table/src/tablekeyboard.js#L365).

As for your question - there is plenty of options you get, to get "editing root" you can:

```
const editingRoot editor.editing.view.document.getRoot();
```

and then use view mapper to get DOM element:

```
editor.editing.view.domConverter.viewToDom( editingRoot );
```

Thus you can get it's `Rect`.

Unfortunately we cannot answer every question here or help with coding. You can ask all kind of questions on [stack overflow using CKEditor 5 tag](https://stackoverflow.com/questions/tagged/ckeditor5).
