### ISSUE TITLE
insertContent with html string, but classes are filtered

### ISSUE THREAD

**Issue by DanielWLam** [ckeditor/ckeditor5#7463]
## 📝 Provide detailed reproduction steps (if any)

1. 
const htmlDP = editor.data.processor
    const viewFragment = htmlDP.toView(`<p class="test"></p>`)
const modelFragment = editor.data.toModel(viewFragment)
    editor.model.insertContent(modelFragment)

### ✔️ Expected result

html string with class rendered

### ❌ Actual result

all classes are filtered

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: 5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. In order to make this code work as expected, you need to allow adding `class` attribute on `paragraph`. Please [refer to this example](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-extending-output.html#adding-a-css-class-to-block-elements).
