### ISSUE TITLE
Full-height separators look bad in balloon tolbars

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7493]
## 📝 Provide a description of the improvement

![](https://user-images.githubusercontent.com/156149/85525889-cbe58900-b609-11ea-9e0f-d197323ae58d.png)

Initial research from 2018 that covers this issue: https://github.com/ckeditor/ckeditor5/issues/645#issuecomment-362608165

Proposal:

![](https://user-images.githubusercontent.com/156149/85526096-ff281800-b609-11ea-886c-e23ac79cdcec.png)

However – should that apply to balloon toolbars only or to all toolbars?

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @panr @oleq

**Comment by panr** [comment]
> However – should that apply to balloon toolbars only or to all toolbars?

I'm always for consistency, so for me - to all toolbars. But on the other hand I presume that this may break something that I'm not aware of...

**Comment by oleq** [comment]
## Full vs non-full height separators

(AFAIR) We went with the full-height separators mainly because they look cool next to drop-downs. They both separate them from the rest of the toolbar and, together with the (top and bottom) boundaries of the toolbar, encompass them like a box which was important for us because most of our toolbars start with the heading drop-down:

![](https://user-images.githubusercontent.com/1099479/86585608-04308400-bf87-11ea-8bb4-7b94f5ccc809.png)

![](https://user-images.githubusercontent.com/1099479/86585609-04308400-bf87-11ea-9895-50c57d5d9cdb.png)

vs

![](https://user-images.githubusercontent.com/1099479/86585610-04308400-bf87-11ea-8fab-c78874ca387b.png)

![](https://user-images.githubusercontent.com/1099479/86585607-04308400-bf87-11ea-840d-e5fa48a74351.png)

Also, full-height separators have more "visual power" (I know this sounds weird but check this out):

![](https://user-images.githubusercontent.com/1099479/86586324-ff200480-bf87-11ea-8b7b-2b485badc12c.png)

![](https://user-images.githubusercontent.com/1099479/86586323-ff200480-bf87-11ea-809c-92643677d2f6.png)

In my opinion, the later feels more structured and organized. Non-full height separators are vague, they sometimes bring more noise than order.

Of course, the trade-off is this balloon arrow issue and we were aware of this when we went with the concept.

## What can we do?

I agree that we should be consistent. If we change the look of separators, it's for all toolbars across the UI. 

OTOH I saw that Google switched from full-height to non-full height some time ago (vide [stackexchange](https://webapps.stackexchange.com/questions/124355/how-can-i-change-the-google-docs-sheets-slides-user-interface-design)) although [Material Design does not showcase a traditional toolbar](https://material.io/components/dividers). We don't know the details but here it is:

![](https://i.stack.imgur.com/xJzIA.png)

vs

![](https://i.stack.imgur.com/ydETS.png)

I think we could try this out, especially that this is a 2LOC change we can easily revert at the end of an iteration if we don't like it.

WDYT?

---

See my post from a different era https://github.com/ckeditor/ckeditor5/issues/645#issuecomment-362608165.

**Comment by panr** [comment]
+1 for the non full-height separators 🙈

**Comment by Reinmar** [comment]
> I think we could try this out, especially that this is a 2LOC change we can easily revert at the end of an iteration if we don't like it.

:+1: 

And let's not notify anyone :D
