### ISSUE TITLE
Issue templates improvement

### ISSUE THREAD

**Issue by Aaron-Junker** [ckeditor/ckeditor5#7502]
Instead of the "security issue" template I would use a link with the help of config.yml in /.github/ISSUE_TEMPLATE

**Comment by jodator** [comment]
Hi @Aaron-Junker - thanks for the tip. Could you post links to a repository using this settings. I wonder how this looks on GH. The [help page](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) isn't very helpful.

**Comment by jodator** [comment]
OK, I've forgot about search in GH :wink: . @Reinmar  - this looks quite nice - instead of opening an issue it adds a link - my concern was that it might not be clearly visible:

*   [Ansible config.yml](https://github.com/ansible/ansible/blob/devel/.github/ISSUE_TEMPLATE/config.yml)
*   [Ansible new issue page](https://github.com/ansible/ansible/issues/new/choose)

![](https://user-images.githubusercontent.com/247363/85822850-2ef72d00-b77c-11ea-8f45-47d67c5832d5.png)
