### ISSUE TITLE
Cannot resize image in CKeditor 5 (working in .NET Core MVC)

### ISSUE THREAD

**Issue by huyle0110** [ckeditor/ckeditor5#7510]
## Cannot resize image in CKeditor 5 (working in .NET Core MVC)
I set up CKeditor 5 in ASP.NET CORE MVC already and work as well. But I upload image but cannot set width, height or resize image.  I import ckeditor with some files 
<script src="~/lib/ckeditor/ckeditor.js"></script>
<script src="~/lib/ckeditor/build-config.js"></script>
<script src="~/lib/ckeditor/config.js"></script>
<script src="~/lib/ckeditor/styles.js"></script>
<script src="~/lib/ckeditor/plugins/image/dialogs/image.js"></script>
<script src="~/lib/ckeditor/adapters/jquery.js"></script>

. So dont know if its's missing plugin  or have any mistake .
Thanks

## 📃 Other details

* CKEditor version: 5
* Installed CKEditor plugins:None

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Please make sure you are familliar with [docs on images](https://ckeditor.com/docs/ckeditor5/latest/features/image.html) and also on [how to install plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html). I suppose that in your case you'll nedd to add image plugins and update editor configuration. If that does not work, we'll need more information ( i.e. editor configuration, steps to reproduce ), in order to look into this.
