### ISSUE TITLE
Image is removed after deleting the block element

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#753]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Select the block quote.
3. Press <kbd>Backspace</kbd> twice.

## ✅ Expected result

Only the block quote should be removed.

## ❎ Actual result

The image has been removed.

## 📃 Other details that might be useful

**Notes**

It's a regression.

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/34523754-16c37696-f099-11e7-914f-f1682bec9791.gif)

**Other information**
OS: Windows 10, MacOS X
Browser: All browsers

**Comment by Mgsy** [comment]
Actually, it's not only about the block quote, but all block elements. I'm updating the description.

**Comment by Reinmar** [comment]
First bad commit is https://github.com/ckeditor/ckeditor5-widget/commit/ee6cc956887170876a6d32c036d8f0853b56660c.

I thought that I broke this when changing the Schema API. But it's older, so I'm leaving this ticket.

**Comment by szymonkups** [comment]
I'll take care of it.

**Comment by szymonkups** [comment]
This is caused by situation in which `DeleteObserver` listens to `keydown` event and fires `delete` event when <kbd>Delete</kbd> or <kbd>Backspace</kbd> keys are pressed. We handle `delete` event in widgets and stop it. But this does not stop initial `keydown` event, which is handled further in `Input` plugin which once again deletes selected content before typing. 

So the situation looks like this:
1. User presses <kbd>Backspace</kbd>.
2. DeleteObserver handles `keydown` event and fires `delete` event.
3. We handle `delete` event in widgets: remove blockquote and select whole widget.
4. Input plugin handles `keydown` event and removes selected image.

After talk with @Reinmar and @pjasiun we decided that DeleteObserver should listen only to `keydown` generic event on highest priority and block it if it was handled. After that it should fire `keydown:delete` specific event (so other plugins listening to `keydown` event will always receive it).
Same solution should be used in EnterObserver.
