### ISSUE TITLE
UL item shouldn't be pasted to the OL

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#754]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the caret in `UL List item 2`.
3. Press <kbd>Tab</kbd>.
4. Select `UL List item 1` and `UL List item 2`.
5. Copy it.
6. Put the caret at the end of the `OL List item 1`.
7. Paste.

## ✅ Expected result

List types won't mix.

## ❎ Actual result

There is `UL` item inside the `OL`.

## 📃 Other details that might be useful

It doesn't occur in `v.0.10.0`.

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/34559939-33d73cf8-f144-11e7-83cd-2395c2ccf715.gif)

**Other information**
OS: Windows 10, MacOS X
Browser: All browsers

**Comment by Reinmar** [comment]
Pasting's behaviour is ok. You can have an ordered sublist of a numbered list. However, something else is not fully ok – that after outdenting this list item your list is split (because it's not converted to a numbered list item, but it remains a bulleted one). I'll report a separate ticket for this.

**Comment by Reinmar** [comment]
Done: https://github.com/ckeditor/ckeditor5-list/issues/88
