### ISSUE TITLE
Plug-in import error

### ISSUE THREAD

**Issue by cangyu1993** [ckeditor/ckeditor5#7547]
**I introduced the plugin but reported an error**
![image](https://user-images.githubusercontent.com/42930030/86453582-9d298a00-bd50-11ea-8ebf-5f101634588e.png)
![image](https://user-images.githubusercontent.com/42930030/86453675-bfbba300-bd50-11ea-8339-36ea8bdb730f.png)

**How do I introduce it**

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. The error occurs because you are trying to add a plugin to editor build, which is not possible. If you want to customise the editor and use it with Vue, please read [docs on building from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-ckeditor-from-source).

**Comment by cangyu1993** [comment]
I used the localization plugin and then introduced the plugin, but I still got an error
![image](https://user-images.githubusercontent.com/42930030/86503065-d3ace680-bddc-11ea-97ba-6d5f1c7b7347.png)
![image](https://user-images.githubusercontent.com/42930030/86503069-e0c9d580-bddc-11ea-9cc8-c6dccb15538e.png)

Going crazy

**Comment by FilipTokarski** [comment]
As I explained above ☝️  you cannot add plugin to the already built editor, you need to build it from source. Please refer to the docs I linked in my previous comment.

**Comment by tasadar** [comment]
Hi. I have the same problem, but i add to my project build all steps from this guide https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source . Why it is not working?

my neutrino config
https://gist.github.com/tasadar/3e9965eae915d7c39b512ee5c7be6437

my output config
https://gist.github.com/tasadar/db91e8b9626ae346421cf2ffc91535a1

During build process i have this error, but i think it is not affect editor build

[CKEditorWebpackPlugin] Error: No JS asset has been found during the compilation. You should add translation assets directly to the application from the `translations` directory. If that was intentional use the `buildAllTranslationsToSeparateFiles` option to get rif of the error.
[CKEditorWebpackPlugin] Error: No translation has been found for the en language.
[CKEditorWebpackPlugin] Error: Too many JS assets has been found during the compilation. You should add translation assets directly to the application from the `translations` directory or use the `addMainLanguageTranslationsToAllAssets` option to add translations for the main language to all assets or use the `buildAllTranslationsToSeparateFiles` if you want to add translation files on your own.

**Comment by FilipTokarski** [comment]
Hi, `duplicated-modules` error might also occur when plugins have different versions. So please check if the `Alignment` plugin you add, has the same version as other plugins. You can read more about this in the [error code docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules).
  
As it comes to translation errors - we are aware of them and there is a [discussion about this problem](https://github.com/ckeditor/ckeditor5-vue/issues/134) which you might find helpful for your case.

**Comment by tasadar** [comment]
Thank you very much for the help. I should better read your documentation. Editing package versions fixed everything

**Comment by cangyu1993** [comment]
I used the custom version to solve my problem, thank you
