### ISSUE TITLE
All toolbar icons defaulting to the overflow in the toolbar when using Firefox on Windows

### ISSUE THREAD

**Issue by julie0842** [ckeditor/ckeditor5#7574]
## 📝 Provide detailed reproduction steps (if any)

For some reason, when using the latest Firefox version on Windows to view CKEditor5 all of the toolbar icons are defaulting to the overflow menu unexpectedly. We are recreating this in different ways, and it appears to happen when resizing the browser window, but all of the icons going into the overflow doesn't seem to be expected behavior. If the window size is smaller, some of the icons may need to move to the overflow as expected to accommodate the smaller sized window, but not all of the icons. 

1. Open CKEditor in Firefox on Windows
2. Note if the icons appear as expected in the toolbar when the browser window is maximized
3. Change the browser window size so it's no longer maximized

### ✔️ Expected result

The icons in the toolbar should appear as expected and only go into the overflow menu if there isn't enough space for all of them.

### ❌ Actual result

All icons in the toolbar go into the overflow menu.

Here's a quick recording:
https://recordit.co/XebS7cTkno 

## 📃 Other details

* Browser: Firefox 78.0
* OS: Windows 10
* CKEditor version: ckeditor5-editor-decoupled
* Installed CKEditor plugins: 
"@ckeditor/ckeditor5-alignment": "^19.0.1"
    "@ckeditor/ckeditor5-autoformat": "19.0.1"
    "@ckeditor/ckeditor5-autosave": "^19.0.1"
    "@ckeditor/ckeditor5-basic-styles": "^19.0.1"
    "@ckeditor/ckeditor5-block-quote": "^19.0.1"
    "@ckeditor/ckeditor5-clipboard": "^19.0.1"
    "@ckeditor/ckeditor5-code-block": "^19.0.1"
    "@ckeditor/ckeditor5-core": "^19.0.1"
    "@ckeditor/ckeditor5-dev-utils": "^20.0.0"
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^20.0.0"
    "@ckeditor/ckeditor5-editor-decoupled": "19.0.1"
    "@ckeditor/ckeditor5-engine": "^19.0.1"
    "@ckeditor/ckeditor5-essentials": "^19.0.1"
    "@ckeditor/ckeditor5-font": "^19.0.1"
    "@ckeditor/ckeditor5-heading": "^19.0.1"
    "@ckeditor/ckeditor5-highlight": "^19.0.1"
    "@ckeditor/ckeditor5-image": "^19.0.1"
    "@ckeditor/ckeditor5-indent": "^19.0.1"
    "@ckeditor/ckeditor5-inspector": "^2.1.0"
    "@ckeditor/ckeditor5-link": "^19.0.1"
    "@ckeditor/ckeditor5-list": "^19.0.1"
    "@ckeditor/ckeditor5-media-embed": "^19.1.0"
    "@ckeditor/ckeditor5-page-break": "^19.0.1"
    "@ckeditor/ckeditor5-paragraph": "^19.1.0"
    "@ckeditor/ckeditor5-paste-from-office": "19.0.2"
    "@ckeditor/ckeditor5-react": "^2.1.0"
    "@ckeditor/ckeditor5-remove-format": "^19.0.1"
    "@ckeditor/ckeditor5-special-characters": "^19.0.1"
    "@ckeditor/ckeditor5-table": "^19.1.0"
    "@ckeditor/ckeditor5-theme-lark": "^19.1.0"
    "@ckeditor/ckeditor5-typing": "^19.0.1"
    "@ckeditor/ckeditor5-ui": "^19.0.1"
    "@ckeditor/ckeditor5-upload": "^19.0.1"
    "@ckeditor/ckeditor5-utils": "^19.0.2"
    "@ckeditor/ckeditor5-widget": "^19.1.0"

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, I just checked it with the latest Firefox and it works fine for me. Are you able to reproduce this issue in plain editor, without any styles customization? If it works fine, then I guess there is some problem with your app integration/styles, so there is not much we can do in such case.

Screencast from my editor:
![toolbar2](https://user-images.githubusercontent.com/34380544/86888870-2ea34e00-c0fb-11ea-8815-d8a539577315.gif)

**Comment by Anamon** [comment]
I'm currently facing the same issue with CKEditor 41.4.2.

- The original report implies, but doesn't specify, that this only happened in Firefox for them. For me, it seems to happen independent of the browser (tested in both Firefox 126.0.1 and Edge 125.0.2535.92).
- No styles customizations are applied to the editor, but the issue *doesn't* happen when just embedding it into a plain HTML page; I only get the issue when the editor is used in a modal dialogue of our Angular SPA. This might be caused by some styling cascading from further up, but so far I couldn't figure out what it is. I don't know if something like this was also the case for the original report, since the recording has been deleted.
- We're using some additional toolbar items from custom-developed plug-ins.
- We didn't have this issue with CKEditor 40.0.0, it first appeared after we updated to 41.4.2.
- As in the original report, any action that forces a resize of the editor will cause the toolbar items to properly drop out of the overflow menu back into the toolbar itself. Since the original recording is offline, I'm attaching my own example to this comment. Notably, if I fix the width of the editor, resizing won't fix the toolbar, it only works when an actual resize of the editor component is triggered.
https://github.com/ckeditor/ckeditor5/assets/517549/666b3917-dbf9-457e-97d8-edfdd7bfa153
