### ISSUE TITLE
How to add text before a blockquote?

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#7636]
If I have a blockquote at the top of the document, I seem to be stuck. No amount of Shift+Enter lets me escape the blockquote.

Perhaps blockquotes should have magic block buttons?

**Comment by Reinmar** [comment]
![](https://user-images.githubusercontent.com/156149/87911885-a4e57000-ca6c-11ea-9317-22ffab03c592.gif)

For me, pressing <kbd>Enter</kbd> (in an empty line) works. Doesn't it work for you?

**Comment by neongreen** [comment]
Hmmm.

It works for me as well. But... sometimes it doesn't.

I accidentally reproduced it once more right now, forgot how I did it, and spent five more minutes failing to reproduce it.

**Comment by neongreen** [comment]
Oh. I just managed to bring my editor to this state again, though I don't know how. Looking at the DOM, I have this:

![image](https://user-images.githubusercontent.com/1523306/87913680-22fb4400-ca78-11ea-8b0d-d9f9dae368bb.png)

I don't know under what circumstances CKEditor inserts zero-width spaces.

**Comment by Reinmar** [comment]
The thing that you see is 7 zero-width-spaces. It's a so-called "inline filler" that forces the browser to render the selection in the exact place where we want. Otherwise, in some cases (not in this one, actually) some browsers (Chrome, Safari) will move the selection where they see it fit.

Anyway, this is handled on the rendering level, so none of the editor features knows about it (the 7ZWSes don't appear in the model and the view) and hence they cannot affect what the Enter does.

What happened in your case is that you tried pressing Shift+Enter and not Enter itself (probably somehow intuitively). That resulted in inserting soft breaks instead of breaking out of the block quote.

**Comment by neongreen** [comment]
Yeah, I think I tried pressing Shift+Enter. Soft breaks are useful so I guess there's nothing else to be done here? Other than the option of adding magic line buttons to blockquotes. (Btw, how do I do that?)

**Comment by Reinmar** [comment]
@oleq pointed out to me that <kbd>Backspace</kbd> could also escape a blockquote in such a case:

```
<blockQuote>
	<paragraph>[]</paragraph>
	<paragraph>xxx</paragraph>
</blockQuote>
```

It might also be quite intuitive. The enter is more natural at the end, while at the beginning it's a bit counterintuitive.

WDYT?

**Comment by neongreen** [comment]
Sure, backspace at the beginning sounds fine.

**Comment by oleq** [comment]
> It might also be quite intuitive. The enter is more natural at the end, while at the beginning it's a bit counterintuitive.

This is something I'm always trying to do and then I get frustrated because it does not work this way.

**Comment by Reinmar** [comment]
This should probably be handled in #8137.
