### ISSUE TITLE
Support easy Trix-style image uploading

### ISSUE THREAD

**Issue by mchaput** [ckeditor/ckeditor5#767]
- Feature request

There are several problems with the current image uploading architecture:

- Very complex and ceremonial, involving multiple classes, adaptors, factories, etc.
- Hard to accomplish at runtime, all but requires a custom build.
- Not documented very well yet.

Trix has a much simpler and easier to use architecture: when the user drops an image, it immediately shows up in the document, and the editor fires an event. It's up to the user's code to listen for the event, upload the image data, and when the data is on the server, set an attribute on the image in the document indicating its server URL.

I'd love for CKEditor to consider supporting this alternative upload workflow.

**Comment by Reinmar** [comment]
CKEditor 5 introduced [Easy Image](https://docs.ckeditor.com/ckeditor5/latest/features/image-upload.html#Easy-Image). All you need to do to make it work is to set up a [CKEditor Cloud Services](https://github.com/ckeditor/ckeditor5-cloudservices) account and configure the editor to use it:

```js
 ClassicCreator
     .create( document.querySelector( '#editor' ), {
         cloudServices: {
             tokenUrl: 'http://url-to-retrieve-token.example.com/'
         }
     } )
     .then( ... )
     .catch( ... );
```

Then, it's Easy Image's service (implemented by CKEditor Cloud Services) role to support things like scaling images for different sizes, cropping, etc. You just drop the image and it works. I think that it can't be done simpler :).

The second option is writing your own upload adapter which is indeed not very well documented yet. However, it doesn't require creating a custom build and it's, in general, quite simple to start (really, not that much ceremony). The only complexity will come from actually sending the file to the server in a secure and reliable way, handle errors and so on.

The third option is enabling upload to CKFinder's server connector (see https://stackoverflow.com/questions/46765197/how-to-enable-image-upload-support-in-ckeditor-5). CKFinder's upload adapter is enabled in all editors as well, so you only need to specify one config option.

All this may look confusing now because we haven't finished CKEditor Cloud Services (soon...) and we haven't documented all this properly. The task about improving the documentation is tracked in https://github.com/ckeditor/ckeditor5/issues/618.
