### ISSUE TITLE
How to translate an model element to documentFragment in ckeditor5

### ISSUE THREAD

**Issue by pheeno** [ckeditor/ckeditor5#7735]
Hi there:
  First thank for the AMAZING framework ckeditor5!  now i hit a wall on use it, is there anyway to translate  model element to documentFragment ? i can get the viewElement  via upcastHelper,  and then i want to translate  the viewElement to documentFragment as a param to another function call.  plz give me some hint. thanks a lot

**Comment by Mgsy** [comment]
Hi! Can you tell more about your use case? Basically, you can't translate the element to the document fragment, because the latter is a detached part of the model tree. It means that it can contain children, i.e. model/view elements. 

So, I believe your question should be - how to insert a model element to the document fragment? To answer it, see the following code example:

```javascript
editor.model.change( writer => {
	const paragraph = writer.createElement( 'paragraph' ); // create a model element.
	const documentFragment = writer.createDocumentFragment(); // create a document fragment.
	
	writer.insert( paragraph, documentFragment ); // insert the model element to the document fragment.
	
	console.log( documentFragment );
} );
```

To learn more, please see our documentation:

*   [`DocumentFragment`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_documentfragment-DocumentFragment.html)
*   [`Writer#createDocumentFragment()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-createDocumentFragment)

**Comment by pheeno** [comment]
thanks a lot! it's helpful , open my mind !!

**Comment by Mgsy** [comment]
@Rajesh-Thiyagarajan, as this issue is solved, please open a new issue with a detailed description of your case. I'll check it.

**Comment by Rajesh-Thiyagarajan** [comment]
> @Rajesh-Thiyagarajan, as this issue is solved, please open a new issue with a detailed description of your case. I'll check it.

@Mgsy created new issue. Please do the needful
https://github.com/ckeditor/ckeditor5-react/issues/176
