### ISSUE TITLE
Research list styles feature

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7736]
## Provide a description of the task

Research what CKEditor 4 offers (we should cover these options) and what other editors offer.

Then, let's think about what we can do better than CKEditor 4.

Part of #1031.

**Comment by pomek** [comment]
Results of the research what do CKEditor 4 and other editors.

### [CKEditor 4](https://ckeditor.com/ckeditor-4/demo/#document)

* No option for setting list style in the toolbar
* Presets/layouts for nested lists do not exist
* The list-style value is applied on `ol` or `ul` element using inline styles

### [TinyMCE](https://www.tiny.cloud/)

* List style option visible in the toolbar (for both kind of lists)
* Presets/layouts for nested lists do not exist
* The value is applied to HTML element (like v4)

### [Quill](https://quilljs.com/)

At this moment, Quill provides the same options/support as CKEditor 5 (no option for setting list styles).

### [Google Docs](https://docs.google.com/)

* List style option visible in the toolbar
* Ability for using presets for nested lists
* GDocs uses `div` and `span` elements for rendering lists.

---

AFAICS, for MVP version, setting the list style value via the toolbar should be enough. List presets will simplify creating nested lists but I am unsure how we will merge two options in single toolbar item (list style, presets for nested lists).

**Comment by pomek** [comment]
After an internal talk with the team, we were considering how to use our UI library in the most efficient way, also keeping in mind that we want to support the content produced by CKEditor 4, we decided to use split buttons on the list (numbered or bulleted) icons. After clicking on them, the UI will show options for setting the list style.

Also, list styles should be disabled for to-do list.

Since the ticket is about researching and at this moment we have a conclusion, I am closing the ticket and if the rest of the discussion should be continued in #1031.
