### ISSUE TITLE
How to set custom dom className ,  like removePlugins [elementspath] in CK4

### ISSUE THREAD

**Issue by hubobbb** [ckeditor/ckeditor5#7754]
I want insert some style or custom dom className 。 
how to config ?
===
eg.
imgDom = '< div class="insert-image-w">< img width="200" src="" ></div >';
        let viewFragment = this.ckeditor.data.processor.toView(imgDom);
        let modelFragment = this.ckeditor.data.toModel(viewFragment);
        this.ckeditor.model.insertContent(modelFragment, this.ckeditor.model.document.selection);

the content is inserted successfully, but has no classname.

Tks

**Comment by hubobbb** [comment]
i see it 
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#why-does-the-editor-filter-out-my-content-styles-classes-elements-where-is-configallowedcontent-true

**Comment by Mgsy** [comment]
Hi, as you noticed, CKEditor 5 filters out some content while inserting it to the editor. It happens because it has a custom data model and accepts only elements which are registered in the schema and have a proper conversion. If you'd like to learn how to preserve a custom content, check our guide [here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-preserving-custom-content.html).
