### ISSUE TITLE
Can't include markdown plugin in editor build

### ISSUE THREAD

**Issue by Mekala-palaniyappan** [ckeditor/ckeditor5#7832]
Have to include the Markdown plugin in Editor build, but not worked.

import React, { Component } from 'react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import GFMDataProcessor from '@ckeditor/ckeditor5-markdown-gfm/src/gfmdataprocessor';

function Markdown(editor) {
  editor.data.processor = new GFMDataProcessor(editor.editing.view.document);
}

class Index extends Component {
  componentDidMount() {
    ClassicEditor.create(document.querySelector('#snippet-markdown'), {
      plugins: [Markdown],
      toolbar: [
        'heading',
        '|',
        'bold',
        'italic',
        'bulletedList',
        'numberedList',
      ],
      heading: {
        options: [
          {
            model: 'paragraph',
            title: 'Paragraph',
            class: 'ck-heading_paragraph',
          },
          {
            model: 'heading1',
            view: 'h1',
            title: 'Heading 1',
            class: 'ck-heading_heading1',
          },
          {
            model: 'heading2',
            view: 'h2',
            title: 'Heading 2',
            class: 'ck-heading_heading2',
          },
        ],
      },
    }).catch((error) => {
      console.log(error);
    });
  }

  render() {
    return (
        <div id={'snippet-markdown'} />
    );
  }
}

export default Index;

Output:

**Unhandled Rejection (CKEditorError): ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules**

**Comment by FilipTokarski** [comment]
Hi, this error occurs because you are adding plugin to an already built editor, which is not allowed. Please see docs on [creating editor from source in React](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source), this should solve the problem.
However, if you don't want to do it this way, you can always [build a standalone custom editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) ( or use [online builder](https://ckeditor.com/ckeditor-5/online-builder/) ) and then add it to your React integration.
