### ISSUE TITLE
Split image insert from upload image feature

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7890]
## 📝 Provide a description of the improvement

We want to go with the "Separate plugin" option from https://github.com/ckeditor/ckeditor5/issues/7794#issuecomment-677456196.

Also, we may want to revert this (from #7835):

> BREAKING CHANGE (image): Keep the `ImageUploadCommand` enabled when an image in the editor's content is selected. This allows us to replace the source URL of the image without the need to remove it.

Although, this one is actually tricky because before this change when an image was selected the image upload button was disabled but the table and media embed buttons were enabled. So we need to choose which is better.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by panr** [comment]
I wonder if we could depend on `ImageUploadCommand` and `ImageUploadProgress` for `ImageInsert` plugin?

Both `ImageUpload` and `ImageInsert` plugins need those. But maybe we could avoid duplication?

- Regarding `ImageUploadCommand`: `ImageInsertCommand` could extend `ImageUploadCommand` with a small tweak for enabling it when an image in editor's content is selected (`ImageUploadCommand` command should be disabled as it was before the changes, but `ImageInsertCommand` should be enabled — we want to update image `src`).
- Then I guess we don't need another `ImagaInsertProgress` since it will be exactly the same as `ImageUploadProgress`.

Both cases are related to the `dropdown.actionButton` which is our current `FileDialogButtonView`

cc @jodator

**Comment by jodator** [comment]
I think that I need to check how the UI is supposed to work. Reading the commands/features names alone gives me this weird feeling that something is not right.

1.  I don't see a need that `Insert*` would have to extend `Upload*` or use any `Upload*` concerns.
    1.  _inserting_ an image is one step process as any other editing feature
    2.  _uploading_ an image is a two-step process (upload then insert)
2.  Does _inserting_ image needs a _progress_?   
    The only thing I could think of is a situation of inserting a relatively big image which Browser would need to download in order to display. This would create a temporal empty block which gets filled as browser download the image and there's need to show a placeholder.... but this probably happens also during the upload when an uploaded image is inserted. So for this case alone I'd see that as image insert concern.

Those are my first thoughts _without_ digging into the UI requirements.

**Comment by jodator** [comment]
@panr  after  briefly checking the UI. The UI in the current is nice :) I really like that I can finally insert an image with a src. 

@Reinmar  & @oleq - After looking at the toolbar and the code:

*   it's an image related button/dropdown
*   by default it uploads image (main button)
*   it allows also inserting an image via dropdown
*   it allows to insert an image via file manager
*   it allows to change currently selected image (by upload or URL or external thing)

So, _for me_, I think it might be beneficial to clear things up here. Similar cleanup (mostly for utils) was done in tables recently because we agreed that we don't have much to add there in the foreseeable future and adding new features there will not happen soon. It might be a similar case for an image, in terms that we might have a solid set of image features for the foreseeable future.

5 min proposal:

*   `Image` - base image plugin, should provide
    *   image editing features
    *   inserting image command (a base command that should handle cases of inserting a image by providing its URL/URI - data image case) and updating image source
*   `ImageUI` - base general UI
    *   provides extensibility (wild idea `image` ui component, which is behaves differently depending on a set of enabled features)
    *   additional `insertImage` UI - solely responsible for inserting image via URL
*   adding `ImageUpload` enables uploading images
    *   adds `ImageUploadUI` - enables UI related parts (potential to have upload commands without UI)
        *   additional `uploadImage` button - solely responsible for uploading
    *   adds `ImageUploadEditing` - enables commands, temporal upload handling in the editing area
*   adding `InsertImageUI` enables inserting image via URL part of UI
*   on the side there's `CKFinder` feature which should provide own, dedicated UI (as `insertImage` and `uploadImage` does) so one could also have separate button for `insertImageWithCKFinder` (I don't recall its button name).

Open question still "how the two-step process of uploading an image should be done behind the scenes?". 

*   Right now it is a shared util between `insertImage` and `uploadImage`.
*   I'd image that expected way is that `ImageUploadCommand` either extends the behavior of the `ImageInsertCommand`  or uses `ImageInsertCommand` to insert an image into the editing area. (@panr  - this might be a real answer to your question).

Pros:

*   cleared up state of things, no waking up in the middle of the night form a bad dreams
*   flexibility of the toolbar composition
    *   either one do-it all `image`
    *   set of atomic UI parts for each of concern to pick & choose: `insertImage`, `uploadImage`, `ckfinderImage`.

Cons:

*   added time to the feature completeness state
*   too short analysis - I've might miss something

---

Looking at this in a broader spectrum - I think that we started from `imageUpload` button and build on top of it. I'd go with clearing things up _if_ we see that the set of features of image feature is complete enough or planned image features align to the above.

**Comment by Reinmar** [comment]
Surprise, surprise, there's already `imageInsert` command registered by `ImageEditing` :D We don't need to create a new one. The existing command is naturally completely independent from the `imageUpload` command as both do different things (although, only slightly).

Another surprise – `imageUpload` command does two things: inserts the image and _then_ uploads it. The order of action was a bit of surprise to me initially, but it makes sense.

As for how to structure this:

*   we don't need a new command,
*   we need to reuse somehow the image upload button in the image insert component.

As for the latter, we're thinking about this:

```javascript
class ImageUpload extends Plugin {
	init() {
		compFactory.add( 'imageUpload', () => {
			return createFileButtonView();
		} );
	}
}

class ImageInsert extends Plugin {
	get requires() {
		return [ ImageUpload ];
	}

	init() {
		compFactory.add( 'imageInsert', () => {
			const buttonView = compFactory.create( 'imageUpload' );
			const dropdownView = createDropdownView();

			return combineBoth();
		} );
	}
}
```

**Comment by Reinmar** [comment]
> Although, this one is actually tricky because before this change when an image was selected the image upload button was disabled but the table and media embed buttons were enabled. So we need to choose which is better.

One big advantage of enabling the object-type features (e.g. image, table, media) when another object is selected is that when the editor contains just an image, it was not clear previously how to insert another image. Right now we've got the widget type around feature, but still – enabling the image button would help with this issue as it'd reduce the number of steps that one needs to make to insert the new image.

Therefore, if we're to choose – I'd be for enabling all object-type features when another object is selected. This was already true for tables and media. And we have adjusted the image behavior in 21.0.0.

**Comment by jodator** [comment]
> Surprise, surprise, there's already `imageInsert` command registered by `ImageEditing` :D

Well, I've added it :P So I know what we have. The issue for me is how we structure the dependencies in `Image` as a whole.

For me this part is not OK:

```javascript
class ImageInsert extends Plugin {
	get requires() {
		return [ ImageUpload ];
	}
```

for me it should be the other way:

```javascript
class ImageUpload extends Plugin {
	get requires() {
		return [ ImageInsert ];
	}
```

as uploading an image is a special case of inserting and image. Anything else is "we don't have time to make it right" and for me it's :man\_shrugging: . The dependency would be surprising _for me_ but would work.

> Therefore, if we're to choose – I'd be for enabling all object-type features when another object is selected. This was already true for tables and media. And we have adjusted the image behaviour in 21.0.0.

I'm for this as well.

**Comment by Reinmar** [comment]
> for me it should be the other way:

Talking about what the action of uploading is and what inserting is, that'd be true. I totally agree. I also agree that  `ImageUploadCommand` could use `ImageInsertCommand`. That'd actually be possible, as the latter is in the base feature (\`ImageEditing\`). Yet, as for which plugin requires which, I think we need to look at which UI component extends which and here clearly the image upload is part of image insert which is broader.

I know that you proposed to do a bigger refactor so the common part is extracted from these two plugins so we can straighten the relation between uploading and inserting, but... yeah, "we don't have the time to make it right" :D

**Comment by oleq** [comment]
> *   we need to reuse somehow the image upload button in the image insert component.

FYI:

1.  Our current API does not allow [passing a button class/instance to the `SplitButtonView`](https://github.com/ckeditor/ckeditor5/blob/603daefa2dd82e9cfeca39e380c7bb3762ecb48c/packages/ckeditor5-ui/src/dropdown/button/splitbuttonview.js#L77)`.`
2.  On top of it, [the `createDropdown()` helper only accepts the class for the entire button](https://github.com/ckeditor/ckeditor5/blob/603daefa2dd82e9cfeca39e380c7bb3762ecb48c/packages/ckeditor5-image/src/imageupload/ui/imageuploadpanelview.js#L238) 
    1.  Lesser of the two problems, we can give up on the helper and do the bindings manually.

**Comment by oleq** [comment]
> *   Our current API does not allow [passing a button class/instance to the `SplitButtonView`](https://github.com/ckeditor/ckeditor5/blob/603daefa2dd82e9cfeca39e380c7bb3762ecb48c/packages/ckeditor5-ui/src/dropdown/button/splitbuttonview.js#L77)

I just noticed that @panr simply [overrides `SplitButtonView#actionView`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-image/src/imageupload/imageuploadui.js#L140) (which is read-only). We need to clean this up.

**Comment by panr** [comment]
@Reinmar @jodator another question... What do you think about introducing a new API for `ImageInsert` panel view? ATM we need to set integrations via `image.upload.panel.items`, but wouldn't be clearer to the user that this should be done via `image.insert.integrations`?

- `insert` is more plugin-specific
- `integrations` says more than `items` (also the new name would play better with the plugin API, where you have `#getIntegration()` method or `#_integrations` collection).
- we skip `panel` part in nesting

Thoughts?

**Comment by jodator** [comment]
> @Reinmar @jodator another question... What do you think about introducing a new API for `ImageInsert` panel view? ATM we need to set integrations via `image.upload.panel.items`, but wouldn't be clearer to the user if this should be done via `image.insert.integrations`?

Generally, yes, but actually (probably) no.

Yes, because:

For me putting focus on `insert` rather then `upload` makes more sense.

It should be `integrations` - for me this has better semantics (meaning vs technical detail of implementation).

No, because:

But that's my advisory voice here only - changing this _might_ be a part of bigger change but as @Reinmar [stated above](https://github.com/ckeditor/ckeditor5/issues/7890#issuecomment-685422558) let's just fix the main issue with a minimal effort. I'll extract my thoughts from here to a separate issue.

And, AFAICS, the No has more weight than Yes (at least today :wink:)

Sorry for messing with this. And to straighten things up:

*   let's not introduce anything new if not really needed to split the feature (clue of the issue)
*   if possible lean toward proper chain of responsibility when needed (ie `UploadCommand` can use/extend `InsertCommand` for inserting image, but in the current state probably the main plugin requires chain should be as described by @Reinmar  `ImageInsert.requires() => [ ImageUpload ]` (even though it is not ideal).
*   \+ @oleq's comment about read-only prop

**Comment by jodator** [comment]
My thoughts moved to: #8002.
