### ISSUE TITLE
CI should detect duplicated context.json entries

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7901]
## Provide a description of the task

Duplicated contexts should be detected by the CI, and should not be a thing that catches you off guard when preparing editor builds.

Followup of #7900

**Comment by mlewand** [comment]
It would make to run it on our uber integration CI (because CF and external projects share the ids with CKE5).

**Comment by pomek** [comment]
TODO: What to do if an error occurs?

**Comment by Reinmar** [comment]
TODO:

*   Document what to do when a duplicate is detected
    *   If the other usage is in a package like ckeditor5-core that we know that is available (because it's a depdendency), then we can simply remove the new usage (e.g. in html-embed).
    *   If the two conflicting usages are in packages like html-embed and media-embed, we cannot assume that the other on is installed, so we need to move this string to ckeditor5-core. This is tricky, because we MUST ensure that Transifex will port translations form the old resource (e.g. ckeditor5-media-embed/"Something") to the new (ckeditor5-core). We think that Transifex is configured to do that, but we cannot be sure without trying. It's e.g. CRITICAL to first download all translations `yarn translations:download` before doing anything so if we lose translations on Transifex we can recreate them from localhost.
    *   Another interesting case is when we have two identical strings but with a different meaning. We have that case predicted in the API (the translation ids) but we never used that nor have it documented anywhere where it'd be visible. We should at least mention that such a case is possible.
*   Once we have the above documented, we should link to that page/section from the CI error.

**Comment by pomek** [comment]
Yesterday I check the `translations:collect` script that we're using for checking translations string.

Unfortunately, it searches for packages in the `packages/` directory only. We could add an option for searching in the `external/` directory too. However, it will impact our downloading/uploading translation process and it seems to be dangerous.

Instead, I'd create a new script that will be searching for packages in directories: `packages/`, `external/*/packages/`. After collecting and validating stuff, the script should remove their results in order to avoid uploading anything by mistake.

The new script could be called `translations:validate` and should be executed on uber CI.

**Comment by pomek** [comment]
PR that allows checking translations in packages inside the `external/` directories: https://github.com/ckeditor/ckeditor5-dev/pull/678.

Some warning occurred and I reported it in proper repositories.

**Comment by pomek** [comment]
We need an article in our KB that will help with resolving issues if a conflict in translations occurs.

The URL to the article could be attached to output on our CI.
