### ISSUE TITLE
Custum build ckeditor-duplicated-modules

### ISSUE THREAD

**Issue by losewin** [ckeditor/ckeditor5#7918]
I don't know why is this not working, im so frustrated now, why is it not working it always says `ckeditor-duplicated-modules` even if there are no other ckeditor5 module/package being installed, T_T
Im so disappointed,

Also there is a Classic build editor with a Bold Header paragraph and others, but why when adding a table you have to create a new editor and include those one by one such as the Bold toolbar, is it not good just to add a plugin instead of recreating the whole thing?

also the `ckeditor-duplicated-modules` means other error instead of having a duplicate editor, Sorry for this, but as a beginner and new to this plugin it should have a better examples and documentation that is easy to understand or I am a slow learner?

**Comment by FilipTokarski** [comment]
Hi, [duplicated modules error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) means you are either trying to add plugin to an already built editor, confused editor build with editor implementation, or you use plugins that have different versions. Please see the docs on [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) and [custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html).
If that doesn't help, in order to look into this issue, we'll need your editor configuration, `package.json` contents and a step by step description to reproduce the error.
