### ISSUE TITLE
Wrong list style in undo stack after merging two different list styles

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#7930]
## 📝 Provide detailed reproduction steps (if any)

1.  Open [lists feature demo](https://ckeditor.com/docs/ckeditor5/latest/features/lists.html) for the upcoming v21 release (not not published yet, so production link won't work).
2.  Focus the editor under the "List styles" section.
3.  Select entire first list.
4.  Change style to upper-roman.
5.  Remove the entire "How to prepare the coffee" paragraph, so that the list get combined.
6.  Undo.

Full screencast:

![](https://user-images.githubusercontent.com/5353898/91058173-712bd600-e628-11ea-86b0-a73d7fc8b119.gif)

### ✔️ Expected result

Both lists preserve their initial styles (the first keeps upper Roman, the second keeps numeric with leading 0)

### ❌ Actual result

You're unable to restore initial list type of the second list.

![](https://user-images.githubusercontent.com/5353898/91057408-7177a180-e627-11ea-85a6-6d98db8eb0ee.png)

## 📃 Other details

*   Browser: Chrome
*   OS: Windows 10
*   CKEditor version: v21

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
The model after applying operations listed above looks ok:

![image](https://user-images.githubusercontent.com/2270764/92577796-5ba2e700-f28b-11ea-9693-ea80d9c188c5.png)

There must be something wrong in the conversion or/adn rendered mechanisms.

**Comment by pomek** [comment]
The issue was fixed (accidentally) while we merged https://github.com/ckeditor/ckeditor5/pull/7902.

Before merging #7902, lists were merged in the view but the model state was invalid. When applying the undo command, the model hasn't changed and the view wasn't rendered.

After merging #7902, the model was updated (change the `listStyle` attribute), the view could render those changes. When applying the undo command, the model was reverted and the view display the proper state of the model.
