### ISSUE TITLE
Is anyone maintaining it

### ISSUE THREAD

**Issue by louieaa** [ckeditor/ckeditor5#7970]
It's been more than 20 days since the request was made, and the email has been sent, but no information has been received,
That's too bad

#7824

**Comment by mlewand** [comment]
Of course there are quite a few people maintaining it 😂 We don't have any precise time limits for GH issues and we always prioritize those with big support from the community so that most of us can benefit our work.

At the same time if you need a premium support, you have the option to use CKEditor 5 premium support option where you have a dedicated support channel. For more information, see https://ckeditor.com/pricing/.

**Comment by louieaa** [comment]
> Of course there are quite a few people maintaining it 😂 We don't have any precise time limits for GH issues and we always prioritize those with big support from the community so that most of us can benefit our work.
> 
> At the same time if you need a premium support, you have the option to use CKEditor 5 premium support option where you have a dedicated support channel. For more information, see https://ckeditor.com/pricing/.

Thank you for your answer!
