### ISSUE TITLE
installed plugin does not work

### ISSUE THREAD

**Issue by vxfil** [ckeditor/ckeditor5#8055]
## 📝 Provide detailed reproduction steps (if any)

I wanted to add additional functionality to the classic editor in the form of a simple upload adapter and other functions.

1. I used the online builder and generated the configuration I needed
2. went to the folder did npm install and npm run build
3. then I connected a custom build to my project using npm and tried to import ClassicEditor and got an error that this module does not exist.
4. since it did not work out, I found this [guide](https://medium.com/@jacobtamus/ckeditor5-custom-react-editor-tutorial-a9e91aab9d16) on medium and went through all its steps and received this error 
![error](https://user-images.githubusercontent.com/46137927/92657030-b88ab580-f2fc-11ea-856c-e7f1c3fa4929.jpg)

### ✔️ Expected result

expected result - included simple upload adapter module and some other modules

### ❌ Actual result

in the case of a guide from a medium - an error, in case of an attempt to connect a custom build - not understanding how to import Editor into react

## 📃 Other details

* Browser: chrome 85.0.4183.83 64bit
* OS: windows 10
* CKEditor version: 5
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, if you want to create a custom build, please refer to [docs on custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html). If you want to integrate custom CKEditor 5 with React app, please follow [docs on building from source in React](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source).  
  
Apart from this, the [duplicated modules error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) means that you're most probably either trying to add a plugin to an existing build or using packages that have different versions. I would advise to check if that is not the case here, because it looks like a problem on your side and not with the editor itself.
  
If that does not help, we'll need more information to reproduce this issue ( step by step description, package.json, editor config, etc ).
