### ISSUE TITLE
Documentation link to an external project breaks the CI

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#8060]
## 📝 Provide a description of requested docs changes

#8046 introduced a `{@link features/export-pdf Export to PDF feature}` link to resource that is not available in core repository.

**Comment by AnnaTomanek** [comment]
[**@mlewand**](https://github.com/mlewand) This is absolutely not an issue that should be fixed in the documentation by changing _valid_ links created as intended in the docs project, according to all the rules, and you should not workaround it by replacing links generated by our own docs building tools to a hardcoded URL because it kinda defeats the purpose of our own link validation mechanisms. If anything, this issue is a problem in your CI integration and something to be fixed there.

Please revert it as this is not the proper way to fix this problem.

**Comment by mlewand** [comment]
We discussed this matter on devops sync today and the only solution to get around this is to either to hook up a second CI that will have access to all the project (and remove the docs check from `ckeditor/ckeditor5` ci) or to revise entire Umberto project and rethink how we should handle cases like that.

Both solutions require substantial amount of effort that we can't afford at this point, so decided to stick to working around this particular annoyance.
