### ISSUE TITLE
Some icons may look blurry on LoDPI screens after theme refactoring

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#808]
Most of them look crisp enough to me but blockquote and image need refactoring.

![capture](https://user-images.githubusercontent.com/1099479/35728492-055a0c0a-080c-11e8-9c8f-41917edfa599.PNG)

A follow-up of https://github.com/ckeditor/ckeditor5/issues/645.

**Comment by pjasiun** [comment]
For me, lists, bold and italic looks very bad on standard screen. :( When I open standard editor I thought there is a rendering bug.

**Comment by Reinmar** [comment]
The biggest difference is, surprise surprise, in 1px -> 1.5px horizontal/vertical lines. Those are blurry now. But all rounded shapes look as good/bad as they did.

![image](https://user-images.githubusercontent.com/156149/35801186-af7b0b56-0a6b-11e8-85d4-24c3471d9f11.png)  ![image](https://user-images.githubusercontent.com/156149/35801313-240493f2-0a6c-11e8-9886-541e77ebb28f.png)


![image](https://user-images.githubusercontent.com/156149/35801208-c758b2fa-0a6b-11e8-83b8-23def3c9076d.png)  ![image](https://user-images.githubusercontent.com/156149/35801295-11f1d8b4-0a6c-11e8-9b34-24f3caf75214.png)



![image](https://user-images.githubusercontent.com/156149/35801253-e8aeebc2-0a6b-11e8-86d8-4fb6b14e5fa0.png)  ![image](https://user-images.githubusercontent.com/156149/35801274-f3f8da38-0a6b-11e8-8162-f102c2d26410.png)

---

I wonder what would happen if we increased the line width from 1.5px to eg. 1.75px. Or down to 1.25px. It might look sharper then because it would round better to 1px or 2px. While the average width would still be ~3px on retina. Could you do such tests on one of the icons, Olek? I'm really curious to see this live.

**Comment by jodator** [comment]
For me all the icons are blurry
![selection_022](https://user-images.githubusercontent.com/247363/35801787-ee3f1736-0a6d-11e8-8e49-565451d494e7.png)

**Comment by oleq** [comment]
@jodator That looks pretty bad, I admit. Linux, I guess?

We might research 1.25 or 1.75 but in truth, the only safe solutions are 1px and 2px. 

Unfortunately, with current technology, we are unable to deliver different icons based on the density of the screen – we'd have to include 2 icon sets in the JS build to do that.

**Comment by Reinmar** [comment]
I just went quickly through other editors and they are:

* either awfully blurry (far worse than what we have)
* or 2px width (which we checked but none of us liked)

That's the state of the web in 2018. Also, it made me realise that I haven't been noticing this so it may happen that we'll stop noticing the blurriness of the new icons in a short time too :D

**Comment by Reinmar** [comment]
I think I got used to this and no one ever reported it, so I'm closing this ticket.
