### ISSUE TITLE
Followups for the changes in error codes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8097]
## 📝 Provide a description of the improvement

We changed the format recently (#7822), but the change is not complete:

*   The documentation was not updated (see e.g. https://github.com/ckeditor/ckeditor5/blob/3e6ea99/packages/ckeditor5-utils/src/ckeditorerror.js#L36-L39 or https://github.com/ckeditor/ckeditor5/blob/3e6ea99/packages/ckeditor5-utils/src/ckeditorerror.js#L139-L141).
*   This regepx is unsafe: https://github.com/ckeditor/ckeditor5/blob/3e6ea99/packages/ckeditor5-utils/src/ckeditorerror.js#L147-L148 unless it's kept in perfect sync with a regexp in the ESLint rule. If you're allowed to write an error like `CKEditorError( 'image-invalid-%-size' )`, then this error will not be enhanced with a link to the documentation. This will be super hard to spot – it will be a silent issue for us. We need to at least check that such a situation is not possible and commented in the code that those regexps are in sync ensuring that all errors are well defined.
*   I don't understand why `console.warn` does not have to follow the same convention. What's the reason for that? If it was following it, we could solve the previous point with a more verbose solution (throw a new error :D).
*   Finally, this: cksource/ckeditor5-internal#327

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
cc @jodator @pomek

**Comment by jodator** [comment]
I think that we've hit the first monorepo issue - no way to have different versions.

The `console.warn` things - It's my fault - I was sure that I've created and issue for this. This should behave the same. Hower, I though tthis might need to discuss more.

So the regexp is unsafe because I wanted to have separate issue for `console.warn` and I forgot. There should be no regexp after the change and `attachLinkToDocumentation()` should work on "id".

As we going to touch this again, I'm for

1.  The same logic for `console` warnings.
2.  Rename `CKEditorError`'s `message` param to `errorId` to reflect that this is not a fully sentenced error message.
3.  Fix the docs.

Again, sorry for that - this ticket should be created earlier.

**Comment by Reinmar** [comment]
Followup about which I forgot: #8140. Non-blocking.
