### ISSUE TITLE
The "Bold" icon is not centered

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#811]
![image](https://user-images.githubusercontent.com/156149/35798066-fcb18e9a-0a61-11e8-9bd0-095c3b7ee548.png)

It's more to the right.

**Comment by oleq** [comment]
It's a rendering issue in Chrome. Take a look at this screenshot:
![image](https://user-images.githubusercontent.com/1099479/35801128-634cc27e-0a6b-11e8-9515-d143197e5996.png)

In both cases, the pink rectangle is centered in the middle of the green rectangle in the image processor and put as an overlay over the button with an icon. 

In the second alignment case, the alignment of the icon is different because the geometry of the toolbar has changed (wrapped items to the next line) which normally would not have any impact. They are the same toolbars.

This is what it looks like in FF (similar to the Chrome wrapped to the 2nd line):

![image](https://user-images.githubusercontent.com/1099479/35801255-ea0908a4-0a6b-11e8-9f94-24d6ba4218c7.png)

And Safari (unlike any of the above):

![image](https://user-images.githubusercontent.com/1099479/35801294-116acdce-0a6c-11e8-91e0-8042aefa0aeb.png)

It's the 21st century and we cannot get over CSS. 

I suspect the cause of the issue is the `inline-block` positioning used for various elements, which depends on the font rendering engine of the web browser, which then is unique and not quite in line with the geometry is certain situations. 

Some more reliable positioning strategies (`block`, `inline-flex` – they have been researched in #645) caused other issues with misalignment and responsiveness. It's a very tricky topic when you expect:
* the UI to be responsive (to the font size), 
* all things to be aligned and perfectly centered,
* buttons with just icons to always stay square and of the same height as buttons with text.

**Comment by dkonopka** [comment]
Besides of browser rendering issues, bold icon needs to be fixed (current size is 11.57px x 13.93px), I've fixed and rounded it and looks much better.

![screen shot 2018-02-12 at 15 52 53](https://user-images.githubusercontent.com/10219857/36102534-e2fd59ce-100c-11e8-8f5b-afad199f05b2.png)

**Comment by Reinmar** [comment]
Will do a PR?
