### ISSUE TITLE
Inconsistent behavior with custom headings

### ISSUE THREAD

**Issue by antoniolucasnobar** [ckeditor/ckeditor5#8117]
## 📝 Provide detailed reproduction steps (if any)

1. Create a custom heading (following [official site](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html)), using this css (instead of the site):

```css
    p.fancy, .ck-heading_heading2_fancy {
        color: #ff0050;
        font-size: 17px;
        text-align: justify;
        font-style: italic;
    }
```
heading definition:
```js
        heading: {
            options: [
                { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
                { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
                { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
                {
                    model: 'headingFancy',
                    view: {
                        name: 'p',
                        classes: 'fancy'
                    },
                    title: 'Heading 2 (fancy)',
                    class: 'ck-heading_heading2_fancy',

                    // It needs to be converted before the standard 'heading2'.
                    converterPriority: 'high'
                }
            ]
        }
```
2. Apply the above style to a text
3. Try to left align the text or to remove italic

### ✔️ Expected result

I expected two main things:
1. When I choose any styling, the toolbar reflect the changes (if the style makes the text is bold for example, the bold button should show activated/clicked). The same for alignment.
2. the text to change when I use the toolbar to override what is defined in the styling.

### ❌ Actual result

The toolbar does not reflect the css of the styling. It shows as the text is left-aligned and the italic button is not activated.
The text can not be left align neither remove italic

## 📃 Other details
- Alignment:
I noted I can center the text, or right align, but not left align. This happens because the alignment plugin does not add anything when left aligned is chosen, as seen in [alignmentcommand.js](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-alignment/src/alignmentcommand.js#L70-L80). Apparently, this would bloat the model as stated in a comment. I disagree with this, because it makes impossible to remove text-align from styles with this property. 

I think it is possible to solve this just adding the element `text-align: left;` when the user click in that button, overriding this way the class option. 
Also, There should have a conversion to the buttons of the plugin reflect what is defined in the class.

- Italic
In this case, it is absolutely impossible to the user to remove this from the styling. The italic button in the basic-styles-plugin adds an `<i></i>` around the selected text. Looking at the [plugin code](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-basic-styles/src/italic/italicediting.js#L44-L55), I see that it makes a conversion between the `'font-style': 'italic'` attribute and the `<i>` tag and it works indeed (even the button is activated when the editor is loaded with a text with that attribute).

It seems to me that the conversors do not look into the css class properties when it should do. The user should be able to customize the text after choosing a style. Sometimes they want that exactly style, except for one thing.

* Browser: Firefox 80.0
* OS: Linux mint 19.3
* CKEditor version: 22.0
* Installed CKEditor plugins: Essentials, Alignment, Paragraph, Heading, List, Bold, Italic

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Hi! Thanks for a well described ticket.

What you observed here is a conflict between semantical and visual styles. The heading configuration allows you to choose between multiple semantically-meaningful options. You associated one of these options with its visual representation – being italicized and justified. That leads to the conflict, as you observed it. This is an unfortunate situation when pure content meets visual styles.

Let's imagine this situation:

1.  Today, the "Fancy heading" style is defined to use an italicized font and to justify the text.
2.  Since you configuration uses semantical and non-semantical styles, the user is given a choice of text alignment options (non-semantical style). They decide to justify the entire text in the editor (all paragraphs), but since the heading is alreadu justified, they don't touch it.
3.  However, one day you decide that "Fancy heading" should not anymore justify the text because that does not work well for a certain medium. You remove that style from your stylesheet.
4.  What happens? The document that was created by the user in step 2 will have the entire text in your editor justified... except the heading. That's certainly not what they planned.

Interestingly, the same may apply to all headings, not only the fancy one. And to many other features too.

The conflict comes from the fact that we need to support two distinctive and highly conflicting modes: semantical and visual. Features that should only work in the visual mode should get a different behavior of semantical features (or rather – a non-semantical version of these). But that'd mean twice as much work as now. Therefore, the situation isn't ideal and there's no easy way out. Each option has its critical drawbacks.

I'd say that the feature closes to what you'd like to see is the styles feature that could be a non-semantical alternative to headings: #648 (or at least have such a mode).

**Comment by antoniolucasnobar** [comment]
Hello @Reinmar , thanks for your response. I read the Style feature thread #648 and, besides your last comment, I do not know if it is what I am looking for. Maybe #5700 is a better option for my user needs. 

IMO, when a user chooses a styling, the toolbar should reflect that and the user should be able to fine tune the style to her/his needs (The styles in LibreOffice works that way AFAIK). 

For now, I have to deliver a set of predefined styles to the users, so not giving them the chance to change will not be good.

You wrote

>  The heading configuration allows you to choose between multiple semantically-meaningful options.

Where do I find these semantically-meaningful options?  

I looked through the documentation and source code and did not find anything related to this semantic options; 

I just followed the [official guide](https://ckeditor.com/docs/ckeditor5/latest/features/headings.html). Because of it, I thought that CSS was the way to go. Later I found the [HeadingOption](https://ckeditor.com/docs/ckeditor5/latest/api/module_heading_heading-HeadingOption.html) and saw that the `view` [object](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_elementdefinition-ElementDefinition.html) can have styles set directly. I tried that. It worked, but it did not transform the styles to model properties. It looks like the model name is bound to that set of styles, classes and attributes you define in the heading configuration properties. 
I wonder if I could, after the heading plugin set the styles, tell the editor to reprocess that block in a way to translate the styles properties to model properties (just like it does when the editor is loaded). 

I am console logging the objects to see what is inside. Is there a way to have code completion on ckeditor modules? It would be very handy right now.

Then, I thought of setting model properties when I choose a specific heading. But I found out the model property is just a String. As a test, I used the attributes of the view object, and changed the HeadingCommand to set the attributes as model attributes. It worked out to the `justified`, but not for `italic`. Using the editor, I saw when I press ENTER with italic turned on, the new  paragraph have `selection:italic` property (which is translated to `italic` property when the user starts to type). I tried to set that property to the block, but it is not translated (only when I press ENTER and start typing.

Finally, I setted the italic attribute directly to the nodes inside `block._children._nodes` (how do I know if it is a block or a text element) and it worked out. But this is already too messy to me. 

So I ask for guidance. Where should I look to implement such a feature? 

Once again, thanks for your kind attention.
Best Regards.
