### ISSUE TITLE
Apply Emoji example on Classic CKEditor 5 downloaded from online builder?

### ISSUE THREAD

**Issue by PeraMika** [ckeditor/ckeditor5#8155]
## Provide a description of the task

I have no experience with npm/webpack/JS,ES6... so I'm using Classic CKEditor 5 downloaded from [online builder](https://ckeditor.com/ckeditor-5/online-builder/). 

I have "_Special Characters_" plugin and  want to add Emojis. In the documentation there are examples of how to add Emojis (within a new category) or how to add characters to an existing category: https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html 

However, these examples are for "npm" users and I'm using CKEditor simply by including the "ckeditor.js" file. 
So I was trying everything... and found a way to add Emoji:

```
<script src="{!! asset('vendor/ckeditor/build/ckeditor.js') !!}"></script>

    <script>
        ClassicEditor
            .create(document.querySelector('#body'), {
               . . . 
            })
            .then(editor => {
                window.editor = editor;

                editor.plugins.get( 'SpecialCharacters' ).addItems( 'Emoji', [
                    { title: 'smiley face', character: '😊' },
                    { title: 'rocket', character: '🚀' },
                    { title: 'wind blowing face', character: '🌬️' },
                    { title: 'floppy disk', character: '💾' },
                    { title: 'heart', character: '❤️' }
                ] );
            });
    </script>
```
The result is this:

![Emoji Attempt 1](https://user-images.githubusercontent.com/41101578/94182794-c49c7880-fea1-11ea-8837-c0ab06474c1f.png)

The problem is that these Emojis (newly added special characters) are at the bottom. 
Is there any way to add (move) them at the top? (without using npm/es6/webpack... )

**Comment by Mgsy** [comment]
Hi! Your emojis appear at the end of the balloon because those are the most recently added items. As you can see, in the right corner of the balloon, you display all categories. If you'd like to display only emojis, simply change the filter. 

> However, these examples are for "npm" users and I'm using CKEditor simply by including the "ckeditor.js" file.

It doesn't matter if you use npm packages or a build. Please, read more about configuring the editor [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html).

Additionally, I've written more about the configuring the special characters plugin in [your second ticket](https://github.com/ckeditor/ckeditor5/issues/8156#issuecomment-699849369).
