### ISSUE TITLE
Separator and 2 lines

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#817]
When the second line of the menu appears it looks like there is missing some lines. The border effect which we had with a single line is broken:

![separator-2-lines](https://user-images.githubusercontent.com/1166967/35802706-567df328-0a71-11e8-91ee-799a532b6e95.gif)

It is not a problem when the separator does not touch top and bottom lines:

![separator-2-lines-fixed](https://user-images.githubusercontent.com/1166967/35802707-56dab20c-0a71-11e8-9f25-2f853ac54083.gif)

**Comment by oleq** [comment]
We decided to go with full-height separators because:
* they look great (especially when the UI is dark), setting boundaries to the dropdowns and grouping buttons,
* this kind of wrapping is not very common,
* if developers decide they want multi-line toolbars, they can easily customize the separator,
* most likely, at some stage we'll have to implement a dynamic grouping mechanism anyway, which is common in many apps if only to have more control over the UI on small (mobile) screens
![image](https://user-images.githubusercontent.com/1099479/35803786-581b2d50-0a75-11e8-8a64-3ad13a9ff3f7.png) 
![image](https://user-images.githubusercontent.com/1099479/35803793-645f89e4-0a75-11e8-9825-bfd1c740e66c.png)

**Comment by Reinmar** [comment]
I'd add one more point to @oleq's list – developers should not accept situations where wrapping appears. It's an issue itself and should be solved so there's no wrapping.
