### ISSUE TITLE
Ckeditor 5 plugins not working

### ISSUE THREAD

**Issue by learn44** [ckeditor/ckeditor5#822]
I am having this issue when I add plugins then ckeditor dont show anything in editor and toolbar and give this error in console: plugincollection-plugin-not-found: Some plugins are not available and could not be loaded. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#plugincollection-plugin-not-found

plugin code is this:
InlineEditorBase
.create(document.querySelector(element), {
// The plugins are now passed directly to .create().
//plugins: [
//EssentialsPlugin,
//AutoformatPlugin,
//BoldPlugin,
//ItalicPlugin,
//BlockquotePlugin,
//HeadingPlugin,
//ImagePlugin,
//ImagecaptionPlugin,
//ImagestylePlugin,
//ImagetoolbarPlugin,
//LinkPlugin,
//ListPlugin,
//ParagraphPlugin
//],

            //So is the rest of the default configuration.
              plugins: ['Alignment'],
            alignment: {
                options: ['left', 'right']
            },
            toolbar: [
                'headings',
                'bold',
                'italic',
                'link',
                'bulletedList',
                'numberedList',
                'blockQuote',
                'undo',
                'redo',
                'alignLeft', 'alignRight', 'alignCenter', 'alignJustify'
            ],
            //removePlugins: ['Heading'],
            //toolbar: 'full',
          
            autoParagraph: false,
            enterMode: 'div',
            ShiftEnterMode: 'br',
            language: 'GB-en'
        })
        .then(editor => {
            editor.setData(data);
            this.ckEditor = editor;
            console.log(editor);
        })
        .catch(error => {
            console.error(error);
        });
I am using angular 5 and ckeditor 5?

**Comment by Reinmar** [comment]
Hi! You're trying to load plugins using the string format which only works when:

* You use an editor build (like e.g. npmjs.com/package/@ckeditor/ckeditor5-build-classic).
* This plugin is available (built-in) there.

Since I see in your code `InlineEditorBase` I can guess that you build the editor from source (like [here](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/quick-start.html)). This means that the plugins are not built into it – you have to provide all plugin constructors through the `plugins` option.

Furthermore, the [Alignment feature](https://github.com/ckeditor/ckeditor5-alignment) hasn't been yet published on npm. It will be done with the next CKEditor 5 release.

PS. I wrote recently a guide targeted at clarifying the plugin installation practices. It's published in the nightly version of the docs here: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/development/installing-plugins.html.

**Comment by learn44** [comment]
Hi,
Thanks Reinmar for the quick reply.
