### ISSUE TITLE
getDataWithAcceptedSuggestions triggers onUpdate for Word Count and makes it return 0 for word and character count

### ISSUE THREAD

**Issue by FilipaBarroso** [ckeditor/ckeditor5#8249]
## 📝 Provide detailed reproduction steps (if any)

```
editor.model.document.on('change:data', () => {
    editor.plugins
        .get('TrackChangesData')
        .getDataWithAcceptedSuggestions()
        .then((data) =>
            setSessionVar("SUGGESTIONS_ACCEPTED", data)
        );
}
```

I'm using this to store the data with accepted suggestions. However, this is causing my onUpdate for Word Count to run twice, and both stats.words and stats.characters are equal to 0 the second time it updates.

### ✔️ Expected result

getDataWithAcceptedSuggestions() should not trigger onUpdate events, or at least it shouldn't make the Word Count plugin return wrong values.  

### ❌ Actual result

getDataWithAcceptedSuggestions() triggers the onUpdate for wordCount, making it run twice per character and returning 0 

## 📃 Other details

* CKEditor version: 22.0.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Track Changes is a commercial plugin and this repository is used for tracking open source issues. Please [submit a support request](https://support.ckeditor.com/hc/en-us/requests/new), so that our team will get back to you as soon as possible. Sorry for the inconvenience. I'll close this ticket for now.
