### ISSUE TITLE
How to focus cursor  at the end of text in ckeditor 5

### ISSUE THREAD

**Issue by learn44** [ckeditor/ckeditor5#825]
This is below code:  
var oldData = this.ckEditor.getData();
this.ckEditor.setData(oldData + "{" + data + "}")
after this how to focus cursor  at the end of text in ckeditor 5
I am using angular 5 and ckeditor 5?

**Comment by oleq** [comment]
Hi,

this is an issue tracker and since this is neither a bug or a feature request I suggest using our [Gitter channel](https://gitter.im/ckeditor/ckeditor5) or [StackOverflow](https://stackoverflow.com/questions/tagged/ckeditor5). Also [more on getting support](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/support/getting-support.html).

**Comment by learn44** [comment]
Hi oleq,
             Thanks for the quick response. Ok I post in the links mentioned.

**Comment by MachinePereere** [comment]
Hi, does anyone know a way to implement cursor positioning at the end of the content in ckeditor5 ?
