### ISSUE TITLE
Edit Source Code

### ISSUE THREAD

**Issue by WebSpectrum** [ckeditor/ckeditor5#8269]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_
Need a view source/edit source code option like older versions of CKEditor. It's my understanding this feature was removed in CKEditor 5?
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Hi @WebSpectrum , this topic was widely discussed here: #592. At this point,for there's no ETA of this feature (read more here: https://github.com/ckeditor/ckeditor5/issues/592#issuecomment-470424532)

The CKEditor 5 was built from scratch with collaboration features in mind. In order to do that we had to switch from the previous implementation to a more controlled one.

As I understand you ask for "Support for "free HTML" editing." as explained in #592. Because of that, I'm closing this issue as a duplicate.

**Comment by John0King** [comment]
@jodator   #592 is locked !

and I want ask,  does  Ckeditor5 allow set Html Content ?(eg. exiting html in the editor)
if it desn't then it's wired, because your online demo have existing content .  if it allow , then  hide source code is that important ?  I can always set a un-**dom**ed html as existing html
