### ISSUE TITLE
Contextual Toolbar wrong positioning on narrow screen

### ISSUE THREAD

**Issue by vokiel** [ckeditor/ckeditor5#827]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

latest/nightly

## 📋 Steps to reproduce

1. Open https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html
2. Resize window to small size, so the horizontal scroll bar appears.
3. Select image and play with its size.

## ✅ Expected result

Contextual Toolbar will be attached at proper position.

## ❎ Actual result

Contextual Toolbar is positioned too high or to low until image is focused again or window is scrolled/resized.

![contextual_toolbar_position](https://user-images.githubusercontent.com/422571/35888311-79b76eec-0b97-11e8-88a4-627c503e57b5.gif)

**Comment by Mgsy** [comment]
I can reproduce this issue. 

Related - https://github.com/ckeditor/ckeditor5-image/issues/174, https://github.com/ckeditor/ckeditor5-ui/issues/326

**Comment by oleq** [comment]
There are 2 problems here:
* Toolbar items are wrapping to the new line. This happens when the absolutely positioned block goes off the `<body>`. The browser does whatever possible to make sure children remain visible.
* The positioning is (probably) wrong because `BalloonPanelView` has a default limiter set to `document.body`, which is just weird in the docs (see the screenshot):
![image](https://user-images.githubusercontent.com/1099479/35913887-88155cd2-0c01-11e8-8e03-617a2d68988c.png)

**Comment by Reinmar** [comment]
I couldn't reproduce this in our docs and we don't get reports about this from elsewhere.
