### ISSUE TITLE
Dropdown button's arrow is misaligned

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#831]
![image](https://user-images.githubusercontent.com/156149/35977391-51d4d732-0ce3-11e8-99da-765952841a5d.png)

Perhaps related to https://github.com/ckeditor/ckeditor5-ui/pull/361.

cc @jodator @oleq

**Comment by oleq** [comment]
It's because before the refac it was `10x10px` and now it is `10x20px`. Something went wrong with styles.

**Comment by oleq** [comment]
In fact, there are 2 misalignments:
![image](https://user-images.githubusercontent.com/1099479/35978833-08017bb6-0ce7-11e8-931b-bc80305465a9.png)

The one in the alignment can be fixed by removing the following https://github.com/ckeditor/ckeditor5-ui/blob/master/theme/components/dropdown/dropdown.css#L17-L18

The one in the headings dropdown is because there's an unnecessary right margin, a default for button icons. But since the arrow is not a regular icon, it has a different (absolute) position and it does not need the right margin.
