### ISSUE TITLE
The ComponentFactory does not have the get() method

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#8383]
## 📝 Provide a description of requested docs changes

As stated in https://github.com/ckeditor/ckeditor5/blob/70a680fb9a39f32dffaae264bbf2f9e0511a2dee/packages/ckeditor5-ui/src/dropdown/utils.js#L113 it is possible to get an existing component instance, but in fact the [`ComponentFactory`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_componentfactory-ComponentFactory.html) does not have the `get()` method.

**Comment by jodator** [comment]
It looks like a typo :upside\_down\_face: . I think that this should be `editor.ui.componentFactory.create()`.

**Comment by jodator** [comment]
Yep, a typo so a good catch :) Fixed by: 98f8ee7.

---

As for the details of the `create()` method. It does not return the existing component instance. This allows creating multiple instances of a registered UI component. This is usefull because:

1.  the instance can be configured to your needs.
2.  the instances can be used in different places and will not interfere with each other.

This "trick" is used for instance in the highlight feature: https://github.com/ckeditor/ckeditor5/blob/43f081bfb4425409b3cff31bfe5df4de75f99c79/packages/ckeditor5-highlight/src/highlightui.js#L205-L214.

This feature will:

*   define separate buttons for each highlighter (so they can be used in the toolbar directly by name)
*   then it also defines a create method for a dropdown which re-uses component factory create method to populate toolbar with the same button
