### ISSUE TITLE
Textarea being submitted with an empty paragraph rather than an actual empty value.

### ISSUE THREAD

**Issue by chrisdpratt** [ckeditor/ckeditor5#842]
## 🐞 Is this a bug report or feature request? (choose one)

Bug report

## 💻 Version of CKEditor

CKEditor 5 (1.0.0-alpha.2) Classic Editor

## 📋 Steps to reproduce

1. Attach CKEditor to empty `textarea`
2. Submit form.

## ✅ Expected result

When submitting the form, posted value of `textarea` should be empty.

## ❎ Actual result

Posted value is `<p>&nbsp;</p>`.

**Comment by Reinmar** [comment]
It's part of https://github.com/ckeditor/ckeditor5/issues/401.

During editing, empty editor == `<p>&nbsp;</p>`, that's why `getData()` returns such thing right now. However, it's totally understandable that people would expect an empty HTML string to be saved in their DBs.

This issue was discussed already in https://github.com/ckeditor/ckeditor5/issues/401 and let's continue there.

**Comment by chrisdpratt** [comment]
Sorry. I searched, but didn't find that issue. Thanks.

**Comment by Reinmar** [comment]
No problem. You'd need to be lucky to find #401 ;)
