### ISSUE TITLE
Unable to use ckeditor5 in React Micro frontend architecture

### ISSUE THREAD

**Issue by andremoah** [ckeditor/ckeditor5#8463]
## 📝 Provide detailed reproduction steps (if any)
Currently, I have a very large and complex frontend application that was split into multiple Micro Frontends. CKeditor works perfectly in any of those applications if published stand-alone, but when trying to integrate them together the below error occurs:

https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

As a simple example with only 2 Micro Applications running together:

1. Micro Application 1 editor works
2. Micro Application 2 editor gives an error making the full application not render

### ✔️ Expected result

All editors to be working in both Micro Applications.

### ❌ Actual result

Only the first Micro Application works, because the second one trows duplicated modules error.

## 📃 Other details

* CKEditor version: 5
* Installed CKEditor plugins: Alignment, Heading, BulletedList, Bold, AutoSave, Image, FontSize, FontFamily,  FontColor, HighLight, Image.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! I don't know how your project is structured, however, the duplicated modules error might occur if you for example: 

*   Try to create multiple different editor types on the single page (that's why we created a [superbuild concept](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds))
*   Have outdated packages and you've installed a new plugin from npm which is on the latest version (all CKEditor 5 packages should be on the same version)
*   Try to add a plugin directly to the build, i.e. import a build, then import a plugin and add it to the plugins array (you can read more about it in our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)).

I recommend checking the above and see whether one of the issues could be recognized in your project.
