### ISSUE TITLE
A single paragraph is not centred in the editor

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#847]
CKEditor doesn't set the typography of its content but I remember that some time ago it was ok – a single paragraph was well centred (vertically) within an editable. Why did it change?

![image](https://user-images.githubusercontent.com/156149/36217449-be50bd72-11b1-11e8-9afd-be1dfbde2d62.png)

**Comment by oleq** [comment]
It's an aftermath of https://github.com/ckeditor/ckeditor5-theme-lark/commit/d717139d061217ceee85fe6f745cb978ea2d1186. Because there are situations where the paragraphs have no top margin (like [nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html)), we simply hardcoded it for the first `p` because by default editable has no vertical padding. 

TBH, I'm not sure how to deal with that...

**Comment by Reinmar** [comment]
Can't we add the same CSS rule for the last child?

**Comment by oleq** [comment]
You mean some symmetrical bottom margin of the last child to that top margin of the first child?

**Comment by Reinmar** [comment]
This, to be precise: 

css```
 +	& > *:last-child {
 +		margin-bottom: var(--ck-spacing-standard);
 +	}
```
