### ISSUE TITLE
Custom Build load error

### ISSUE THREAD

**Issue by accorinti** [ckeditor/ckeditor5#8496]
Editor doesn't show.
[ckeditor5.zip](https://github.com/ckeditor/ckeditor5/files/5577442/ckeditor5.zip)

This is the console.log from the sample/index.html file of my custom build

Oops, something went wrong! 
Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:
CKEditorError: t.config[_0x1c3b(...)](...) is undefined
    m ckeditor.js:5
    <anonymous> ckeditor.js:5
    o ckeditor.js:5
    fire ckeditor.js:5
    init ckeditor.js:5
    create ckeditor.js:5

Uncaught CKEditorError: invalid-license-key
    o ckeditor.js:5
    s ckeditor.js:5

## 📃 Other details

* Browser: Firefox latest …
* OS: WIN 10
* CKEditor 5

NOTE: Using the CDN version works perfectly.
<script src="https://cdn.ckeditor.com/ckeditor5/23.1.0/decoupled-document/ckeditor.js"></script>

Attached the custom build downloaded zip file

**Comment by Mgsy** [comment]
Hi! Your build contains the pagination plugin which is our commercial feature and requires providing a license key. Additionally, it requires a configuration, without [providing a proper config](https://github.com/ckeditor/ckeditor5/issues/8238), the error will occur. We'll be working on this issue here. I encourage you to take a look at out [pagination plugin documentatio](https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html)n to learn more and start a free trial to see it in action!

**Comment by YagorlitskiyVyacheslav** [comment]
> Hi! Your build contains the pagination plugin which is our commercial feature and requires providing a license key. Additionally, it requires a configuration, without [providing a proper config](https://github.com/ckeditor/ckeditor5/issues/8238), the error will occur. We'll be working on this issue here. I encourage you to take a look at out [pagination plugin documentatio](https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html)n to learn more and start a free trial to see it in action!

why does it require a license key for me? I don't use your commercial feature, but it still needs a key.
[ckeditor5-32.0.0-mot9g3803wv2.zip](https://github.com/ckeditor/ckeditor5/files/8015876/ckeditor5-32.0.0-mot9g3803wv2.zip)
