### ISSUE TITLE
Setting attribute in editingDowncast or getting parent element before creating element

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5#8515]
I need to apply attribute `proporcja` to element based on parent element. Down there is my code.
Problem is that this attribute is not handled by `upcast` and `dataDowncast` - it is gone.
I have it as `allowAttributes: ['path', 'proporcja']`

```
conversion.for('editingDowncast').elementToElement({
            model: 'imagePathPreview',
            view: (modelElement, {writer: viewWriter}) => {
                const path = modelElement.getAttribute('path');
                let proporcja = '';
                if (modelElement && modelElement.parent && modelElement.parent.name == 'bsKolumna') {
                    proporcja = 'pionowo';
                }

                const section = viewWriter.createContainerElement('figure', {
                    class: 'media',
                    // 'data-id': id
                });

                const attrs = {
                    class: 'zdjecie-placeholder'
                };
                if (path) {
                    attrs['data-path'] = path;
                }
                if (proporcja) {
                    attrs['data-proporcja'] = proporcja;
                }
                const reactWrapper = viewWriter.createRawElement('div', attrs, function (domElement) {
                    ImagePathRenderer(path, domElement);
                });

                viewWriter.insert(viewWriter.createPositionAt(section, 0), reactWrapper);

                return toWidget(section, viewWriter, {label: 'Podgląd zdjęcia'});
            }
```

I think that this attribute has to be created in 
```
execute(path) {
        this.editor.model.change(writer => {
            this.editor.model.insertContent(writer.createElement('imagePathPreview', {path}));
        });
    }
```
But I cannot do that because It is dependent on parent element.
I don't know how to get parent element before creating `imagePathPreview`.
I tried also in `editingDowncast` `modelElement.setAttribute('proporcja', proporcja)` but that method does not exists.

How to do it?

**EDIT**: I was able to do it using `private` method `modelElement._setAttribute('proporcja', proporcja)`.
Maybe it should be public?

**Comment by Reinmar** [comment]
> I don't know how to get parent element before creating `imagePathPreview`.

There are three options:

* You can set the attribute *after* inserting the element with the standard `writer.setAttribute()` call. However, to make this work, you'll need to change your downcast converter so the attribute is converted separately. Note that elements and attributes are converted granularly. It is possible to handle element's attributes when converting that element, but usually you'll also want to write attribute converters *in order to handle attribute changes*.
* The other option is to get the attribute of the parent element from the model's structure before creating this `imagePathPreview` element. However, IDK exactly how does the logic of this command work, so which element you want to check. But in general, you should be going throug what `editor.model.document.selection` offers. E.g. `editor.model.document.selection.anchor` will give you the element in which the start of the selection is located. However, if the selection is not empty, you may want to check something like `editor.model.document.selection.getFirstRange().getCommonAncestor()`. 
* The third option is not to set this attribute on this inner element. Because, if it's always read from the parent element, then you can read it while downcasting the inner element. After all, you have the `modelElement` available there and can check the parent.

Sorry for the late answer and I hope this will help :)
