### ISSUE TITLE
Unable to fetch the current cursor position for CKEditor5 using custom build, giving error  Uncaught TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by DineshAmzur** [ckeditor/ckeditor5#8555]
![image](https://user-images.githubusercontent.com/43564720/100704775-0e3a9f80-33cc-11eb-876b-ce37db702b67.png)

**Comment by xinglie** [comment]
try follow code
```js
EditorFactory.create({
  //your configs
}).then(editor=>{
    console.log(editor.model.document.selection.focus);//model position
    console.log(editor.editing.view.document.selection.focus);//editing position
});
```

for more information you can read model document selection api: https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_documentselection-DocumentSelection.html

and view document selection api: https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_documentselection-DocumentSelection.html

**Comment by Reinmar** [comment]
The snippet you posted works fine e.g. in https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html so that's not due to the editor. Maybe there's something wrong with your editor factory?

![](https://user-images.githubusercontent.com/156149/101328843-da9ac200-3870-11eb-9662-71e6e3645d7a.png)
