### ISSUE TITLE
Link's href isn't aligned vertically in the first link balloon 

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#857]
![image](https://user-images.githubusercontent.com/156149/36306682-308b67da-1319-11e8-8859-af1dc8ec368b.png)

**Comment by dkonopka** [comment]
It's known issue related to https://github.com/ckeditor/ckeditor5-theme-lark/issues/145. Chrome has the problem with rendering. 

Because we can't fix it easily (I guess we tried everything), we should really start thinking about change `display: inline-block` to `flex / inline-flex`. 

![screen shot 2018-02-16 at 15 46 22](https://user-images.githubusercontent.com/10219857/36313002-99848412-1330-11e8-8354-fb0ecf294a64.png)

**Comment by dkonopka** [comment]
Anyway, can you reproduce this issue ATM? Same height of red rectangles here on screenshot:

![link-vertical](https://user-images.githubusercontent.com/10219857/36589643-4f2be304-188c-11e8-8a9d-dcb63b1efaa7.png)

**Comment by Reinmar** [comment]
It's not ideal, but it's better now. The only thing which still looks bad is the link color. It's (I think) the default blue color of links.
