### ISSUE TITLE
Is a full toolbar build available for CKEditor 5? -----   QUESTION

### ISSUE THREAD

**Issue by RudyFiero** [ckeditor/ckeditor5#860]
## 🐞 Is this a bug report or feature request? (choose one)

- Feature request

## 💻 Version of CKEditor 5

Is there a Classic editor full package build with a full toolbar? (as with CKEditor 4) Or is there any simple documentation to show how to enable the full toolbar?

**Comment by Reinmar** [comment]
Hi! There's no full build of CKEditor 5 and we won't provide such. Even CKEditor 4's "full" build isn't really full because it doesn't make sense due to its size and conflicting plugins. CKEditor 5 will only provide more "semantical" builds, designed to match as closely as possible certain use cases.

So, if you want more feature, you need to [customise one of the existing builds](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html). Besides, we don't have that many features yet so the default builds showcase 95% of them. This will change with the upcoming release when we'll add font size, font family, text highlight and text alignment features. But they will be also provided in a new build called "document editor".

**Comment by HiradNikoo** [comment]
@Reinmar Isn't it weird that text alignment plugin is not part of classic build as default? And I should customize the build?
