### ISSUE TITLE
Inline images - UX design

### ISSUE THREAD

**Issue by pkwasnik** [ckeditor/ckeditor5#8657]
Create a design of a button(s) to switch the image state between inline and block

1. Most likely two buttons to switch the state
2. Hard to differentiate these buttons visually from the alignment icons
3. May require changing current alignment icons
4. We can consider introducing just one icon with an on/off state (e.g. an "inline image" icon) – introducing just one icon may be simpler than two
5. How to name the switch button(s) ? Can't use "inline" or "block". Check out other document editors. "Text wrapping" seems to be the term.

**Comment by oleq** [comment]
Some idea:

![](https://user-images.githubusercontent.com/1099479/104038713-be72a380-51d5-11eb-82d8-18a98d7a146f.png)

**Comment by magda-chrzescian** [comment]
I also wanted to share some thoughts.  
  
1\. In my opinion, the inline and block icons aren't semantic enough. The user doesn't care what plugin serves the image, he wants to see how it's going to interact with the rest of the editor content. In the example above, he doesn't really know how to display the image with wrapped text. I would go with:

\- "in line",   
\- "in paragraph" and   
\- "between paragraphs", 

where "in paragraph" would convert the image into the inline mode with the float.  
  
2\. As we discussed with @oleq, the alignment options should vary depending on the current state of the image.  
  
3\. The caption issue. In my opinion pretty problematic and pretty important. Again, for the user, there is no relation between image display mode and the caption. How do we explain to him that only the image placed between paragraphs can be captioned? An icon? Is it technically possible to add a caption to the inline image with the float in the future?  
  
The image below is not a design:

![](https://user-images.githubusercontent.com/14334820/104160699-d7f03700-53f1-11eb-9d93-19b6b1803235.png)

**Comment by Reinmar** [comment]
Just one requirement to keep in mind regarding the icons used for alignment options: We need to remember that sometimes this feature will be loaded with only the block mode or only the inline mode available, hence, without the button(s) to switch the inline<->block mode. Therefore, the alignment buttons need to stay understanble in this context.

And one more – the alignment buttons are also used for media and potentially for tables, html embeds, etc.

**Comment by pkwasnik** [comment]
1\. Naming inline as \`in paragraph\` sounds good to me.  
3\. In the future captions for inline images could be visible "on hover" and "on click" which activates the widget.

@oleq How align of inline images should work? The same as a block, or by moving an image to the beginning/end of a paragraph? (the first option will duplicate things, the second doesn't make sense to me).

If we decide that aligning always uses block images, then we could avoid the block/inline switch which could be confusing. So from the user perspective, there will be four IMO reasonable states:

*   center (block center)
*   left/right (block left/right, text around)
*   inline

![](https://user-images.githubusercontent.com/16957311/104311272-393d0680-54d5-11eb-802f-598bdea1417c.png)

It corresponds with the states from the picture pasted by @magda, except the type of image that we will be used for alignment.

**Comment by magda-chrzescian** [comment]
Here is a summary of the behaviors of images we are dealing with, so we're on the same page with this.

**1\. Inline with left/right alignment**

![](https://user-images.githubusercontent.com/14334820/104453399-a7043380-55a4-11eb-9db3-038d2176be22.png)

**2\. Inline with "none" alignment**

![](https://user-images.githubusercontent.com/14334820/104453524-d9159580-55a4-11eb-9be0-1a1a0e679cf0.png)

**3\. Block with center alignment**

![](https://user-images.githubusercontent.com/14334820/104453585-f0ed1980-55a4-11eb-8cb1-fe4ca40524b2.png)

**4\. Block with left/right alignment**

![](https://user-images.githubusercontent.com/14334820/104453649-06624380-55a5-11eb-8d1b-92dfe6d1f357.png)

  
As far as I understand, we can't ommit any of those, at least at the initial conversion level. The question is if each of them will be achievable with the interface (especially the left/right alignment with block AND inline modes).  
  
As @pkwasnik said, using blocks for right/left alignments would simplify the interface, but the image couldn't be placed inside a paragraph (1). What would we do with the existing content when the user has an image inside the paragraph aligned to the left and he wants to align it to the right - are we going to convert it to block and break the paragraph? If not, how can he force it to add a caption for this image?

**Comment by magda-chrzescian** [comment]
Since the previous solution I proposed assumes that both inline and block images can have captions, I came with some other option. It assumes that, in opposition to the [diagram](https://github.com/ckeditor/ckeditor5/issues/8831), no inline-block conversion would be made while changing the alignment, so every display mode transition is transparent to the user and he can consciously decide if he wants the image inside or outside the paragraph.

Thanks to the extended title and disabled state on the caption button, he would be aware of what happens to the caption whaen he moves his image into the paragraph.

![image](https://user-images.githubusercontent.com/14334820/104705267-fd46b300-5719-11eb-81a7-1a8a202957d4.png)

_*Probably the alignment should be put in the dropdown_

**Comment by oleq** [comment]
> The alternative is to allow the caption in the 'in paragraph' mode and to break the paragraph when the caption is being added.

How would the user add the caption? I mean, physically, since in this scenario there would be no option to render the caption under the inline ("in paragraph") image?

**Comment by magda-chrzescian** [comment]
The caption button would have to be enabled. Maybe the title should be changed to "will break the paragraph" or something like that. And then the first step after the user clicks the caption button is to break the paragraph, then convert the image to block, then add the caption. Does it make sense?

**Comment by magda-chrzescian** [comment]
#### I updated the previous design based on our last conversation (all of the buttons are always enabled):

![image](https://user-images.githubusercontent.com/14334820/104900213-1c447f80-597c-11eb-8e32-1f230927a10e.png)

#### To consider:
* The UI for managing the alignment,
* The feedback for the user about an action leading to:
  * hiding a caption (block -> inline conversion)
  * breaking a paragraph (inline -> block conversion inside the paragraph)
(The warning BEFORE and/or AFTER taking an action should be considered.)

**Comment by magda-chrzescian** [comment]
# UI for aligning the images

## Context and Problem Statement

A new UI has to designed for the image alignment since the previous alignment icons are going to be used as display type buttons.

## Decision Drivers 

* The icons need to cover the following alignments:
  * left (inline or block images),
  * right (inline or block images),
  * center (block images),
  * full-width (block images)
_I'm not sure what's the difference between the center and the full-width alignments._
* The alignment buttons are also used for media and potentially for tables, html embeds, etc.
* The icons should be also understandable if only the inline or block image mode is enabled.
* As few clicks as possible have to be made to achieve a desirable layout.

## Considered Options - Pros and Cons of the Options 

### 1. Separate button for each alignment in image toolbar:
![image](https://user-images.githubusercontent.com/14334820/105032519-27b8a900-5a57-11eb-93b0-a4ea48cf8dbc.png)
In this approach, the available alignment buttons shown in the toolbar are depending on the display mode. 

👍 All of the icons are easily distinguishable.
👍 We do not suggest the text wrapping behavior in the alignment icons, which is correct, because we can't always predict it.
👍 The alignment icons can be used for other widgets.
👍 The default alignments are set automatically when the user selects the display mode, so the most commonly used layouts are achievable with only one click. Changing the alignment also requires only one click.
👍 Looks good and is useful also when only inline or block mode is available (alignment icons look as on the design, the rest of the icons are hidden).

❌ The image toolbar can get really big (potential solution to wrap the icons?).
❌ The content of the alignment menu section is changing along with the selected display mode.
  -We need to render it.
  -The user is aware of some possible alignments only after he selects a certain display mode.

❌ The previous alignment icons change their function, which can be confusing for experienced users. 

### 2. Alignment buttons available as a drop-down under the display mode button

![image](https://user-images.githubusercontent.com/14334820/105034851-61d77a00-5a5a-11eb-8204-711ce2840f71.png)

👍 The image toolbar gets really small and neat.
👍 The behavior of the icons can be easier to understand for experienced users - we still select the alignment with the same icons, only the options are arranged differently.

❌ Needs an additional implementation of the toolbar if the given widget has only block mode enabled/available (or there will be only a single drop-down for selecting the alignment instead of a few icons).
❌ Some icons would represent a very similar layout, it can be confusing (e.g. the state from the attached picture, when 'between paragraph' display mode is selected and the alignment is set to the left - it looks almost like the 'in paragraph' display mode).
❌ The user always needs to click twice to set anything - the first time to expand the drop-down and the second time to select the alignment.

**Comment by magda-chrzescian** [comment]
## The menu state for block image with `display: block` and `alignment: left/right`

### Current proposition:

![](https://user-images.githubusercontent.com/14334820/105459349-64b8b180-5c8a-11eb-9ca5-f3cec1a9581c.png)

#### Problem: The visual state of the image is different than the state shown in the toolbar.

---

### New proposition:

I analyzed once more the solution proposed by @niegowski, to display the following menu state if the image has `type: block` and `alignment: left/right.` It would be consistent with the visible state of the image.

![](https://user-images.githubusercontent.com/14334820/105458926-adbc3600-5c89-11eb-86a8-d6ef72626ea8.png)

**The problem that we recognized is that this state would be the same for `type: inline` and `alignment: left/right`.**

#### Doubts:

1.  How to convert the image to the inline image?
2.  How to unify the behavior of the inline and block images in the considered state? It has to be consistent because the user won't be aware of the difference.

#### Answers:

1.  Do we really need to do this? Let's consider the following case:

<table><tbody><tr><td>The current state</td><td>The desired state</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/14334820/105460500-2b814100-5c8c-11eb-836f-89ed22a4cca4.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/14334820/105461340-5fa93180-5c8d-11eb-9c9a-7f488f842093.png"></figure></td></tr></tbody></table>

To achieve this in Word we need to drag and drop the image or paste it in the middle of the text. Both of these behaviors we can support in CKE5 and there is no need to convert the image to inline. There are no benefits from inline images other than wrapping with text, which is useful only in the content of the paragraph. The image has to be placed there somehow anyway, so the block->inline conversion would occur while pasting/dragging.

   2. Consistency of the behavior

*   Pasting and dragging are ok because we decided not to break the paragraph while pasting the block image.
*   The backspace button at the beginning of the paragraph is also ok (it selects the image) - no change from current behavior.

---

### Conclusion:

There is no need to go with the drop-downs, since we can achieve the consistency between the image behavior and menu state with the regular buttons.

**Comment by magda-chrzescian** [comment]
## Preview of the alignment buttons vs the drop-downs

![](https://user-images.githubusercontent.com/14334820/105484188-3b5c4d80-5cab-11eb-8eee-d38bb22a0fca.png)

---

![](https://user-images.githubusercontent.com/14334820/105484238-4dd68700-5cab-11eb-912f-e4462b221db8.png)

**Comment by AnnaTomanek** [comment]
The design seems to be done so can we close this issue?
