### ISSUE TITLE
Editing a link logs the rect-source-not-in-dom warning

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#867]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

master

## 📋 Steps to reproduce

1. Create a link
2. Edit it
3. `rect-source-not-in-dom` is logged

## 📃 Other details that might be useful

![feb-26-2018 16-46-11](https://user-images.githubusercontent.com/156149/36679916-b9b05c52-1b14-11e8-8651-87d159bb65da.gif)

**Comment by Reinmar** [comment]
cc @Mgsy did you report it maybe?

**Comment by Mgsy** [comment]
> cc @Mgsy did you report it maybe?

I haven't reported it. I think it has started to occur not long ago.

**Comment by oleq** [comment]
Probably some balloon positioning mechanism kicks in after the balloon is hidden. Such mechanisms depend on the `Rect` class, which throws an error because there's no way to use the native `getBoundingClientRect` if a Node is not actually rendered anywhere. 

I'd check when the `LinkUI._hideUI` and `_removeFormView` are called first. My gut tells me that since this does **not** happen when the link has **not** been changed (at least I couldn't reproduce it in that scenario) it is linked to the editing view re-rendering the `<a>` upon href change. The UI tries to position the balloon with respect to the old view (DOM) element, while it has already been replaced by some new one.

Deferring the UI repositioning could be the easiest solution.

**Comment by Mgsy** [comment]
This issue isn't reproducible anymore.
