### ISSUE TITLE
Custom Build load error 

### ISSUE THREAD

**Issue by BarnameESF** [ckeditor/ckeditor5#8681]
Editor doesn't show.
ckeditor 5 Custom Build 

This is the console.log from the sample/index.html file of my custom build

Oops, something went wrong! index.html:213:12
Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace: index.html:214:12
Build id: o6e65dxi2b7n-i9u6xmcpw1yx index.html:215:12
Cross site scripting is only allowed for HTTP.

## 📃 Other details

* Browser: Firefox 84
* OS: win10
* CKEditor version: 5
* Build id: o6e65dxi2b7n-i9u6xmcpw1yx
* Installed CKEditor plugins: 'heading', 'fontFamily', 'fontSize', 'fontColor', 'fontBackgroundColor', 'removeFormat', 'highlight', 'bold', 'italic', 'underline', 'strikethrough', 'horizontalLine', 'bulletedList', 'todoList', 'numberedList', 'indent', 'outdent', 'alignment', 'link', 'imageInsert', 'imageUpload', 'blockQuote', 'insertTable', 'mediaEmbed', 'undo', 'redo', 'code', 'codeBlock', 'comment', 'MathType', 'ChemType', 'specialCharacters', 'restrictedEditingException', 'CKFinder', 'trackChanges', 'exportWord', 'exportPdf', 'htmlEmbed', 'imageTextAlternative', 'imageStyle:full', 'imageStyle:side', 'linkImage', 'tableColumn', 'tableRow', 'mergeTableCells', 'tableCellProperties', 'tableProperties'

**Comment by LukaszGudel** [comment]
Hi @BarnameESF, I’m guessing that you are opening sample/index.html as a file in the browser? Some of the plugins used in your build needs http server in order to work properly. Try to use some kind of local webserver to test if this was the issue. I can recommend live server plugins available for VSC or atom. Please, let me know if this fixes your issue.
