### ISSUE TITLE
Mathtype plugin trying to import in Ckeditor5 in vuejs.

### ISSUE THREAD

**Issue by development0261** [ckeditor/ckeditor5#8709]
## 📝 Provide detailed reproduction steps (if any)
1.Project created in Vue2 or Vue3.
2. Import Ckeditor 4 and 5 in both vue versions.
3. Now I want use wiris-mathtype plugin in Ckeditor 4 or 5.
4. In bothe version I face the same issues.
5. I have follow the article. -> https://ckeditor.com/docs/ckeditor5/latest/features/math-equations.html

### ✔️ Expected result

_What is the expected result of the above steps?_
https://prnt.sc/w6wido

### ❌ Actual result
_What is the actual result of the above steps?_
https://prnt.sc/w6wkct

## 📃 Other details

* Browser: All
* CKEditor version: 5
* Installed CKEditor plugins: npm install --save @wiris/mathtype-ckeditor5

Issue: Uncaught CKEditorError: ckeditor-duplicated-modules
---
If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by LukaszGudel** [comment]
Hello, encountered error suggests that there is a problem with importing packages. When adding additional plugins to the editor I can suggest using [CKEditor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v3.html#using-ckeditor-from-source) approach. First, follow this guide to run the editor with basic plugins, then you can add additional plugins like MathType using installation instructions from [this article](https://ckeditor.com/docs/ckeditor5/latest/features/math-equations.html#installation).  

There is one more step needed when adding MathType to vue.js. Webpack configuration provided in the guide above can cause issues with .svg imports. You can read more about this here: #2048. This issue will be fixed by #8114 but for now you can manually edit webpack configuration. [This gist](https://gist.github.com/LukaszGudel/b61036ed8053ffe2238f8d560d2b9651) should make it possible to run correctly. 

Side note: `yarn serve` will not reload automatically after saving webpack config file and you need to rerun this command.

Please, let me know if you successfully add MathType to your Vue project. If you still have issues with this you can add your editor configuration here.

**Comment by LukaszGudel** [comment]
Hello, encountered error suggests that there is a problem with importing packages. When adding additional plugins to the editor I can suggest using [CKEditor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v3.html#using-ckeditor-from-source) approach. First, follow this guide to run the editor with basic plugins, then you can add additional plugins like MathType using installation instructions from [this article](https://ckeditor.com/docs/ckeditor5/latest/features/math-equations.html#installation).  

There is one more step needed when adding MathType to vue.js. Webpack configuration provided in the guide above can cause issues with .svg imports. You can read more about this here: #2048. This issue will be fixed by #8114 but for now you can manually edit webpack configuration. [This gist](https://gist.github.com/LukaszGudel/b61036ed8053ffe2238f8d560d2b9651) should make it possible to run correctly. 

Side note: `yarn serve` will not reload automatically after saving webpack config file and you need to rerun this command.

Please, let me know if you successfully add MathType to your Vue project. If you still have issues with this you can add your editor configuration here.
