### ISSUE TITLE
[Docs] Update animated GIFs and videos

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#872]
A follow-up of https://github.com/ckeditor/ckeditor5/issues/869.

I skipped GIFs and videos in #869 because updating them would consume a lot of time. It does not mean we will not update them in the future, though.

**Comment by mlewand** [comment]
@oleq could you check if this issue is still a thing? I briefly checked couple of cases:

* https://ckeditor.com/docs/ckeditor5/latest/builds/guides/whats-new.html - gif in "Simple linking" section looks pretty much similar to me
* https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html - the not sure if buttons look fine here though

**Comment by oleq** [comment]
Nothing was updated. Some videos and GIFs still present the editor with its (long outdated) beta UI and very few features.

**Comment by Reinmar** [comment]
Both guides – What's new and Quick start have to be severely rewritten right now, so there's no point in updating the GIFs inside them right now. 

Let's close this issue and have separate issues for both guides.

**Comment by Reinmar** [comment]
Here they are: https://github.com/ckeditor/ckeditor5/issues/958 and https://github.com/ckeditor/ckeditor5/issues/1998.
