### ISSUE TITLE
Performance is degraded when the editor has a lot of content 

### ISSUE THREAD

**Issue by marcellofuschi** [ckeditor/ckeditor5#8730]
Hi. I've been experiencing some lag in the editor's content modification when there's a lot of content in it. You can experience it also with the [official CKEditor demo](https://ckeditor.com/ckeditor-5/demo/).

My use case is scientific articles editing. Those can, unfortunately, be quite long. [Here is a sample](https://github.com/ckeditor/ckeditor5/files/5751463/sample.docx) (if you paste it into the CKEditor demo, you should be able to notice the lag when you edit).

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It seems like this problem is already being tracked [here](https://github.com/ckeditor/ckeditor5/issues/8054). Recently we've merged some performance fixes into the latest `master` and if everything goes ok, there's a chance this one will be closed in the next release too.  
  
Meanwhile, I'll close this ticket as a duplicate.

**Comment by marcellofuschi** [comment]
If I understand correctly, the issue you linked only has to do with the freezing when pasting a lot of content. The problem I am experiencing, on the other hand, is when you try to edit and the editor already has a lot of content (independently of how or when the content was inserted). You aren't able to edit smoothly because of the lag that any of your actions causes.

**Comment by FilipTokarski** [comment]
Sorry, I could have been more explicit in my previous comment. The merged fix that I mentioned was addressing [this issue](https://github.com/ckeditor/ckeditor5/issues/8188) - I believe this will apply also to your use case.
