### ISSUE TITLE
An error was encountered using mathype

### ISSUE THREAD

**Issue by jiashitao** [ckeditor/ckeditor5#8754]
Use CKEditor 5 online editor builder .
Choose editor type：Decoupled Document
Choose editor plugins：MathType
Choose toolbar items：Mathtype,ChemType
Choose the default editor language：English
Then build mycustom CKEditor 5 build and download.
Open the index.html with my Chrome browser and An error was encountered.
who know what happend,please tell me.thank you
<img width="622" alt="批注 2021-01-07 004220" src="https://user-images.githubusercontent.com/33249979/103795793-62970600-5081-11eb-98d8-957fdb9561b4.png">
<img width="919" alt="批注 2021-01-07 004327" src="https://user-images.githubusercontent.com/33249979/103795800-6460c980-5081-11eb-8b85-0a93d08953ea.png">

**Comment by LukaszGudel** [comment]
<table><tbody><tr><td>Hello, I’m can see that you are opening sample/index.html as a file in the browser. Some of the plugins used in your build needs http server in order to work properly. Try to use some kind of local webserver to test if this was the issue. I can recommend live server plugins available for VSC or atom. Please, let me know if this fixes your issue.</td></tr></tbody></table>
