### ISSUE TITLE
Integrate inline images with image styles

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#8775]

**Comment by oleq** [comment]
I realised styles such as `imageStyle:alignCenter` or `imageStyle:full` do not make sense with inline images. We'll need two different configurations for inline and block and the UI will need to adapt on-the-fly and present only those styles matching the image type.

**Comment by magda-chrzescian** [comment]
I encountered a problem worth mentioning while implementing this functionality.

Since we need a wrapper for the inline mages, the image style class needs to be set on the `<span>` element instead of the `<img>`. It will cause some inconsistency between the editor view and the HTML output, where is no wrapper element at all and the class is applied to the `<img>` element directly.

It shouldn't cause any catastrophic consequences. Two really edge cases come to mind:

*   The behavior of the content added with the `::after` pseudoselector, which will work only on the `<span>` element.
*   If someone will try to override the outline that we apply on the widget - which is unlikely since the same effect is easily achievable with the border property.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/8991.
