### ISSUE TITLE
Pasted mentions get dirty

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5#8792]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the [Mentions feature page in the documentation](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html).
2.  Go to the last editor in the page. It is the one that can be accessed with `editor` in the console.
3.  Remove the editor contents.
4.  Type "Foo @Ted" (with uppercase "T").
5.  In the console, execute `editor.data.model.document.getRoot().getChild( 0 ).getChild( 1 ).getAttribute( 'mention' )`. This should output the value of the mention attribute set to the "@Ted" text node as a simple object.
6.  Select all and cut.
7.  Paste.
8.  Repeat step 5.

### ✔️ Expected result

The output in the console on step 8 (after pasting) should be a simple object similar to the one in step 5 (after typing).

### ❌ Actual result

The output of step 8 is a complex object similar to [UpcastConversionApi](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_upcastdispatcher-UpcastConversionApi.html#function-updateConversionResult).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
This is fixed on master already. 

This is from the current public release:

![image](https://user-images.githubusercontent.com/156149/104160811-0a019900-53f2-11eb-82e0-c7f7e4ff1496.png)

This on nightly docs:

![image](https://user-images.githubusercontent.com/156149/104160973-4fbe6180-53f2-11eb-933f-152f557d3538.png)

So, you could check whether this issue is reproducible in GH Writer when using `ckeditor5@master`.
