### ISSUE TITLE
Move all env variables from .travis.yml to Travis web interface

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#886]
I don't know why we decided to put BrowserStack's vars in `.travis.yml`. Perhaps it was meant to save us time, because that meant everyone can set them. But it turns out that all of us can set them on https://travis-ci.org so it'll be easier to have them there. Currently, setting up a new repo is more timeconsuming due to the fact that some things can only be set in `.travis.yml`.

Also, when moving these vars, let's remove all Codeclimate tokens.

**Comment by pomek** [comment]
TBH I don't see any reason why you would move all variables from dedicated config to Web interface.

If all env variables are in `.travis.yml` you can modify those by calling a node script and using mrgit. Otherwise, you need to open 50+ tabs and copy and paste everything step by step. Not to mention that you can copy/paste wrong values.

Also, if they are defined in the config file, they can keep different values for different branches (if needed). Not possible in Web interface configuration.

In both cases, those variables are encrypted and safe no matter where they are defined. Also, they're **visible** in build log even if they are saved using Web interface.

And the last thing (personal) – I am the one person who modifies those values and managing all of them. Why do you want to make my job harder? :D

**Comment by Reinmar** [comment]
> Why do you want to make my job harder? :D

Sorry :) I didn't mean that. I was just curious and apparently didn't know how it works. So, if you prefer `.travis.yml` then I'm closing this ticket as invalid.
