### ISSUE TITLE
Research for potential uses of the toast feature.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#8935]
## Provide a description of the task

We need to summarize the issues that can be solved with the toast feature (#8934) to make the decision if it is justified to devote our time to implement this functionality.

![Image for post](https://miro.medium.com/max/3400/1*R4lNMpEdY0VOD96MtkLx4g@2x.png)

**Comment by magda-chrzescian** [comment]
Here is what I found:

*   The user pastes the content from Word and some of the images aren't rendering. (#2493)
*   The user adds a caption on inline image inside the paragraph and the paragraph gets split into two. (The toast should provide proper information and an undo action).
*   The user pastes the block image with caption into the paragraph and the caption is being removed. (The toast should provide proper information and action to break the paragraph instead of removing the caption).
*   The user pastes a table into an image caption and nothing happens.

I think that toasts should also be used for handling all the runtime errors that have an effect visible to the user, especially for asynchronous actions like downloading a PDF file. E.g. there is an issue in the internal repo where the user clicks the download PDF button and nothing happens (in certain circumstances).

**Comment by Reinmar** [comment]
Some context:

* There's a base class for this: https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_notification_notification-Notification.html but it has no visual presentation (UI) – it's just a common API for showing notifications. I think it's triggering native alerts at the moment.
* This is a bit of a UI that might often need to be adjusted by the integrator (but that's allowed by the `Notification` plugin).
* CKEditor 4 and Letters (CKE5 based) have their complete implementations (base API + UI).
* AFAIR, we didn't decide to have a complete implementation for CKE5 for now due to challenges that it brings.
I think these were mostly related to the number of editor types and floating things. But it may be high time to tackle this down.

**Comment by Reinmar** [comment]
And right after posting my comment, I realized that you only want to research the use cases in this ticket :D Sorry for an off-topic.

**Comment by niegowski** [comment]
Other cases: 

*   Image upload failed.
*   Error while generating PDF/Word document.
*   CKFinder error.

In general, I would check for usages of the `Notification` plugin. But there are for sure cases like pasting some content that is not allowed in a specified position.

**Comment by magda-chrzescian** [comment]
I'm going to close this one since this was only research. The decision should be made in #8934.
