### ISSUE TITLE
CKEditor 5 missed the CkEditor 4 feature. on right click it don't show numbered list property 

### ISSUE THREAD

**Issue by raoshahid799** [ckeditor/ckeditor5#8957]
hello 
      can we change numbered list starting number like we can change in ckeditor 5 see in image

![image](https://user-images.githubusercontent.com/13733062/106293393-c7ecaa00-626f-11eb-9e2d-07cde142f054.png)

**Comment by Mgsy** [comment]
Hi, thanks for the report. CKEditor 5 is a different product than CKEditor 4, with different architecture, plugins set and it doesn't implement context menus, that's why you can't open. 

As it comes to changing list numbering, this feature is unavailable, however, we have an [open feature request](https://github.com/ckeditor/ckeditor5/issues/1032) for it, so feel free to add :+1: to the first post to bump its popularity.

**Comment by crest-daksh** [comment]
I am working with ckEditor and I want to show custom context menu when user's selects the text in the ckEdtior , and in that context menu I want to show one option where user can refactor the selected text. Is it possible to do this in CKEditor5 ?
