### ISSUE TITLE
missing dependency in the "Implementing a block widget" doc

### ISSUE THREAD

**Issue by theOtherNir** [ckeditor/ckeditor5#9013]
## missing dependency in the "Implementing a block widget" doc

in the "npm install .." section need to add package "@ckeditor/ckeditor5-widget"
without it the example does not work.

edit: link to the document :
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html#demo

**Comment by AnnaTomanek** [comment]
@ckeditor/qa-team Can you check this, please?

**Comment by LukaszGudel** [comment]
Hi, it looks like everything is correct in this guide. When you follow this guide step by step then somewhere in the middle it asks to install this package by running command: `npm install --save @ckeditor/ckeditor5-widget`. Details here: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html#making-simple-box-a-widget

What's more, running the first `npm install --save \ ...` command from this guide will already install widget package, because even if we do not install it directly there, it is used as a subdependency in [theme-lark package](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-theme-lark/package.json), and thus it will be already installed.

@theOtherNir Could you provide steps to recreate your case?

**Comment by theOtherNir** [comment]
Hi,
You 100% are correct that the installation shows in the middle of the doc, just found it now, sorry.
It happened to me after :
1. reading the doc
2. installed the dependencies at the of the page
3. jumped directly to the "full source code" section to copy it in one go.
A bit confusing but it's my fault I guess. 
(IMHO it would be better if it was located right at the top with the rest of the dependencies)
Thanks for the response!
