### ISSUE TITLE
Test the next release

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9015]
## Provide a description of the task

We've done quite big changes in some places. It'd be good to have a sanity check that once it's all installed from npm it actually works.

**Comment by Reinmar** [comment]
Let's go for the low hanging fruit here – let's change package.json of ckeditor5 on GitHub to what it'd be on npm and see if our CIs stay green.

**Comment by pomek** [comment]
I updated the `package.json` file in CKEditor 5 repository: https://github.com/ckeditor/ckeditor5/compare/testing-release

It uses changes from this PR – https://github.com/ckeditor/ckeditor5/pull/8973.

Our uber-integration CI bootstrapped projects properly. All tests were green. I didn't build our documentation because we didn't introduce any change in this subject.

Do we need to do anything more?

**Comment by Reinmar** [comment]
Danke
