### ISSUE TITLE
CKEditor5 + CKFinder Image Upload Error

### ISSUE THREAD

**Issue by CyrilGadara** [ckeditor/ckeditor5#9027]
Hello
I'm CyrilGadara.
I was trying to use ckeditor5 with ckfinder php version. But when i try to upload images it gives me upload failed with erro. In network tab the response is '110','unknown error'. But when i upload files .pdf,.docx the files are uploaded successfully and i can use them in ckeditor textarea. When it comes to images its not working and gives unknown error. I'm using XAMPP.
Can someone help me solve this issue with image uploads please

**Comment by LukaszGudel** [comment]
Hello, I've tested few CKE5 configurations with CKFinder plugin and everything seems to work properly. I would suggest you temporarily remove CKFinder configuration from CKEditor 5 config object. CKFinder will connect to the public php file server. 

If you will be able to upload both files and images then the issue is not on the CKEditor 5 side. But if the issue still occurs then I would like to ask you to provide more information about CKEditor 5 usage in your app - config and editor build would be very helpful.

Please remember that this is CKEditor 5 repo, and we only provide a plugin for integration with CKFinder.  When I was investigating your issue I've found [this comment](https://github.com/ckfinder/ckfinder-symfony-bundle/issues/24#issuecomment-748996067) which might be useful to you

**Comment by MustafaBilal313** [comment]
@LukaszGudel i used this setting 
ckfinder: {
  uploadUrl: 'https://ckeditor.com/apps/ckfinder/3.5.0/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'
}
issue was solved image upload was working properly but now i am getting this error 
It was not possible to complete the request due to authorization restrictions.
