### ISSUE TITLE
Improve the performance of the crawler

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9041]
I tried to understand what's causing the crawler to be so slow. It's odd because running it for manual tests (215 in CKE5 itself) should take maybe 215\*15s. 15 is enough to serve all files and execute the editor, right? Unfortunately, I'm at 52% done and testing the next test takes over 1 minute. This is odd.

What's also odd is this:

![](https://user-images.githubusercontent.com/156149/108086184-65204e80-7076-11eb-862a-897d8764cd9d.png)

Why is chrome taking 103% of my CPU while the Idle is 86.7%. It somehow does not add up, but perhaps it's only how macOS shows the load.

Anyway, 1 minute per test is odd. And it seems like it slows down with time - every next test takes more time.

I found the crawler super useful but the performance aspect makes it hard to use at times. I'd love if we find the solution as it seems that it's not perhaps related to using one thread (although, spawning more may help significantly). It seems like something else is not working well.

E.g. how do you open and close the new test?

_Originally posted by @Reinmar in https://github.com/ckeditor/ckeditor5/issues/8800#issuecomment-779925825_

**Comment by psmyrek** [comment]
I confirm that after some time the crawler slows down significantly and then it takes 30 seconds to visit the next test page, which is the default Puppeteer timeout value.

It turns out that the manual test for `Title` on http://localhost:8125/ckeditor5-heading/tests/manual/title.html is failing so hard, that it hangs the whole page within the Puppeteer's headless browser instance.

For unknown reasons already existing error handlers in the crawler are not able to detect such issue.

Currently, the crawler creates just one page within the Puppeteer's headless browser instance, and re-uses it in all subsequent requests for the whole test run. Maybe each test should be opened in the separate Puppeteer's page to create something like a sandbox for each of them?

**Comment by psmyrek** [comment]
The results from this issue should be:
* correct handling of crashed or not responding pages during the test run (i.e. the `Title` manual test),
* investigation/implementation of crawler parallelization (currently pages are opened sequentially).

**Comment by psmyrek** [comment]
Today I learned that not all errors, which Puppeteer encounters while navigating, are reported by the `page.on()` method, but some of them 👇🏻 are thrown as an exception from the `page.goto()` method:

* there's an SSL error (e.g. in case of self-signed certificates),
* target URL is invalid,
* the timeout is exceeded during navigation (like in the `Title` manual test mentioned above),
* the remote server does not respond or is unreachable,
* the main resource failed to load.

I will add support for them to the crawler.
