### ISSUE TITLE
Review and rewriting the DLL guide

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#9094]
## 📝 Provide a description of requested docs changes

[_http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/builds/guides/development/dll-builds.html_](http://fake.ckeditor.com:8081/build/docs/ckeditor5/latest/builds/guides/development/dll-builds.html)

![](https://user-images.githubusercontent.com/1232187/109011621-63c3d700-76b1-11eb-95db-f507df08eb98.png)

**Comment by pomek** [comment]
Except for the typo, we need to resolve the following problems:

- `TODO: Mention about using the @ckeditor/ckeditor5-dev-utils package.`
  
  We prepared a function that returns an object that can be used as a configuration for webpack.
- `libraryTarget: 'umd',` 
  
  It must be changed to `'window'` instead of `'umd'`.
- `manifest: require( 'node_modules/ckeditor5/build/ckeditor5-dll.manifest.json' ),`
  
  We won't publish the manifest file in the upcoming release, so we need to mention that the guide requires cloning the entire CKEditor 5 repository.
- > To use DLL compatible editor you need to use the base DLL build, a DLL-consumer editor build, and a DLL-consumer editor features build for every package.
  
  "a DLL-consumer editor build," - we don't have such a thing. The entire "The editor bundles" section requires a review
- It's worth mentioning that DLLs will work if everything will be passed through webpack (see all-features-dll manual test)

**Comment by pomek** [comment]
Resolved with https://github.com/ckeditor/ckeditor5/pull/9147.
