### ISSUE TITLE
Managing multiple block images

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9183]
## 📝 Provide detailed reproduction steps (if any)

After adding the new image styles (https://github.com/ckeditor/ckeditor5/tree/i/8909-inline-images-styles) and inline images, there is an inconsistency in displaying multiple block and inline images side by side.

❌ Actual result

All images below have the same `image-style-align-left` class, but the first two are the block images and the next inline images. The reason for this behavior is that the block images have the `clear: both` rule for the `img` element.

![](https://user-images.githubusercontent.com/14334820/110314737-8ab2cf00-8008-11eb-892b-3cd5c17d6dd4.gif)

### ✔️ Expected result

* It should be possible to display multiple block images side by side.
* The behavior of the inline and block images set by the same button should be consistent.
 
It can be fixed easily by overriding the `clear: both` rule for the `image-style-align-left` class.

**The problem is that this particular class is one of the default classes provided in the editor. Changing its appearance can lead to unexpected (and expected) results in clients' content.**

**Comment by magda-chrzescian** [comment]
We could also just use a new class like `image-style-float-left` in the new toolbar and leave the `image-style-align-left` and `image-style-align-right` unused just for the content backward compatibility.

**Comment by oleq** [comment]
`clear: both` was (most likely) used because the only style at the [moment of implementation](https://github.com/ckeditor/ckeditor5-image/pull/23) was the side image for semantic content, which actually benefits from it. Take for instance an article on Wikipedia:
![image.png](https://images.zenhubusercontent.com/5db82ed39f933c00013cf856/7317352d-0b72-423e-92cf-2121752cce1c)
the images in the sidebar should never overlap, that's the point of an article.

However, in other (non-article) cases, it's OK for them to stay in the same line. So I'm for moving the `clear-both` to the semantic side style CSS definition and letting the rest of block images act like inline images when it comes to floating.

**Comment by magda-chrzescian** [comment]
To keep the `clear: both` rule for the image with no class, I added `clear: none` to the block images with float.

Otherwise, the `full` image inserted right after a floating block image, was pushed to the right, instead of the next line.

**Comment by oleq** [comment]
Closed in #9381.
