### ISSUE TITLE
Document text part language feature

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor5#9211]
## 📝 Provide a description of requested docs changes

Followup ticket for text part feature documentation - https://github.com/ckeditor/ckeditor5/pull/9074

**Comment by jacekbogdanski** [comment]
Since we already have [UI Language](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html) feature category, I'm wondering where should be put new documentation for text part language (which is being a part of the `language` package).

I worry that an additional `Langauge` category to already existing `UI Language` could be misleading. On the other side, the feature is not really related to the editor UI anyhow, so adding docs on top of `UI Language` also doesn't seem like a good idea. Maybe we could add an additional category for the existing `UI Langauge` and text part language feature? Something like:

* Language
  * UI Language
  * Multilingual Content

However, it would break the `ckeditor5/latest/features/ui-language.html` link on the `latest` version which may not be what we want. Any thoughts on that @AnnaTomanek, @Reinmar, @Mgsy?

**Comment by godai78** [comment]
We have UI Language entry, not a category ;)  
  
Getting this together seems like a good idea at first, but won't we cause confusion? We already need to underline this feature got nothing to do with the UI language, so that becomes slippery.  
  
Feature-wise and application oriented, this would also make sense to have it grouped with spellecheck rather, than UI.  
  
Broken links is something we can deal with by relinking, so this would be least concern.
