### ISSUE TITLE
[Table Caption] Selection placement after hiding the caption

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#9304]
Currently, when the caption in a table is toggled off, the selection is placed on the entire table. This has a downside of making the **content toolbar** (the most common type of toolbar configuration for table UI) disappear. To toggle the caption on, the user has to click inside the table on any cell to show the **content toolbar** and then is able to turn the caption on.

On the other hand, if we place the caption button on the **table toolbar**, it will be visible after toggling off the caption. The problem is with the general discoverability of the button as you have to click on the helper in the top left corner of the table to be able to add a caption to the table.

We can either:
- Select an arbitrary cell when hiding the caption, which will show the **content toolbar** with the caption button (hopefully) added there.
- Keep selecting table but expect the user to configure it so it has a **table toolbar** with caption button.
- Do something else?

To add insult to the injury, the current placement of the Table properties button inside the **content toolbar** seems illogical, as is the **table toolbar** seems the right place for it (not a convenient place though).

cc: @oleq @magda-chrzescian @Reinmar @niegowski

**Comment by magda-chrzescian** [comment]
The table toolbar default behavior is not consistent with other widgets. The rest of the widgets has their toolbars active while the whole widget is selected, the table has no toolbar if the whole widget is selected (in all default configurations). Therefore I can see another solution - to unify the `contentToolbar` and the `tableToolbar` items, so the toolbar would be the same for the content and the whole table by default.
+ Solves the problem above.
+ Consistent with the rest of the widgets.
+ Ease of use of the buttons supporting the entire table, not the content.
---
Let’s consider the following scenario:
1. The user wants to set the caption for the toolbar.
2. He hovers the table (and sees the whole table selector).
3. He probably clicks it (?), because the caption is an action regarding the whole table, not the content.
4. He should see the caption button and other buttons supporting the table widget (e.g. styles and table properties) - so they should be present in the `tableToolbar`.

Here some questions arise:
* Why did we decide not to use the `tableToolbar` for the whole-table-specific actions (like table properties)?
* Do we want to
  * unify the `tableToolbar` and `contentToolbar` to have the same items by default (as mentioned above)
  * or put the cell-specific actions into the `contentToolbar` and the widget-specific actions into the `tableToolbar`? 
I’m not sure if it wouldn’t be confusing - clicking in the middle of the table and on the whole-table selector would result in displaying another set of the options.
---
If we want to go with the simplest solution, selecting the cell when hiding a caption seems to be fine. However, we should keep in mind that a developer is able to configure a custom toolbar, but can’t easily change the selection behaviour(?). If it made sense to put the caption button into the `tableToolbar` and the developer did that, the button wouldn’t be visible while hiding the caption then.

**Comment by maxbarnas** [comment]
> Therefore I can see another solution - to unify the `contentToolbar` and the `tableToolbar` items

This would work if we made sure the buttons just for the content action are either disabled or hidden when we select the table widget. And having the table actions visually separated in the toolbar from the content actions would be a plus, but the toolbar items are user-configured. Not sure we want to enforce anything there to make this visual separation.

> Why did we decide not to use the `tableToolbar` for the whole-table-specific actions (like table properties)?

I would guess it's because of the discoverability. Honestly, at first, I was surprised that the helper in the corner of the table is doing anything more than selecting the table. And for the most part, is - the usage of `tableToolbar` config is very limited in the codebase.

> If it made sense to put the caption button into the `tableToolbar` and the developer did that, the button wouldn’t be visible while hiding the caption then.

My point exactly. I want to make sure the caption can be quickly toggled on/off without constant clicking on the table helper (because focusing on the cell will hide the table toolbar and vice versa).

**Comment by magda-chrzescian** [comment]
> but the toolbar items are user-configured. Not sure we want to enforce anything there to make this visual separation.

Yup, but AFAIK we provide the default toolbars configurations for our builds. I think that all that we're discussing here regarding the toolbars is about these defaults - that's all we have under control.

> My point exactly. I want to make sure the caption can be quickly toggled on/off without constant clicking on the table helper (because focusing on the cell will hide the table toolbar and vice versa).

But in the end, we can't be sure where the caption button will be displayed (the `tableToolbar or `contentToolbar`) if the developer doesn't use the default builds. So IMO we should follow these guidelines:
* Decide in which toolbar it really makes sense to have the caption button (and guess that the developer also will put it there).
* After we decide where to put it by default, set the selection behavior properly to focus the right toolbar.

**Comment by maxbarnas** [comment]
To help decide I prepared short demo of current state of the toolbar behavior:

> ![table-caption](https://user-images.githubusercontent.com/1112966/112128272-8bca2b80-8bc6-11eb-8069-9679eee9c6b9.gif)

The button works fine both from table and content toolbar. To achieve smooth experience we can just duplicate the button in both toolbars. As @magda-chrzescian pointed out offline, we would have to update editor builds to have it by default at least there.

Other things to consider/do:
- Place the Table Properties button in `tableToolbar`.
- In the `contentToolbar` move both Caption and Table Properties to the end behind a separator.

**Comment by maxbarnas** [comment]
Update: According to @niegowski we should put the selection on the first cell to mitigate this weird behavior when caption is toggled off.

**Comment by niegowski** [comment]
Closed in #9263
