### ISSUE TITLE
Integreate Multiple CkEditor 5 instances with Plugins into Angular Project

### ISSUE THREAD

**Issue by VooDooTo** [ckeditor/ckeditor5#9331]
Hi,

I am trying to integrate multiple instances of CkEditor 5 with Plugins like htmlEmbed into my Angular project.

📝 Steps to reproduce:

`       const ClassicEditor = require('../../../../../src/assets/ckeditor/ckeditor');
        const editorId = this.editorEl.nativeElement;
        ClassicEditor.create(editorId, plugins: [ HtmlEmbed ],
          toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'blockQuote', 'numberedList', 'htmlEmbed', 'highlight' ],
          heading: {
              options: [
                  { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
                  { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
                  { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' }
              ]
       }).then((editor: any) => {
         editor.execute('insertHtmlEmbed', replacedText);
            editor.model.document.on('change', () => {
                // console.log( 'The data has changed!', this.editor.getData());
            });
        }).catch((error: any) => {
            console.log(error);
        });
`

However when instantiating the editor twice or more times, because we have different forms with different editor instances, the editor throws me an error:
 **CKEditorError: ckeditor-duplicated-modules**

![image](https://user-images.githubusercontent.com/11502383/112103070-e60cc180-8bb1-11eb-85c0-5a4bc84d4728.png)

### ✔️ Expected result

How can I instantiate two or more editors with plugins and they will have different content and state on same page?

### ❌ Actual result

I would expect to be able to run two or more instances on the same page without the editor throwing me an error.

## 📃 Other details

* Browser: ALL
* OS: Windows 10
* First affected CKEditor version: Ckeditor 5 (latest)
* Installed CKEditor plugins: Highlight, HtmlEmbed

**Comment by FilipTokarski** [comment]
Hi, [duplicated modules error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) happens because you are trying to add plugins to the build ( instead of class ). Currently our Angular integration doesn't allow to build it from source like in React or Vue. You need to create your custom editor first and then integrate it into Angular app -  please see the docs on how to create [custom editor build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build) in Angular.
