### ISSUE TITLE
Importing modules always report errors: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

### ISSUE THREAD

**Issue by andrew2558** [ckeditor/ckeditor5#9355]
## 📝 Provide detailed reproduction steps (if any)

Importing modules always report errors: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

How to solve this problem, and is there any operation guide to avoid this problem?

### ✔️ Expected result

Import modules do not report errors

### ❌ Actual result
Import module error:
CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules 

## 📃 Other details

```
import { CKEditor } from "@ckeditor/ckeditor5-react";
import DecoupledEditor from "@ckeditor/ckeditor5-build-decoupled-document";
import Bold from "@ckeditor/ckeditor5-basic-styles/src/bold";
```

This DecoupledEditor does not contain any plugins (use online builder)

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by tranhanam19999** [comment]
Same issue

**Comment by FilipTokarski** [comment]
Hi, the [error documentation you linked](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) explains why this happens. Most probably because you are trying to add a plugin to editor build ( instead of class ). So if you want to customise you React integration, you'll need to [build it from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source). Also, if you're using editor from Online Builder, please see the section on [integrating it with React app](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-a-build-from-the-online-builder).
  
As it comes to:
> This DecoupledEditor does not contain any plugins (use online builder)  
  
I'm not sure what you mean, I just checked decoupled editor generated with Online Builder and it contains all chosen plugins.

**Comment by andrew2558** [comment]
@FilipTokarski  Thanks, The current version is too cumbersome for adding custom plugins.

> This DecoupledEditor does not contain any plugins (use online builder)
 
I used online builder, but I didn't select any plugins.

**Comment by tranhanam19999** [comment]
Hey andrew, i fixed this by simply upgrading all of my plugins into newest version and the problem disappear
Ex: Alignment plugin was 24.0.0 in package.json -> change to 27.0.0

**Comment by andrew2558** [comment]
thanks @tranhanam19999 Let me try

**Comment by Superlukec** [comment]
My problem is solved now 👍

**Comment by andrew2558** [comment]
@Superlukec  How did you solve it?

**Comment by Superlukec** [comment]
@andrew2558 I did what @tranhanam19999 suggested. 

I've pulled the latest Ckeditor build and then add all the plugins, which I needed and compiled everything. It works normally now.

Previously I had version 25.0.0 now I have 27.0.0
