### ISSUE TITLE
Text alignment buttons should be disabled when the table is selected

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#9369]
## 📝 Provide detailed reproduction steps (if any)

Extracted from: https://github.com/ckeditor/ckeditor5/pull/9242#issuecomment-808166132

Can be reproduced here: https://ckeditor.com/docs/ckeditor5/latest/features/table.html#configuring-styling-tools

## 📃 Other details

**Table properties plugin must be enabled**

**Comment by Reinmar** [comment]
For the reference, when an image is  selected, the text alignment options are disabled:

![](https://user-images.githubusercontent.com/156149/140051610-3335cad4-0355-4a0a-a014-4518fdccc8cb.png)

So, it makes sense to be consistent with that when the table is selected.

**Comment by otherblandart** [comment]
Returning to this, while I understand the desire for consistency mentioned, one important difference between Tables and Images is  that Tables can and often do contain text, so disabling inline formatting like this means that users now have to manually select every cell in the Table in order to apply text alignment across the table (since there seems to be no shorthand way to select all cells). For a large table this can be unwieldy. We had a customer raise this as a bug in our product, and now have to explain to them it's related to your product.
