### ISSUE TITLE
Heading element doesn't exist in getAttributes()

### ISSUE THREAD

**Issue by mehradboe** [ckeditor/ckeditor5#9383]
When I apply H1, H2 and so on to the selected text And I try to get the applied attributes I get nothing about heading styles in it

**Comment by FilipTokarski** [comment]
Hi, could you explain your use case and provide some steps/code to reproduce the issue?

**Comment by mehradboe** [comment]
Yes of course
I would like to make CKEditor with Native UI for mobile devices
in this situatuion i can't use Bind-ing system for button, then i use command system for executeing each style or feature

for example in my issue:
i use
"editor.execute( 'heading', { value: 'heading2' } );"
to set h2 tag in selection text part, everything do good with command system

when i wana return wich feature is on in the selection text
i use 
"selection.getAttributes()"
from model, and it is work fine in all of feature except heading and alignment, the i can't find which heading or alignment is seting with selection text part

**Comment by mlewand** [comment]
@mehradboe sorry for chiming in a little late, but there's a nicer way to look for this.

`HeadingCommand` has a `value` observable property. This property holds value like `heading1` ... `headingn` if there's a heading in the selection or `false` if no heading is applied to the selection. Since this method is observable you can easily listen to even when it's changed and react accordingly.

I see that respective property is in the `AlignmentCommand`.

In case it doesn't work for you feel free to reopen this issue.
