### ISSUE TITLE
getViewImgFromWidget assumes img has always a wrapper

### ISSUE THREAD

**Issue by lauriii** [ckeditor/ckeditor5#9405]
## 📝 Provide detailed reproduction steps (if any)

Add an overriding converter to the image model that converts the model into an `img` element without wrapper. For example: 

```
editor.conversion.for('dataDowncast')
.elementToElement( {
  model: 'image',
  view: 'img',
  converterPriority: 'high',
});
```

### ✔️ Expected result
The `img` element should be rendered without errors

### ❌ Actual result
There's an error because `getViewImgFromWidget` assumes img element is always wrapped with something.

**Comment by mlewand** [comment]
Is there a chance that inline images will fix it @magda-chrzescian @oleq?

**Comment by oleq** [comment]
The inline image feature will downcast the `imageInline` model element to `<img>` in data.

**Comment by mlewand** [comment]
Ok, so just to be clear, that's a different model, meaning that it will not affect the existing converter. That being said since you're changing the `dataDowncast` of our image it is to be expected that other our converters will no longer work - so you need to follow it with overriding other controllers to.

If we changed the default implementation we would end up with dead code (as we don't use this case in our code).

**Comment by Reinmar** [comment]
This is a specific request for Drupal's use case where all images (block and inline ones) are downcasted in the data pipeline to simple `<img>` tags. It wasn't possible before because getViewImgFromWidget's call that could not be canceled AFAIR was expecting the figure>img structure.

I think, though, that we can close this specific request because we'll need to review this thoroughly and it'll be easier to coordinate this in one place (meaning – different than this ticket :D).
