### ISSUE TITLE
Numbered List not continuing number with text in between when copied from word

### ISSUE THREAD

**Issue by hsavnio** [ckeditor/ckeditor5#9443]
Issue is specifically when content is being copied from other place e.q Word and pasted to CKEditor 5

While adding Numbered list with single line text works but when each we have text between each list item then the number restarts from 1 for each bullet list and considered as new. This same text works fine in ckeditor 4.

![image](https://user-images.githubusercontent.com/82156123/114200988-5f0e6600-9973-11eb-8494-776e7f9a0d05.png)

### ✔️ Expected result

![image](https://user-images.githubusercontent.com/82156123/114201637-0e4b3d00-9974-11eb-8689-c05f957ec0be.png)

### ❌ Actual result

![image](https://user-images.githubusercontent.com/82156123/114201274-a137a780-9973-11eb-942b-aa5713d4bf24.png)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, this happens because current implementation of lists in CKEditor 5 doesn't allow inserting block elements inside the lists. So every time you try inserting an empty paragraph/image/table/etc., the list gets split.  
  
We have an open feature request for more advanced lists, which you can track [here](https://github.com/ckeditor/ckeditor5/issues/2973). Feel free to add there anything you consider important and add 👍  to bump its popularity.  
  
I'm closing this ticket as a duplicate.
