### ISSUE TITLE
The nested widget selection handle is visible while the outer table cells are selected

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#9491]
## 📝 Provide detailed reproduction steps (if any)

1.  https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/table.html
2.  make nested table
3.  select multiple cells in the outer table

### ✔️ Expected result

The selection handle is not visible

### ❌ Actual result

![](https://user-images.githubusercontent.com/1232187/114998129-ecd0e080-9ea0-11eb-8542-beeafe624087.gif)

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Issue is not limited to tables but is reproducible for any other widget with selection handle, e.g. HTML embed:

![](https://user-images.githubusercontent.com/5353898/133435834-f2906130-3d1b-4a55-9f0c-a86a9b0ea4cb.png)

**Comment by oleq** [comment]
Before we jump to conclusions and start writing code, let's figure out the right UX first. In my opinion, there are multiple approaches to this problem.

### Status of things (`master`)

![](https://user-images.githubusercontent.com/1099479/133984335-64202e9b-cb96-46da-b75b-6b084cd8b6e5.png)

![](https://user-images.githubusercontent.com/1099479/133984332-5df58c89-342c-47cc-acf0-eff18c82ddf5.png)

![](https://user-images.githubusercontent.com/1099479/133984333-1362358a-2d94-4b30-a999-4040dc4ed6a7.png)

![](https://user-images.githubusercontent.com/1099479/133984334-af34b857-8bd1-42c1-934e-9dc5d55d6c38.png)

*   When the selection includes inline widgets in text, they get the selected outline.
*   When the selection includes block widgets, they get the selected outline (but not their children).
*   When the selection includes a single block widget, it gets the selected outline (but not its children).
*   When the selection spans multiple table cells, the children inside (inline widgets and block widgets), don't get the outline except for the block selection handle glitch reported in this issue.

I noticed there's a certain inconsistency between the "normal selections" (first two screenshots) and the table cell selections (brought by the `TableSelection` plugin). Normal selections highlight children's widgets (but only 1st level). Table cell selections don't select anything.

The latter is a result of the decision we took last year 237cb30.

*   Why did we go this way BTW?

## Possible solutions

### Make the table cell selection more like the "regular selection"

You can remove the restriction introduced in the commit I mentioned and things will look slightly different:

```jsx
diff --git a/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css b/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css
index 5a0901f589..cd8c0bd5e7 100644
--- a/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css
+++ b/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css
@@ -31,9 +31,5 @@
                   &:focus {
                            background-color: transparent;
                   }
-
-                  & .ck-widget_selected {
-                           outline: unset;
-                  }
          }
 }
```

![](https://user-images.githubusercontent.com/1099479/133984425-a09d6a94-c85b-4203-bd84-811cb3528ee7.png)

![](https://user-images.githubusercontent.com/1099479/133984423-28b4ea7d-a223-4068-84a5-4a325e736516.png)

![](https://user-images.githubusercontent.com/1099479/133984424-2b0ea68e-ecb1-472f-be9e-6cd9d24114d3.png)

![](https://user-images.githubusercontent.com/1099479/133984427-567eadf3-3f45-4747-bd5f-9fca57416c69.png)

You may notice that the table cell selection acts sort of more like the "regular selection". It highlights both inline and block widgets within its reach but only the first level down the tree.

### Stay with the UX we have on master but ditch the nested block widget selection handle

This was the intent of [https://github.com/ckeditor/ckeditor5/pull/10556/files](https://github.com/ckeditor/ckeditor5/pull/10556/files). There's no need to manipulate the widget CSS classes, in my opinion. The `.ck-widget_selected` class is OK to stay whenever the widget is included in any selection because, well... engine–wise, it is selected 😛. The presentational layer can provide the right UX on top of it using pure CSS, though.

We can ditch the selected block widget handle in table cell selection by:

```jsx
diff --git a/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css b/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css
index 5a0901f589..6b0b4f8ea2 100644
--- a/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css
+++ b/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css
@@ -34,6 +34,10 @@
 
                   & .ck-widget_selected {
                            outline: unset;
+
+                           & .ck-widget__selection-handle {
+                                    display: none;
+                           }
                   }
          }
 }
```

![](https://user-images.githubusercontent.com/1099479/133984531-8f5edfc3-3ccd-4e4e-a41c-91d2805c181d.png)

![](https://user-images.githubusercontent.com/1099479/133984532-120b22e6-7b8c-41fb-8890-86dfa8ba239e.png)

![](https://user-images.githubusercontent.com/1099479/133984533-d6df0185-5722-4e6f-a3e4-6ab9577e75f9.png)

![](https://user-images.githubusercontent.com/1099479/133984534-db08035b-ce3b-4f4b-8116-be0483ab8d58.png)

**Comment by oleq** [comment]
During today's UX sync we decided 

> ### **Stay with the UX we have on master but ditch the nested block widget selection handle (safer)**

is the right direction ATM.

**Comment by EwelinaD** [comment]
About this safer resolution:

If we set `display: none` for selection handle in tableselection we will also change its behavior during mouse hover. See the screenshots below

1.  master

![](https://user-images.githubusercontent.com/11716070/134005974-d2804435-e6d0-46bf-b3f8-9017dbd51715.png)

2\. with safer resolution (`display: none`)

![](https://user-images.githubusercontent.com/11716070/134005996-b4057d01-765a-4963-bcd5-d3efcc84b4e2.png)

As you can see there's no selection handle for selected table with hover.

There's also another problem on master with nested tables: there's no border and selection handle for first nested table - I'm not sure if it should be handle within this ticket or not.

**Comment by oleq** [comment]
Side-note: Looks like there's a lot of funny things going on we need to straighten out. 

For instance, only the innermost widget gets the yellow hover outline when the mouse is over it because as per #4594 

https://github.com/ckeditor/ckeditor5/blob/52b37324aeb4eba6e1465d46cfcd5477934b349e/packages/ckeditor5-widget/src/widget.js#L135-L136

> // Do not mark nested widgets in selected one. See: #57.

![](https://user-images.githubusercontent.com/1099479/134011473-0ddb1b89-e487-4f47-8898-acc6bf9c979d.gif)

and as a result, the innermost widget does not get the `.ck-widget_selected` class. This was OK in 2018 when there were no nested widgets. Now we need to figure this all out.

**Comment by oleq** [comment]
A rough idea based on the fact that we don't really care if the widget has the selected CSS class or not when it's inside table selection. The fact it is there is all that really matters. I wouldn't merge it to master two days before the code-freeze, though.

```diff
diff --git a/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css b/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css
index 5a0901f589..fdfa20b009 100644
--- a/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css
+++ b/packages/ckeditor5-theme-lark/theme/ckeditor5-table/tableselection.css
@@ -32,8 +32,16 @@
                            background-color: transparent;
                   }
 
-                  & .ck-widget_selected {
+                  /*
+                   * To reduce the amount of noise, all widgets in the table selection have no outline and no selection handle.
+                   * See https://github.com/ckeditor/ckeditor5/issues/9491.
+                   */
+                  & .ck-widget {
                            outline: unset;
+
+                           & > .ck-widget__selection-handle {
+                                    display: none;
+                           }
                   }
          }
 }
```

![](https://user-images.githubusercontent.com/1099479/134013067-a7c73c46-075d-4656-8c8c-bf5fcf4a461a.gif)
