### ISSUE TITLE
Custom build sample displays raw HTML

### ISSUE THREAD

**Issue by Elwetana** [ckeditor/ckeditor5#9504]
## 📝 Provide detailed reproduction steps (if any)

1. Create custom build for CKEditor 5, include some plugins
2. Download, extract the zip
3. Open file `sample/index.html`

### ✔️ Expected result

WISIWYG representation of the text. This happens with the vanilla classic build 27.0.0

### ❌ Actual result

I can see the content of editor as raw HTML. This does not happen when I download the CKEditor build classic.

## 📃 Other details

* Browser: Vivaldi
* OS: Windows

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Elwetana** [comment]
Also, when I set the same text with `setData` the text is displayed correctly.

**Comment by Elwetana** [comment]
Further observation suggests that the error appears when the text in editor div starts with whitespace. When I use the following code:
```javascript
let d = document.getElementById("editor")
let t = d.innerHTML
d.innerHTML = ""
ClassicEditor.create(d, { ... }).then(editor => { editor.setData(t.trim()) } )
```
the text in the editor is then displayed correctly.

**Comment by FilipTokarski** [comment]
Hi, first please make sure you follow the [guide on creating custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html). As it comes to setting initial data when creating the editor, use [`initialData` config option](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-initialData), otherwise use `setData()`.

**Comment by Elwetana** [comment]
I got the build from the online builder at https://ckeditor.com/ckeditor-5/online-builder/

Thank you for the tip about `initialData`, actually it's enough not to include whitespace when creating HTML for the editor. This is a workaround that works for me, however, it still looks like a bug.
