### ISSUE TITLE
Comment-only mode documentation should mention `command.forceDisabled` feature instead of old command disable method

### ISSUE THREAD

**Issue by asimkt** [ckeditor/ckeditor5#9517]
In https://ckeditor.com/docs/ckeditor5/11.1.1/features/collaboration/comment-only-mode.html?docId=e3c8202b09ed481801341ae307f9bd38a, instead of 

```
command.on( 'change:isEnabled', evt => {
                command.isEnabled = false;
                evt.stop();
            }, { priority: 'highest' } );

            command.isEnabled = false;
```

We can say:

```
command.forceDisabled( 'CommentOnlyMode' );
```

It's better and easier to understand. And if somebody wants to switch back to normal editing, it would be easy to do that also.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. The docs you linked use very old version of the editor. Current one is `27.0.0` and we really encourage to keep the editor's version up to date.  
As it comes to disabling/enabling comments-only mode, this has also changed since that time and the current solution [can be found here](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-only-mode.html?docId=ef1a6900fa825e19fbceb314e9911131d#enabling-comments-only-plugin).

**Comment by asimkt** [comment]
Thanks @FilipTokarski .

I was really lucky to see the old doc as I had a similar feature to implement. 😄 (not the actual comment only mode) I think we should mention about how to do "Some feature-only" mode with not just comment only mode, so that devs can implement their own versions.

And can we show an alert at the beginning of the page saying that the doc is outdated.

**Comment by asimkt** [comment]
And this is google
![image](https://user-images.githubusercontent.com/10784527/115866143-e1f4ed80-a456-11eb-836a-8d68984a6091.png)
 which redirects to 11.1.1
