### ISSUE TITLE
Make the update process less erroneous

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5#954]
I'm missing a command that would just update CKEditor 5 dependencies correctly. Some `go go power rangers` command that I could run and that would work (e.g. `npm run reinstall`).

Currently it is easy to make a mistake when trying to update "CKEditor 5" which leads to a waste of time. For example I was trying to build the documentation and it did not work because of wrong dependencies. In my case the problem was in not running `mgit bootstrap` before `lerna clean && lerna bootstrap` (yeah, shame, I know).

My second thought is that the problem might be not in the missing command but in missing documentation. [Setting development environment](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/contributing/development-environment.html#setting-up-the-ckeditor-development-environment) is pretty extensive  but does not mention mgit bootstrap: see [fetching changes](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/contributing/development-environment.html#fetching-changes).

**Comment by Reinmar** [comment]
> My second thought is that the problem might be not in the missing command but in missing documentation. Setting development environment is pretty extensive but does not mention mgit bootstrap: see fetching changes.

There's `mgit update` mentioned in "fetching changes". And `mgit bootstrap` is mentioned in "Switching to dev version of pkgs". The problem may be that since it's optional (you can base on `npm i`) the documentation first mentions `npm i` and then `mgit bootstrap`. It just depends on what you want. But perhaps... we should simply stick to `mgit bootstrap` there and simplify this guide.

Another topic is that `mgit update` ~= `mgit bootstrap`, while we should just have `mgit pull`, `mgit fetch`, etc. Just like in git. There's `mgit co` already but we can improve it too, in fact.

---

Regarding the command, I see two main use cases:

* updating the repo
* installing the repo for the first time

While `reinstall` makes sense for the former, it's not a good name for the latter. But I guess we can have both – `npm run install` === `npm run reinstall`.

**Comment by Reinmar** [comment]
I've reported a ticket in mgit's repo regarding the commands: https://github.com/cksource/mgit2/issues/73

**Comment by pjasiun** [comment]
`mgit` does not solve this problem. The `go go power rangers` command (a.k.a. `npm run reinstall`) is needed for people who wants to run CKE 5 after a month or more of not using it. In such case you want to reinstall everything: remove `node_modules` and `packages` and call all installation commands needed to be sure you have everything updated. You do not care that it takes some time, you want to be sure that you will not meet some bugs.

**Comment by Reinmar** [comment]
OTOH... PJ is right :D

And we'd never validate that you pushed everything anyway, right, @scofalik?

**Comment by pjasiun** [comment]
We have a similar command in Letters and we usually use to have reset project if one did not work with it for a long time or something big changed. I do not want any question and additional steps. Just want to be sure that everything is reset and updated.
