### ISSUE TITLE
Inline images: Image loses size property when converted to inline

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#9562]
### Steps:
1. Change block image size.
2. Drag resized image to the paragraph.

### Result:
Size value resets back to 'Original'.

https://user-images.githubusercontent.com/58658048/115712890-a6362700-a375-11eb-96cf-deab9cd85fdd.mp4

Notes:
- All browsers
- When dragging resized inline image to empty paragraph size is kept

**Comment by magda-chrzescian** [comment]
The problem lies in the `inputTransformation` listener in the `ImageInlineEditing` plugin. When a block image is pated/dropped into a non-empty paragraph, it passes only the `<img>`, not the entire `<figure>` and the attributes present on the `<figure>` (`style` in this case) are lost because of that.

We also agreed that, to simplify the code, we should listen to the `contentInsertion` event instead of the `inputTransformation`, which operates on the model, not view, elements.

I had some problems with implementing the solution described above, so I'm creating a follow-up to cover that.

**Comment by oleq** [comment]
Closed in #9591.
