### ISSUE TITLE
Inline images: Pasting content with relative src image is crashing editor

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#9563]
### Steps:
1. Select all content from https://ckeditor.com/ckeditor-5/demo/ and copy it.
2. Paste it to all-features manual test.

### Result:
Editor crashes with error:
```
TypeError: null is not an object (evaluating 'modelImageElement.name')
  fire - emittermixin.js:232
  domListener - emitermixin.js:247
```

Notes:
- Only in Safari
- this is related to relative image src (`<img src="/assets/images/bg/volcano-8967c4575e.jpg" >`) in demo content
- other browsers do not crash with those steps and are showing missing image icon
- same scenario in Safari with editor on `master` branch or in our demos/docs is not crashing

**Comment by pomek** [comment]
The minimum code that reproduces the issue on any browser:

```js
editor.setData( '<img alt="Three Monks walking on ancient temple.">' );
```

Note: There is no `[src]` attribute on `<img>`.

Ok, you can ask, why do I create the image element without specifying the source? That's why Safari does when pasting the image with the non-existing resource. 

Safari, `console.log` at the beginning of Clipboard pipeline (`viewDocument#clipboardInput`) when reproducing the steps specified above. It's enough to copy the image only.
![image](https://user-images.githubusercontent.com/2270764/116665774-74871680-a99a-11eb-8cc4-23eb52c57df7.png)

I'd say we have two solutions:

- do not paste anything in such a case, just remove the element,
- try to extract the content of the `figcaption` element if specified and insert it as a new paragraph.

**Comment by niegowski** [comment]
Closed in https://github.com/ckeditor/ckeditor5/pull/9600.
