### ISSUE TITLE
How to apply custom skin CSS to React NextJS CKEditor5?

### ISSUE THREAD

**Issue by yelnyaface** [ckeditor/ckeditor5#9587]
Hi, how do I apply custom skin CSS ( make whole UI with dark css background ) to React CKEditor5?

in the doc: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html

it said I should create a `custom,css` file, but file like this cannot be included into `Nextjs`:
```
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages\_app.js. Or convert the import to Component-Level CSS (CSS Modules).
```

what is the work around?

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. First of all, as the error message says, you should place [global css in `pages/_app.js` file](https://nextjs.org/docs/basic-features/built-in-css-support#adding-a-global-stylesheet). Now, the tricky part is, that if you use [custom CKEditor stylesheet](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html#customization-with-css-variables), Next will fail with `Selector ':root' is not pure` error due to use of css modules. So the fix that worked for me, is to replace `:root` selector with `.ck` class, in the stylesheet from docs. This way the css file gets imported properly and styles are applied to CKEditor elements.
Let me know if that helps.
