### ISSUE TITLE
Development environment: `yarn start` development loop w/ live reloading?

### ISSUE THREAD

**Issue by tony** [ckeditor/ckeditor5#9611]
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

Problem: We use a [custom, super build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds) of CKEditor5 and don't have a way to preview our custom build without publishing a build to NPM.  From there, we need to `npm install` the new ckeditor build into our React app, then rebuild the react app on our side w/ the new build. 

Is there a way we could speed up this workflow/reduce the steps taken to see modifications made to our custom build? 

Idea: When inside our CKEditor fork of this repo, is there a way we could use a "development mode" w/ just the build, without having to publish to NPM?

Is there a dev loop, e.g. `yarn start` / `npm start` that could be used when we are developing with File Watching + Hot/Livereloading?

What I'd expect:
- `git clone https://github.com/ckeditor/ckeditor5.git`
- `cd ckeditor5/`
- `yarn`
- `yarn start` - compiles and browser opens at http://localhost:<port\> and rebuilds+reloads with `packages/**/*.js` files are changed

Related pages:
- Quick start: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html
- Development environment: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/development-environment.html
- Creating a simple plugin: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by tony** [comment]
Related issues: Working on the [`ckeditor5-math`](https://github.com/isaul32/ckeditor5-math/issues/37) plugin for KaTeX / MathTeX: https://github.com/isaul32/ckeditor5-math/issues/37

**Comment by pomek** [comment]
When developing new features, we use manual tests to verify whether everything works as expected.

We have many manual tests located in the `tests/manual/` directory in [the main repository](https://github.com/ckeditor/ckeditor5/tree/master/tests/manual), but also for each package separately (e.g. [`ckeditor5-basic-styles`](https://github.com/ckeditor/ckeditor5/tree/master/packages/ckeditor5-basic-styles/tests/manual)). 

The manual test server can be created using the [`yarn run test:manual`](https://github.com/ckeditor/ckeditor5/blob/36b685ce665431a7df31179e3b4e15f2fa4a81e4/package.json#L148) command. It accepts additional options specified in the [`@ckeditor/ckeditor5-dev-tests`](https://www.npmjs.com/package/@ckeditor/ckeditor5-dev-tests) package's README. These options are common for manual tests but also automated (executed by karma). For manual server, some of them have no impact:

* `browsers` - because the server does not open any browser, 
* `coverage` - because a manual test checks a specified scenario, 
* `production` - because we accept `console.log` in manual tests, 
* `reporter` - because developers write their own scenarios, 
* `server` - whether Karma should not open any browser by default,
* `watch` - whether re-run tests when any source has changed.

We have a special test, called [`all-features`](https://github.com/ckeditor/ckeditor5/blob/master/tests/manual/all-features.js) which contains all available features enabled in a single file.

To create a new manual test, you need to create 3 source files:

- `[name].js` which creates the editor with your configuration,
- `[name].html` which provides the document (HTML) for the test,
- `[name.md]` which described what is checked and what is expected (it can be empty)

You can also create additional assets ([see the `sample.*` files](https://github.com/ckeditor/ckeditor5/tree/master/tests/manual)) which will be available when the HTTP server is live.

The manual test server watches for changes in source files but does not watch for changes in assets. They are copied once. If you want to refresh them, you need to restart the server. 

I hope it helps.

**Comment by tony** [comment]
@pomek I recognize the need for test infrastructure and appreciate your detailed response! I support test coverage and TDD.  I also recall hearing a policy of complete test coverage on the CKEditor project.

However, `yarn start` / `npm start` is a different thing. These commands get into a development loop where there is an instant incremental rebuild. It's become ubiquitous in frontend development.

Writing tests for an existing project has a learning curve (to perform actions, assert expected results).

`yarn start` is booting straight into a workflow where you can see changes to direct behavior.  It's helpful for someone like me is who is still new to the API but needing to experiment alongside the docs when debugging.

For example of a dev loop I made to [ckeditor5-math](https://github.com/isaul32/ckeditor5-math) at [#38](https://github.com/isaul32/ckeditor5-math/pull/38), [readme](https://github.com/isaul32/ckeditor5-math#development):

https://user-images.githubusercontent.com/26336/117490089-fabfd180-af33-11eb-9e9a-af271beceeef.mp4

It's designed to be used in tandem with the browser inspector.

In CKEditor, the equivalent would be to have a webpack-dev-server target a build and run `HTMLWebpackPlugin` to launch into an HTML file, except it would use the monorepo source code and respond to changes to `packages/`.

If you'd like, I may be able to propose a PR / concept. (Not fully sure how difficult it'd be yet though)

**Comment by tony** [comment]
@pomek To get a better idea of what I mean, I've created #9817 

When I'm making changes to the [Media Embed](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html) plugin, this lets me see changes instantly.

I think it's be insanely efficient if `packages/` had a `yarn start` that boot up a dev environment like this.

**Comment by pomek** [comment]
Closing in favor of https://github.com/ckeditor/ckeditor5/issues/9613#issuecomment-933384380.
