### ISSUE TITLE
[Firefox] Error when clicking on label elements inside editor

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#9635]
## 📝 Provide detailed reproduction steps (if any)

There are multiple ways to reproduce this ( see screencasts below ), example steps:
1. Open Firefox and go to https://ckeditor.com/ckeditor-5/demo/
2. Open image alternative balloon
3. Click several times on label `Text alternative` 

### ✔️ Expected result

Nothing Happens

### ❌ Actual result

```js
Uncaught CKEditorError: Permission denied to access property Symbol.toStringTag
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-Permission denied to access property Symbol.toStringTag
    tr istext.js:17
    domSelectionToView domconverter.js:515
    _handleSelectionChange selectionobserver.js:145
    observe selectionobserver.js:104
    fire emittermixin.js:199
    i emittermixin.js:247
    attach emittermixin.js:202
    listenTo emittermixin.js:61
    observe selectionobserver.js:103
    attachDomRoot view.js:288
    init classiceditorui.js:104
    create classiceditor.js:193
    promise callback*create/< classiceditor.js:193
    create classiceditor.js:188
    A app-bb5ed7289d.js:33
    P app-bb5ed7289d.js:33
    q app-bb5ed7289d.js:33
    init app-bb5ed7289d.js:33
    default app-bb5ed7289d.js:44
    init app-bb5ed7289d.js:16
    EventListener.handleEvent* app-bb5ed7289d.js:16
    n app-bb5ed7289d.js:1
    <anonymous> app-bb5ed7289d.js:1
    <anonymous> app-bb5ed7289d.js:1
ckeditorerror.js:64:2
```
## Screencasts

https://user-images.githubusercontent.com/34380544/117288882-4149f900-ae6c-11eb-95f9-ed722c1b6d7b.mp4

https://user-images.githubusercontent.com/34380544/117288891-45761680-ae6c-11eb-8a19-76268d3ca743.mp4

https://user-images.githubusercontent.com/34380544/117288896-460ead00-ae6c-11eb-960a-e9e6ecce0972.mp4

## 📃 Other details

* Browser: Firefox
* Happens since version `24.0.0`
* It happens when I click inside forms, specifically on label elements, but only those that are inside editor - for example I cannot reproduce this when opening media embed toolbar dropdown and clicking on the label.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
To me it looks like some sort of weird issue in Firefox.

From a quick research, it looks like it is connected with selection and inputs. As far as I can tell, the error does not occur when you click on texts in the version item (for example, author name).

The issue happens when you click on place next to an input. I think that Firefox messes up with selection then.

What happens is, Firefox set selection in a way that the selection is in the input but when you try to get a range from the selection and then start and end container of the range, Firefox returns "Restricted" object, which throws when any of its property is accessed:

![image.png](https://images.zenhubusercontent.com/5e272596fe6fac151d87240f/72ef5cba-a2e9-4f7f-9a95-afd32f5903c3)

When you check selection anchor and focus, correct DOM element is returned, but in line 512 "Restricted" object is returned.

AFAICS, this error does not have an impact on editor, i.e. editor works. Am I right?

![image.png](https://images.zenhubusercontent.com/5e272596fe6fac151d87240f/418f6fbe-cd4c-4705-9188-bbd6feeac2ee)

What we could do is:

1.  Try to reproduce this using the most basic HTML possible and report the error to Firefox.
2.  Until it is fixed, we could either use try-catch or just use selection anchor and offset in this part of code (since this is just one range, using selection anchor and offset should be safe?).
3.  However, I guess there are other places where we use `isText()` that also might be affected by that.

**Comment by o-alquimista** [comment]
I just found another way to reproduce this, but it doesn't involve interacting with CKEditor *at all*. All you need is a CKEditor instance on the page. Ignore it. Leave it there. Focus on the rest of the form. Click randomly on any other `<label>` element on the page. Eventually, the error pops up. Very weird, right?

![Captura de tela de 2021-05-25 22-14-07](https://user-images.githubusercontent.com/25424263/119588224-ba22dd80-bda6-11eb-8a8d-599a1161eee0.png)

**Comment by AhmedEzzat12** [comment]
Any update on this?

**Comment by scofalik** [comment]
Does this error in any way impact how your editor works?

**Comment by AhmedEzzat12** [comment]
@scofalik It freezes the whole UI for a few seconds and then it resumes, the problem is that it doesn't happen when interacting with the editor itself only but having at least one instance of it on the page is enough for the error to occur.
for a little context, I'm using it in react app.

**Comment by ovidiua2003** [comment]
Subscribe +1 
This still happens randomly without even clicking the ckeditor just like [o-alquimista](https://github.com/o-alquimista) said

**Comment by OrenMag** [comment]
> @scofalik It freezes the whole UI for a few seconds and then it resumes, the problem is that it doesn't happen when interacting with the editor itself only but having at least one instance of it on the page is enough for the error to occur. for a little context, I'm using it in react app.

Same here, we experience freezing after this error
