### ISSUE TITLE
Create the "equalMarkup" assertion

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#9668]
## 📝 Provide a description of the improvement

We already have the `assertEqualMarkup()` util for comparing markups.

https://github.com/ckeditor/ckeditor5/blob/2b1ea1a6ccc4d16a2b466c7ae50711707f83fe0d/packages/ckeditor5-utils/tests/_utils/utils.js#L148-L172

However, many of us may do not know about the helper. Also, it requires adding additional imports.

We could add a new function to chai (https://www.chaijs.com/guide/helpers/#adding-methods) that will introduce the new assertion. The goal is to have something like this:

```js
expect( editor.getData() ).to.equalMarkup( /* ... */ );
```

In details, the function will use the `assertEqualMarkup()` helper.

It would be nice to add the new helper to existing bindings to have the new assertion in IDE autocomplete list.

---

If you'd like to see, this improvement implemented, add a 👍 reaction to this post.

**Comment by pomek** [comment]
Scope:
* Create a new mocha assertion.
* Replace existing `equalMarkup` functions with the created assertion.

**Comment by przemyslaw-zan** [comment]
Normaly, you'd have to `import` this new assertion to use it within tests. However, there is a way of avoiding that - any new `chai` assertions can be imported [in this file](https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-tests/lib/tasks/runautomatedtests.js#L100-L102) - after that, they are available in all tests.

[`attribute.js`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-core/tests/_utils/assertions/attribute.js) is an example of already existing custom `chai` assertion that has to be imported manually whenever needed. Do we want to move that to `ckeditor5-dev-tests` and include it in automatic import for all tests, so that there is no need to import that whenever needed? 

There might be other custom `chai` assertions that i'm not aware of, that also could be moved there.

**Comment by pomek** [comment]
> [`attribute.js`](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-core/tests/_utils/assertions/attribute.js) is an example of already existing custom `chai` assertion that has to be imported manually whenever needed. Do we want to move that to `ckeditor5-dev-tests` and include it in automatic import for all tests, so that there is no need to import that whenever needed? 

Wow. I wasn't aware of this. Yes, let's move all custom assertions to `ckeditor5-dev-tests` and enable using them in any test without importing it directly.

**Comment by przemyslaw-zan** [comment]
> It would be nice to add the new helper to existing bindings to have the new assertion in IDE autocomplete list.

We ended up skipping that part, so perhaps it could be extracted to a followup?
