### ISSUE TITLE
Should we rename the .image CSS class to .image-block (just like .image-inline)?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#9710]
## Provide a description of the task

I know this is another breaking change (a really big one, I admit bc existing integrators' data would no longer upcast) on top of many we did in inline images, but since we rename the model element in #9246, maybe this is the right moment to have things consistent?

*   `imageBlock` -> `.image-block`
*   `imageInline`\-> `.image-inline`

**Comment by niegowski** [comment]
I think that the CSS class should not be changed because:

*   A big breaking change for integrators - all the content would get imported differently (upcast of `<figure class="image">`)
*   Those classes are set on different elements, for block images it's `<figure>`, but for inline images, it's only set in the editing view (on a `<span>`) and it's completely skipped in the data view.
*   Since the above, the styling could be done based on the element name, not only the class name.

**Comment by oleq** [comment]
I assume the discussion is over. We're staying with old CSS class names.
