### ISSUE TITLE
setData strips out <code> tags

### ISSUE THREAD

**Issue by frostbyte3** [ckeditor/ckeditor5#9713]
## 📝 Provide detailed reproduction steps (if any)

Trying to run `commentEditor.setData("<p>test comment</p><code class=\"python-code\">def withCodeBlock:<br /> print('test')</code>");` results in the `<code>` tags being stripped out

### ✔️ Expected result

Editor should contain data:

```
<p>test comment</p>
<code class="python-code">def withCodeBlock:<br /> 
    print('test')</code>"
```

### ❌ Actual result

Editor contains:
```
<p>test comment</p>
<p>def withCodeBlock:<br>
print('test')</p>
```

## 📃 Other details

* Browser: Chrome
* OS: MacOSX 11.2.3
* First affected CKEditor version: using CKEditor5
* Installed CKEditor plugins: ["alignment:left", "alignment:right", "alignment:center", "alignment:justify", "alignment", "undo", "redo", "blockQuote", "bold", "codeBlock", "selectAll", "fontColor", "fontFamily", "fontSize", "heading", "highlight:yellowMarker", "highlight:greenMarker", "highlight:pinkMarker", "highlight:blueMarker", "highlight:redPen", "highlight:greenPen", "removeHighlight", "highlight", "horizontalLine", "htmlEmbed", "imageTextAlternative", "uploadImage", "imageUpload", "insertImage", "imageInsert", "resizeImage:original", "resizeImage:25", "resizeImage:50", "resizeImage:75", "resizeImage", "imageResize", "imageStyle:full", "imageStyle:side", "indent", "outdent", "italic", "link", "linkImage", "numberedList", "bulletedList", "mediaEmbed", "specialCharacters", "strikethrough", "subscript", "superscript", "insertTable", "tableColumn", "tableRow", "mergeTableCells", "tableCellProperties", "tableProperties", "underline"]

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Hi! The inline `<code>` is a [basic text formatting option](https://ckeditor.com/docs/ckeditor5/latest/features/basic-styles.html#available-text-styles) that doesn't support `class` attribute, that's why it's removed (CKEditor 5 doesn't allow elements and attributes that are not introduced by plugins).

However, your example indicates that the code block is something that might better fit your use case, so check the [code blocks feature documentation](https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html) to learn more.

**Comment by frostbyte3** [comment]
I am utilizing the codeblock plugin, this is not an inline yet it's still being stripped.
