### ISSUE TITLE
Mention plugin should allow autocomplete with space

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/ckeditor5#9741]
## 📝 Provide a description of the new feature

Currently, when you press `spacebar` while using the mention feature it will hide the dropdown and add space after what has been written - this is behaving exactly like mentions on GitHub.  
  
However, it could be a more natural user experience if it would be working in a different way - where you can add space after for example @Barney (following the example from editor 2 - on [features/mention](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html#fully-customized-mention-feed) page in docs) and still be able to filter the feed to select `Barney Stinson` from the dropdown.  
  
This issue was already discussed partially here: #7306 - but that issue was created to resolve a slightly different problem, so I'm extracting this as a separate one.  
  
Mentioning @EricPaulson and @robjbrain as you gave the most recent feedback regarding this and might want to leave a 👍 reaction.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by CatStrategist** [comment]
Issue fixed in #11017 

Mention plugin didn't allow spaces because of regexp for matching mentions in currently edited text that only allowed visible characters to occur after a mention mark.
At first it seemed as an easy improvement of regexp to just allow a space but a scenario with multiple registered markes complicated it a lot.

Take this case:

> aaa @fooo #bar

Regexp allowing space would match @foo as well as #bar. After playing a little bit with regexp to handle that case it quickly got overcomplicated and still had some other edge cases so I had to withdraw from this approach.

Previously regexp to match mention tested entire text node till caret but what we really needed to test is just a text since last valid marker in text. But yet again, case with multiple markers complicated it a little bit. Previously there was a `TextWatcher` for each marker that tried to match a mention for it's own marker. It run outside of state of mention plugin and executed `matched` or `unmachted` events without knowledge of matches for other markers. It could find a match for one marker and tried to show UI, but the other marker fired `unmatched` event and immediately hid UI. Before going with solution for spaces it had to be fixed. When initializing plugin I've merged watchers to a single one who knows about each marker and runs only one on each text change. Having that in place, I could pass a test function to `TextWatcher` and find last valid marker in text, trim text since last marker (+1 a character behind to test if marker is in correct place) till caret. Having only that part the rest of the code could stay as usual with just a little change to regexp that now allows any character after marker character instead of just visible characters.

**Comment by robjbrain** [comment]
It seems like we're very restricted by the current implementation of the UI.

Would it be better to have an alternative plugin that when typing `@` a popup appears with an input and the focus then goes on the input, something similar to the link UI.

This is what it looks like currently:
![image](https://user-images.githubusercontent.com/10143910/146475123-b4c9bffe-ba5f-43f1-b9c7-ae7313f3e1a4.png)

It could instead look something like this:
![image](https://user-images.githubusercontent.com/10143910/146475212-148ca888-3d36-4164-b760-129d412416d6.png)

In this example `Enter` or `Esc` or using the green and red buttons would close the popup.

Such a plugin could be generic for multiple uses, such as such as `#` creating a popup of tags where you could search existing tags or create a new one. But could also be used for more advanced mentions that the basic mentions plugin itself can't cater for.

**Comment by Reinmar** [comment]
Hi @robjbrain! Thanks for the suggestion. However, this issue is solely about handling mentions with spaces and a quick win we can have there. Your idea goes well beyond this and would need a separate ticket.

**Comment by oldmansutton** [comment]
Going to chime in here, in that for me I actually WANT space to end the mention logic (hide ui, accept, etc).  This is what happens (sort of).  Say I type @stuff, hit the space bar (I have no valid matches at this point).  I would expect that there is no highlighting, etc, and that is indeed correct.  However, I'm noticing that by providing a callback for the feed, that it keeps firing for every character that continues to be typed. Since I'm making an ajax call that returns a promise in the feed callback, this means it continues to keep firing long after I would have expected the @mention to have finished.

This does lead me to believe though, that the people that DO want space to be a valid character in their mentions, could do this fairly easily by using a callback.
