### ISSUE TITLE
Normalize further patterns passed to Matcher

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5#9813]
As mentioned in https://github.com/cksource/ckeditor5-internal/issues/718#issuecomment-852362126, we came across a conflicting case while trying to limit the scope of attributes filtering.

We would like to normalize patterns of cases such as the one in [LinkImageEditing](https://github.com/ckeditor/ckeditor5/blob/8024a9169fb4aa1cbc89078c1ba18560b68ccf15/packages/ckeditor5-link/src/linkimageediting.js#L253-L258) by essentially making this:

```js
const pattern = {
	attributes: {
		rel: 'no-follow',
		class: 'foo-class'
	}
}
```

into 

```js
const pattern = {
	attributes: {
		rel: 'no-follow'
	},
	classes: [ 'foo-class' ]
}
```
	

Things to consider:
- Pattern `attributes: true` makes the normalization problematic. Should we match styles and classes in such case?
- Methods like `element.getAttribute()`, `element._setAttribute()` etc. do work with `style` and `class` attributes.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by jacekbogdanski** [comment]
This issue is also problematic in GHS. Let's consider below config and HTML structure:
```js
const ghsConfig = { 
  allow: [ { name: 'span', attributes: true } ]
};
```
```html
<span style="color: red;"><span style="background: blue;">foobar</span></span>
```
Currently, `attributes: true` matches `style` attribute by String comparison and outputs result as 
```js
{ attributes: [ 'style' ] }
```
which breaks above HTML style nesting as the outer style is just replaced. If we decide that those attributes should be handled by `attributes: true` pattern, we should normalize them earlier, so the output would be 
```js
{ styles: [ 'background', 'color' ] }
```

Unfortunately, it also means that the API will start to be a bit inconsistent because the code:
```js
{ attributes: true }
```
will be just a shortcut to (if we decide to normalize it):
```js
{
  attributes: true,
  classes: true,
  styles: true
}
```

**Comment by jacekbogdanski** [comment]
After discussion with the compact team, we decided to remove `style` and `class` attributes from the `attributes` matcher pattern scope and do as follows:

* Since `attributes: true` is a new feature that shouldn't provide any breaking changes, we would like to limit its support to every attribute except `style` and `class` attributes. These properties should not be supported by `attributes` property.
* In case of the object format `{ attributes: { style: true, class: true } }` which was supported before recent Matcher changes, we will log warning message informing that this feature is deprecated and developer should use `classes` and/or `styles` properties instead. However, we will still support the old format (for some time) to avoid 3rd party code regressions.
* We will verify other places in our codebase which abuses Matcher API allowing to match styles and classes using `attributes` property and correct them if needed.
