### ISSUE TITLE
Introduce checkbox type for search and replace

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#9880]
UI mockups (#9719) contain checkboxes. Currently we don't have checkbox views in CKE5.

Let's start by creating the view here in Find and Replace plugin. From here we'll populate it to the UI lib as soon as it will be reused in another feature later.

**Comment by mateuszzagorski** [comment]
I've introduced checkboxes for search and replace here: c3155a7, but since then there were some changes throughout various files,  I'd suggest looking at fa2c3b1.  
  
I've consulted with Magda regarding the color palette and as per her latest comment we'll be using default colors for text/buttons: [https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-861438305](https://github.com/ckeditor/ckeditor5/issues/9719#issuecomment-861438305)

**Comment by mlewand** [comment]
You made a litreral

*   You made the checboxes [using a generic View by passing a custom template](https://github.com/ckeditor/ckeditor5/blob/c061fff7f97fe735afe0eb30eb362703345b6f9b/packages/ckeditor5-find-and-replace/src/ui/findandreplaceformview.js#L422-L447) however, here we'll need it created as other reusable view class. For example we already have [ButtonView](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_button_buttonview-ButtonView.html), [FileInputView](https://ckeditor.com/docs/ckeditor5/latest/api/module_upload_ui_filedialogbuttonview-FileInputView.html), [LabeledInputView](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_labeledinput_labeledinputview-LabeledInputView.html) (etc) we need also a view class for a labelled checkbox. That's the reason why I said that we'll have it in find and replace first rather than in UI lib in the issue description (as that might seem unusual). It should have a `isChecked` observable property.
*   How about calling it `ck-replace-form__buttons` [instead of `ck-replace-buttons`](https://github.com/ckeditor/ckeditor5/blob/c061fff7f97fe735afe0eb30eb362703345b6f9b/packages/ckeditor5-find-and-replace/src/ui/findandreplaceformview.js#L344)?

**Comment by mlewand** [comment]
Closed in #9958.
